import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {mockQuestionVersionHistoryPage,mockQuestionReviewHistoryPage} from '@remoa/contracts/mocks';
import {QuestionHistory} from './question-history';
import {QuestionsApiError} from '@/features/questions/request';
vi.mock('@/features/admin/questions/catalog-api',()=>({getQuestionVersionHistory:vi.fn(),getQuestionReviewHistory:vi.fn()}));
import {getQuestionVersionHistory,getQuestionReviewHistory} from '@/features/admin/questions/catalog-api';
const id=mockQuestionVersionHistoryPage.questionId,other='00000000-0000-4000-8000-000000000999',version=mockQuestionVersionHistoryPage.items[0]!;
beforeEach(()=>{vi.resetAllMocks();vi.mocked(getQuestionVersionHistory).mockResolvedValue(mockQuestionVersionHistoryPage);vi.mocked(getQuestionReviewHistory).mockResolvedValue(mockQuestionReviewHistoryPage);});afterEach(cleanup);
const open=()=>fireEvent.click(screen.getByRole('button',{name:'Ver versões e revisões'}));
describe('selected question version and medical history',()=>{
 it('does not fetch closed or disabled histories and keeps signatures scoped to the selected version',async()=>{const{rerender}=render(<QuestionHistory id={id} admin={false} enabled={false}/>);expect(screen.queryByRole('button')).not.toBeInTheDocument();rerender(<QuestionHistory id={id} admin={false} enabled/>);expect(getQuestionVersionHistory).not.toHaveBeenCalled();expect(getQuestionReviewHistory).not.toHaveBeenCalled();open();await screen.findByText(version.stemPreview);expect(getQuestionReviewHistory).toHaveBeenCalledWith(false,id,{limit:25},expect.any(AbortSignal));expect(screen.getByText(/somente à versão aberta/i)).toBeInTheDocument();});
 it('renders actual lineage/status metadata and the reviewer hash, reason and dates without mutating publication',async()=>{vi.mocked(getQuestionVersionHistory).mockResolvedValue({...mockQuestionVersionHistoryPage,items:[{...version,supersedesId:other,catalogStatus:'withdrawn',availability:'superseded',publishedAt:new Date('2026-01-01T00:00:00Z')}]});vi.mocked(getQuestionReviewHistory).mockResolvedValue({questionId:id,items:[{id:other,questionId:id,decision:'approved',contentHash:'b'.repeat(64),reason:'Conferência sintética auditada',reviewerName:'Revisor sintético',reviewerCrm:'12345-SP',referenceDate:'2026-01-01',reviewedAt:new Date('2026-01-02T00:00:00Z')}],nextCursor:null});render(<QuestionHistory id={id} admin enabled/>);open();await screen.findByText('Conteúdo aprovado');expect(screen.getByText('Retirada de circulação')).toBeVisible();expect(screen.getByText('Substituída')).toBeVisible();expect(screen.getByRole('link',{name:'Ver versão anterior'})).toHaveAttribute('href',`/app/editorial/questoes/${other}`);expect(screen.getByText(/Conferência sintética auditada/)).toBeVisible();expect(screen.getByText(new RegExp('b'.repeat(64)))).toBeVisible();expect(screen.queryByRole('button',{name:'Publicar questão'})).not.toBeInTheDocument();});
 it('paginates versions and signatures independently without discarding loaded entries',async()=>{vi.mocked(getQuestionVersionHistory).mockResolvedValueOnce({...mockQuestionVersionHistoryPage,nextCursor:'versions2'}).mockResolvedValue({...mockQuestionVersionHistoryPage,items:[{...version,id:other,version:2,stemPreview:'Versão posterior sintética'}]});render(<QuestionHistory id={id} admin={false} enabled/>);open();await screen.findByText(version.stemPreview);fireEvent.click(screen.getByRole('button',{name:'Carregar versões anteriores'}));await screen.findByText('Versão posterior sintética');expect(screen.getByText(version.stemPreview)).toBeVisible();expect(getQuestionVersionHistory).toHaveBeenLastCalledWith(false,id,{limit:25,cursor:'versions2'},expect.any(AbortSignal));expect(getQuestionReviewHistory).toHaveBeenCalledOnce();});
 it('preserves a versions denial, retries explicitly, and aborts/ignores old question replies',async()=>{vi.mocked(getQuestionVersionHistory).mockRejectedValueOnce(new QuestionsApiError('forbidden')).mockResolvedValue(mockQuestionVersionHistoryPage);const{rerender}=render(<QuestionHistory id={id} admin enabled/>);open();const region=screen.getByRole('region',{name:'Versões da mesma questão'});await within(region).findByRole('alert');fireEvent.click(within(region).getByRole('button',{name:'Tentar de novo'}));await screen.findByText(version.stemPreview);let resolve!:(value:typeof mockQuestionVersionHistoryPage)=>void;vi.mocked(getQuestionVersionHistory).mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));rerender(<QuestionHistory id={other} admin enabled/>);await waitFor(()=>expect(getQuestionVersionHistory).toHaveBeenLastCalledWith(true,other,{limit:25},expect.any(AbortSignal)));const signal=vi.mocked(getQuestionVersionHistory).mock.calls.at(-1)![3]!;rerender(<QuestionHistory id={id} admin enabled/>);await screen.findByText(version.stemPreview);expect(signal.aborted).toBe(true);resolve({...mockQuestionVersionHistoryPage,questionId:other,items:[{...version,stemPreview:'Resposta de outro identificador'}]});await waitFor(()=>expect(screen.queryByText('Resposta de outro identificador')).not.toBeInTheDocument());});
});
