'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {t} from '@/features/questions/labels';
import {Alert,Button,Select,Textarea} from '@remoa/ui';
import type {QuestionReportQueueQuery,questionReportQueueItemSchema,questionReportDetailSchema} from '@remoa/contracts';
import type {z} from 'zod';
import {listQuestionReports,getQuestionReport,resolveQuestionReport} from '@/features/admin/questions/api';
import {AdminQuestionTitle,AdminQuestionTabs} from '@/features/admin/questions/admin-shared';
import {tq,adminQuestionError} from '@/features/admin/questions/labels';
import {actionLink,panel} from '@/features/questions/shared';
type Report=z.infer<typeof questionReportQueueItemSchema>;
type Detail=z.infer<typeof questionReportDetailSchema>;
const statuses=['open','resolved','dismissed'] as const;
const types=['key','statement','image','explanation','rights','other'] as const;
const route=(admin:boolean)=>admin?'/admin/questoes/relatos':'/app/editorial/questoes/relatos';
export function QuestionReportsQueue({admin=false}:{admin?:boolean}){
 const[status,setStatus]=useState<QuestionReportQueueQuery['status']>('open');const[type,setType]=useState<QuestionReportQueueQuery['type']>();const[items,setItems]=useState<Report[]>([]);const[cursor,setCursor]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[moreBusy,setMoreBusy]=useState(false);const[error,setError]=useState<string|null>(null);const sequence=useRef(0);
 const load=useCallback(async()=>{const requestId=++sequence.current;setLoading(true);setError(null);try{const result=await listQuestionReports(admin,{status,type});if(requestId!==sequence.current)return;setItems(result.items);setCursor(result.nextCursor);}catch(e){if(requestId===sequence.current)setError(adminQuestionError(e));}finally{if(requestId===sequence.current)setLoading(false);}},[admin,status,type]);
 useEffect(()=>{const guard=sequence;void load();return()=>{guard.current++;};},[load]);
 const more=async()=>{if(!cursor||moreBusy)return;const requestId=sequence.current;setMoreBusy(true);try{const result=await listQuestionReports(admin,{status,type,cursor});if(requestId!==sequence.current)return;setItems(old=>[...old,...result.items.filter(item=>!old.some(v=>v.id===item.id))]);setCursor(result.nextCursor);}catch(e){setError(adminQuestionError(e));}finally{setMoreBusy(false);}};
 return <div className="space-y-6"><AdminQuestionTitle title={tq('questionsAdmin.reportsTitle')} description={tq('questionsAdmin.reportsDescription')}/>{admin?<AdminQuestionTabs/>:<Link className={actionLink} href="/app/editorial/questoes">{tq('questionsAdmin.medicalQueue')}</Link>}<div className="grid gap-4 sm:grid-cols-2"><Select label={tq('questionsAdmin.reportStatus')} value={status??'all'} onValueChange={value=>setStatus(value==='all'?undefined:value as typeof status)} options={[{value:'all',label:tq('questionsAdmin.reportAll')},...statuses.map(value=>({value,label:tq(`questionsAdmin.reportStatuses.${value}`)}))]}/><Select label={tq('questionsAdmin.reportType')} value={type??'all'} onValueChange={value=>setType(value==='all'?undefined:value as typeof type)} options={[{value:'all',label:tq('questionsAdmin.reportAll')},...types.map(value=>({value,label:t(`questions.reportKinds.${value}`)}))]}/></div>{loading?<p role="status">{t('common.loading')}</p>:items.length?items.map(item=><article className={`${panel} min-w-0 space-y-3`} key={item.id}><p className="font-bold">{t(`questions.reportKinds.${item.type}`)} · {tq(`questionsAdmin.reportStatuses.${item.status}`)}</p><p className="whitespace-pre-wrap break-words">{item.description}</p><p className="text-xs text-muted">{tq('questionsAdmin.reportVersion',{n:item.version})}</p><Link className={actionLink} href={`${route(admin)}/${item.id}`}>{tq('questionsAdmin.reportOpen')}</Link></article>):!error?<p>{tq('questionsAdmin.reportsEmpty')}</p>:null}{error?<Alert role="alert" title={error} tone="review"><Button onClick={()=>void load()}>{t('common.retry')}</Button></Alert>:null}{cursor?<Button loading={moreBusy} onClick={()=>void more()}>{tq('questionsAdmin.reportMore')}</Button>:null}</div>;
}
export function QuestionReportDetail({id,admin=false}:{id:string;admin?:boolean}){
 const[data,setData]=useState<Detail|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[status,setStatus]=useState<Report['status']>('open');const[reason,setReason]=useState('');const[notice,setNotice]=useState<string|null>(null);const loadSequence=useRef(0);const reasonField=useRef<HTMLTextAreaElement>(null);
 const load=useCallback(async()=>{const requestId=++loadSequence.current;setLoading(true);setError(null);try{const detail=await getQuestionReport(admin,id);if(requestId!==loadSequence.current)return;setData(detail);setStatus(detail.report.status);}catch(e){if(requestId===loadSequence.current){setData(null);setError(adminQuestionError(e));}}finally{if(requestId===loadSequence.current)setLoading(false);}},[admin,id]);
 useEffect(()=>{const guard=loadSequence;void load();return()=>{guard.current++;};},[load]);
 useEffect(()=>{if(error&&!busy)reasonField.current?.focus();},[error,busy]);
 const save=async()=>{if(!data?.editable||busy)return;setBusy(true);setError(null);setNotice(null);try{const{questionReportResolveInputSchema}=await import('@/features/admin/questions/schema-loaders');const parsed=questionReportResolveInputSchema.safeParse({status,reason:reason.trim(),expectedUpdatedAt:data.report.updatedAt});if(!parsed.success)return;const result=await resolveQuestionReport(admin,id,parsed.data);setData(old=>old?{...old,report:result.report}:null);setNotice(tq(result.changed?'questionsAdmin.reportSaved':'questionsAdmin.reportNoChange'));}catch(e){setError(adminQuestionError(e));}finally{setBusy(false);}};
 return <div className="space-y-6"><AdminQuestionTitle title={tq('questionsAdmin.reportDetailTitle')} description={tq('questionsAdmin.reportNoCorrection')}/><Link className={actionLink} href={route(admin)}>{tq('questionsAdmin.reportsTitle')}</Link>{loading?<p role="status">{t('common.loading')}</p>:data?<><article className={`${panel} min-w-0 space-y-4`}><h2 className="font-display text-xl font-bold">{t(`questions.reportKinds.${data.report.type}`)}</h2><p className="whitespace-pre-wrap break-words">{data.report.description}</p><p>{tq('questionsAdmin.reportVersion',{n:data.report.version})}</p><p className="text-sm text-muted">{tq('questionsAdmin.reportUpdated')}: {new Date(data.report.updatedAt).toLocaleString('pt-BR')}</p><h2 className="font-bold">{tq('questionsAdmin.reportQuestion')}</h2>{data.question.stem===null?<p>{tq('questionsAdmin.reportPrivacy')}</p>:<p className="whitespace-pre-wrap break-words">{data.question.stem}</p>}{data.question.visibility==='public'?<Link className={actionLink} href={`/app/editorial/questoes/${data.question.id}`}>{tq('questionsAdmin.medicalQueue')}</Link>:null}</article>{data.editable?<section className={`${panel} space-y-5`}><Select label={tq('questionsAdmin.reportStatus')} value={status} onValueChange={value=>{if(!busy)setStatus(value as typeof status);}} options={statuses.map(value=>({value,label:tq(`questionsAdmin.reportStatuses.${value}`)}))}/><Textarea ref={reasonField} label={tq('questionsAdmin.reason')} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} minLength={8} maxLength={500}/><Button loading={busy} disabled={busy||reason.trim().length<8} onClick={()=>void save()}>{tq('questionsAdmin.reportSave')}</Button></section>:<p>{tq('questionsAdmin.reportReadOnly')}</p>}</>:null}{notice?<p role="status">{notice}</p>:null}{error?<Alert role="alert" title={error} tone="review"><Button disabled={busy} onClick={()=>void load()}>{tq('questionsAdmin.reportRefresh')}</Button></Alert>:null}</div>;
}
