import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QuestionReportDetail,QuestionReportsQueue} from './reports-screen';
import {QuestionsApiError} from '@/features/questions/api';
vi.mock('@/features/admin/questions/api',()=>({listQuestionReports:vi.fn(),getQuestionReport:vi.fn(),resolveQuestionReport:vi.fn()}));
import{listQuestionReports,getQuestionReport,resolveQuestionReport}from '@/features/admin/questions/api';
const id='550e8400-e29b-41d4-a716-446655440000',stamp='2026-10-08T00:00:00.000Z';
const report={id,questionId:id,version:1,type:'key' as const,description:'Relato sintético sobre gabarito',status:'open' as const,createdAt:new Date(stamp),updatedAt:new Date(stamp)};
const detail={report,question:{id,version:1,canonicalId:id,visibility:'private' as const,catalogStatus:'draft' as const,availability:'active' as const,stem:null},editable:true};
afterEach(()=>{cleanup();vi.resetAllMocks();});
describe('question report triage',()=>{
 it('does not expose a resolution form after role404',async()=>{vi.mocked(getQuestionReport).mockRejectedValue(new QuestionsApiError('not_found'));render(<QuestionReportDetail id={id} admin/>);await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Registrar encaminhamento'})).toBeNull();});
 it('hides unavailable private text and requires a reason, using the version read',async()=>{vi.mocked(getQuestionReport).mockResolvedValue(detail);vi.mocked(resolveQuestionReport).mockResolvedValue({report:{...report,status:'resolved'},changed:true,audit:{} as never});render(<QuestionReportDetail id={id} admin/>);await screen.findByText('O conteúdo privado desta questão não está disponível para seu perfil.');expect(screen.getByRole('button',{name:'Registrar encaminhamento'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Triagem sintética com motivo'}});fireEvent.click(screen.getByRole('button',{name:'Registrar encaminhamento'}));await screen.findByText('Encaminhamento registrado');expect(resolveQuestionReport).toHaveBeenCalledWith(true,id,{status:'open',reason:'Triagem sintética com motivo',expectedUpdatedAt:new Date(stamp)});expect(screen.queryByRole('link',{name:'Revisão médica'})).toBeNull();});
 it('keeps reason and focuses it after conflict; refresh updates expected timestamp explicitly',async()=>{vi.mocked(getQuestionReport).mockResolvedValue(detail);vi.mocked(resolveQuestionReport).mockRejectedValue(new QuestionsApiError('conflict'));render(<QuestionReportDetail id={id}/>);const input=await screen.findByLabelText('Motivo desta operação');fireEvent.change(input,{target:{value:'Motivo sintético preservado'}});fireEvent.click(screen.getByRole('button',{name:'Registrar encaminhamento'}));await screen.findByRole('alert');expect(input).toHaveValue('Motivo sintético preservado');await waitFor(()=>expect(input).toHaveFocus());vi.mocked(getQuestionReport).mockResolvedValue({...detail,report:{...report,updatedAt:new Date('2026-10-09T00:00:00.000Z')}});fireEvent.click(screen.getByRole('button',{name:'Atualizar relato'}));await waitFor(()=>expect(getQuestionReport).toHaveBeenCalledTimes(2));await screen.findByLabelText('Motivo desta operação');expect(screen.getByLabelText('Motivo desta operação')).toHaveValue('Motivo sintético preservado');});
 it('uses the exact lazy validator before mutation and releases busy for correction',async()=>{vi.mocked(getQuestionReport).mockResolvedValue(detail);vi.mocked(resolveQuestionReport).mockResolvedValue({report,changed:false,audit:{} as never});render(<QuestionReportDetail id={id} admin/>);const input=await screen.findByLabelText('Motivo desta operação');fireEvent.change(input,{target:{value:'x'.repeat(501)}});const submit=screen.getByRole('button',{name:'Registrar encaminhamento'});fireEvent.click(submit);await waitFor(()=>expect(submit).not.toBeDisabled());expect(resolveQuestionReport).not.toHaveBeenCalled();fireEvent.change(input,{target:{value:'Motivo válido para triagem sintética'}});fireEvent.click(submit);await screen.findByText('O encaminhamento já estava registrado');expect(resolveQuestionReport).toHaveBeenCalledTimes(1);});
 it('shows empty state and handles a load failure with retry',async()=>{vi.mocked(listQuestionReports).mockRejectedValueOnce(new QuestionsApiError('forbidden')).mockResolvedValue({items:[],nextCursor:null});render(<QuestionReportsQueue/>);await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Tentar de novo'}));await screen.findByText('Nenhum relato encontrado');expect(listQuestionReports).toHaveBeenLastCalledWith(false,{status:'open',type:undefined});});
});
