// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const boards = {
  title: 'Meus mapas',
  new: 'Novo mapa',
  create: 'Criar mapa',
  titleLabel: 'Nome do mapa',
  titlePlaceholder: 'Ex.: Sepse',
  counts: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
  stateBarLabel: '{review} para revisitar, {watch} a acompanhar, {steady} mais estáveis, {unknown} sem revisões',
  menu: 'Mais ações de {title}',
  today: {
    label: 'Hoje',
    due: '{n, plural, one {# conceito vence} other {# conceitos vencem}} hoje · {m} em {title}',
    none: 'Nada vence hoje. Que tal criar um mapa?',
    start: 'Começar',
  },
  soon: { title: 'Em breve', body: 'A importação chega nas próximas versões. Por enquanto, crie um mapa e adicione seus cards.' },
  open: 'Abrir {title}',
  rename: 'Renomear',
  renameTitle: 'Renomear mapa',
  duplicate: 'Duplicar',
  duplicateTitle: '{title} (cópia)',
  duplicated: 'Mapa duplicado',
  archive: 'Arquivar',
  archiveTitle: 'Arquivar “{title}”?',
  archiveBody: 'O mapa sai de Meus mapas. Cards e revisões continuam guardados.',
  archived: 'Mapa arquivado',
  unarchive: 'Desarquivar',
  unarchived: 'Mapa desarquivado',
  archivedBadge: 'Arquivado',
  delete: 'Excluir',
  deleteTitle: 'Excluir “{title}” para sempre?',
  deleteBody: 'Isso apaga o mapa, todos os cards e o histórico de revisão dele. Não dá para desfazer.',
  deleteConfirmLabel: 'Para confirmar, digite o nome do mapa',
  deleted: 'Mapa excluído',
  statusLabel: 'Mostrar mapas',
  statusActive: 'Ativos',
  statusArchived: 'Arquivados',
  statusAll: 'Todos',
  emptyArchived: 'Nenhum mapa arquivado',
  undo: 'Desfazer',
  sidebarLabel: 'Seus mapas',
  area: {
    CM: 'Clínica Médica',
    CIR: 'Cirurgia',
    GO: 'Ginecologia e Obstetrícia',
    PED: 'Pediatria',
    MP: 'Medicina Preventiva e Saúde Coletiva',
  },
} as const;
