// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const canvas = {
  layers: { structure: 'Estrutura', retrievability: 'Lembrança estimada', coverage: 'Cobertura' },
  layersLabel: 'Estados dos cards',
  legend: 'Legenda dos estados',
  legendLabel: 'Legenda dos estados',
  zoom: {
    in: 'Aumentar zoom',
    out: 'Diminuir zoom',
    fit: 'Ajustar à tela',
    percent: '{n}%',
    controls: 'Controles de zoom',
  },
  toolbar: {
    label: 'Ferramentas do mapa',
    concept: 'Card',
    flow: 'Fluxograma',
    image: 'Imagem',
    case: 'Caso',
    move: 'Mover o mapa',
    connect: 'Ligar dois cards',
    organize: 'Organizar o mapa',
    heat: 'Lembrança estimada',
    explore: 'Explorar',
    challenge: 'Desafio',
    select: 'Selecionar',
    hint: {
      select: 'Selecionar: clique num card para ver e editar; arraste para mover.',
      move: 'Mover o mapa: arraste o fundo para navegar sem mexer nos cards.',
      concept: 'Adicionar Pergunta e Resposta: cria um card para revisar com pergunta e resposta.',
      note: 'Adicionar Conteúdo: cria um card de anotação livre.',
      flow: 'Adicionar fluxograma: cria um card com passos ligados em sequência.',
      image: 'Adicionar imagem: cria um card com figura para oclusão.',
      case: 'Adicionar caso clínico: cria um card com as etapas de um caso.',
      connect: 'Ligar dois cards: arraste de um card para outro e dê um rótulo à conexão.',
      organize: 'Organizar o mapa: arruma os cards automaticamente.',
    },
  },
  // T5 (editor v2)
  fitShort: 'Ajustar',
  layerSwitch: { structure: 'Estrutura', recall: 'Lembrança', coverage: 'Cobertura' },
  nodeType: { concept: 'Pergunta e Resposta', flow: 'Fluxograma', image: 'Imagem', case: 'Caso clínico', note: 'Conteúdo' },
  selectCard: 'Selecionar {title}',
  footer: {
    recall: '{state} · {pct}%',
    due: '{text} · vence hoje',
    none: 'Sem revisões ainda',
    edges: '{n, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    coverage: 'Entra em {item}',
    noItem: 'Fora da matriz do Enamed',
  },
  edgeDialog: 'Rótulo da conexão',
  edgeDialogBody: 'Sem rótulo, a conexão não vira pergunta no desafio.',
  // G02
  flip: 'Ver resposta',
  unflip: 'Ver pergunta',
  backLoading: 'Carregando resposta…',
  backEmpty: 'Sem resposta ainda.',
  connectFrom: 'Agora clique no card de destino.',
  connectStart: 'Clique no card de origem.',
  // G06
  stepImageAlt: 'Imagem do passo {n} de {title}',
  stageImageAlt: 'Imagem da etapa {stage} de {title}',
  backImageAlt: 'Imagem da resposta de {title}',
} as const;
