// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const cards = {
  edit: 'Editar card',
  editorLabel: 'Editar {title}',
  loading: 'Carregando card…',
  loadError: 'Não conseguimos abrir este card.',
  saving: 'Salvando…',
  saved: 'Card salvo',
  shortcuts: 'Enter salva (Ctrl+Enter nos textos longos). Esc cancela.',
  fields: {
    title: 'Título',
    front: 'Pergunta ou dica (opcional)',
    // G06: Conteúdo (note)
    text: 'Texto',
    noteHint: 'Conteúdo é só informativo: não tem resposta, não entra no desafio nem na revisão.',
    back: 'Resposta',
    backHint: 'Aceita **negrito**, *itálico*, listas com - e [links](https://…).',
    preview: 'Prévia da resposta',
    source: 'Fonte (texto ou URL)',
    sourcePlaceholder: 'Ex.: Diretriz Surviving Sepsis 2021',
  },
  flow: {
    count: '{n, plural, one {# passo} other {# passos}}',
    stepsLabel: 'Passos',
    step: 'Passo {n}',
    note: 'Observação do passo {n} (opcional)',
    image: 'Imagem do passo {n} (opcional)',
    addImage: 'Adicionar imagem ao passo {n}',
    removeImage: 'Remover imagem do passo {n}',
    add: 'Adicionar passo',
    remove: 'Remover passo {n}',
    drag: 'Reordenar passo {n}',
    min: 'Um fluxograma tem pelo menos 2 passos.',
    max: 'Um fluxograma tem no máximo 12 passos.',
    dnd: {
      instructions: 'Para reordenar, pressione espaço ou Enter, use as setas e pressione espaço ou Enter de novo. Esc cancela.',
      start: 'Passo {n} pego.',
      over: 'Passo {n} sobre a posição {to}.',
      end: 'Passo {n} solto na posição {to}.',
      cancel: 'Reordenação cancelada.',
    },
  },
  case: {
    stagesLabel: 'Etapas do caso',
    stage: {
      presentation: 'Apresentação',
      workup: 'Exames',
      diagnosis: 'Diagnóstico',
      management: 'Conduta',
    },
    // G06: o que é cada etapa e o que muda ao preenchê-la (tooltip no nó, no painel e no editor)
    hint: {
      presentation: 'Apresentação: quem é o paciente e por que procurou atendimento (queixa, história, exame físico). Preenchida, abre o caso: no desafio, é o contexto mostrado antes das perguntas.',
      workup: 'Exames: o que pedir e o que veio (laboratório, imagem, escores). Preenchida, o desafio mostra as etapas anteriores e pergunta os exames.',
      diagnosis: 'Diagnóstico: a hipótese principal e o que a sustenta. Preenchida, o desafio mostra as etapas anteriores e pergunta o diagnóstico.',
      management: 'Conduta: o que fazer agora (tratamento, dose, destino). Preenchida, o desafio mostra as etapas anteriores e pergunta a conduta.',
    },
    hintLabel: 'O que é {stage}?',
    empty: 'Etapa vazia: fica fora do desafio.',
    image: 'Imagem da etapa {stage} (opcional)',
    addImage: 'Adicionar imagem à etapa {stage}',
    removeImage: 'Remover imagem da etapa {stage}',
  },
  image: {
    alt: 'Imagem do card {title}',
    pick: 'Escolher imagem',
    dropHint: 'Arraste, cole ou escolha uma imagem JPG, PNG ou WebP de até 100 MB.',
    replace: 'Trocar imagem',
    openMasks: 'Abrir editor de máscaras',
    license: 'Licença da imagem',
    licenses: {
      own: 'Própria',
      cc_by: 'Creative Commons (CC BY)',
      servier: 'Servier Medical Art',
      openstax: 'OpenStax',
    },
    attribution: 'Autoria / atribuição',
    uploading: 'Enviando imagem… {pct}%',
    uploadProgress: 'Progresso do envio',
    failed: 'O envio da imagem falhou.',
    tooBig: 'A imagem passa de 100 MB. Reduza e tente de novo.',
    badType: 'Formato não aceito. Use JPG, PNG ou WebP.',
    noLicense: 'Licença não escolhida: informe a autoria da imagem para essa licença.',
    masksOne: '1 máscara',
    masks: '{n} máscaras',
  },
  frontImage: {
    label: 'Imagem da pergunta (opcional)',
    hint: 'Aparece na frente do card e no desafio.',
    alt: 'Imagem da pergunta de {title}',
    remove: 'Remover imagem',
  },
  backImage: {
    label: 'Imagem da resposta (opcional)',
    hint: 'Aparece no verso do card, depois de "Ver resposta".',
    alt: 'Imagem da resposta de {title}',
    remove: 'Remover imagem da resposta',
  },
  shape: {
    label: 'Formato no mapa',
    rect: 'Retângulo',
    pill: 'Pílula',
    circle: 'Círculo',
    diamond: 'Losango',
    hexagon: 'Hexágono',
    imageHint: 'No mapa, a imagem da pergunta só aparece no formato Retângulo.',
    saving: 'Salvando formato…',
    saved: 'Formato salvo.',
    error: 'Não deu para salvar o formato. Voltamos ao anterior.',
  },
  mask: {
    editorTitle: 'Máscaras de {title}',
    editorDescription: 'Cubra as regiões que você quer ser cobrado. As máscaras ficam por cima da imagem, nunca gravadas nela.',
    tools: 'Ferramenta',
    tool: {
      select: 'Selecionar',
      rect: 'Retângulo',
      polygon: 'Polígono',
    },
    surface: 'Área de desenho das máscaras',
    item: 'Máscara: {label}',
    defaultLabel: 'Região {n}',
    label: 'Rótulo da máscara',
    delete: 'Excluir máscara',
    add: 'Adicionar máscara',
    count: '{n} de {max} máscaras',
    limit: 'Limite de {max} máscaras por imagem.',
    polygonHint: 'Clique para marcar os pontos. Feche clicando no primeiro ponto, com duplo clique ou Enter.',
    rectHint: 'Arraste sobre a imagem para cobrir uma região.',
    selectHint: 'Clique numa máscara para mover; arraste os pontos para redimensionar. Setas movem, Delete exclui.',
    noImage: 'Envie a imagem antes de desenhar máscaras.',
  },
  rubric: {
    title: 'Rubrica',
    essential: 'Essencial',
    source: 'Fonte: {source}',
    generate: 'Gerar rubrica',
  },
  errors: {
    title: 'Dê um título ao card.',
    stepText: 'Preencha o texto de todos os passos.',
    steps: 'Um fluxograma tem de 2 a 12 passos.',
    caseMin: 'Preencha pelo menos uma etapa do caso.',
    image: 'Envie uma imagem antes de salvar.',
    maskLabel: 'Toda máscara precisa de um rótulo.',
    tooLong: 'Algum campo passou do tamanho máximo.',
    notSynced: 'O card ainda não chegou ao servidor. Confira a conexão e tente de novo.',
    offline: 'Sem conexão. Tente de novo quando voltar.',
  },
} as const;
