// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const challenge = {
  progress: '{n} de {total}',
  progressLabel: 'Progresso da sessão',
  loading: 'Montando sua sessão…',
  loadError: 'Não conseguimos montar a sessão.',
  backToReview: 'Voltar para Revisar hoje',
  empty: { title: 'Nada para revisar agora', body: 'Volte mais tarde ou adicione conceitos ao mapa.' },
  stagesLabel: 'Etapas até aqui',
  stepsLabel: 'Passos até aqui',
  context: 'No mapa',
  edgeAsk: 'O que liga {from} a {to}?',
  imageAlt: 'Imagem com regiões cobertas',
  answerMode: 'Como responder',
  write: 'Escrever',
  options: 'Opções',
  optionsLabel: 'Alternativas',
  textLabel: 'Sua resposta',
  submitText: 'Corrigir resposta',
  grading: 'Corrigindo…',
  submitOption: 'Confirmar alternativa',
  reveal: 'Revelar resposta',
  skip: 'Pular',
  skipLimit: 'Este item já foi pulado duas vezes. Responda para seguir.',
  skipError: 'Não conseguimos pular agora. Tente de novo.',
  noRubricBody: 'Este conceito ainda não tem rubrica aprovada. Revele a resposta e diga como foi.',
  ownRubric: 'Rubrica sua',
  answerError: 'Não conseguimos registrar a resposta. Tente de novo.',
  canonical: 'Resposta',
  yourAnswer: 'Sua resposta',
  gradeLocked: 'Nota travada em “Não lembrei”: a resposta tem um erro crítico (dose, droga ou conduta). Reveja a resposta acima.',
  fallbackNoRubric: 'Sem rubrica aprovada para corrigir: avalie você mesmo.',
  fallbackGraderError: 'A correção automática falhou. Compare com a resposta e avalie você mesmo.',
  fallbackQuota: 'Suas correções por IA de hoje acabaram. Compare com a resposta e avalie você mesmo.',
  fallbackOffline: 'Sem conexão. A resposta ficou neste aparelho e a correção por IA acontece quando a rede voltar.',
  quotaCta: 'Ver planos',
  rateError: 'Não conseguimos salvar a nota. Tente de novo.',
  disputed: 'Obrigado. Vamos revisar esta correção.',
  disputeError: 'Não conseguimos enviar. Tente de novo.',
  intervalDays: { zero: 'hoje', one: '1 dia', many: '{n} dias' },
  shortcuts: 'Atalhos: 1 a 4 notas · Enter corrige ou revela · Esc pula',
  verdict: {
    title: { correct: 'Acertou', partial: 'Quase lá', incorrect: 'Não foi dessa vez' },
    matched: 'Acertou',
    missing: 'Faltou',
  },
  summary: {
    title: 'Sessão concluída',
    correct: 'Acertos',
    wrong: 'Erros',
    duration: 'Tempo',
    minutes: '{n} min',
    toReview: 'Cards que pedem revisão',
    toReviewNone: 'Nenhum card pede revisão agora.',
    openBoard: 'Abrir no mapa',
    untitled: 'Card sem título',
    nextDue: 'Próximo vencimento',
    nextNone: 'Sem vencimentos agendados',
    more: 'Mais 5',
  },
} as const;
