// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const coverage = {
  areaFilter: 'Grande área',
  summaryLabel: 'Resumo da cobertura',
  catalog: 'Cobertura do catálogo',
  catalogHint: 'Média sobre todos os itens da área; item sem mapa conta 0%',
  reviewToday: 'Revisar hoje',
  reviewTodayHint: '{n, plural, =0 {nenhum card vence} one {# card vence} other {# cards vencem}}',
  maps: 'Mapas',
  tableLabel: 'Cobertura por tópico',
  topic: 'Tópico',
  mapCount: 'Mapas',
  coverage: 'Cobertura',
  recall: 'Lembrança estimada',
  noRecall: '—',
  footer: 'Cobertura mede quanto do tópico você mapeou, não quanto você lembra. Lembrança estimada vem das suas revisões. Os tópicos são uma organização do Remoa, não uma lista oficial do INEP, e não indicam peso de prova.',
  loadError: 'Não foi possível carregar a cobertura.',
  explain: 'Cobertura é quantos cards você tem num tema dividido pela meta do tema. Temas sem mapa são lacunas: comece por eles.',
  gapsTitle: 'Lacunas',
  gapsCount: '{gaps} de {total} temas sem mapa',
  gapsNone: 'Todos os temas desta área já têm mapa. Veja abaixo onde falta aprofundar.',
  gapsListLabel: 'Temas sem mapa em {group}',
  gapsNoGroup: 'Outros temas',
  target: 'meta: {n, plural, one {# card} other {# cards}}',
  createMap: 'Criar mapa para este tema',
  createMapFor: 'Criar mapa para {topic}',
  linkExisting: 'Ligar um mapa que já tenho',
  linkExistingFor: 'Ligar um mapa que já tenho a {topic}',
  linkTitle: 'Ligar um mapa a {topic}',
  linkBody: 'Escolha um dos seus mapas ainda sem tema.',
  linkNone: 'Você não tem mapas sem tema. Crie um mapa para este tema.',
  linkPick: 'Ligar {map}',
  linkCards: '{n, plural, one {# card} other {# cards}}',
  linkDone: '{map} ligado a {topic}.',
  linkError: 'Não foi possível ligar o mapa. Tente de novo.',
  inProgressTitle: 'Em andamento',
  inProgressHint: 'Do tema menos coberto para o mais coberto.',
  openMap: 'Abrir mapa',
  openMapFor: 'Abrir mapa de {topic}',
  openMapMore: '+{n}',
  actions: 'Ações',
  loading: 'Carregando a cobertura',
  emptyIntro1: 'Você ainda não ligou nenhum mapa a um tema do Enamed.',
  emptyIntro2: 'Comece por um destes temas ou abra seus mapas e ligue um deles a um tema.',
  emptySuggestionsLabel: 'Temas para começar',
  myMaps: 'Meus mapas',
  heroLabel: 'Cobertura geral da área',
  heroRing: '{pct}% da matriz coberta',
  heroSub: '{covered} cobertos · {partial} em andamento · {gaps} sem mapa',
  stateGap: 'Sem mapa',
  statePartial: 'Em andamento',
  stateCovered: 'Coberto',
  nextTitle: 'Comece por aqui',
  nextHint: 'Os temas sem mapa com a maior meta de cards.',
  filterLabel: 'Filtrar por estado',
  filterAll: 'Todos',
  searchLabel: 'Buscar tema',
  searchPlaceholder: 'Buscar tema',
  groupsTitle: 'Temas por grupo',
  groupsHint: 'Do tema menos coberto ao mais coberto em cada grupo.',
  groupSummary: '{n, plural, one {# tema} other {# temas}} · {pct}% coberto',
  groupBar: 'Cobertura de {group}',
  topicBar: 'Cobertura de {topic}',
  recallInline: 'lembrança {pct}%',
  noResults: 'Nenhum tema encontrado com esse filtro.',
  clearFilters: 'Limpar filtros',
  noAreaItems: 'Esta área ainda não tem temas na matriz do Remoa.',
  groupsCount: '{n, plural, =0 {nenhum tema} one {# tema} other {# temas}} na lista',
} as const;
