// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const editorial = {
  title: 'Revisão editorial',
  empty: 'Nenhum card na fila.',
  queueWaiting: '{shown} de {total} na fila',
  forbidden: 'Esta área é só para revisores.',
  approve: 'Aprovar',
  request: 'Pedir ajuste',
  reject: 'Rejeitar',
  note: 'Nota',
  metrics: 'Concordância do corretor',
  metricsCounts: '{overridden} notas alteradas em {submitted} correções',
  metricsError: 'Não foi possível carregar a concordância.',
  seeds: 'Mapas prontos',
  copy: 'Adicionar aos meus mapas',
  publish: 'Publicar versão',
  publishBlocked: 'Ainda há cards em rascunho. Aprove a fila antes de publicar.',
  changelog: 'O que mudou nesta edição',
  temporalMark: 'Marco temporal',
  publishMark: 'Informe o marco temporal da edição.',
  editOnComputer: 'Editar no computador',
  filterAll: 'Todos',
  filterDraft: 'Rascunho',
  filterAi: 'Sinal da IA',
  filterDisagree: 'Discordância',
  filterMap: 'Mapa',
  source: 'Fonte: {fonte}',
  studentAnswer: 'Resposta do aluno',
  noAnswer: 'Sem texto de resposta.',
  verdict: 'Veredito',
  noVerdict: 'Sem veredito.',
  critical: 'Erro crítico',
  verdictName: { correct: 'Correto', partial: 'Parcial', incorrect: 'Incorreto' },
  rubricCorrect: 'Rubrica estava certa',
  rubricAdjust: 'Ajustar rubrica',
  point: 'Ponto {n} da rubrica',
  crm: 'CRM',
  crmSave: 'Salvar CRM',
  crmSaved: 'CRM salvo. As próximas aprovações levam esse registro.',
  ownCard: 'Outro revisor precisa aprovar este card. Você criou o mapa.',
  before: 'Versão anterior',
  diffOut: 'Saiu: {text}',
  diffIn: 'Entrou: {text}',
  diffSame: 'A rubrica está igual à versão anterior.',
  crmPlaceholder: '123456-SP',
  onlyReviewer: 'Só o revisor médico assina.',
  crmRequired: 'Informe seu CRM para assinar decisões.',
  crmRequiredLink: 'Informar CRM',
  crmFormat: 'Formato do CRM: número e UF, como 123456-SP.',
  stateChanged: 'Este item já foi decidido ou mudou. A fila foi atualizada.',
  publishPending: 'Ainda há {n, plural, one {# card} other {# cards}} em rascunho. Aprove a fila antes de publicar.',
  provenance: 'Revisado por {name}, CRM {crm}, em {date}',
} as const;
