// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const home = {
  greeting: 'Boa {periodo}. {n, plural, =0 {Nenhum conceito espera} one {# conceito espera} other {# conceitos esperam}} por você.',
  reviewSection: 'Revisão de hoje',
  reviewSummary: '{boards, plural, one {# mapa} other {# mapas}}, {n, plural, one {# conceito} other {# conceitos}} para fixar hoje.',
  queueStart: 'A fila começa por {card}, que vence hoje com lembrança estimada de {pct}%.',
  startReview: 'Começar revisão',
  reviewOnlyBoard: 'Só {board}',
  reviewOpenLabel: 'Abrir o mapa {mapa}',
  continueFrom: 'Continue de onde parou',
  seeAll: 'Ver todos os mapas',
  coverage: 'Cobertura da matriz do Enamed',
  coverageHint: 'Conteúdo mapeado, não peso de prova',
  weekTitle: 'Sua semana',
  weekStreak: '{n, plural, =0 {0 dias seguidos} one {# dia seguido} other {# dias seguidos}}',
  weekDays: { seg: 'Seg', ter: 'Ter', qua: 'Qua', qui: 'Qui', sex: 'Sex', sab: 'Sáb', dom: 'Dom' },
  done: 'Feitos',
  planned: 'Previstos',
  reviewedToday: '{n} de {total} revisados hoje',
  reviewedTitle: '{n} de {total}',
  reviewedCaption: 'revisados hoje',
  nextReviewsTitle: 'Próximas revisões',
  nextReviews: { today: 'Hoje', tomorrow: 'Amanhã', saturday: 'Sábado', sunday: 'Domingo' },
  startSomething: 'Comece algo novo',
  generatePdf: 'Gerar mapa de um PDF',
  generatePdfDesc: 'Rascunho por IA para revisar',
  importAnki: 'Importar do Anki',
  importAnkiDesc: 'Seu .apkg vira mapa',
  seedMap: 'Mapa pronto',
  seedMapDesc: 'Revisado por médico, com fonte',
  salutation: { morning: 'Bom dia', afternoon: 'Boa tarde', evening: 'Boa noite' },
  greetingDue: '{saudacao}. {n, plural, one {# conceito espera} other {# conceitos esperam}} por você.',
  greetingNone: '{saudacao}. Nada vence hoje.',
  greetingNoMaps: '{saudacao}. Seu primeiro mapa começa aqui.',
  reviewEmptyTitle: 'Nada para revisar hoje.',
  reviewEmptyBody: 'Quando um conceito vencer, ele entra aqui. Que tal abrir um mapa e conectar mais um card?',
  noMapsTitle: 'Crie o seu primeiro mapa.',
  noMapsBody: 'Cada card do mapa entra na revisão espaçada e a cobertura da matriz aparece aqui.',
  openMaps: 'Abrir meus mapas',
  coverageEmpty: 'Ligue um mapa a um item da matriz ao criar para ver a cobertura aqui.',
  weekBarLabel: '{dia}: {done} feitos, {planned} previstos',
  loadError: 'Não foi possível carregar o resumo de hoje.',
  slider: {
    title: 'Continue de onde parou',
    viewAll: 'Ver todos',
    prevArrow: 'Mapas anteriores',
    nextArrow: 'Próximos mapas',
    counter: '{from}–{to} de {total}',
    a11y: {
      containerMessage: 'Carrossel de mapas. Use as setas para navegar.',
      slideLabelMessage: '{{index}} de {{slidesLength}}',
    },
    newCard: {
      aria: 'Criar um novo mapa',
      title: 'Novo mapa',
      text: 'Comece do zero, de um PDF ou do seu Anki.',
      freeRemaining: 'Você ainda pode criar {n, plural, one {# mapa} other {# mapas}} no plano Free.',
    },
    lockedCard: {
      title: 'Limite do plano Free',
      text: 'O Free permite até {max} mapas. Faça upgrade para criar o próximo.',
      aria: 'Criar novo mapa (bloqueado no plano Free)',
    },
  },
} as const;
