// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const inspector = {
  essentialLabel: 'Essencial',
  reviewerLabel: 'Revisor',
  temporalLabel: 'Marco temporal',
  sourceLabel: 'Fonte',
  statusLabel: 'Status',
  status: { draft: 'Rascunho', approved: 'Aprovada' },
  aiDraft: 'Gerado por IA, não revisado',
  reviewerInfo: '{revisor} · CRM {crm}',
  reviewerSourceNote: 'Corrigido contra a rubrica do card, revisada por {revisor} · CRM {crm}. Fonte: {fonte}.',
  coverage: 'Cobertura de {pct, plural, one {# por cento} other {# por cento}}',
  version: 'Versão',
  reviewThis: 'Revisar este card',
  noRubricWarning: 'Este card ainda não tem rubrica. A correção por texto só funciona contra uma rubrica aprovada; sem ela, o desafio usa autoavaliação.',
  noHistory: 'Nenhuma tentativa ainda. O histórico aparece depois da primeira revisão.',
  // T5 (editor v2)
  tabs: { content: 'Conteúdo', rubric: 'Rubrica', origin: 'Origem', history: 'Histórico' },
  nextToday: 'próxima revisão: hoje',
  nextOn: 'próxima revisão: {data}',
  connections: 'Conexões · {n}',
  noConnections: 'Nenhuma conexão ainda.',
  unlabelled: 'sem rótulo',
  outgoing: 'Sai para',
  incoming: 'Chega de',
  optionalLabel: 'Opcional',
  rubricApproved: 'v{v} · usada na correção por IA',
  rubricDraft: 'v{v} · aguardando revisão editorial',
  editorialLabel: 'Revisão editorial',
  noSource: 'Você ainda não adicionou fonte',
  noMark: 'Sem marco (card privado)',
  changelog: 'O que mudou na edição {mark}',
  noEditorial: 'Sem revisão editorial',
  reviewerPending: 'Aprovado; nome e CRM do revisor indisponíveis',
  reviewerNamed: 'Revisado por {revisor}',
  noSummary: 'Sem resumo ainda.',
} as const;
