// F31 (G23 T4/T5): Biblioteca de mapas prontos, Ver, Usar e Reportar erro.
export const mapLibrary = {
  tabsLabel: 'Mapas',
  tabMine: 'Meus mapas',
  tabLibrary: 'Biblioteca',
  title: 'Biblioteca de mapas prontos',
  lead: 'Mapas revisados por médico, prontos para estudar. Veja à vontade; ao usar, você ganha uma cópia sua, editável.',
  empty: 'Nenhum mapa pronto com esses filtros.',
  none: 'Os mapas prontos aparecem aqui quando a revisão editorial publicar a primeira edição.',
  error: 'Não foi possível carregar a biblioteca. Tente de novo.',
  filters: 'Filtros da biblioteca',
  search: 'Buscar por tema',
  area: 'Área',
  level: 'Nível',
  allAreas: 'Todas as áreas',
  allLevels: 'Todos os níveis',
  levelN: 'Nível {n}',
  badgeTop10: 'Top 10 ENAMED',
  cards: '{n} cards',
  minutes: '~{n} min',
  version: 'Versão {v}',
  mark: 'Marco: {mark}',
  reviewedBy: 'Revisado por Dr(a). {name}, CRM {crm}',
  see: 'Ver',
  use: 'Usar este mapa',
  using: 'Copiando…',
  useError: 'Não foi possível copiar o mapa. Tente de novo.',
  disclaimer: 'Conteúdo educacional. Não substitui diretriz clínica nem supervisão.',
  terms: 'Termos de Uso',
  back: 'Voltar à biblioteca',
  readOnly: 'Leitura: este é o mapa original. Use-o para ganhar uma cópia que você pode editar.',
  trail: 'Trilha de estudo',
  cardsHeading: 'Cards do mapa',
  prereqNote: 'Ordem da trilha {n}',
  sources: 'Fontes: {list}',
  loadError: 'Não foi possível abrir este mapa.',
  report: 'Reportar erro',
  reportTitle: 'Reportar erro neste card',
  reportLead: 'Conte o que está errado. Um revisor médico analisa e decide.',
  reportNote: 'O que está errado?',
  reportSend: 'Enviar',
  reportSent: 'Recebido. Um revisor vai analisar este card.',
  reportError: 'Não foi possível enviar. Tente de novo.',
  close: 'Fechar',
} as const;
