// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const map = {
  canvasLabel: 'Mapa {title}',
  hint: 'Clique em um conceito para abrir. Arraste para reorganizar o mapa.',
  listEmpty: 'Nenhum card com esse filtro.',
  stats: '{cards, plural, =0 {0 conceitos} one {# conceito} other {# conceitos}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
  titleLabel: 'Nome do mapa',
  titleEdit: 'Renomear mapa',
  eyebrow: 'Seu mapa de {area}',
  attribution: 'React Flow',
  legend: 'Legenda dos estados',
  toolbar: {
    label: 'Ferramentas do mapa',
    concept: 'Card',
    flow: 'Fluxograma',
    image: 'Imagem',
    case: 'Caso',
    add: 'Adicionar {type}',
    organize: 'Organizar',
    heat: 'Lembrança estimada',
    mode: 'Modo do mapa',
    explore: 'Explorar',
    challenge: 'Desafio',
    move: 'Mover',
    connect: 'Conexão',
    addCard: 'Card',
  },
  cardType: {
    concept: 'Conceito',
    flow: 'Fluxograma',
    image: 'Imagem',
    case: 'Caso',
  },
  newCardTitle: {
    concept: 'Novo conceito',
    flow: 'Novo fluxograma',
    image: 'Nova imagem',
    case: 'Novo caso',
    note: 'Novo conteúdo',
  },
  card: {
    open: 'Abrir',
    openLabel: 'Abrir {title}',
    menu: 'Mais ações de {title}',
    delete: 'Excluir',
    drag: 'Arrastar {title}',
    label: '{type}: {title}',
  },
  edge: {
    labelPlaceholder: 'Rótulo da conexão',
    labelInput: 'Rótulo da conexão',
    editLabel: 'Editar rótulo: {label}',
    addLabel: 'Adicionar rótulo',
    noLabel: 'Sem rótulo não vira pergunta',
    empty: '+ rótulo',
  },
  zoom: {
    in: 'Aproximar',
    out: 'Afastar',
    fit: 'Ajustar à tela',
    minimap: 'Mini-mapa',
    controls: 'Controles de zoom',
    percent: '{n}%',
  },
  save: {
    saving: 'Salvando…',
    offline: 'Sem conexão, salvando depois',
    error: 'Não conseguimos salvar suas mudanças.',
  },
  delete: {
    title: 'Excluir os cards selecionados?',
    body: 'As conexões desses cards também saem. Você pode desfazer com Ctrl+Z.',
    confirm: 'Excluir',
  },
  limit: 'Este mapa chegou ao limite de {max} cards.',
  ago: {
    minutes: '{n} min',
    hours: '{n} h',
  },
  a11y: {
    node: 'Enter ou espaço seleciona o card. Delete exclui; Esc cancela.',
    nodeKeyboard: 'Enter ou espaço seleciona o card. Use as setas para mover; Delete exclui; Esc cancela.',
    moved: 'Card movido. Nova posição: x {x}, y {y}',
    edge: 'Enter ou espaço seleciona a conexão. Delete exclui; Esc cancela.',
    handle: 'Porta de conexão',
  },
  inspector: {
    label: 'Detalhes do card',
    empty: 'Selecione um card no mapa',
    shortcuts: 'Atalhos',
    addCard: 'Adicionar card',
    challenge: 'Desafiar',
    yourCard: 'Card do seu mapa',
    type: 'Tipo',
    summary: 'Resumo',
    noSummary: 'Sem resumo ainda.',
    nextReview: 'Próxima revisão: {data}',
    noReview: 'Ainda sem revisões',
    provenance: 'Origem e edição',
    source: 'Fonte',
    temporalMark: 'Marco temporal',
    reviewer: 'Revisor',
    none: '—',
    reviewThis: 'Revisar este conceito',
    viewSource: 'Ver fonte e versão',
    status: {
      draft: 'Rascunho',
      approved: 'Aprovado',
    },
  },
} as const;
