// P-507 (D-1069): one module per namespace, so a page only ships the namespaces it uses (webpack keeps or drops whole modules).
export const newMap = {
  step: { one: 'Início', two: 'Detalhes', three: 'Material' },
  step1Title: 'Como você quer começar?',
  step1Desc: 'Você muda de ideia quando quiser. O mapa é seu e continua editável.',
  path: {
    pdf: 'Do meu PDF',
    pdfDesc: 'Resumo, apostila ou capítulo. A IA monta um rascunho do mapa para você revisar.',
    pdfTag: 'Rascunho por IA',
    anki: 'Do meu Anki',
    ankiDesc: 'Importe o arquivo .apkg: os cards viram conceitos e a oclusão de imagem vem junto.',
    ankiTag: 'Importação',
    seed: 'De um mapa pronto',
    seedDesc: 'Mapas revisados por médico, com fonte, versão e marco temporal da edição.',
    seedTag: 'Revisado',
    blank: 'Em branco',
    blankDesc: 'Comece do zero e monte do seu jeito, card por card.',
    blankTag: 'Livre',
  },
  step2Title: 'Sobre o que é este mapa?',
  step2Desc: 'A área e o item da matriz do Enamed organizam a cobertura e sugerem o nome.',
  areaLabel: 'Grande área',
  itemLabel: 'Item da matriz',
  nameLabel: 'Nome do mapa',
  step3Title: {
    pdf: 'Envie o seu material',
    anki: 'Envie o seu arquivo',
    seed: 'Escolha o mapa pronto',
    blank: 'Tudo pronto para criar',
  },
  step3Desc: {
    pdf: 'Aceitamos PDF de resumos e capítulos. O resultado é um rascunho que você revisa antes de estudar.',
    anki: 'Seus cards viram conceitos; a repetição espaçada começa do zero.',
    seed: 'Cada mapa vem com fontes, rubricas aprovadas e a edição do Enamed em que foi revisado.',
    blank: 'Confira os dados. Você poderá mudar tudo depois no editor.',
  },
  dropTitle: { pdf: 'Arraste seu PDF aqui', anki: 'Arraste seu arquivo .apkg aqui' },
  dropDesc: { pdf: 'ou escolha um arquivo do computador', anki: 'ou escolha o arquivo exportado do Anki' },
  cta: { pdf: 'Gerar rascunho do mapa', anki: 'Importar para o mapa', seed: 'Adicionar ao meu mapa', blank: 'Criar mapa' },
  generating: '{stage}… {n}%',
  generatingLabel: 'Progresso da geração do mapa',
  pdfUnreadable: 'Não foi possível ler este PDF. Envie um arquivo com texto selecionável.',
  aiNotConfigured: 'A geração de mapas por IA não está disponível neste ambiente. Crie o mapa em branco ou tente mais tarde.',
  pdfTooLarge: 'O PDF passa de 10 MB. Envie um arquivo menor ou divida o material.',
  pdfInvalid: 'Este arquivo não é um PDF. Escolha um arquivo .pdf.',
  cancel: 'Cancelar geração',
  canceled: 'Geração cancelada. A cota foi devolvida.',
  dropped: '{n} cards foram descartados por não terem trecho de origem no texto. Confira o mapa.',
  openMap: 'Abrir o mapa',
  generateTimeout: 'A geração passou de 10 minutos e foi interrompida. A cota foi devolvida.',
  stage: { ocr: 'Lendo o PDF', extract: 'Extraindo conceitos', layout: 'Organizando o mapa' },
  previewLabel: 'Prévia do seu mapa',
  limits: { notIncluded: 'não incluso', unlimited: 'sem limite', perMonth: '{n} por mês' },
  info: {
    howLabel: 'Como funciona',
    getsLabel: 'Você recebe',
    limitLabel: 'Limites',
    pdf: {
      title: 'Do PDF ao rascunho',
      lead: 'A IA lê o seu material e propõe um mapa. Você revisa antes de estudar.',
      s1: 'Você envia um resumo, apostila ou capítulo em PDF.',
      s2: 'A IA extrai conceitos, fluxogramas de conduta e as conexões entre eles.',
      s3: 'Tudo chega marcado como “rascunho não revisado”, para você conferir.',
      gets: 'Um mapa editável, com rubricas de correção sugeridas. Cada card leva a marca de rascunho até a sua revisão.',
      limit: 'Mapas gerados de PDF: {free} no Free, {pro} no Pro.',
      status: 'Em breve: a geração por IA ainda não está ativa.',
    },
    anki: {
      title: 'Do Anki para o mapa',
      lead: 'Importe o arquivo .apkg e seus cards viram um mapa que você liga e edita.',
      s1: 'No Anki, exporte o baralho como .apkg com “Support older Anki versions” marcado.',
      s2: 'Cada nota vira um card. O cloze mantém as lacunas; a oclusão de imagem vira card de imagem com máscaras.',
      s3: 'Você dá nome ao mapa, confere o resumo e importa. Os baralhos viram colunas.',
      gets: 'Um mapa só, com os baralhos como colunas e as imagens. O agendamento do Anki não é trazido: a repetição espaçada começa do zero.',
      limit: 'Free: {freeImports, plural, one {# importação} other {# importações}} de até {free} cards. Pro: {pro}. As tags do Anki não entram.',
      status: 'Disponível agora.',
    },
    seed: {
      title: 'Mapas prontos e revisados',
      lead: 'Mapas montados e revisados por médico, com fonte e marco temporal.',
      s1: 'Cada card traz a fonte, a edição e o nome e CRM de quem revisou.',
      s2: 'Você escolhe um mapa e o adiciona à sua biblioteca.',
      s3: 'Depois, liga o que já sabe e estuda com a revisão espaçada.',
      gets: 'Conteúdo aprovado por médico revisor. Nada gerado por IA é publicado sem essa revisão.',
      limit: 'Os limites serão definidos junto com a primeira edição.',
      status: 'A lista mostra a edição já publicada pela revisão editorial.',
    },
    blank: {
      title: 'Comece do zero',
      lead: 'Um mapa vazio e você no comando, card por card.',
      s1: 'Dê um nome ao mapa e escolha o item da matriz do Enamed.',
      s2: 'Adicione o primeiro card e escreva o que você já sabe.',
      s3: 'Ligue os cards com rótulos como “causa”, “leva a” e “trata com”.',
      gets: 'Um card central, pronto para você ligar ao resto do que sabe. Nada é gerado por IA.',
      limit: 'Free: {boards} mapas e {cards} cards. Pro: sem limite.',
      status: 'Disponível agora.',
    },
  },
  stepsLabel: 'Passos',
  stepDone: 'concluído',
  areaSoon: 'Em breve',
  noItems: 'Nenhum item da matriz disponível para esta área.',
  seedSoon: 'Os mapas prontos aparecem aqui quando a revisão editorial publicar a primeira edição.',
  replaceFile: 'Trocar',
  fileMeta: '{mb} MB',
  opts: {
    pdf: { flows: 'Gerar fluxogramas de conduta quando houver algoritmo no texto', rubrics: 'Gerar rubricas de correção para cada card' },
    anki: { tags: 'Transformar tags do Anki em seções do mapa', images: 'Trazer imagens e máscaras de oclusão' },
  },
  previewSub: {
    pdf: 'Rascunho por IA a partir do seu PDF',
    anki: 'Importado do seu arquivo do Anki',
    seed: 'Mapa pronto, revisado por médico',
    blank: 'Mapa em branco',
  },
  sat: {
    concept: 'Conceito',
    flow: 'Fluxograma',
    image: 'Imagem',
    case: 'Caso clínico',
    ankiCard: 'Card do Anki',
    definition: 'Definição',
    conduct: 'Conduta',
    criteria: 'Critérios',
    case1: 'Caso 1',
    figure: 'Figura',
    treatment: 'Tratamento',
    occlusion: 'Oclusão',
    diagnosis: 'Diagnóstico',
    exams: 'Exames',
  },
  closeLabel: 'Cancelar e voltar',
  filePickerLabel: 'Escolher arquivo',
  seedsLabel: 'Mapas prontos',
  backButton: 'Voltar',
  continueButton: 'Continuar',
} as const;
