import {beforeEach,describe,expect,it} from 'vitest';
import {questionAdminCatalogResultSchema,questionAdminCatalogPageSchema,questionEditorialDetailSchema,questionVersionHistoryResultSchema,questionReviewHistoryPageSchema,questionCatalogMetricsSchema,questionSourceListSchema,questionImportListSchema,questionEditorialQueueSchema} from '@remoa/contracts';
import {resetCatalogHistoryScenario,catalogHistoryRoute} from './catalog-history-fixtures';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function read(path:string){let data:unknown;let failure:{code:string;status?:number;message?:string}|undefined;const url=new URL(path,'http://127.0.0.1');const handled=catalogHistoryRoute(url.pathname,'GET',url,value=>{data=value;},(code,status,message)=>{failure={code,status,message};});return{data,failure,handled};}
beforeEach(()=>resetCatalogHistoryScenario('catalog-normal'));
describe('strict dedicated synthetic catalog/histories',()=>{
 it('returns 66 latest rows in bound pages without duplicates, exposes no list answers/assets and rejects role/filter cursor reuse',()=>{let path='/v1/admin/questions/catalog?limit=25&versions=latest';const ids:string[]=[];for(let page=0;page<3;page++){const result=questionAdminCatalogResultSchema.parse(read(path).data);expect(JSON.stringify(result.items)).not.toMatch(/correctKey|assets|objectKey|explanation|referenceRef|ownerId/);ids.push(...result.items.map(item=>item.id));if(result.nextCursor){expect(read('/v1/editorial/questions/catalog?limit=25&versions=latest&cursor='+encodeURIComponent(result.nextCursor)).failure?.status).toBe(409);expect(read('/v1/admin/questions/catalog?limit=25&versions=latest&status=published&cursor='+encodeURIComponent(result.nextCursor)).failure?.status).toBe(409);path='/v1/admin/questions/catalog?limit=25&versions=latest&cursor='+encodeURIComponent(result.nextCursor);}else expect(page).toBe(2);}expect(ids).toHaveLength(66);expect(new Set(ids).size).toBe(66);});
 it('distinguishes draft latest from previous published all and applies source/type/search',()=>{const latest=questionAdminCatalogPageSchema.parse(read('/v1/editorial/questions/catalog?versions=latest&search=família%20autoral').data);expect(latest.items.map(item=>item.catalogStatus)).toEqual(['draft']);const all=questionAdminCatalogPageSchema.parse(read('/v1/editorial/questions/catalog?versions=all&search=família%20autoral').data);expect(all.items.map(item=>item.catalogStatus)).toEqual(['draft','published']);const filtered=questionAdminCatalogPageSchema.parse(read('/v1/editorial/questions/catalog?versions=all&search=Registro&sourceId='+id(210)+'&type=discursive').data);expect(filtered.items.length).toBeGreaterThan(0);expect(filtered.items.every(item=>item.sourceId===id(210)&&item.type==='discursive')).toBe(true);expect(read('/v1/editorial/questions/catalog?private=true').failure?.status).toBe(422);});
 it('returns strict inventory/legacy/detail DTOs and audits only administrative histories',()=>{questionCatalogMetricsSchema.parse(read('/v1/admin/questions/metrics').data);questionSourceListSchema.parse(read('/v1/admin/questions/sources').data);questionImportListSchema.parse(read('/v1/admin/questions/imports').data);questionEditorialQueueSchema.parse(read('/v1/editorial/questions').data);questionEditorialDetailSchema.parse(read('/v1/editorial/questions/'+id(1201)).data);const family=questionVersionHistoryResultSchema.parse(read('/v1/admin/questions/'+id(1201)+'/history').data);expect(family.canonicalId).toBe(id(1200));expect(family.items.map(item=>item.version)).toEqual([2,1]);const selected=questionReviewHistoryPageSchema.parse(read('/v1/editorial/questions/'+id(1200)+'/reviews').data);expect(selected.items.every(item=>item.questionId===id(1200)&&item.contentHash==='c'.repeat(64))).toBe(true);expect(selected.items).toHaveLength(25);expect(selected.nextCursor).not.toBeNull();const more=questionReviewHistoryPageSchema.parse(read('/v1/editorial/questions/'+id(1200)+'/reviews?cursor='+encodeURIComponent(selected.nextCursor!)).data);expect(more.items).toHaveLength(6);});
 it('keeps dedicated error/disabled/mismatch scenarios distinct and never falls through generic fixtures',()=>{resetCatalogHistoryScenario('catalog-error');expect(read('/v1/admin/questions/catalog').failure?.status).toBe(503);questionAdminCatalogResultSchema.parse(read('/v1/admin/questions/catalog').data);resetCatalogHistoryScenario('catalog-flagoff');expect(read('/v1/admin/questions/catalog').failure?.status).toBe(404);questionEditorialQueueSchema.parse(read('/v1/editorial/questions').data);resetCatalogHistoryScenario('catalog-history-mismatch');const wrong=questionVersionHistoryResultSchema.parse(read('/v1/admin/questions/'+id(1201)+'/history').data);expect(wrong.questionId).not.toBe(id(1201));expect(read('/v1/not-implemented').handled).toBe(true);expect(read('/v1/not-implemented').failure?.status).toBe(404);});
});
