import React from 'react';
import {createRoot} from 'react-dom/client';
import '@/app/globals.css';
import './style.css';
import {QuestionsHub} from '@/features/questions/questions-hub';
import {SessionScreen} from '@/features/questions/session-screen';
import {SessionScreen as ChallengeSessionScreen} from '@/features/challenge-ai/session-screen';
import {ExamsScreen,ExamDetailScreen,SessionsScreen} from '@/features/questions/exams-screen';
import {InventoryScreen,ImportListScreen} from '@/features/admin/questions/inventory-screen';
import {SourcesScreen} from '@/features/admin/questions/sources-screen';
import {UploadScreen} from '@/features/admin/questions/upload-screen';
import {ImportDetailScreen} from '@/features/admin/questions/import-detail-screen';
import {QuestionEditorialQueue} from '@/features/editorial/questions/queue-screen';
import {QuestionEditorialDetail} from '@/features/editorial/questions/detail-screen';
import {QuestionReportsQueue,QuestionReportDetail} from '@/features/editorial/questions/reports-screen';
import {DialogBoundaryHarness} from './dialog-boundary';
const path=location.pathname;const id=path.split('/').at(-1)!;const admin=new URLSearchParams(location.search).get('role')==='admin';let screen:React.ReactNode;
if(path==='/qa/dialog-boundary')screen=<DialogBoundaryHarness/>;else if(/^\/app\/mapas\/[^/]+\/desafio-ia$/.test(path))screen=<ChallengeSessionScreen sessionId={new URLSearchParams(location.search).get('session')??''} boardId={path.split('/')[3]!}/>;else if(path==='/admin/questoes/relatos'||path==='/app/editorial/questoes/relatos')screen=<QuestionReportsQueue admin={path.startsWith('/admin')}/>;else if(path.startsWith('/admin/questoes/relatos/')||path.startsWith('/app/editorial/questoes/relatos/'))screen=<QuestionReportDetail id={id} admin={path.startsWith('/admin')}/>;else if(path.startsWith('/app/simulados/'))screen=<SessionScreen sessionId={id}/>;else if(path==='/app/simulados')screen=<SessionsScreen/>;else if(path.startsWith('/app/provas/'))screen=<ExamDetailScreen examId={id}/>;else if(path==='/app/provas')screen=<ExamsScreen/>;else if(path==='/admin/questoes/fontes')screen=<SourcesScreen/>;else if(path==='/admin/questoes/importar')screen=<UploadScreen/>;else if(path.startsWith('/admin/questoes/importacoes/'))screen=<ImportDetailScreen id={id}/>;else if(path==='/admin/questoes/importacoes')screen=<ImportListScreen/>;else if(path==='/admin/questoes')screen=<InventoryScreen/>;else if(path.startsWith('/app/editorial/questoes/'))screen=<QuestionEditorialDetail id={id} canAdmin={admin} canReview={!admin}/>;else if(path==='/app/editorial/questoes')screen=<QuestionEditorialQueue/>;else screen=<QuestionsHub/>;
createRoot(document.getElementById('root')!).render(<><aside className="border-b border-border bg-surface px-4 py-3 text-sm">{(import.meta as ImportMeta & {env:{VITE_F33_REAL_API?:boolean}}).env.VITE_F33_REAL_API?'Harness: HTTP e PostgreSQL isolado reais; JWT e armazenamento locais de teste.':'Harness de teste — respostas sintéticas de API; nenhuma gravação no Remoa.'}</aside><main className="min-w-0 p-4 md:p-8">{screen}</main></>);
