/* eslint-disable @typescript-eslint/no-explicit-any -- Raw synthetic request bodies exist only in the isolated QA harness. */
/** Synthetic, nonmedical fixtures. Runs only inside this explicitly started Vite QA harness. */
import type {IncomingMessage,ServerResponse} from 'node:http';
import {resetCatalogHistoryScenario,catalogHistoryRoute} from './catalog-history-fixtures';
import {resetResultReviewScenario,resultReviewRoute} from './result-review-fixtures';
import * as recoverySchemas from '@remoa/contracts';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const originalPdf=readFileSync(fileURLToPath(new URL('../artifacts/recovery-source/original-exam.pdf',import.meta.url)));
const originalPng=readFileSync(fileURLToPath(new URL('../artifacts/recovery-source/original-page-1.png',import.meta.url)));
const originalPdfSha=createHash('sha256').update(originalPdf).digest('hex');
const nativePages=new Map([1,2].map(page=>{const bytes=page===1?originalPng:readFileSync(fileURLToPath(new URL('../artifacts/recovery-source/original-page-2.png',import.meta.url)));return[page,{bytes,width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),sha:createHash('sha256').update(bytes).digest('hex')}] as const;}));
const recoveryDocument={id:'00000000-0000-4000-8000-000000000005',kind:'exam',sha256:originalPdfSha,bytes:originalPdf.length,pages:4};
export const ID=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const now=()=>new Date().toISOString();const hash='a'.repeat(64);const base='http://127.0.0.1:4317';
const audit={id:1,createdAt:now(),actorType:'admin',actor:null,action:'question.import',targetType:null,targetId:null,targetLabel:null,reason:'Teste sintético',result:'success',denial:null,before:null,after:null,ipHash:null,userAgent:null,requestId:null};
const long='https://example.org/'+ 'x'.repeat(200);
const q={id:ID(1),canonicalId:ID(1),version:1,type:'objective',stem:'Amostra sintética não médica. Interprete o diagrama. '+long,alternatives:[{key:'A',text:'Comparar os círculos '+long},{key:'B',text:'Ignorar a relação'}],origin:'official_exam',visibility:'public',availability:'active',difficulty:'medium',topicId:null,areaId:null,sourceId:ID(2),sourceLabel:'Fonte demonstrativa',occurrences:{items:[{examId:ID(3),name:'Prova demonstrativa',institution:'Instituição sintética',year:2026,edition:'Teste',booklet:'Um',ordinal:0,originalNumber:'01',sourceId:ID(2),sourceLabel:'Fonte demonstrativa'}],total:1,truncated:false},reviewed:true,assets:[{id:ID(8),alt:'Dois círculos sintéticos de tamanhos distintos',url:base+'/diagram.svg',provenance:null}],boardId:null,cardIds:[],createdAt:now()};
const source={id:ID(2),name:'Fonte sintética',publisher:'Instituição demonstrativa',url:'https://example.org/prova',rightsStatus:'authorized',rightsEvidence:'Autorização fictícia para teste de interface',rightsScope:'Apenas fixture do harness',rightsExpiresAt:null,accessedAt:now(),documentVersion:'1',createdAt:now(),updatedAt:now()};
const paper={id:ID(3),name:'Prova demonstrativa',institution:'Instituição sintética',year:2026,edition:'Teste',booklet:'Um',sourceId:ID(2),version:1,durationSec:120,questionCount:1,status:'published'};
const reference={questionId:q.id,version:1,correctKey:'A',explanation:'Comentário sintético: compare os círculos.',distractorNotes:null,annulled:false,reviewed:true,reviewerName:'Revisor sintético',reviewerCrm:'CRM-DEMO',referenceDate:'2026-10-08',sourceUrl:'https://example.org/prova',obsolete:false};
const reviewQuestion={id:q.id,canonicalId:q.canonicalId,version:1,type:q.type,difficulty:q.difficulty,stem:q.stem,alternatives:q.alternatives,correctKey:'A',explanation:reference.explanation,areaId:null,topicId:null,origin:q.origin,sourceId:q.sourceId,catalogStatus:'draft',rightsStatus:'authorized',availability:'active',integrityConfirmed:true,keyFinal:true,enamedConfirmed:true,contentHash:hash,reviewedHash:null,reviewerName:null,reviewerCrm:null,referenceDate:null,assets:[]};
const doc={id:ID(5),kind:'exam',sha256:hash,bytes:1024,pages:2};const keyDoc={...doc,id:ID(6),kind:'answer_key'};
const candidate={id:ID(7),importId:ID(4),chunkId:null,ordinal:1,originalNumber:'01',payload:{stem:'Questão extraída sintética',alternatives:[{key:'A',text:'Círculo maior'},{key:'B',text:'Círculo menor'}],correctKey:'A',annulled:false,explanation:null,areaId:null,topicId:null,keyFinal:false,integrityConfirmed:false,imagesConfirmed:false,assets:[],imageRefs:[{page:1,bbox:{x:20,y:30,width:500,height:300},method:'text',objectKey:'private/demo',provenance:{documentId:doc.id,page:1,bbox:[.1,.1,.7,.4]}}]},confidence:{stem:.9,answerKey:.5},provenance:[{documentId:doc.id,page:1,bbox:[.1,.1,.7,.4]}],issues:['ambiguous_key'],fingerprint:hash,duplicateOf:null,questionId:null as string|null,state:'needs_review',revision:0,createdAt:now(),updatedAt:now()};
let scenario='normal';let userState={favorite:false,doubtful:false,annotation:''};let session=makeSession('simulation');let progress=makeProgress();let currentCandidate=structuredClone(candidate);let currentQuestion=structuredClone(reviewQuestion);let reviews:null|Record<string,unknown>=null;let calls:{path:string;method:string;body:unknown}[]=[];
function makeSession(mode:string){return {id:ID(20),mode,status:'active',revision:0,startedAt:now(),deadline:new Date(Date.now()+120000).toISOString(),finishedAt:null as string|null,serverTime:now(),items:[{id:ID(21),position:0,question:q,originalNumber:'01',selectedKey:null as string|null,answered:false,doubtful:false,revision:0}]};}
function makeProgress(){return {id:ID(4),answerKeyPages:null,status:'review',totalPages:2,completedPages:2,candidates:1,accepted:0,rejected:0,duplicate:0,costCents:0,errorCode:null,updatedAt:now()};}
function report(){const answer=session.items[0]!;return {sessionId:session.id,version:1,correct:answer.selectedKey==='A'?1:0,incorrect:answer.answered&&answer.selectedKey!=='A'?1:0,unanswered:answer.answered?0:1,annulled:0,denominator:1,score:answer.selectedKey==='A'?1:0,items:[{itemId:ID(21),result:answer.selectedKey==='A'?'correct':answer.answered?'incorrect':'unanswered',reference}]};}
export async function apiMiddleware(req:IncomingMessage,res:ServerResponse,next:()=>void){const url=new URL(req.url??'/',base);const path=url.pathname;if(!path.startsWith('/v1/')&&!path.startsWith('/__test/')&&path!='/diagram.svg'&&path!='/recovery-page.pdf'&&path!='/recovery-original.png')return next();if(path==='/recovery-page.pdf'){res.setHeader('content-type','application/pdf');res.setHeader('cache-control','no-store');return res.end(recoveryDetail?originalPdf:recoveryPdf());}if(path==='/recovery-original.png'){res.setHeader('content-type','image/png');res.setHeader('cache-control','no-store');const image=nativePages.get(Number(url.searchParams.get('page')??1));if(!image){res.statusCode=404;return res.end();}return res.end(image.bytes);}if(path==='/diagram.svg'){res.setHeader('content-type','image/svg+xml');return res.end('<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="600" viewBox="0 0 1600 600"><rect fill="#f1ecff" width="1600" height="600"/><circle cx="500" cy="300" r="210" fill="#9568ee"/><circle cx="1100" cy="300" r="110" fill="#cbb7f2"/></svg>');}let body:Record<string,any>={};for await(const chunk of req)body.__raw=(body.__raw??'')+chunk;if(body.__raw&&req.headers['content-type']?.includes('application/json'))body=JSON.parse(body.__raw);calls.push({path:req.url??'',method:req.method??'GET',body});const ok=(data:unknown)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:true,data}));};const fail=(code:string,status=400,message=code)=>{res.statusCode=status;res.setHeader('content-type','application/json');res.end(JSON.stringify({error:{code,message}}));};
if(path==='/__test/reset'){scenario=url.searchParams.get('scenario')??'normal';session=makeSession(url.searchParams.get('mode')??'simulation');progress=makeProgress();currentCandidate=structuredClone(candidate);currentQuestion=structuredClone(reviewQuestion);reviews=null;userState={favorite:false,doubtful:false,annotation:''};calls=[];recoveryDetail=scenario.startsWith('recovery')?makeRecoveryDetail(`http://${req.headers.host}`):null;recoveryConflictPending=scenario==='recovery-conflict';pagePreviewCalls=0;parserWarningCalls=0;resetResultReviewScenario(scenario,`http://${req.headers.host}`);resetCatalogHistoryScenario(scenario);return ok({reset:true});}if(path==='/__test/calls')return ok(calls);
if(resultReviewRoute(path,req.method??'GET',url,body,ok,fail))return;
if(catalogHistoryRoute(path,req.method??'GET',url,ok,fail))return;
if(path===`/v1/admin/questions/imports/${ID(4)}/parser-warnings`&&req.method==='GET'){parserWarningCalls++;if(scenario==='recovery-warnings-denied'&&parserWarningCalls===1)return fail('forbidden',403,'admin_required');return ok(makeParserWarnings());}
if(recoveryDetail&&recoveryRoute(path,req.method??'GET',body,ok,fail,`http://${req.headers.host}`))return;
if(path==='/v1/question-institutions')return ok({items:[{name:paper.institution,paperCount:1}],truncated:false});
if(path.endsWith('/recalculation'))return session.status==='active'?fail('conflict',409,'reference_not_available'):ok({sessionId:session.id,originalVersion:1,calculatedAt:now(),complete:true,aggregates:{correct:report().correct,incorrect:report().incorrect,unanswered:report().unanswered,annulled:0,denominator:1,score:report().score},items:[{itemId:ID(21),originalQuestionId:q.id,originalQuestionVersion:1,comparedQuestionId:q.id,comparedQuestionVersion:1,outcome:report().items[0]!.result,reasonCode:'unchanged',reference}]});
if(path==='/v1/question-features')return ok({import:true,catalog:true,sessions:true});
if(path.includes('/taxonomy'))return ok(url.searchParams.get('kind')==='area'?[{id:ID(9),name:'Área sintética'}]:[{id:ID(10),name:'Assunto sintético'}]);
if(path==='/v1/questions'){if(scenario==='quota')return fail('quota_exceeded');return ok({items:scenario==='empty'||url.searchParams.get('scope')==='mine'?[]:[{...q,userState}],nextCursor:null,total:scenario==='empty'?0:1});}if(path.endsWith('/user-state')){if(req.method==='PUT')userState={...userState,...body};return ok(userState);}if(path.endsWith('/reports'))return ok({reported:true});
if(path==='/v1/exams')return ok([paper]);if(path===`/v1/exams/${paper.id}`)return ok({paper,questions:[q]});
if(path==='/v1/question-sessions'){if(req.method==='POST'){if(body.count>1)return fail('validation',400,'insufficient_questions');session=makeSession(body.mode);return ok(session);}const{items,...metadata}=session;return ok([{...metadata,count:items.length,answeredCount:items.filter(i=>i.answered).length}]);}
if(path.endsWith('/answer')){const item=session.items[0]!;item.selectedKey=body.selectedKey;item.answered=true;item.revision++;return ok({itemId:item.id,selectedKey:item.selectedKey,revision:item.revision,savedAt:now()});}if(path.endsWith('/reference')){if(session.mode==='simulation'&&session.status==='active')return fail('forbidden',403,'reference_locked');return ok(reference);}if(path.endsWith('/finish')){session.status='finished';session.finishedAt=now();return ok(report());}if(path.endsWith('/report'))return session.status==='active'?fail('forbidden',403,'reference_locked'):ok(report());if(path===`/v1/question-sessions/${session.id}`){session.serverTime=now();return ok(session);}
if(path==='/v1/admin/questions/metrics')return ok({publicCanonical:1,importsByStatus:[{status:progress.status,count:1}],candidateCounts:[{state:currentCandidate.state,count:1}],documents:2,generatedPrivate:0,duplicateOrVersionNotCounted:true,publicByOrigin:[{origin:'official_exam',count:1}],coverageByArea:[{areaId:ID(40),name:'Área sintética',count:1}],coverageByTopic:[{topicId:ID(41),name:'Assunto sintético',count:1}],coverageTruncated:false,audit});
if(path==='/v1/admin/questions/sources')return ok(req.method==='POST'?{source:{...source,...body},audit}:{items:[source],audit});
if(path==='/v1/admin/questions/documents')return ok({document:doc,audit});if(path.endsWith('/preview'))return ok({id:ID(7),url:base+'/diagram.svg',expiresInSec:3600,audit});
if(path==='/v1/admin/questions/imports')return ok(req.method==='POST'?{import:progress,paperId:paper.id,audit}:{items:[progress],audit});if(path===`/v1/admin/questions/imports/${progress.id}`)return ok({import:progress,paper:{...paper,questionCount:undefined,documentId:doc.id,answerKeyDocumentId:keyDoc.id,keyFinal:false,keyRevision:null,createdAt:now(),updatedAt:now()},candidates:[currentCandidate],documents:[doc,keyDoc],audit});
if(path.endsWith('/retry')||path.endsWith('/cancel')){progress.status=path.endsWith('/cancel')?'cancelled':'queued';return ok({import:progress,audit});}if(path.includes('/candidates/')&&req.method==='PATCH'){if(body.state==='accepted'&&(!body.areaId||!body.topicId))return fail('validation');if(scenario==='conflict')return fail('conflict',409);currentCandidate={...currentCandidate,payload:{...currentCandidate.payload,...body},state:body.state,revision:currentCandidate.revision+1,questionId:body.state==='accepted'?q.id:null};return ok({candidate:currentCandidate,questionId:currentCandidate.questionId,audit});}
if(path==='/v1/editorial/questions')return ok({items:[currentQuestion]});if(path===`/v1/editorial/questions/${q.id}`)return ok({question:currentQuestion,source,latestReview:reviews});if(path.endsWith('/review')){reviews={decision:body.decision,contentHash:body.contentHash,reviewerName:'Revisor sintético',reviewerCrm:'CRM-DEMO',referenceDate:body.referenceDate,reviewedAt:now()};currentQuestion.reviewedHash=body.contentHash;return ok({id:q.id,decision:body.decision,contentHash:body.contentHash,audit});}if(path.endsWith('/publish')||path.endsWith('/withdraw'))return ok({id:q.id,status:path.endsWith('/publish')?'published':'withdrawn',audit});if(path.endsWith('/rectify'))return ok({id:q.id,version:2,supersedesId:q.id,audit});if(path===`/v1/admin/questions/${q.id}`&&req.method==='PATCH')return fail('conflict',409);
return fail('not_found',404);
}

// CCR130 branch is test-only and parses every recovery request AND response using exact shared schemas.
let recoveryDetail:ReturnType<typeof recoverySchemas.questionImportDetailSchema.parse>|null=null;
let recoveryConflictPending=false;let pagePreviewCalls=0;let parserWarningCalls=0;
function makeRecoveryDetail(origin:string){
 const candidateOne=recoverySchemas.questionCandidateSchema.parse({...candidate,ordinal:9,originalNumber:'1',payload:{...candidate.payload,stem:'O registro C01-01 solicita o marcador 1010.',ownStem:'O registro C01-01 solicita o marcador 1010.',alternatives:[{key:'A',text:'Marcador 1010'},{key:'B',text:'Marcador 1011'},{key:'C',text:'Marcador 1012'},{key:'D',text:'Marcador 1013'}],contextBindings:[],imageRefs:[]},issues:['context_unresolved']});
 const candidateThree=recoverySchemas.questionCandidateSchema.parse({...candidateOne,id:ID(73),ordinal:10,originalNumber:'33',payload:{...candidateOne.payload,stem:'O registro C01-03 solicita o marcador 1032.',ownStem:'O registro C01-03 solicita o marcador 1032.',alternatives:[{key:'A',text:'Marcador 1030'},{key:'B',text:'Marcador 1031'},{key:'C',text:'Marcador 1032'},{key:'D',text:'Marcador 1033'}],correctKey:'C'},issues:['number_marker_unconfirmed']});
 const context=recoverySchemas.questionImportContextSchema.parse({id:ID(70),importId:ID(4),documentId:doc.id,evidenceHash:hash,evidenceObjectKey:`questions/imports/${ID(4)}/contexts/${ID(70)}/evidence`,originalText:'Processo Seletivo - corpus autoral de engenharia, sem conteúdo clínico. Demonstração de resolução: a extração deste contexto não está sendo validada.',declaredNumbers:[1,2],provenance:[{documentId:doc.id,page:1,bbox:[0,0,1,.3]}],imageRefs:[{id:ID(71),page:1,bbox:{x:10,y:10,width:300,height:100},method:'text',objectKey:'private/recovery/context.png',url:origin+'/diagram.svg',provenance:{documentId:doc.id,page:1,bbox:[0,0,.5,.3]}}],revision:0,status:'unresolved',resolution:null,resolutionHash:null,createdAt:now(),updatedAt:now()});
 const {questionCount,...rawPaper}=paper;void questionCount;
 return recoverySchemas.questionImportDetailSchema.parse({import:{...makeProgress(),revision:0,candidates:2,totalPages:4,completedPages:4},paper:{...rawPaper,name:'Acervo autoral de recuperação — teste',status:'draft',documentId:doc.id,answerKeyDocumentId:keyDoc.id,keyFinal:false,keyRevision:null,createdAt:now(),updatedAt:now()},candidates:[candidateOne,candidateThree],contexts:[context],acceptanceBlocked:true,documents:[recoveryDocument,keyDoc],audit});
}
function recoveryRoute(path:string,method:string,body:unknown,ok:(data:unknown)=>void,fail:(code:string,status?:number,message?:string)=>void,origin:string){
 const d=recoveryDetail!;const prefix=`/v1/admin/questions/imports/${d.import.id}`;
 const pagePath=path.match(new RegExp(`^${prefix}/documents/${doc.id}/pages/(\\d+)/preview$`));if(pagePath&&method==='GET'){pagePreviewCalls++;const page=Number(pagePath[1]);if(scenario==='recovery-preview-error'&&pagePreviewCalls===1){fail('forbidden',403,'preview_access_denied');return true;}const native=nativePages.get(page);if(!native){fail('not_found',404,'fixture_page_png_not_available');return true;}ok(recoverySchemas.questionDocumentPagePreviewSchema.parse({importId:d.import.id,documentId:doc.id,page,pages:4,width:scenario==='recovery-preview-dimensions'&&pagePreviewCalls===1?native.width+1:native.width,height:native.height,dpi:100,documentSha256:originalPdfSha,imageSha256:native.sha,url:origin+'/recovery-original.png?page='+page,expiresInSec:300,provenance:{documentId:doc.id,page,bbox:[0,0,1,1]},audit}));return true;}
 if(path===prefix&&method==='GET'){ok(recoverySchemas.questionImportDetailSchema.parse(d));return true;}
 if(path===`/v1/admin/questions/documents/${doc.id}/preview`){ok(recoverySchemas.questionDocumentPreviewSchema.parse({id:doc.id,url:origin+'/recovery-page.pdf',expiresInSec:3600,audit}));return true;}
 const create=path===prefix+'/candidates'&&method==='POST';const number=path.match(new RegExp(`^${prefix}/candidates/([^/]+)/number$`));const resolve=path.match(new RegExp(`^${prefix}/contexts/([^/]+)/resolve$`));
 if(!create&&!number&&!resolve)return false;
 const schema=create?recoverySchemas.questionCandidateCreateInputSchema:number?recoverySchemas.questionCandidateNumberInputSchema:recoverySchemas.questionImportContextResolveInputSchema;
 const parsed=schema.safeParse(body);if(!parsed.success){fail('validation',422,'invalid_recovery_input');return true;}const input=parsed.data;
 if(recoveryConflictPending){recoveryConflictPending=false;d.import.revision++;fail('conflict',409,'context_revision_conflict');return true;}
 if(input.importRevision!==d.import.revision){fail('conflict',409,'context_revision_conflict');return true;}
 if(create){const value=recoverySchemas.questionCandidateCreateInputSchema.parse(input);if(d.candidates.some(c=>c.originalNumber===value.originalNumber)){fail('conflict',409,'original_number_exists');return true;}
 const c=recoverySchemas.questionCandidateSchema.parse({...candidate,id:value.candidateId,ordinal:11,originalNumber:value.originalNumber,payload:{stem:value.ownStem,ownStem:value.ownStem,alternatives:value.alternatives,correctKey:null,annulled:false,contextBindings:[]},provenance:value.provenance,issues:['manual_recovery_requires_review'],fingerprint:null,revision:0,state:'needs_review'});d.candidates.push(c);d.import.revision++;d.import.candidates=d.candidates.length;ok(recoverySchemas.questionImportRecoveryResultSchema.parse({candidate:c,affectedCandidates:[],importRevision:d.import.revision,audit}));return true;}
 if(number){const value=recoverySchemas.questionCandidateNumberInputSchema.parse(input);const c=d.candidates.find(c=>c.id===number[1]);if(!c){fail('not_found',404);return true;}if(c.revision!==value.revision){fail('conflict',409,'candidate_revision_conflict');return true;}c.originalNumber=value.originalNumber;c.revision++;c.state='needs_review';c.payload.integrityConfirmed=false;c.payload.keyFinal=false;d.import.revision++;ok(recoverySchemas.questionImportRecoveryResultSchema.parse({candidate:c,affectedCandidates:[],importRevision:d.import.revision,audit}));return true;}
 const value=recoverySchemas.questionImportContextResolveInputSchema.parse(input);const c=d.contexts.find(c=>c.id===resolve?.[1]);if(!c){fail('not_found',404);return true;}if(c.revision!==value.revision||c.evidenceHash!==value.evidenceHash){fail('conflict',409,'context_revision_conflict');return true;}
 if(value.targetNumbers.some(n=>!d.candidates.some(q=>Number(q.originalNumber)===n))){fail('validation',422,'target_number_missing');return true;}
 c.revision++;c.status=value.decision==='bind'?'bound':'non_question';c.resolution={decision:value.decision,targetNumbers:value.targetNumbers,text:value.text,imageRefIds:value.imageRefIds,reason:value.reason};c.resolutionHash='b'.repeat(64);
 const affected=d.candidates.filter(q=>value.targetNumbers.includes(Number(q.originalNumber))||q.payload.contextBindings.some(b=>b.contextId===c.id));
 for(const q of affected){const bindings=q.payload.contextBindings.filter(b=>b.contextId!==c.id);if(value.decision==='bind')bindings.push({contextId:c.id,contextRevision:c.revision,resolutionHash:c.resolutionHash});q.payload.contextBindings=bindings;q.payload.stem=(value.decision==='bind'?value.text+'\n\n':'')+(q.payload.ownStem??q.payload.stem);q.payload.integrityConfirmed=false;q.payload.keyFinal=false;q.payload.imagesConfirmed=false;q.state='needs_review';q.revision++;}
 d.import.revision++;d.acceptanceBlocked=d.contexts.some(c=>c.status==='unresolved');ok(recoverySchemas.questionImportContextResolvedSchema.parse({context:c,affectedCandidates:affected,importRevision:d.import.revision,acceptanceBlocked:d.acceptanceBlocked,audit}));return true;
}
// Tiny original PDF, generated locally. No external PDF/content/provider/storage access.
function recoveryPdf(){const stream='BT /F1 16 Tf 40 750 Td (SYNTHETIC AUTHORIAL DOCUMENT - UI TEST ONLY) Tj 0 -50 Td (Context: compare two circles. Questions 1 and 2.) Tj 0 -70 Td (1. Which circle is larger? A: left B: right) Tj 0 -70 Td (2. Which circle is smaller? A: right B: left) Tj 0 -70 Td (3. Compare the circles again.) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n';const offsets=[0];for(const[o,text]of objects.entries()){offsets.push(Buffer.byteLength(pdf));pdf+=`${o+1} 0 obj\n${text}\nendobj\n`;}const offset=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${offset}\n%%EOF`;return Buffer.from(pdf);}

/** Exact safe diagnostic shapes; this fixture is not a parser execution or clinical source. */
function makeParserWarnings(){const result={importId:ID(4),parserVersion:recoverySchemas.QUESTION_PDF_PARSER_VERSION,ocrVersion:null,attempt:1,planHash:hash,availability:'available',reason:null,phase:'parsed',complete:true,errorCode:null,detectedCandidates:2,detectedContexts:1,total:1,knownCount:1,unknownCount:0,omittedKnownCount:0,items:[{source:'exam',code:'expected_question_unmatched',number:83,count:1}],truncated:false,audit};
 if(!scenario.startsWith('recovery-warnings')||['recovery-warnings-pending','recovery-warnings-not-recorded'].includes(scenario))return recoverySchemas.questionParserWarningsSchema.parse({...result,availability:'not_available',reason:scenario==='recovery-warnings-pending'?'pending':'not_recorded',phase:null,complete:false,detectedCandidates:null,detectedContexts:null,total:null,knownCount:null,unknownCount:null,omittedKnownCount:null,items:[]});
 if(scenario==='recovery-warnings-unknown')return recoverySchemas.questionParserWarningsSchema.parse({...result,items:[],knownCount:0,unknownCount:3,total:3});
 if(scenario==='recovery-warnings-incomplete')return recoverySchemas.questionParserWarningsSchema.parse({...result,items:[{source:'answer_key',code:'conflicting_key',number:83,count:1}],phase:'key_parse',complete:false,errorCode:'ambiguous_key_geometry',detectedCandidates:null,detectedContexts:null,total:null});
 if(scenario==='recovery-warnings-truncated')return recoverySchemas.questionParserWarningsSchema.parse({...result,knownCount:6,unknownCount:2,omittedKnownCount:5,total:8,truncated:true});
 return recoverySchemas.questionParserWarningsSchema.parse(result);
}
