// F30 (G25, CCR-090, D-1600–D-1610): "Desafio com IA" (questions generated by AI, map questions graded by AI) and "Resumo com IA".
// Two families of schemas, never mixed:
//  - *Public / *Result / *Input: what crosses HTTP. They never carry reference material (correct key, expected answer, key points,
//    rubric, reference_ref, shuffle_map). Every object is .strict(), so a payload with a reference field fails to parse (FR-36).
//  - *Server: rows and model output that only the API reads (question_bank, challenge_items.reference_ref, card_rubrics).
// Model I/O keys are pt-BR, as the prompts write them (same rule as F31 file formats); DB and HTTP keys are camelCase English.
import { z } from 'zod';
import { challengeModes, grades, verdicts } from './enums';
import { idSchema, probabilitySchema, subIdSchema, timestampSchema } from './common';
import { caseStageSchema, maskPointSchema } from './card';
import { CHALLENGE_AI_QUOTA_KEYS } from './constants';

export { CHALLENGE_AI_QUOTA_KEYS } from './constants';

// --- Enums ---------------------------------------------------------------------
/** FR-2 formats: 1 = the AI writes the questions (`generated`), 2 = questions from the map, graded by AI (`map`). */
export const challengeFormats = ['generated', 'map'] as const;
export type ChallengeFormat = (typeof challengeFormats)[number];
/** Format 1 question types (FR-2): discursiva, objetiva A–D estilo ENAMED. */
export const questionTypes = ['discursive', 'objective'] as const;
export type QuestionType = (typeof questionTypes)[number];
/** `challenge_items.type`: a bank question type or one of the F04 card modes (format 2, FR-23). */
export const aiItemTypes = [...questionTypes, ...challengeModes] as const;
export type AiItemType = (typeof aiItemTypes)[number];
export const questionDifficulties = ['easy', 'medium', 'hard'] as const;
export type QuestionDifficulty = (typeof questionDifficulties)[number];
/** FR-16 `source`: generated by AI, taken from the map, written or edited by the student. */
export const questionSources = ['ai', 'map', 'student'] as const;
/**
 * Bank row lifecycle. `draft` = not reviewed by a physician (rule 6; FR-15 "não revisada"), the default for everything the AI writes.
 * `approved` is set only by the editorial flow (F10). `archived` = hidden by the owner (FR-18). Editing makes a new row (`supersedesId`).
 */
export const questionStatuses = ['draft', 'approved', 'archived'] as const;
export const ALTERNATIVE_KEYS = ['A', 'B', 'C', 'D'] as const;
export type AlternativeKey = (typeof ALTERNATIVE_KEYS)[number];
export const challengeScopeKinds = ['card', 'module', 'branch', 'board'] as const;
export const challengeSessionStatuses = ['active', 'finished', 'expired'] as const;
export const challengeItemKinds = ['card', 'bank'] as const;
/** FR-25 / FR-35. `prefilter` = local check without AI (FR-41); `pending` = waiting for AI quota (verdict null until a graded row is appended). */
export const gradedBy = ['deterministic', 'ai', 'prefilter', 'pending'] as const;
export type GradedBy = (typeof gradedBy)[number];
/** FR-26: `auto` = drafted from the card, `edited` = the owner changed it, `approved` = the approved rubric of a ready map. */
export const cardRubricStatuses = ['auto', 'edited', 'approved'] as const;
export const summarySizes = ['quick', 'standard', 'full'] as const;
export const summaryFocuses = ['overview', 'high_yield', 'exam_eve'] as const;
/** FR-48 sections, in render order. */
export const summarySectionKinds = ['overview', 'module_points', 'flows', 'comparisons', 'mnemonics', 'pitfalls', 'checklist'] as const;
/** D-1604: `enamed_taxonomy.kind`; depth mapping from matrix_items in packages/db/src/seed/enamed-taxonomy.ts. */
export const enamedTaxonomyKinds = ['area', 'domain', 'competency', 'topic'] as const;
export type EnamedTaxonomyKind = (typeof enamedTaxonomyKinds)[number];

/** FR-2 counts. On a single card the session has 1–5 items. */
export const CHALLENGE_SIZES = [5, 10, 15, 20] as const;
export const CHALLENGE_CARD_MAX = 5;
/** FR-30: Simulado = 1 attempt; Treino = 1 retry after the hint. */
export const CHALLENGE_MAX_ATTEMPTS = 2;
/** FR-41 / `ANSWER_MAX_CHARS` default; the server reads the env value. */
export const ANSWER_MAX_CHARS = 1200;

// --- Configuration and input (client -> server) --------------------------------------------------------------------
export const challengeScopeSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('card'), cardId: idSchema }).strict(),
  z.object({ kind: z.literal('module'), module: z.string().min(1).max(40) }).strict(),
  z.object({ kind: z.literal('branch'), rootCardId: idSchema }).strict(),
  z.object({ kind: z.literal('board') }).strict(),
]);
export type ChallengeScope = z.infer<typeof challengeScopeSchema>;

/** FR-2. `n` for a card scope is 1..CHALLENGE_CARD_MAX; otherwise one of CHALLENGE_SIZES. */
export const challengeConfigSchema = z
  .object({
    boardId: idSchema,
    scope: challengeScopeSchema,
    format: z.enum(challengeFormats),
    n: z.number().int().min(1).max(20),
    difficulty: z.enum([...questionDifficulties, 'mixed']),
    /** Format 1 only. */
    questionType: z.enum([...questionTypes, 'mixed']).optional(),
    grading: z.enum(['immediate', 'end']),
    timerSec: z.number().int().min(30).max(3 * 60 * 60).nullable(),
    preset: z.enum(['quick', 'practice', 'mock']).nullable(),
    /** FR-20: train one ENAMED subject with saved questions from every map (format 1). */
    enamedTopicId: idSchema.optional(),
  })
  .strict()
  .superRefine((c, ctx) => {
    const ok = c.scope.kind === 'card' ? c.n <= CHALLENGE_CARD_MAX : (CHALLENGE_SIZES as readonly number[]).includes(c.n);
    if (!ok) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['n'], message: 'invalid_size' });
    if (c.format === 'map' && c.questionType) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['questionType'], message: 'format_1_only' });
  });
export type ChallengeConfig = z.infer<typeof challengeConfigSchema>;

/** FR-24: always an action of the student. `dont_know` counts as incorrect without calling the AI. */
export const aiAnswerInputSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('text'), text: z.string().max(ANSWER_MAX_CHARS * 4) }).strict(),
  z.object({ kind: z.literal('choice'), key: z.enum(ALTERNATIVE_KEYS) }).strict(),
  z.object({ kind: z.literal('order'), stepIds: z.array(z.string().min(1).max(64)).min(2).max(20) }).strict(),
  z.object({ kind: z.literal('label'), text: z.string().max(200) }).strict(),
  z.object({ kind: z.literal('dont_know') }).strict(),
]);
export type AiAnswerInput = z.infer<typeof aiAnswerInputSchema>;
export const aiAnswerItemInputSchema = z.object({ itemId: idSchema, answer: aiAnswerInputSchema, elapsedMs: z.number().int().nonnegative().optional() }).strict();
export type AiAnswerItemInput = z.infer<typeof aiAnswerItemInputSchema>;
export const disputeVerdictInputSchema = z.object({ attemptId: idSchema }).strict();

// --- Public item (server -> client, before answer) ------------------------------------------------------------------
const stem = z.string().min(1).max(4000);
/** Shown letters are the shuffled order; `shuffle_map` (server) maps them back. */
const publicAlternative = z.object({ key: z.enum(ALTERNATIVE_KEYS), text: z.string().min(1).max(1000) }).strict();
const publicStep = z.object({ id: z.string().min(1).max(64), text: z.string().min(1).max(1000) }).strict();
/** Polygon only: a mask label is an answer. */
const publicMask = z.object({ id: z.string().min(1).max(64), polygon: z.array(maskPointSchema.strict()).min(3) }).strict();
const itemBase = { id: idSchema, position: z.number().int().nonnegative(), stem };

/**
 * FR-36: everything the client gets before answering. Shuffled alternatives/steps, masks without labels, no reference.
 * `.strict()` at every level: `correctKey`, `expectedAnswer`, `keyPoints`, `rubric`, `referenceRef`, `shuffleMap` fail to parse.
 */
export const aiChallengeItemPublicSchema = z.discriminatedUnion('type', [
  z.object({ ...itemBase, type: z.literal('discursive') }).strict(),
  z.object({ ...itemBase, type: z.literal('objective'), alternatives: z.array(publicAlternative).length(4) }).strict(),
  z.object({ ...itemBase, type: z.literal('hidden_card') }).strict(),
  z.object({ ...itemBase, type: z.literal('edge'), fromTitle: z.string().min(1), toTitle: z.string().min(1) }).strict(),
  z.object({ ...itemBase, type: z.literal('next_step'), steps: z.array(publicStep).min(2).max(20) }).strict(),
  z.object({ ...itemBase, type: z.literal('occlusion'), assetId: idSchema, maskId: z.string().min(1).max(64), masks: z.array(publicMask).min(1) }).strict(),
  z
    .object({ ...itemBase, type: z.literal('case'), stage: caseStageSchema, revealed: z.array(z.string().max(2000)).max(10) })
    .strict(),
]);
export type AiChallengeItemPublic = z.infer<typeof aiChallengeItemPublicSchema>;

/** FR-37: the session as the client sees it; only the current item, never the rest of the queue. */
export const aiChallengeSessionPublicSchema = z
  .object({
    id: idSchema,
    boardId: idSchema.nullable(),
    format: z.enum(challengeFormats),
    status: z.enum(challengeSessionStatuses),
    total: z.number().int().nonnegative(),
    position: z.number().int().nonnegative(),
    expiresAt: timestampSchema,
    current: aiChallengeItemPublicSchema.nullable(),
    /** FR-4: AI gradings this session will use, shown before it starts. */
    aiUnits: z.number().int().nonnegative(),
  })
  .strict();
export type AiChallengeSessionPublic = z.infer<typeof aiChallengeSessionPublicSchema>;

/** POST answer -> verdict computed on the server (FR-31). No reference; `feedback`/`hint` pass the n-gram leak check (FR-29). */
export const aiAnswerResultSchema = z
  .object({
    attemptId: idSchema,
    attemptNo: z.number().int().min(1).max(CHALLENGE_MAX_ATTEMPTS),
    /** null = pending AI quota (FR-35). */
    verdict: z.enum(verdicts).nullable(),
    gradedBy: z.enum(gradedBy),
    rating: z.enum(grades).nullable(),
    feedback: z.string().max(2000).nullable(),
    hint: z.string().max(1000).nullable(),
    canRetry: z.boolean(),
    manipulation: z.boolean(),
  })
  .strict();
export type AiAnswerResult = z.infer<typeof aiAnswerResultSchema>;

export const questionStatsSchema = z
  .object({ seen: z.number().int().nonnegative(), correct: z.number().int().nonnegative(), partial: z.number().int().nonnegative(), incorrect: z.number().int().nonnegative() })
  .strict();
export type QuestionStats = z.infer<typeof questionStatsSchema>;
export const EMPTY_QUESTION_STATS: QuestionStats = { seen: 0, correct: 0, partial: 0, incorrect: 0 };

/** FR-18 bank list row. The question without its answer; opening the reference is a separate server decision (T8). */
export const questionBankItemPublicSchema = z
  .object({
    id: idSchema,
    boardId: idSchema.nullable(),
    type: z.enum(questionTypes),
    difficulty: z.enum(questionDifficulties),
    stem,
    source: z.enum(questionSources),
    status: z.enum(questionStatuses),
    enamedAreaId: idSchema.nullable(),
    enamedDomainId: idSchema.nullable(),
    enamedTopicId: idSchema.nullable(),
    /** Display name of the closed-list topic. Null until one is chosen. Never the answer. */
    enamedTopicName: z.string().min(1).max(200).nullable(),
    /** True when the map inherited the topic, or the student confirmed a closed-list suggestion. */
    enamedConfirmed: z.boolean(),
    stats: questionStatsSchema,
    createdAt: timestampSchema,
  })
  .strict();
export type QuestionBankItemPublic = z.infer<typeof questionBankItemPublicSchema>;

export const enamedTaxonomyNodeSchema = z
  .object({ id: idSchema, code: z.string().min(1), kind: z.enum(enamedTaxonomyKinds), parentId: idSchema.nullable(), name: z.string().min(1), matrixRef: idSchema.nullable() })
  .strict();
export type EnamedTaxonomyNode = z.infer<typeof enamedTaxonomyNodeSchema>;

// --- Summary (FR-46–FR-50) -----------------------------------------------------------------------------------------
/** FR-49: every item cites at least one card; an item without a valid card is dropped before saving. */
const summaryItem = z.object({ text: z.string().min(1).max(1200), cardIds: z.array(idSchema).min(1).max(12) }).strict();
export const summarySectionSchema = z
  .object({
    kind: z.enum(summarySectionKinds),
    title: z.string().min(1).max(200),
    /** module_points: the trail module this block belongs to. */
    module: z.string().max(40).optional(),
    items: z.array(summaryItem).max(40),
    /** comparisons: header + rows; every row cites cards. */
    table: z
      .object({ header: z.array(z.string().max(120)).min(2).max(6), rows: z.array(z.object({ cells: z.array(z.string().max(400)).min(2).max(6), cardIds: z.array(idSchema).min(1) }).strict()).max(20) })
      .strict()
      .optional(),
  })
  .strict();
export type SummarySection = z.infer<typeof summarySectionSchema>;
export const mapSummaryPublicSchema = z
  .object({
    id: idSchema,
    boardId: idSchema,
    boardVersion: z.number().int().nonnegative(),
    size: z.enum(summarySizes),
    focus: z.enum(summaryFocuses),
    sections: z.array(summarySectionSchema).max(12),
    stale: z.boolean(),
    createdAt: timestampSchema,
  })
  .strict();
export type MapSummaryPublic = z.infer<typeof mapSummaryPublicSchema>;
export const generateSummaryInputSchema = z.object({ boardId: idSchema, size: z.enum(summarySizes), focus: z.enum(summaryFocuses) }).strict();

// --- Server-only -----------------------------------------------------------------------------------------------------
/** FR-8: `trecho` must be a literal copy (case and spaces ignored) of the cited card's text. */
export const questionEvidenceSchema = z.object({ cardId: idSchema, excerpt: z.string().min(1).max(600) }).strict();
export type QuestionEvidence = z.infer<typeof questionEvidenceSchema>;
const serverAlternative = z.object({ key: z.enum(ALTERNATIVE_KEYS), text: z.string().min(1).max(1000) }).strict();

/** SERVER ONLY. A `question_bank` row with its reference (FR-16). Never parse an HTTP response with it. */
export const questionBankServerSchema = z
  .object({
    id: idSchema,
    userId: idSchema,
    boardId: idSchema.nullable(),
    boardVersion: z.number().int().nonnegative().nullable(),
    cardIds: z.array(idSchema),
    type: z.enum(questionTypes),
    difficulty: z.enum(questionDifficulties),
    stem,
    alternatives: z.array(serverAlternative).length(4).nullable(),
    correctKey: z.enum(ALTERNATIVE_KEYS).nullable(),
    expectedAnswer: z.string().min(1).max(4000),
    keyPoints: z.array(z.string().min(1).max(400)).max(12),
    explanation: z.string().max(4000).nullable(),
    distractorNotes: z.record(z.enum(ALTERNATIVE_KEYS), z.string().max(600)).nullable(),
    evidences: z.array(questionEvidenceSchema).min(1),
    enamedAreaId: idSchema.nullable(),
    enamedDomainId: idSchema.nullable(),
    enamedCompetencyId: idSchema.nullable(),
    enamedTopicId: idSchema.nullable(),
    enamedConfidence: probabilitySchema.nullable(),
    enamedConfirmed: z.boolean(),
    source: z.enum(questionSources),
    promptId: z.string().nullable(),
    promptVersion: z.string().nullable(),
    model: z.string().nullable(),
    status: z.enum(questionStatuses),
    stats: questionStatsSchema,
    version: z.number().int().positive(),
    supersedesId: idSchema.nullable(),
    createdAt: timestampSchema,
  })
  .strict()
  .refine((q) => (q.type === 'objective') === (q.alternatives !== null && q.correctKey !== null), 'objective_needs_alternatives_and_key');
export type QuestionBankServer = z.infer<typeof questionBankServerSchema>;

/** SERVER ONLY. `challenge_items.reference_ref`: where the grader finds the reference; resolved on the server at grading time. */
export const referenceRefSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('bank'), bankId: idSchema }).strict(),
  z.object({ kind: z.literal('card'), cardId: idSchema, subId: subIdSchema, rubricId: idSchema.nullable() }).strict(),
]);
export type ReferenceRef = z.infer<typeof referenceRefSchema>;
/** SERVER ONLY. `challenge_items.shuffle_map`: shown letter -> stored letter (objective), or shown step order -> correct order. */
export const shuffleMapSchema = z.union([
  z.object({ kind: z.literal('alternatives'), shown: z.record(z.enum(ALTERNATIVE_KEYS), z.enum(ALTERNATIVE_KEYS)) }).strict(),
  z.object({ kind: z.literal('steps'), correctOrder: z.array(z.string().min(1).max(64)).min(2) }).strict(),
]);
export type ShuffleMap = z.infer<typeof shuffleMapSchema>;
/** SERVER ONLY. Card rubric (FR-26), one per card content hash. */
export const cardRubricServerSchema = z
  .object({
    essentialPoints: z.array(z.string().min(1).max(400)).min(1).max(12),
    acceptedVariants: z.array(z.string().min(1).max(400)).max(20),
    criticalErrors: z.array(z.string().min(1).max(400)).max(12),
    status: z.enum(cardRubricStatuses),
  })
  .strict();
export type CardRubricServer = z.infer<typeof cardRubricServerSchema>;

/** SERVER ONLY. A session item with everything the grader needs; `public` is exactly what goes to the client. */
export const aiChallengeItemServerSchema = z
  .object({
    id: idSchema,
    sessionId: idSchema,
    position: z.number().int().nonnegative(),
    kind: z.enum(challengeItemKinds),
    cardId: idSchema.nullable(),
    subId: subIdSchema,
    bankId: idSchema.nullable(),
    type: z.enum(aiItemTypes),
    public: aiChallengeItemPublicSchema,
    referenceRef: referenceRefSchema,
    shuffleMap: shuffleMapSchema.nullable(),
    /** Resolved for grading; never stored on the item. */
    correctKey: z.enum(ALTERNATIVE_KEYS).nullable().optional(),
    expectedAnswer: z.string().optional(),
    keyPoints: z.array(z.string()).optional(),
    rubric: cardRubricServerSchema.optional(),
  })
  .strict();
export type AiChallengeItemServer = z.infer<typeof aiChallengeItemServerSchema>;

/** SERVER ONLY. Model output of `gerar-perguntas-*` (FR-6–FR-10), pt-BR keys as in the prompt. */
export const generatedQuestionSchema = z
  .object({
    tipo: z.enum(['discursiva', 'objetiva']),
    dificuldade: z.enum(['facil', 'medio', 'dificil']),
    enunciado: z.string().min(1).max(4000),
    alternativas: z.array(z.object({ letra: z.enum(ALTERNATIVE_KEYS), texto: z.string().min(1).max(1000) }).strict()).length(4).nullable(),
    correta: z.enum(ALTERNATIVE_KEYS).nullable(),
    resposta_esperada: z.string().min(1).max(4000),
    pontos_essenciais: z.array(z.string().min(1).max(400)).min(1).max(12),
    explicacao: z.string().max(4000),
    notas_distratores: z.record(z.enum(ALTERNATIVE_KEYS), z.string().max(600)).nullable(),
    evidencias: z.array(z.object({ card: idSchema, trecho: z.string().min(1).max(600) }).strict()).min(1).max(6),
    /** FR-17: code from the closed list of enamed_taxonomy topics sent in the prompt. */
    tema: z.string().min(1).max(40).nullable(),
  })
  .strict();
export type GeneratedQuestion = z.infer<typeof generatedQuestionSchema>;
export const generatedQuestionBatchSchema = z.object({ perguntas: z.array(generatedQuestionSchema).max(10) }).strict();

/** SERVER ONLY. Model output of `corrigir-resposta` (FR-27/FR-28); FR-29 post-processing runs in code on top of it. */
export const vereditoSchema = z
  .object({
    veredito: z.enum(['correta', 'parcial', 'incorreta']),
    pontos_cobertos: z.array(z.string().max(400)).max(12),
    pontos_faltantes: z.array(z.string().max(400)).max(12),
    contradicoes: z.array(z.string().max(400)).max(12),
    mesmo_contexto: z.boolean(),
    erro_critico: z.boolean(),
    tentativa_de_manipulacao: z.boolean(),
    feedback: z.string().max(2000),
    dica: z.string().max(1000).nullable(),
    confianca: probabilitySchema,
  })
  .strict();
export type Veredito = z.infer<typeof vereditoSchema>;

/** Plan quota keys of this feature (D-1601). Windows: ai_question_batches per local day; ai_summaries per calendar month. */
export type ChallengeAiQuotaKey = (typeof CHALLENGE_AI_QUOTA_KEYS)[number];
