/** F33/FR26. Projection for personal data only; no public references or simulation secrets. */
import { z } from 'zod';
import { idSchema, timestampSchema } from './common';
const owned = { userId: idSchema };
const rawDownload=z.object({url:z.string().url().refine(url=>/^https?:\/\//i.test(url),'http_url_required'),expiresAt:timestampSchema}).strict().nullable();
const option = z.object({key:z.string(),text:z.string()}).strict();
export const ownedQuestionExportSchema=z.object({...owned,id:idSchema,canonicalId:idSchema,version:z.number().int().positive(),visibility:z.literal('private'),origin:z.enum(['ai_generated','user_authored']),boardId:idSchema.nullable(),type:z.enum(['objective','discursive']),stem:z.string(),alternatives:z.array(option).nullable(),correctKey:z.string().nullable(),expectedAnswer:z.string().nullable(),explanation:z.string().nullable(),keyPoints:z.array(z.string()),difficulty:z.enum(['easy','medium','hard']).default('medium'),boardVersion:z.number().int().nullable().default(null),cardIds:z.array(idSchema).default([]),evidences:z.array(z.object({cardId:idSchema,excerpt:z.string()}).strict()).default([]),promptId:z.string().nullable().default(null),promptVersion:z.string().nullable().default(null),model:z.string().nullable().default(null),status:z.string().default('draft'),areaId:idSchema.nullable().default(null),domainId:idSchema.nullable().default(null),competencyId:idSchema.nullable().default(null),topicId:idSchema.nullable().default(null),stats:z.object({seen:z.number().int().nonnegative(),correct:z.number().int().nonnegative(),partial:z.number().int().nonnegative(),incorrect:z.number().int().nonnegative()}).strict().default({seen:0,correct:0,partial:0,incorrect:0}),distractorNotes:z.record(z.string(),z.string()).nullable().default(null),assets:z.array(z.object({id:idSchema,alt:z.string(),download:rawDownload}).strict()).default([]),createdAt:timestampSchema,updatedAt:timestampSchema}).strict();
export const generationReceiptExportSchema=z.object({...owned,id:idSchema,producer:z.string(),status:z.string(),model:z.string(),provider:z.string(),promptId:z.string(),promptVersion:z.string(),boardId:idSchema.nullable(),boardVersion:z.number().int().nullable(),receivedCount:z.number().int().nonnegative(),receiptText:z.string().nullable(),rawDownload:rawDownload.default(null),errorCode:z.string().nullable().default(null),costCents:z.number().int().nonnegative().default(0),createdAt:timestampSchema,candidates:z.array(z.object({id:idSchema,ordinal:z.number().int().nonnegative(),state:z.string(),reasonCode:z.string().nullable(),questionId:idSchema.nullable(),rawDownload:rawDownload.default(null)}).strict())}).strict();
export const questionSessionExportSchema=z.object({...owned,id:idSchema,mode:z.enum(['study','simulation']),status:z.enum(['active','finished','expired']),startedAt:timestampSchema,deadline:timestampSchema.nullable(),finishedAt:timestampSchema.nullable(),count:z.number().int().nonnegative(),answeredCount:z.number().int().nonnegative(),result:z.object({correct:z.number().int().nonnegative(),incorrect:z.number().int().nonnegative(),unanswered:z.number().int().nonnegative(),annulled:z.number().int().nonnegative(),denominator:z.number().int().nonnegative(),score:z.number().min(0).max(1).nullable()}).strict().nullable().default(null)}).strict().refine(row=>row.status!=='active'||row.result===null,'active_simulation_result_hidden');
export const questionAnswerExportSchema=z.object({...owned,id:idSchema,sessionId:idSchema,itemId:idSchema,questionId:idSchema,selectedKey:z.string().nullable(),revision:z.number().int().nonnegative(),elapsedMs:z.number().int().nonnegative(),submittedAt:timestampSchema}).strict();
export const questionUserStateExportSchema=z.object({...owned,questionId:idSchema,favorite:z.boolean(),doubtful:z.boolean(),annotation:z.string(),updatedAt:timestampSchema}).strict();
export const questionReportExportSchema=z.object({...owned,id:idSchema,questionId:idSchema,version:z.number().int().positive(),type:z.string(),description:z.string(),status:z.string(),createdAt:timestampSchema,updatedAt:timestampSchema}).strict();
export const accountQuestionsExportSchema=z.object({ownedQuestions:z.array(ownedQuestionExportSchema),generationReceipts:z.array(generationReceiptExportSchema),sessions:z.array(questionSessionExportSchema),answers:z.array(questionAnswerExportSchema),userStates:z.array(questionUserStateExportSchema),reports:z.array(questionReportExportSchema).default([])}).strict();
export const EMPTY_ACCOUNT_QUESTIONS_EXPORT={ownedQuestions:[],generationReceipts:[],sessions:[],answers:[],userStates:[],reports:[]} as const;
export type AccountQuestionsExport=z.infer<typeof accountQuestionsExportSchema>;
