import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {mockQuestionAdminCatalogPage} from '@remoa/contracts/mocks';
import {QuestionsApiError} from '@/features/questions/request';
import {QuestionCatalogBrowser} from './catalog-browser';
vi.mock('./catalog-api',()=>({listQuestionCatalog:vi.fn()}));vi.mock('./api',()=>({listSources:vi.fn()}));
import {listQuestionCatalog} from './catalog-api';import {listSources} from './api';
const scrollDescriptor=Object.getOwnPropertyDescriptor(HTMLElement.prototype,'scrollIntoView');
beforeAll(()=>Object.defineProperty(HTMLElement.prototype,'scrollIntoView',{configurable:true,value:vi.fn()}));
afterAll(()=>{if(scrollDescriptor)Object.defineProperty(HTMLElement.prototype,'scrollIntoView',scrollDescriptor);else delete (HTMLElement.prototype as Partial<HTMLElement>).scrollIntoView;});
const item=mockQuestionAdminCatalogPage.items[0]!;
beforeEach(()=>{vi.resetAllMocks();vi.mocked(listSources).mockResolvedValue({items:[],audit:{} as never});vi.mocked(listQuestionCatalog).mockResolvedValue(mockQuestionAdminCatalogPage);});afterEach(cleanup);
describe('administrative catalog discovery',()=>{
 it('distinguishes a disabled feature from a service/permission failure',async()=>{const{rerender}=render(<QuestionCatalogBrowser admin enabled={false}/>);expect(listQuestionCatalog).not.toHaveBeenCalled();expect(listSources).not.toHaveBeenCalled();expect(screen.getByText('O catálogo de versões não está disponível neste momento.')).toBeVisible();vi.mocked(listQuestionCatalog).mockRejectedValue(new QuestionsApiError('not_found'));rerender(<QuestionCatalogBrowser admin enabled/>);await screen.findByRole('alert');expect(screen.queryByText('Nenhuma versão encontrada para estes filtros.')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Tentar de novo'})).toBeVisible();});
 it('finds published/withdrawn versions with explicit states instead of describing latest as public',async()=>{vi.mocked(listQuestionCatalog).mockResolvedValue({items:[{...item,catalogStatus:'draft',version:2},{...item,id:'00000000-0000-4000-8000-000000000222',catalogStatus:'withdrawn',availability:'superseded',version:1}],nextCursor:null});render(<QuestionCatalogBrowser admin={false}/>);await screen.findAllByText('Questão sintética de navegação.');expect(screen.getByText('Rascunho',{exact:true})).toBeVisible();expect(screen.getByText('Retirada de circulação',{exact:true})).toBeVisible();expect(screen.getByText(/A versão mais recente pode ser um rascunho/)).toBeVisible();expect(listSources).not.toHaveBeenCalled();expect(screen.getAllByRole('link',{name:'Conferência médica'})).toHaveLength(2);});
 it('loads the bound cursor without duplicate entries and resets it after a search',async()=>{vi.mocked(listQuestionCatalog).mockResolvedValueOnce({...mockQuestionAdminCatalogPage,nextCursor:'bound1'}).mockResolvedValueOnce({items:[item,{...item,id:'00000000-0000-4000-8000-000000000222',stemPreview:'Segunda versão sintética'}],nextCursor:null}).mockResolvedValue(mockQuestionAdminCatalogPage);render(<QuestionCatalogBrowser admin={false}/>);await screen.findByText(item.stemPreview);fireEvent.click(screen.getByRole('button',{name:'Carregar mais versões'}));await screen.findByText('Segunda versão sintética');expect(screen.getAllByText(item.stemPreview)).toHaveLength(1);expect(listQuestionCatalog).toHaveBeenNthCalledWith(2,false,{limit:25,versions:'latest',cursor:'bound1'},expect.any(AbortSignal));fireEvent.change(screen.getByLabelText('Buscar no catálogo administrativo'),{target:{value:'nova busca'}});await waitFor(()=>expect(listQuestionCatalog).toHaveBeenLastCalledWith(false,{limit:25,versions:'latest',search:'nova busca'},expect.any(AbortSignal)));expect(screen.queryByText('Segunda versão sintética')).not.toBeInTheDocument();});
 it('changes version and editorial filters with a fresh cursor-free request',async()=>{render(<QuestionCatalogBrowser admin={false} initialStatus="in_review"/>);await screen.findByText(item.stemPreview);fireEvent.keyDown(screen.getByRole('combobox',{name:'Versões exibidas'}),{key:'Enter',code:'Enter'});fireEvent.click(await screen.findByRole('option',{name:'Todas as versões'}));await waitFor(()=>expect(listQuestionCatalog).toHaveBeenLastCalledWith(false,{limit:25,versions:'all',status:'in_review'},expect.any(AbortSignal)));fireEvent.keyDown(screen.getByRole('combobox',{name:'Estado editorial'}),{key:'Enter',code:'Enter'});fireEvent.click(await screen.findByRole('option',{name:'Publicada'}));await waitFor(()=>expect(listQuestionCatalog).toHaveBeenLastCalledWith(false,{limit:25,versions:'all',status:'published'},expect.any(AbortSignal)));});
 it('ignores stale role responses and aborts old requests rather than showing foreign data',async()=>{let resolve!:(value:typeof mockQuestionAdminCatalogPage)=>void;vi.mocked(listQuestionCatalog).mockImplementationOnce(()=>new Promise(done=>{resolve=done;}));const{rerender}=render(<QuestionCatalogBrowser admin={false}/>);await waitFor(()=>expect(listQuestionCatalog).toHaveBeenCalledOnce());const signal=vi.mocked(listQuestionCatalog).mock.calls[0]![2]!;rerender(<QuestionCatalogBrowser admin/>);await screen.findByText(item.stemPreview);expect(signal.aborted).toBe(true);resolve({items:[{...item,stemPreview:'Resposta antiga não permitida'}],nextCursor:null});await waitFor(()=>expect(screen.queryByText('Resposta antiga não permitida')).not.toBeInTheDocument());});
});
