import {beforeEach,describe,expect,it,vi} from 'vitest';
import {mockQuestionAdminCatalogPage,mockQuestionVersionHistoryPage,mockQuestionReviewHistoryPage} from '@remoa/contracts/mocks';
import {testAudit as mockAuditEntry} from './recovery.test-fixtures';
vi.mock('@/lib/api',()=>({api:vi.fn()}));
import {api} from '@/lib/api';
import {listQuestionCatalog,getQuestionVersionHistory,getQuestionReviewHistory} from './catalog-api';
const id=mockQuestionVersionHistoryPage.questionId;
beforeEach(()=>vi.resetAllMocks());
describe('strict catalog and history role boundary',()=>{
 it('uses reviewer DTO without audit and retains latest/default bound page',async()=>{vi.mocked(api).mockResolvedValue({ok:true,data:mockQuestionAdminCatalogPage});await expect(listQuestionCatalog(false,{})).resolves.toEqual(mockQuestionAdminCatalogPage);expect(api).toHaveBeenCalledWith('/v1/editorial/questions/catalog?limit=25&versions=latest',{signal:undefined});});
 it('requires admin audit and serializes all versions/status/source/search with cursor',async()=>{vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionAdminCatalogPage,audit:mockAuditEntry}});await listQuestionCatalog(true,{versions:'all',status:'withdrawn',sourceId:id,search:' fonte ',cursor:'bound cursor'});const path=vi.mocked(api).mock.calls[0]![0];expect(path).toContain('/v1/admin/questions/catalog?');const query=new URL('http://test'+path).searchParams;expect(Object.fromEntries(query)).toEqual({limit:'25',versions:'all',status:'withdrawn',sourceId:id,search:'fonte',cursor:'bound cursor'});vi.mocked(api).mockResolvedValue({ok:true,data:mockQuestionAdminCatalogPage});await expect(listQuestionCatalog(true,{})).rejects.toMatchObject({code:'invalid_response'});});
 it('rejects malformed queries before any HTTP and malformed responses without fallback',async()=>{await expect(listQuestionCatalog(false,{limit:51})).rejects.toThrow();expect(api).not.toHaveBeenCalled();vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionAdminCatalogPage,total:900}});await expect(listQuestionCatalog(false,{})).rejects.toMatchObject({code:'invalid_response'});expect(api).toHaveBeenCalledOnce();});
 it('preserves denial and reauthentication instead of empty discovery',async()=>{for(const code of ['forbidden','unauthorized','not_found'] as const){vi.mocked(api).mockResolvedValue({ok:false,error:{code,message:'deny'}});await expect(listQuestionCatalog(true,{})).rejects.toMatchObject({code,detail:'deny'});}});
 it('guards selected question and canonical family in version responses',async()=>{vi.mocked(api).mockResolvedValue({ok:true,data:mockQuestionVersionHistoryPage});await expect(getQuestionVersionHistory(false,id,{})).resolves.toEqual(mockQuestionVersionHistoryPage);vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionVersionHistoryPage,questionId:'00000000-0000-4000-8000-000000000999'}});await expect(getQuestionVersionHistory(false,id,{})).rejects.toMatchObject({code:'invalid_response'});vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionVersionHistoryPage,items:mockQuestionVersionHistoryPage.items.map(item=>({...item,canonicalId:'00000000-0000-4000-8000-000000000999'}))}});await expect(getQuestionVersionHistory(false,id,{})).rejects.toMatchObject({code:'invalid_response'});});
 it('guards medical signatures to this selected question and exact admin schema',async()=>{vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionReviewHistoryPage,audit:mockAuditEntry}});await expect(getQuestionReviewHistory(true,id,{cursor:'signature cursor'})).resolves.toEqual(mockQuestionReviewHistoryPage);expect(vi.mocked(api).mock.calls[0]![0]).toContain('/v1/admin/questions/'+id+'/reviews?limit=25&cursor=signature+cursor');vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionReviewHistoryPage,questionId:'00000000-0000-4000-8000-000000000999'}});await expect(getQuestionReviewHistory(false,id,{})).rejects.toMatchObject({code:'invalid_response'});});
});
