import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {ContextReview} from './context-review';
import {QuestionsApiError} from '@/features/questions/request';
import {testId,testContext,testAudit} from './recovery.test-fixtures';
vi.mock('./api',()=>({resolveImportContext:vi.fn()}));
vi.mock('./private-preview',()=>({PrivatePreview:()=>null}));
vi.mock('@remoa/ui',async original=>{const ui=await original<typeof import('@remoa/ui')>();return{...ui,Select:({label,value,onValueChange,options}:{label:string;value:string;onValueChange:(value:string)=>void;options:{value:string;label:string}[]})=><label>{label}<select value={value} onChange={event=>onValueChange(event.target.value)}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>};});
import {resolveImportContext} from './api';
afterEach(()=>{cleanup();vi.clearAllMocks();});
const reason='Conferência sintética do contexto comum';
function open(){fireEvent.click(screen.getByRole('button',{name:'Conferir contexto'}));fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:reason}});}
function confirm(){fireEvent.click(screen.getByLabelText('Conferi o trecho, seu alcance e as imagens no documento original'));}
it('binds explicit original numbers and existing image IDs with read evidence/revisions; edits reset confirmation',async()=>{const context=testContext();vi.mocked(resolveImportContext).mockResolvedValue({context:{...context,status:'bound',revision:3,resolution:{decision:'bind',targetNumbers:[1,2],text:'Contexto sintético conferido',imageRefIds:[testId],reason},resolutionHash:'b'.repeat(64)},affectedCandidates:[],importRevision:8,acceptanceBlocked:false,audit:testAudit});const saved=vi.fn();render(<ContextReview context={context} importRevision={7} enabled onSaved={saved} onReload={vi.fn()}/>);open();expect(screen.getByLabelText('Números originais das questões')).toHaveValue('');fireEvent.change(screen.getByLabelText('Números originais das questões'),{target:{value:'1,2'}});fireEvent.change(screen.getByLabelText('Texto comum conferido'),{target:{value:'Contexto sintético conferido'}});fireEvent.click(screen.getByLabelText('Imagem do contexto 1'));confirm();fireEvent.change(screen.getByLabelText('Texto comum conferido'),{target:{value:'Contexto sintético conferido novamente'}});expect(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'})).toBeDisabled();confirm();fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await waitFor(()=>expect(saved).toHaveBeenCalledOnce());const payload=vi.mocked(resolveImportContext).mock.calls[0]![2];expect(payload).toEqual({importRevision:7,revision:2,evidenceHash:'a'.repeat(64),decision:'bind',targetNumbers:[1,2],text:'Contexto sintético conferido novamente',imageRefIds:[testId],reason});expect(JSON.stringify(payload)).not.toContain('private/test/circle');});
it('records non-question with no target/text/image inheritance and an audit reason',async()=>{const context=testContext();vi.mocked(resolveImportContext).mockResolvedValue({context:{...context,status:'non_question',revision:3,resolution:{decision:'non_question',targetNumbers:[],text:'',imageRefIds:[],reason},resolutionHash:'b'.repeat(64)},affectedCandidates:[],importRevision:8,acceptanceBlocked:false,audit:testAudit});render(<ContextReview context={context} importRevision={7} enabled onSaved={vi.fn()} onReload={vi.fn()}/>);open();fireEvent.change(screen.getByLabelText('Números originais das questões'),{target:{value:'1,2'}});fireEvent.click(screen.getByLabelText('Imagem do contexto 1'));fireEvent.change(screen.getByLabelText('Destino do trecho'),{target:{value:'non_question'}});confirm();fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await waitFor(()=>expect(resolveImportContext).toHaveBeenCalledWith(testId,testId,expect.objectContaining({decision:'non_question',targetNumbers:[],text:'',imageRefIds:[],reason})));});
it('rejects bind without targets or with duplicate numbers and preserves the draft across conflict refresh',async()=>{const context=testContext();vi.mocked(resolveImportContext).mockRejectedValue(new QuestionsApiError('conflict'));const reload=vi.fn().mockResolvedValue({importRevision:9,contextRevision:4,evidenceHash:'a'.repeat(64)});render(<ContextReview context={context} importRevision={7} enabled onSaved={vi.fn()} onReload={reload}/>);open();confirm();fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await screen.findByRole('alert');expect(resolveImportContext).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Números originais das questões'),{target:{value:'1,1'}});confirm();fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'})).toBeEnabled());expect(resolveImportContext).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Números originais das questões'),{target:{value:'1,2'}});confirm();fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await waitFor(()=>expect(resolveImportContext).toHaveBeenCalledOnce());await screen.findByText('Este conteúdo mudou. Atualize e confira novamente antes de continuar.');fireEvent.click(screen.getByRole('button',{name:'Atualizar os dados do lote'}));await waitFor(()=>expect(reload).toHaveBeenCalledOnce());expect(screen.getByLabelText('Texto comum conferido')).toHaveValue(context.originalText);expect(screen.getByLabelText('Números originais das questões')).toHaveValue('1,2');await waitFor(()=>expect(screen.getByLabelText('Conferi o trecho, seu alcance e as imagens no documento original')).not.toBeChecked());confirm();fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await waitFor(()=>expect(resolveImportContext).toHaveBeenCalledTimes(2));expect(vi.mocked(resolveImportContext).mock.calls[1]![2]).toMatchObject({importRevision:9,revision:4,targetNumbers:[1,2]});});
