import {unavailableWarnings} from './parser-warnings.test-fixtures';
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {questionImportDetailSchema} from '@remoa/contracts';
import {ImportDetailScreen} from './import-detail-screen';
import {testId,testAudit,testCandidate,testContext} from './recovery.test-fixtures';
vi.mock('@/features/questions/flags',()=>({useQuestionFeatureFlags:()=>({import:true,catalog:true,sessions:true})}));
vi.mock('@/features/questions/api',()=>({listQuestionTaxonomy:vi.fn(async()=>[])}));
vi.mock('./api',()=>({getImportParserWarnings:vi.fn(async()=>unavailableWarnings('not_recorded')),getImport:vi.fn(),importAction:vi.fn(),attachCandidatePage:vi.fn(),saveCandidate:vi.fn(),resolveImportContext:vi.fn()}));
vi.mock('./private-preview',()=>({PrivatePreview:()=>null}));
vi.mock('@remoa/ui',async original=>{const ui=await original<typeof import('@remoa/ui')>();return{...ui,Select:({label,value,onValueChange,options}:{label:string;value:string;onValueChange:(value:string)=>void;options:{value:string;label:string}[]})=><label>{label}<select value={value} onChange={event=>onValueChange(event.target.value)}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>};});
import {getImport,resolveImportContext,saveCandidate} from './api';
afterEach(()=>{cleanup();vi.clearAllMocks();});
it('updates affected revisions without replacing the local draft, and reloads only after explicit confirmation',async()=>{const candidate=testCandidate(),context=testContext();const detail=questionImportDetailSchema.parse({import:{id:testId,revision:7,status:'review',totalPages:3,completedPages:3,candidates:1,accepted:0,rejected:0,duplicate:0,costCents:0,errorCode:null,updatedAt:new Date()},paper:null,candidates:[candidate],contexts:[context],acceptanceBlocked:true,documents:[{id:testId,kind:'exam',sha256:'a'.repeat(64),bytes:100,pages:3}],audit:testAudit});const updated={...candidate,revision:4,payload:{...candidate.payload,stem:'Contexto comum conferido. Texto no servidor.',ownStem:'Texto no servidor.',contextBindings:[{contextId:testId,contextRevision:3,resolutionHash:'b'.repeat(64)}]}};const resolved={...context,status:'bound' as const,revision:3,resolution:{decision:'bind' as const,targetNumbers:[1],text:'Contexto comum conferido.',imageRefIds:[],reason:'Conferência sintética comum'},resolutionHash:'b'.repeat(64)};vi.mocked(getImport).mockResolvedValue(detail);vi.mocked(resolveImportContext).mockResolvedValue({context:resolved,affectedCandidates:[updated],importRevision:8,acceptanceBlocked:false,audit:testAudit});render(<ImportDetailScreen id={testId}/>);await screen.findByLabelText('Enunciado');expect(screen.getByRole('option',{name:'Número 1 · extração 9'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Enunciado'),{target:{value:'Rascunho local ainda não salvo'}});fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Motivo local preservado'}});fireEvent.click(screen.getByRole('button',{name:'Conferir contexto'}));fireEvent.change(screen.getByLabelText('Números originais das questões'),{target:{value:'1'}});const reasons=screen.getAllByLabelText('Motivo desta operação');fireEvent.change(reasons[0]!,{target:{value:'Conferência sintética comum'}});fireEvent.click(screen.getByLabelText('Conferi o trecho, seu alcance e as imagens no documento original'));fireEvent.click(screen.getByRole('button',{name:'Registrar decisão sobre o trecho'}));await screen.findByText(/Esta candidata foi alterada/);expect(screen.getByLabelText('Enunciado')).toHaveValue('Rascunho local ainda não salvo');expect(screen.getByRole('button',{name:'Salvar conferência'})).toBeDisabled();expect(saveCandidate).not.toHaveBeenCalled();vi.mocked(getImport).mockResolvedValue({...detail,import:{...detail.import,revision:8},candidates:[updated],contexts:[resolved],acceptanceBlocked:false});fireEvent.click(screen.getByRole('button',{name:'Recarregar candidata'}));expect(screen.getByLabelText('Enunciado')).toHaveValue('Rascunho local ainda não salvo');fireEvent.click(screen.getAllByRole('button',{name:'Recarregar candidata'}).at(-1)!);await waitFor(()=>expect(screen.getByLabelText('Trecho próprio desta questão')).toHaveValue('Texto no servidor.'));expect(screen.getByText('Contexto comum conferido. Texto no servidor.')).toBeInTheDocument();});

it('returns focus to the actual create or repair opener after controlled dialog unmount',async()=>{const candidate=testCandidate();vi.mocked(getImport).mockResolvedValue(questionImportDetailSchema.parse({import:{id:testId,revision:7,status:'review',totalPages:3,completedPages:3,candidates:1,accepted:0,rejected:0,duplicate:0,costCents:0,errorCode:null,updatedAt:new Date()},paper:null,candidates:[candidate],contexts:[],acceptanceBlocked:false,documents:[{id:testId,kind:'exam',sha256:'a'.repeat(64),bytes:100,pages:3}],audit:testAudit}));render(<ImportDetailScreen id={testId}/>);const create=await screen.findByRole('button',{name:'Recuperar questão ausente'});create.focus();fireEvent.click(create);await screen.findByRole('dialog');fireEvent.click(screen.getByRole('button',{name:/^Fechar$/}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(create).toHaveFocus());const repair=screen.getByRole('button',{name:'Corrigir número original'});repair.focus();fireEvent.click(repair);const dialog=await screen.findByRole('dialog');fireEvent.keyDown(dialog,{key:'Escape',code:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(repair).toHaveFocus());});

it('shows the persisted original key-page selection as immutable and links to a new import',async()=>{vi.mocked(getImport).mockResolvedValue(questionImportDetailSchema.parse({import:{id:testId,answerKeyPages:[1,3],revision:7,status:'review',totalPages:3,completedPages:3,candidates:0,accepted:0,rejected:0,duplicate:0,costCents:0,errorCode:null,updatedAt:new Date()},paper:null,candidates:[],contexts:[],acceptanceBlocked:false,documents:[{id:testId,kind:'answer_key',sha256:'a'.repeat(64),bytes:100,pages:3}],audit:testAudit}));render(<ImportDetailScreen id={testId}/>);await screen.findByText('Gabarito: páginas originais 1, 3');expect(screen.getByText(/Esta seleção pertence à importação/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Importar uma prova'})).toHaveAttribute('href','/admin/questoes/importar');expect(screen.queryByLabelText('Páginas originais do gabarito')).not.toBeInTheDocument();});
