import {afterEach,expect,it,vi} from 'vitest';
import {useLayoutEffect,useState} from 'react';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {MarkerPreview,type MarkerPreviewProps} from './marker-preview';
afterEach(()=>{cleanup();vi.restoreAllMocks();});
const image={url:'https://example.org/private-page.png',width:600,height:800,identity:'import/doc-sha/page-1/image-sha/request-1'};
function load(node=screen.getByRole('img')){Object.defineProperties(node,{naturalWidth:{value:600,configurable:true},naturalHeight:{value:800,configurable:true}});fireEvent.load(node);}
function props(overrides:Partial<MarkerPreviewProps>={}):MarkerPreviewProps{return{image,bbox:[.1,.2,.2,.1],onChange:vi.fn(),onReady:vi.fn(),onRetry:vi.fn(),...overrides};}
it('positions the region using displayed bounds, clamps edges and preserves dimensions',()=>{const p=props();render(<MarkerPreview {...p}/>);const target=screen.getByRole('button',{name:'Posicionar região do número'});vi.spyOn(screen.getByRole('img'),'getBoundingClientRect').mockReturnValue({left:20,top:40,width:300,height:400,right:320,bottom:440,x:20,y:40,toJSON:()=>({})});fireEvent.click(target,{clientX:170,clientY:240,detail:1});expect(p.onChange).not.toHaveBeenCalled();load();fireEvent.click(target,{clientX:170,clientY:240,detail:1});expect(p.onChange).toHaveBeenLastCalledWith([.5,.5,.2,.1]);fireEvent.click(target,{clientX:400,clientY:600,detail:1});expect(p.onChange).toHaveBeenLastCalledWith([.8,.9,.2,.1]);expect(screen.getByText('Região: esquerda 10%, topo 20%, largura 20%, altura 10%.')).toBeInTheDocument();});
it('provides keyboard precision while preserving the page and region boundaries',()=>{const p=props({bbox:[.8,0,.2,.1]});render(<MarkerPreview {...p}/>);load();const target=screen.getByRole('button',{name:'Posicionar região do número'});fireEvent.keyDown(target,{key:'ArrowRight'});expect(p.onChange).toHaveBeenLastCalledWith([.8,0,.2,.1]);fireEvent.keyDown(target,{key:'ArrowUp'});expect(p.onChange).toHaveBeenLastCalledWith([.8,0,.2,.1]);fireEvent.keyDown(target,{key:'ArrowLeft',shiftKey:true});expect(p.onChange).toHaveBeenLastCalledWith([.799,0,.2,.1]);fireEvent.keyDown(target,{key:'ArrowDown'});expect(p.onChange).toHaveBeenLastCalledWith([.8,.01,.2,.1]);});
it('revokes readiness on page or request changes and ignores detached previous image loads',()=>{const p=props();const view=render(<MarkerPreview {...p}/>);const oldImage=screen.getByRole('img');load(oldImage);expect(p.onReady).toHaveBeenLastCalledWith({identity:image.identity,ready:true});const next={...image,identity:'import/doc-sha/page-2/image-sha-2/request-2'};view.rerender(<MarkerPreview {...p} image={next}/>);expect(p.onReady).toHaveBeenLastCalledWith({identity:next.identity,ready:false});const calls=vi.mocked(p.onReady).mock.calls.length;fireEvent.load(oldImage);expect(p.onReady).toHaveBeenCalledTimes(calls);expect(screen.getByRole('button',{name:'Posicionar região do número'})).toHaveAttribute('aria-disabled','true');load();expect(p.onReady).toHaveBeenLastCalledWith({identity:next.identity,ready:true});view.rerender(<MarkerPreview {...p} image={{...next,identity:next.identity+'/retry-3'}}/>);expect(p.onReady).toHaveBeenLastCalledWith({identity:next.identity+'/retry-3',ready:false});});
it('reports failure and keeps readiness false through retry until the next image loads',()=>{const p=props();const view=render(<MarkerPreview {...p}/>);load();fireEvent.error(screen.getByRole('img'));expect(screen.getByRole('alert')).toBeVisible();expect(p.onReady).toHaveBeenLastCalledWith({identity:image.identity,ready:false});fireEvent.click(screen.getByRole('button',{name:'Atualizar prévia'}));expect(p.onRetry).toHaveBeenCalledOnce();fireEvent.keyDown(screen.getByRole('button',{name:'Posicionar região do número'}),{key:'ArrowRight'});expect(p.onChange).not.toHaveBeenCalled();const next={...image,identity:image.identity+'/retry'};view.rerender(<MarkerPreview {...p} image={next}/>);load();expect(p.onReady).toHaveBeenLastCalledWith({identity:next.identity,ready:true});expect(screen.queryByRole('alert')).not.toBeInTheDocument();});
it('rejects invalid geometry or dimensions and ignores image load events while loading',()=>{const p=props({bbox:[.9,.2,.2,.1],loading:true});const view=render(<MarkerPreview {...p}/>);load();expect(p.onReady).not.toHaveBeenCalledWith({identity:image.identity,ready:true});fireEvent.keyDown(screen.getByRole('button',{name:'Posicionar região do número'}),{key:'ArrowLeft'});expect(p.onChange).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Atualizar prévia'})).toBeDisabled();view.rerender(<MarkerPreview {...p} loading={false} image={{...image,width:0}}/>);expect(screen.queryByRole('img')).not.toBeInTheDocument();expect(screen.getByText('Informe uma região válida pelos controles para posicionar o contorno.')).toBeVisible();});

it('rejects zero or mismatched intrinsic image dimensions despite an onLoad event',()=>{const p=props();render(<MarkerPreview {...p}/>);const image=screen.getByRole('img');fireEvent.load(image);expect(p.onReady).toHaveBeenLastCalledWith({identity:p.image!.identity,ready:false});Object.defineProperties(image,{naturalWidth:{value:1,configurable:true},naturalHeight:{value:1,configurable:true}});fireEvent.load(image);expect(screen.getByRole('alert')).toBeVisible();expect(p.onReady).not.toHaveBeenCalledWith({identity:p.image!.identity,ready:true});load(image);expect(p.onReady).toHaveBeenLastCalledWith({identity:p.image!.identity,ready:true});});

it('does not move on keyboard-generated Enter or Space clicks',()=>{const p=props();render(<MarkerPreview {...p}/>);load();const target=screen.getByRole('button',{name:'Posicionar região do número'});for(const key of ['Enter',' ']){fireEvent.keyDown(target,{key});fireEvent.click(target,{detail:0,clientX:0,clientY:0});}expect(p.onChange).not.toHaveBeenCalled();});
it('keeps image readiness across stateful parent callbacks and box edits, while revoking region confirmation',()=>{const signals=vi.fn();function Parent(){const[ready,setReady]=useState(false),[box,setBox]=useState<MarkerPreviewProps['bbox']>([.1,.2,.2,.1]),[confirmed,setConfirmed]=useState(false);return <><MarkerPreview image={{...image}} bbox={box} onReady={state=>{signals(state);setReady(state.ready);}} onChange={value=>{setBox(value);setConfirmed(false);}} onRetry={()=>{setReady(false);}}/><p>{ready?'Imagem atual carregada':'Imagem pendente'}</p><label><input type="checkbox" disabled={!ready} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Conferência da região</label></>;}render(<Parent/>);load();expect(screen.getByText('Imagem atual carregada')).toBeVisible();fireEvent.click(screen.getByLabelText('Conferência da região'));expect(screen.getByLabelText('Conferência da região')).toBeChecked();fireEvent.keyDown(screen.getByRole('button',{name:'Posicionar região do número'}),{key:'ArrowRight'});expect(screen.getByLabelText('Conferência da região')).not.toBeChecked();expect(screen.getByLabelText('Conferência da região')).toBeEnabled();expect(screen.getByText('Região: esquerda 11%, topo 20%, largura 20%, altura 10%.')).toBeVisible();expect(signals).toHaveBeenCalledTimes(2);});

it('keeps an intrinsic-dimension-verified cached load ready even before passive effects run on initial load or retry',()=>{const signals=vi.fn();function CachedParent({identity}:{identity:string}){useLayoutEffect(()=>{const node=screen.getByRole('img');Object.defineProperties(node,{naturalWidth:{value:600,configurable:true},naturalHeight:{value:800,configurable:true}});fireEvent.load(node);},[identity]);return <MarkerPreview image={{...image,identity}} bbox={[.1,.2,.2,.1]} onChange={vi.fn()} onReady={signals} onRetry={vi.fn()}/>;}const view=render(<CachedParent identity={image.identity}/>);expect(signals).toHaveBeenLastCalledWith({identity:image.identity,ready:true});view.rerender(<CachedParent identity={image.identity+'/refresh'}/>);expect(signals).toHaveBeenLastCalledWith({identity:image.identity+'/refresh',ready:true});expect(screen.getByRole('button',{name:'Posicionar região do número'})).toHaveAttribute('aria-disabled','false');});

it('zooms the original image inside an accessible scroll region without changing readiness or normalized geometry',()=>{const p=props();render(<MarkerPreview {...p}/>);load();const imageNode=screen.getByRole('img'),target=screen.getByRole('button',{name:'Posicionar região do número'}),viewport=screen.getByRole('region',{name:'Página original com rolagem'});const calls=vi.mocked(p.onReady).mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'200%'}));expect(target).toHaveStyle({width:'200%'});expect(screen.getByRole('button',{name:'200%'})).toHaveAttribute('aria-pressed','true');expect(viewport).toHaveAttribute('tabindex','0');expect(viewport).toHaveClass('overflow-auto','max-h-[60vh]','max-w-full');expect(screen.getByRole('img')).toBe(imageNode);expect(p.onReady).toHaveBeenCalledTimes(calls);viewport.scrollLeft=120;viewport.scrollTop=90;vi.spyOn(imageNode,'getBoundingClientRect').mockReturnValue({left:-100,top:-50,width:600,height:800,right:500,bottom:750,x:-100,y:-50,toJSON:()=>({})});fireEvent.click(target,{clientX:200,clientY:350,detail:1});expect(p.onChange).toHaveBeenLastCalledWith([.5,.5,.2,.1]);fireEvent.keyDown(target,{key:'ArrowRight'});expect(p.onChange).toHaveBeenLastCalledWith([.11,.2,.2,.1]);fireEvent.keyDown(target,{key:'ArrowDown',shiftKey:true});expect(p.onChange).toHaveBeenLastCalledWith([.1,.201,.2,.1]);const overlay=target.querySelector('[aria-hidden]');expect(overlay).toHaveStyle({width:'20%',height:'10%'});fireEvent.click(screen.getByRole('button',{name:'Restaurar zoom e posição'}));expect(target).toHaveStyle({width:'100%'});expect(viewport.scrollLeft).toBe(0);expect(viewport.scrollTop).toBe(0);expect(p.onReady).toHaveBeenCalledTimes(calls);});
it('keeps zoom across box changes but resets scroll and zoom for a different current image identity',()=>{const p=props(),view=render(<MarkerPreview {...p}/>);load();const viewport=screen.getByRole('region',{name:'Página original com rolagem'});fireEvent.click(screen.getByRole('button',{name:'300%'}));viewport.scrollLeft=200;viewport.scrollTop=250;view.rerender(<MarkerPreview {...p} bbox={[.2,.3,.2,.1]}/>);expect(screen.getByRole('button',{name:'300%'})).toHaveAttribute('aria-pressed','true');expect(viewport.scrollLeft).toBe(200);view.rerender(<MarkerPreview {...p} image={{...image,identity:image.identity+'/page-2'}}/>);expect(screen.getByRole('button',{name:'100%'})).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('button',{name:'Posicionar região do número'})).toHaveStyle({width:'100%'});expect(viewport.scrollLeft).toBe(0);expect(viewport.scrollTop).toBe(0);expect(p.onReady).toHaveBeenLastCalledWith({identity:image.identity+'/page-2',ready:false});});
