import {afterEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {questionDocumentPagePreviewSchema} from '@remoa/contracts';
import {MarkerPagePreview} from './marker-page-preview';
import {testId,testAudit} from './recovery.test-fixtures';
import {QuestionsApiError} from '@/features/questions/request';
vi.mock('./api',()=>({previewDocumentPage:vi.fn()}));
import {previewDocumentPage} from './api';
afterEach(()=>{cleanup();vi.clearAllMocks();vi.useRealTimers();});
const response=(page=1)=>questionDocumentPagePreviewSchema.parse({importId:testId,documentId:testId,page,pages:2,width:600,height:800,dpi:100,documentSha256:'a'.repeat(64),imageSha256:String(page).repeat(64),url:`https://example.org/private-page-${page}.png`,expiresInSec:300,provenance:{documentId:testId,page,bbox:[0,0,1,1]},audit:testAudit});
function load(){const node=screen.getByRole('img');Object.defineProperties(node,{naturalWidth:{value:600,configurable:true},naturalHeight:{value:800,configurable:true}});fireEvent.load(node);}
it('fetches the exact original page and enables readiness only after matching PNG dimensions load',async()=>{vi.mocked(previewDocumentPage).mockResolvedValue(response());const onReady=vi.fn();render(<MarkerPagePreview importId={testId} documentId={testId} page={1} bbox={[.1,.2,.1,.1]} onReady={onReady} onChange={vi.fn()}/>);await screen.findByRole('img');expect(screen.queryByRole('status')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Atualizar prévia'})).toBeEnabled();expect(previewDocumentPage).toHaveBeenCalledWith(testId,testId,1,expect.any(AbortSignal));expect(onReady).not.toHaveBeenCalledWith(true);load();expect(onReady).toHaveBeenLastCalledWith(true);});
it('aborts old requests and ignores an older response after the selected page changes',async()=>{let resolveFirst!:(value:ReturnType<typeof response>)=>void;vi.mocked(previewDocumentPage).mockImplementationOnce(()=>new Promise(resolve=>{resolveFirst=resolve;})).mockResolvedValueOnce(response(2));const onReady=vi.fn();const props={importId:testId,documentId:testId,bbox:[.1,.2,.1,.1] as const,onReady,onChange:vi.fn()};const view=render(<MarkerPagePreview {...props} page={1}/>);view.rerender(<MarkerPagePreview {...props} page={2}/>);await screen.findByRole('img');expect(vi.mocked(previewDocumentPage).mock.calls[0]![3]!.aborted).toBe(true);await act(async()=>resolveFirst(response(1)));expect(screen.getByRole('img')).toHaveAttribute('src',response(2).url);expect(onReady).not.toHaveBeenCalledWith(true);load();expect(onReady).toHaveBeenLastCalledWith(true);});
it('fails closed on API denial and retries through a new request without reusing old readiness',async()=>{vi.mocked(previewDocumentPage).mockRejectedValueOnce(new QuestionsApiError('forbidden')).mockResolvedValueOnce(response());const onReady=vi.fn();render(<MarkerPagePreview importId={testId} documentId={testId} page={1} bbox={[.1,.2,.1,.1]} onReady={onReady} onChange={vi.fn()}/>);await screen.findByRole('alert');expect(screen.queryByRole('img')).not.toBeInTheDocument();expect(onReady).not.toHaveBeenCalledWith(true);fireEvent.click(screen.getByRole('button',{name:'Atualizar prévia'}));await screen.findByRole('img');expect(previewDocumentPage).toHaveBeenCalledTimes(2);load();expect(onReady).toHaveBeenLastCalledWith(true);});
it('expires the original image and revokes confirmation before any new preview is requested',async()=>{vi.useFakeTimers();vi.mocked(previewDocumentPage).mockResolvedValue(response());const onReady=vi.fn();render(<MarkerPagePreview importId={testId} documentId={testId} page={1} bbox={[.1,.2,.1,.1]} onReady={onReady} onChange={vi.fn()}/>);await act(async()=>{await Promise.resolve();});load();expect(onReady).toHaveBeenLastCalledWith(true);act(()=>vi.advanceTimersByTime(300000));expect(onReady).toHaveBeenLastCalledWith(false);expect(screen.queryByRole('img')).not.toBeInTheDocument();expect(screen.getByRole('alert')).toBeVisible();expect(previewDocumentPage).toHaveBeenCalledOnce();});
