import {useState} from 'react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {ReasonDialog} from './reason-dialog';
afterEach(()=>{cleanup();vi.clearAllMocks();});
function Host({confirm=async()=>{},disableAfter=false}:{confirm?:(reason:string)=>Promise<void>;disableAfter?:boolean}){
 const[open,setOpen]=useState(false);const[done,setDone]=useState(false);
 return <section><h2>Importação demonstrativa</h2><button disabled={done} onClick={()=>setOpen(true)}>Repetir importação</button><button>Consultar importação</button><ReasonDialog title="Confirmar operação" description="Operação sintética" open={open} onOpenChange={setOpen} confirmLabel="Enviar operação" onConfirm={async reason=>{await confirm(reason);if(disableAfter)setDone(true);}}/></section>;
}
async function openDialog(){const opener=screen.getByRole('button',{name:'Repetir importação'});opener.focus();fireEvent.click(opener);return{opener,dialog:await screen.findByRole('dialog',{name:'Confirmar operação'})};}
describe('reason dialog controlled caller lifecycle',()=>{
 it('restores an import caller after Escape and clears its reason when reopened',async()=>{render(<Host/>);const{opener,dialog}=await openDialog();fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Conferência da importação'}});fireEvent.keyDown(dialog,{key:'Escape',code:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());await waitFor(()=>expect(opener).toHaveFocus());fireEvent.click(opener);await screen.findByRole('dialog');expect(screen.getByLabelText('Motivo desta operação')).toHaveValue('');expect(screen.getByRole('button',{name:'Enviar operação'})).toBeDisabled();});
 it('keeps the draft after a failure and blocks Escape and close while pending',async()=>{let reject!:(error:Error)=>void;const confirm=vi.fn(()=>new Promise<void>((_,no)=>{reject=no;}));render(<Host confirm={confirm}/>);const{dialog}=await openDialog();fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Motivo conferido de teste'}});fireEvent.click(screen.getByRole('button',{name:'Enviar operação'}));fireEvent.keyDown(dialog,{key:'Escape',code:'Escape'});fireEvent.click(screen.getByRole('button',{name:'Fechar'}));expect(screen.getByRole('dialog')).toBeInTheDocument();reject(new Error('network'));await screen.findByRole('alert');expect(screen.getByLabelText('Motivo desta operação')).toHaveValue('Motivo conferido de teste');expect(confirm).toHaveBeenCalledOnce();fireEvent.keyDown(dialog,{key:'Escape',code:'Escape'});await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());});
 it('moves focus to the next available action after success disables the opener',async()=>{const confirm=vi.fn(async()=>{});render(<Host confirm={confirm} disableAfter/>);await openDialog();fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Operação conferida de teste'}});fireEvent.click(screen.getByRole('button',{name:'Enviar operação'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(screen.getByRole('button',{name:'Repetir importação'})).toBeDisabled();await waitFor(()=>expect(screen.getByRole('button',{name:'Consultar importação'})).toHaveFocus());expect(confirm).toHaveBeenCalledWith('Operação conferida de teste');});
});
