import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {useEffect} from 'react';
import {RecoveryDialog} from './recovery-dialog';
import {QuestionsApiError} from '@/features/questions/request';
import {testId,testCandidate,testAudit} from './recovery.test-fixtures';
vi.mock('./api',()=>({createCandidate:vi.fn(),repairCandidateNumber:vi.fn()}));
vi.mock('./marker-page-preview',()=>({MarkerPagePreview:({page,onReady}:{page:number;onReady?:(value:boolean)=>void})=>{useEffect(()=>onReady?.(true),[page,onReady]);return <><p>Prévia sintética da página {page}</p><button onClick={()=>onReady?.(false)}>Imagem expirada no teste</button><button onClick={()=>onReady?.(true)}>Nova imagem carregada no teste</button></>;}}));
import {createCandidate,repairCandidateNumber} from './api';
afterEach(()=>{cleanup();vi.clearAllMocks();});
function marker(){for(const[label,value]of [['Página do número','2'],['Esquerda (%)','10'],['Topo (%)','5'],['Largura (%)','20'],['Altura (%)','10']])fireEvent.change(screen.getByLabelText(label!),{target:{value}});}
async function fill(){fireEvent.change(screen.getByLabelText('Número original da questão'),{target:{value:'01'}});marker();fireEvent.change(screen.getByLabelText('Enunciado próprio da questão'),{target:{value:'Pergunta sintética recuperada'}});fireEvent.change(screen.getByLabelText('Páginas que compõem a questão'),{target:{value:'2, 3'}});fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Transcrição sintética conferida'}});await waitFor(()=>expect(screen.getByLabelText('Conferi o número e sua região no documento original')).toBeEnabled());fireEvent.click(screen.getByLabelText('Conferi o número e sua região no documento original'));}
it('creates needs-review evidence with normalized marker, distinct number and stable ID across a conflict retry',async()=>{const candidate=testCandidate();vi.mocked(createCandidate).mockRejectedValueOnce(new QuestionsApiError('conflict')).mockResolvedValue({candidate,affectedCandidates:[candidate],importRevision:9,audit:testAudit});const saved=vi.fn();const reload=vi.fn().mockResolvedValue({importRevision:8});render(<RecoveryDialog importId={testId} importRevision={7} documentId={testId} onClose={vi.fn()} onSaved={saved} onReload={reload}/>);await fill();fireEvent.click(screen.getByRole('button',{name:'Criar candidata para revisão'}));await screen.findByRole('alert');const first=vi.mocked(createCandidate).mock.calls[0]![1];expect(first).toMatchObject({importRevision:7,originalNumber:'1',ownStem:'Pergunta sintética recuperada',markerProvenance:{documentId:testId,page:2,bbox:[.1,.05,.2,.1]},provenance:[{documentId:testId,page:2,bbox:[0,0,1,1]},{documentId:testId,page:3,bbox:[0,0,1,1]}]});expect(first).not.toHaveProperty('correctKey');expect(saved).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Atualizar os dados do lote'}));await waitFor(()=>expect(reload).toHaveBeenCalledOnce());expect(screen.getByLabelText('Enunciado próprio da questão')).toHaveValue('Pergunta sintética recuperada');await waitFor(()=>expect(screen.getByLabelText('Conferi o número e sua região no documento original')).not.toBeChecked());fireEvent.click(screen.getByLabelText('Conferi o número e sua região no documento original'));fireEvent.click(screen.getByRole('button',{name:'Criar candidata para revisão'}));await waitFor(()=>expect(saved).toHaveBeenCalledOnce());expect(vi.mocked(createCandidate).mock.calls[1]![1]).toMatchObject({candidateId:first.candidateId,importRevision:8,originalNumber:'1',ownStem:first.ownStem});});
it('rejects invalid number/page/region without a mutation and retains the entered fields',async()=>{render(<RecoveryDialog importId={testId} importRevision={7} documentId={testId} onClose={vi.fn()} onSaved={vi.fn()} onReload={vi.fn()}/>);await fill();fireEvent.change(screen.getByLabelText('Número original da questão'),{target:{value:'O1'}});fireEvent.click(screen.getByLabelText('Conferi o número e sua região no documento original'));fireEvent.click(screen.getByRole('button',{name:'Criar candidata para revisão'}));await screen.findByRole('alert');expect(createCandidate).not.toHaveBeenCalled();expect(screen.getByLabelText('Número original da questão')).toHaveValue('O1');expect(screen.getByLabelText('Enunciado próprio da questão')).toHaveValue('Pergunta sintética recuperada');});
it('repairs only the number using both read revisions, preserving evidence and requiring original preview',async()=>{const candidate=testCandidate();vi.mocked(repairCandidateNumber).mockResolvedValue({candidate,affectedCandidates:[candidate],importRevision:8,audit:testAudit});render(<RecoveryDialog importId={testId} importRevision={7} documentId={testId} candidate={candidate} onClose={vi.fn()} onSaved={vi.fn()} onReload={vi.fn()}/>);expect(screen.getByLabelText('Conferi o número e sua região no documento original')).toBeDisabled();marker();fireEvent.change(screen.getByLabelText('Número original da questão'),{target:{value:'02'}});fireEvent.change(screen.getByLabelText('Motivo desta operação'),{target:{value:'Número sintético conferido na página'}});await waitFor(()=>expect(screen.getByLabelText('Conferi o número e sua região no documento original')).toBeEnabled());fireEvent.click(screen.getByLabelText('Conferi o número e sua região no documento original'));fireEvent.click(screen.getByRole('button',{name:'Registrar número conferido'}));await waitFor(()=>expect(repairCandidateNumber).toHaveBeenCalledWith(testId,testId,{importRevision:7,revision:3,originalNumber:'2',markerProvenance:{documentId:testId,page:2,bbox:[.1,.05,.2,.1]},reason:'Número sintético conferido na página'}));expect(screen.queryByLabelText('Enunciado próprio da questão')).toBeNull();});

it('revokes the previous region confirmation when the image expires or refreshes, requiring an explicit new confirmation',async()=>{render(<RecoveryDialog importId={testId} importRevision={7} documentId={testId} onClose={vi.fn()} onSaved={vi.fn()} onReload={vi.fn()}/>);await fill();const confirmation=screen.getByLabelText('Conferi o número e sua região no documento original');expect(confirmation).toBeChecked();fireEvent.click(screen.getByRole('button',{name:'Imagem expirada no teste'}));expect(confirmation).not.toBeChecked();expect(confirmation).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Nova imagem carregada no teste'}));expect(confirmation).toBeEnabled();expect(confirmation).not.toBeChecked();expect(screen.getByRole('button',{name:'Criar candidata para revisão'})).toBeDisabled();expect(createCandidate).not.toHaveBeenCalled();});
it('does not permit confirmation for zero or off-page typed geometry, and preserves those inputs for correction',async()=>{render(<RecoveryDialog importId={testId} importRevision={7} documentId={testId} onClose={vi.fn()} onSaved={vi.fn()} onReload={vi.fn()}/>);await fill();const confirmation=screen.getByLabelText('Conferi o número e sua região no documento original');fireEvent.change(screen.getByLabelText('Largura (%)'),{target:{value:'0'}});expect(confirmation).toBeDisabled();expect(confirmation).not.toBeChecked();fireEvent.change(screen.getByLabelText('Largura (%)'),{target:{value:'95'}});expect(confirmation).toBeDisabled();expect(screen.getByLabelText('Largura (%)')).toHaveValue(95);expect(createCandidate).not.toHaveBeenCalled();});
