'use client';
import { useState } from 'react';
import type { z } from 'zod';
import type { questionSourceInputSchema } from '@remoa/contracts';
import { t } from '@remoa/strings';
import { Alert, Button, Input, Select, Textarea } from '@remoa/ui';
import { adminQuestionError, tq } from './labels';
type SourceInput=z.output<typeof questionSourceInputSchema>;
export function SourceForm({initial,onSave}:{initial?:Partial<SourceInput>;onSave:(input:SourceInput)=>Promise<void>}){
  const [name,setName]=useState(initial?.name??'');const[publisher,setPublisher]=useState(initial?.publisher??'');const[url,setUrl]=useState(initial?.url??'');const[rights,setRights]=useState<SourceInput['rightsStatus']>(initial?.rightsStatus??'pending');const[evidence,setEvidence]=useState(initial?.rightsEvidence??'');const[scope,setScope]=useState(initial?.rightsScope??'');const[expiry,setExpiry]=useState(initial?.rightsExpiresAt?new Date(initial.rightsExpiresAt).toISOString().slice(0,10):'');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[saved,setSaved]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setError(null);setSaved(false);setBusy(true);try{const{questionSourceInputSchema}=await import('./schema-loaders');const parsed=questionSourceInputSchema.safeParse({name:name.trim(),publisher:publisher.trim(),url:url.trim(),rightsStatus:rights,rightsEvidence:evidence.trim()||null,rightsScope:scope.trim()||null,rightsExpiresAt:expiry?new Date(`${expiry}T23:59:59Z`):null,reason:reason.trim()});if(!parsed.success){setError(tq('questionsAdmin.rightsNotice'));return;}await onSave(parsed.data);setSaved(true);}catch(e){setError(adminQuestionError(e));}finally{setBusy(false);}};
  return <form className="flex flex-col gap-5" onSubmit={e=>void submit(e)}><Input label={tq('questionsAdmin.sourceName')} maxLength={300} required value={name} onChange={e=>setName(e.target.value)}/><Input label={tq('questionsAdmin.publisher')} maxLength={300} required value={publisher} onChange={e=>setPublisher(e.target.value)}/><Input label={tq('questionsAdmin.sourceUrl')} type="url" required value={url} onChange={e=>setUrl(e.target.value)}/><Select label={tq('questionsAdmin.rights')} value={rights} onValueChange={v=>setRights(v as SourceInput['rightsStatus'])} options={(['pending','authorized','restricted','revoked'] as const).map(value=>({value,label:tq(`questionsAdmin.rightsLabels.${value}`)}))}/><Textarea label={tq('questionsAdmin.rightsEvidence')} maxLength={4000} required={rights==='authorized'} value={evidence} onChange={e=>setEvidence(e.target.value)}/><Textarea label={tq('questionsAdmin.rightsScope')} maxLength={2000} value={scope} onChange={e=>setScope(e.target.value)}/><Input label={tq('questionsAdmin.rightsExpiry')} type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/><Textarea label={tq('questionsAdmin.reason')} minLength={8} maxLength={500} required value={reason} onChange={e=>setReason(e.target.value)}/><p className="text-xs text-muted">{tq('questionsAdmin.reasonHelp')}</p><Alert title={tq('questionsAdmin.sourceRightsInfo')}/>{error?<Alert role="alert" tone="review" title={error}/>:null}{saved?<p role="status">{tq('questionsAdmin.sourceSaved')}</p>:null}<Button type="submit" loading={busy} loadingLabel={t('common.loading')} disabled={reason.trim().length<8||!name.trim()||!publisher.trim()||!url.trim()||(rights==='authorized'&&!evidence.trim())}>{tq('questionsAdmin.createSource')}</Button></form>;
}
