import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import { UploadScreen } from './upload-screen';
import { questionImportInputSchema,questionSourceSchema } from '@remoa/contracts';
vi.mock('next/navigation',()=>({useRouter:()=>({push:vi.fn()})}));
vi.mock('./api',()=>({listSources:vi.fn(),uploadDocument:vi.fn(),createImport:vi.fn()}));
vi.mock('@remoa/ui',async original=>{const ui=await original<typeof import('@remoa/ui')>();return {...ui,Select:({label,value,onValueChange,options}:{label:string;value:string;onValueChange:(v:string)=>void;options:{value:string;label:string}[]})=><label>{label}<select value={value} onChange={e=>onValueChange(e.target.value)}>{options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></label>};});
import { listSources,uploadDocument,createImport } from './api';
const id='550e8400-e29b-41d4-a716-446655440000';
const proofId='550e8400-e29b-41d4-a716-446655440001',keyId='550e8400-e29b-41d4-a716-446655440002';
afterEach(()=>{cleanup();vi.clearAllMocks();});
beforeEach(()=>{vi.resetAllMocks();vi.mocked(listSources).mockResolvedValue({items:[questionSourceSchema.parse({id,name:'Fonte sintética',publisher:'Instituição',url:'https://example.org',rightsStatus:'pending',rightsEvidence:null,rightsScope:null,rightsExpiresAt:null,documentVersion:null,accessedAt:new Date(),createdAt:new Date(),updatedAt:new Date()})],audit:{} as never});vi.mocked(uploadDocument).mockImplementation(async(_file,_source,kind)=>({document:{id:kind==='exam'?proofId:keyId,kind,sha256:'a'.repeat(64),bytes:8,pages:3},audit:{} as never}));vi.mocked(createImport).mockRejectedValue(new Error('network'));});
async function prepare(withKey=true){render(<UploadScreen/>);await screen.findByRole('option',{name:'Fonte sintética'});fireEvent.change(screen.getByLabelText('Fonte registrada'),{target:{value:id}});for(const label of withKey?['Prova em PDF','Gabarito definitivo em PDF']:['Prova em PDF'])fireEvent.change(screen.getByLabelText(label),{target:{files:[new File(['%PDF-1'],'sample.pdf',{type:'application/pdf'})]}});for(const[label,value] of [['Nome da prova','Prova sintética'],['Instituição','Instituição sintética'],['Edição','2026'],['Caderno','Um'],['Motivo desta operação','Importação demonstrativa autorizada']])fireEvent.change(screen.getByLabelText(label!),{target:{value}});return screen.getByRole('button',{name:'Enviar para processamento'});}

it('retains a successful proof upload when key upload fails; retry reuses saved docs and same creation key',async()=>{
 vi.mocked(listSources).mockResolvedValue({items:[questionSourceSchema.parse({id,name:'Fonte sintética',publisher:'Instituição',url:'https://example.org',rightsStatus:'pending',rightsEvidence:null,rightsScope:null,rightsExpiresAt:null,accessedAt:new Date(),documentVersion:null,createdAt:new Date(),updatedAt:new Date()})],audit:{} as never});let keyCalls=0;vi.mocked(uploadDocument).mockImplementation(async(_file,_source,kind)=>{if(kind==='answer_key'&&++keyCalls===1)throw new Error('network');return {document:{id:kind==='exam'?proofId:keyId,kind,sha256:'a'.repeat(64),bytes:8,pages:1},audit:{} as never};});vi.mocked(createImport).mockRejectedValue(new Error('network'));render(<UploadScreen/>);await screen.findByRole('option',{name:'Fonte sintética'});fireEvent.change(screen.getByLabelText('Fonte registrada'),{target:{value:id}});for(const label of ['Prova em PDF','Gabarito definitivo em PDF'])fireEvent.change(screen.getByLabelText(label),{target:{files:[new File(['%PDF-1'],'sample.pdf',{type:'application/pdf'})]}});for(const[label,value] of [['Nome da prova','Prova sintética'],['Instituição','Instituição sintética'],['Edição','2026'],['Caderno','Um'],['Motivo desta operação','Importação demonstrativa autorizada']])fireEvent.change(screen.getByLabelText(label!),{target:{value}});const submit=screen.getByRole('button',{name:'Enviar para processamento'});fireEvent.click(submit);await screen.findByText('Não conseguimos executar a operação. Tente novamente.');expect(uploadDocument).toHaveBeenCalledTimes(2);fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledOnce());expect(uploadDocument).toHaveBeenCalledTimes(3);const firstCall=vi.mocked(createImport).mock.calls[0]!;const firstKey=firstCall[1];
 const payload=questionImportInputSchema.parse(firstCall[0]);
 expect(payload).toEqual(firstCall[0]);
 expect(payload).toMatchObject({sourceId:id,documentId:proofId,answerKeyDocumentId:keyId,parserVersion:'f33-layout-v7',ocr:true,excludedPages:[],budgetCents:0,reason:'Importação demonstrativa autorizada',exam:{name:'Prova sintética',institution:'Instituição sintética',edition:'2026',booklet:'Um',durationSec:null}});
 expect(payload.parserVersion).not.toBe('f33-layout-v6');
await waitFor(()=>expect(submit).toBeEnabled());fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledTimes(2));expect(uploadDocument).toHaveBeenCalledTimes(3);expect(vi.mocked(createImport).mock.calls[1]?.[1]).toBe(firstKey);expect(vi.mocked(createImport).mock.calls[1]?.[0]).toEqual(payload);
});

it('creates without an answer-key document, uploads only the proof and sends no invented answer data',async()=>{
 const submit=await prepare(false);expect(screen.queryByLabelText('Páginas originais do gabarito')).not.toBeInTheDocument();fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledOnce());expect(uploadDocument).toHaveBeenCalledOnce();expect(vi.mocked(uploadDocument).mock.calls[0]?.[2]).toBe('exam');expect(questionImportInputSchema.parse(vi.mocked(createImport).mock.calls[0]![0])).toMatchObject({answerKeyDocumentId:null,answerKeyPages:null});
});
it('rejects malformed or duplicate pages before uploads; retains documents on discovered bounds failure',async()=>{
 const submit=await prepare();const pages=screen.getByLabelText('Páginas originais do gabarito');for(const value of ['1,1','abc','501']){fireEvent.change(pages,{target:{value}});fireEvent.click(submit);await screen.findByText('Informe páginas únicas entre 1 e 500, dentro do PDF do gabarito.');expect(uploadDocument).not.toHaveBeenCalled();expect(createImport).not.toHaveBeenCalled();}
 fireEvent.change(pages,{target:{value:'4'}});fireEvent.click(submit);await waitFor(()=>expect(uploadDocument).toHaveBeenCalledTimes(2));await waitFor(()=>expect(submit).toBeEnabled());expect(createImport).not.toHaveBeenCalled();fireEvent.click(submit);expect(uploadDocument).toHaveBeenCalledTimes(2);expect(createImport).not.toHaveBeenCalled();
 fireEvent.change(pages,{target:{value:'3,1'}});fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledOnce());expect(uploadDocument).toHaveBeenCalledTimes(2);const [payload,firstKey]=vi.mocked(createImport).mock.calls[0]!;expect(questionImportInputSchema.parse(payload)).toEqual(payload);expect(payload.answerKeyPages).toEqual([1,3]);await waitFor(()=>expect(submit).toBeEnabled());fireEvent.change(pages,{target:{value:'1,3'}});fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledTimes(2));expect(vi.mocked(createImport).mock.calls[1]?.[1]).toBe(firstKey);
});
it('removes key selection and cached key while retaining the proof on retry',async()=>{
 const submit=await prepare();fireEvent.change(screen.getByLabelText('Páginas originais do gabarito'),{target:{value:'2'}});fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledOnce());await waitFor(()=>expect(submit).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Remover gabarito'}));fireEvent.click(submit);await waitFor(()=>expect(createImport).toHaveBeenCalledTimes(2));expect(uploadDocument).toHaveBeenCalledTimes(2);expect(vi.mocked(createImport).mock.calls[1]?.[0]).toMatchObject({answerKeyDocumentId:null,answerKeyPages:null});expect(vi.mocked(createImport).mock.calls[1]?.[1]).not.toBe(vi.mocked(createImport).mock.calls[0]?.[1]);
});
