'use client';
import { QUESTION_PDF_PARSER_VERSION } from '@remoa/contracts/constants';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { t } from '@remoa/strings';
import { Alert,Button,Input,Select,Tag,Textarea } from '@remoa/ui';
import type { QuestionSource,QuestionDocument } from '@remoa/contracts';
import { actionLink,panel } from '@/features/questions/shared';
import { createImport,listSources,uploadDocument } from './api';
import { AdminQuestionTabs,AdminQuestionTitle } from './admin-shared';
import { parseAnswerKeyPages,parseExcludedPages,pdfFileError } from './inputs';
import { tq,adminQuestionError } from './labels';
export function UploadScreen(){
  const router=useRouter();const[sources,setSources]=useState<QuestionSource[]>([]);const[sourceId,setSourceId]=useState('');const[proof,setProof]=useState<File|null>(null);const[key,setKey]=useState<File|null>(null);const[uploadedProof,setUploadedProof]=useState<QuestionDocument|null>(null);const[uploadedKey,setUploadedKey]=useState<QuestionDocument|null>(null);const[examName,setExamName]=useState('');const[institution,setInstitution]=useState('');const[year,setYear]=useState(new Date().getFullYear());const[edition,setEdition]=useState('');const[booklet,setBooklet]=useState('');const[minutes,setMinutes]=useState(0);const[excluded,setExcluded]=useState('');const[keyPages,setKeyPages]=useState('');const[keyInputGeneration,setKeyInputGeneration]=useState(0);const[budget,setBudget]=useState(0);const[ocr,setOcr]=useState(true);const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[loadError,setLoadError]=useState(false);const[reload,setReload]=useState(0);const pending=useRef<{signature:string;key:string}|null>(null);
  useEffect(()=>{let active=true;setLoadError(false);void listSources().then(data=>{if(active)setSources(data.items);}).catch(()=>{if(active)setLoadError(true);});return()=>{active=false;};},[reload]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setError(null);const fileErrors=[pdfFileError(proof),key?pdfFileError(key):null];if(fileErrors.some(Boolean)){setError(tq(fileErrors.includes('size')?'questionsAdmin.fileTooLarge':'questionsAdmin.pdfOnly'));return;}const pages=parseExcludedPages(excluded);if(pages===null){setError(tq('questionsAdmin.excludedInvalid'));return;}const selectedKeyPages=key?parseAnswerKeyPages(keyPages):null;if(selectedKeyPages===undefined||(selectedKeyPages&&uploadedKey?.pages!=null&&selectedKeyPages.some(page=>page>uploadedKey.pages!))){setError(tq('questionsAdmin.keyPagesInvalid'));return;}if(!sourceId){setError(tq('questionsAdmin.sourceRequired'));return;}setBusy(true);
    try{let proofDoc=uploadedProof;let keyDoc=uploadedKey;const jobs=await Promise.allSettled([proofDoc?Promise.resolve(proofDoc):uploadDocument(proof!,sourceId,'exam',reason.trim()).then(r=>r.document),!key?Promise.resolve(null):keyDoc?Promise.resolve(keyDoc):uploadDocument(key,sourceId,'answer_key',reason.trim()).then(r=>r.document)]);if(jobs[0]!.status==='fulfilled'){proofDoc=jobs[0]!.value;setUploadedProof(proofDoc);}if(jobs[1]!.status==='fulfilled'){keyDoc=jobs[1]!.value;setUploadedKey(keyDoc);}const failed=jobs.find(r=>r.status==='rejected');if(failed?.status==='rejected')throw failed.reason;
      if(selectedKeyPages&&keyDoc?.pages!=null&&selectedKeyPages.some(page=>page>keyDoc.pages!)){setError(tq('questionsAdmin.keyPagesInvalid'));return;}const{questionImportInputSchema}=await import('./schema-loaders');const parsed=questionImportInputSchema.safeParse({sourceId,exam:{name:examName.trim(),institution:institution.trim(),year,edition:edition.trim(),booklet:booklet.trim(),durationSec:minutes?minutes*60:null},documentId:proofDoc!.id,answerKeyDocumentId:keyDoc?.id??null,answerKeyPages:selectedKeyPages,parserVersion:QUESTION_PDF_PARSER_VERSION,ocr,excludedPages:pages,budgetCents:Math.round(budget*100),reason:reason.trim()});if(!parsed.success){setError(tq('questionsAdmin.operationError'));return;}const signature=JSON.stringify(parsed.data);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};const result=await createImport(parsed.data,pending.current.key);router.push(`/admin/questoes/importacoes/${result.import.id}`);
    }catch(e){setError(adminQuestionError(e));}finally{setBusy(false);}
  };
  const chosen=sources.find(s=>s.id===sourceId);
  return <div className="flex flex-col gap-6 p-5 md:p-9"><AdminQuestionTitle title={tq('questionsAdmin.uploadTitle')} description={tq('questionsAdmin.uploadDescription')}/><AdminQuestionTabs/><form className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]" onSubmit={e=>void submit(e)}><section className={`${panel} flex flex-col gap-5`}>
    {loadError?<Alert role="alert" tone="review" title={tq('questionsAdmin.loadError')}><Button variant="secondary" onClick={()=>setReload(v=>v+1)}>{t('common.retry')}</Button></Alert>:null}<Select label={tq('questionsAdmin.source')} value={sourceId||'none'} onValueChange={value=>{if(busy)return;setSourceId(value==='none'?'':value);setUploadedProof(null);setUploadedKey(null);setKeyPages('');pending.current=null;}} options={[{value:'none',label:tq('questionsAdmin.sourceRequired')},...sources.map(s=>({value:s.id,label:s.name}))]}/><Link className={actionLink} href="/admin/questoes/fontes">{tq('questionsAdmin.sourceNew')}</Link>
    <div className="rounded-map border-2 border-dashed border-border-strong bg-primary-tint p-5"><Input label={tq('questionsAdmin.proof')} type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>{setProof(e.target.files?.[0]??null);setUploadedProof(null);}}/>{uploadedProof?<p className="mt-3 text-sm text-primary-deep" role="status">{tq('questionsAdmin.uploadedProofReuse')}</p>:null}</div><div className="rounded-map border-2 border-dashed border-border-strong bg-primary-tint p-5"><Input key={keyInputGeneration} label={tq('questionsAdmin.key')} type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>{setKey(e.target.files?.[0]??null);setUploadedKey(null);setKeyPages('');pending.current=null;}}/><p className="mt-3 text-sm text-muted">{tq('questionsAdmin.keyOptional')}</p>{key?<><Button variant="secondary" disabled={busy} onClick={()=>{setKey(null);setUploadedKey(null);setKeyPages('');setKeyInputGeneration(v=>v+1);pending.current=null;}}>{tq('questionsAdmin.keyRemove')}</Button><Input label={tq('questionsAdmin.keyPages')} value={keyPages} disabled={busy} placeholder={tq('questionsAdmin.keyPagesPlaceholder')} onChange={e=>setKeyPages(e.target.value)}/><p className="text-xs text-muted">{tq('questionsAdmin.keyPagesHelp')}</p></>:null}{uploadedKey?<p className="mt-3 text-sm text-primary-deep" role="status">{tq('questionsAdmin.uploadedKeyReuse')}</p>:null}</div>
    <div className="grid gap-4 md:grid-cols-2"><Input label={tq('questionsAdmin.examName')} required maxLength={300} value={examName} disabled={busy} onChange={e=>setExamName(e.target.value)}/><Input label={tq('questionsAdmin.institution')} required maxLength={300} value={institution} disabled={busy} onChange={e=>setInstitution(e.target.value)}/><Input label={tq('questionsAdmin.year')} type="number" required min={1900} max={2200} value={year} disabled={busy} onChange={e=>setYear(Number(e.target.value))}/><Input label={tq('questionsAdmin.edition')} required maxLength={200} value={edition} disabled={busy} onChange={e=>setEdition(e.target.value)}/><Input label={tq('questionsAdmin.booklet')} required maxLength={100} value={booklet} disabled={busy} onChange={e=>setBooklet(e.target.value)}/><Input label={tq('questionsAdmin.duration')} type="number" min={0} max={1440} value={minutes} disabled={busy} onChange={e=>setMinutes(Number(e.target.value))}/></div>
    <Input label={tq('questionsAdmin.excluded')} placeholder={tq('questionsAdmin.excludedPlaceholder')} value={excluded} disabled={busy} onChange={e=>setExcluded(e.target.value)}/><p className="text-xs text-muted">{tq('questionsAdmin.excludedHelp')}</p><Input label={tq('questionsAdmin.budget')} type="number" min={0} max={1000} step="0.01" value={budget} disabled={busy} onChange={e=>setBudget(Number(e.target.value))}/><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={ocr} disabled={busy} onChange={e=>setOcr(e.target.checked)}/>{tq('questionsAdmin.ocr')}</label><Textarea label={tq('questionsAdmin.reason')} required minLength={8} maxLength={500} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/><p className="text-xs text-muted">{tq('questionsAdmin.reasonHelp')}</p>{error?<Alert role="alert" tone="review" title={error}/>:null}<Button type="submit" loading={busy} loadingLabel={tq('questionsAdmin.uploading')} disabled={reason.trim().length<8||!sourceId||!proof}>{tq('questionsAdmin.uploadSubmit')}</Button>
  </section><aside className={`${panel} flex h-fit flex-col gap-4`}><h2 className="font-display text-2xl font-extrabold">{tq('questionsAdmin.publication')}</h2>{chosen?<Tag tone={chosen.rightsStatus==='authorized'?'steady':'watch'}>{tq(`questionsAdmin.rightsLabels.${chosen.rightsStatus}`)}</Tag>:null}<p className="text-muted">{tq('questionsAdmin.rightsNotice')}</p><p className="text-sm text-muted">{tq('questionsAdmin.publicationDescription')}</p><p className="text-sm text-muted">{tq('questionsAdmin.confidence')}</p></aside></form></div>;
}
