// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/auditoria" | "/admin/indicacoes" | "/admin/lista-de-espera" | "/admin/mapas" | "/admin/suporte" | "/admin/transacoes" | "/admin/usuarios" | "/app/calendario" | "/app/cobertura" | "/app/conta" | "/app/conta/[secao]" | "/app/editorial" | "/app/editorial/metricas" | "/app/hoje" | "/app/indicar" | "/app/loja" | "/app/m/revisar" | "/app/mapas" | "/app/mapas/[id]" | "/app/mapas/[id]/desafiar" | "/app/mapas/novo" | "/app/mapas/prontos" | "/app/notificacoes" | "/app/onboarding" | "/app/planos" | "/app/planos/sucesso" | "/app/progresso" | "/app/revisar" | "/app/revisar/sessao" | "/cadastro" | "/dev/emails" | "/entrar" | "/i/[code]" | "/lp" | "/m/[token]" | "/precos" | "/privacidade" | "/recuperar-senha" | "/redefinir-senha" | "/regulamento-indicacao" | "/termos"
type AppRouteHandlerRoutes = "/auth/callback" | "/offline.html"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/app" | "/app/conta"
type RedirectRoutes = "/app" | "/cobertura/[[...rest]]" | "/conta/[[...rest]]" | "/editorial/[[...rest]]" | "/hoje/[[...rest]]" | "/loja/[[...rest]]" | "/m/revisar/[[...rest]]" | "/mapas/[[...rest]]" | "/planos/[[...rest]]" | "/progresso/[[...rest]]" | "/revisar/[[...rest]]"
type RewriteRoutes = "/"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/auditoria": {}
  "/admin/indicacoes": {}
  "/admin/lista-de-espera": {}
  "/admin/mapas": {}
  "/admin/suporte": {}
  "/admin/transacoes": {}
  "/admin/usuarios": {}
  "/app": {}
  "/app/calendario": {}
  "/app/cobertura": {}
  "/app/conta": {}
  "/app/conta/[secao]": { "secao": string; }
  "/app/editorial": {}
  "/app/editorial/metricas": {}
  "/app/hoje": {}
  "/app/indicar": {}
  "/app/loja": {}
  "/app/m/revisar": {}
  "/app/mapas": {}
  "/app/mapas/[id]": { "id": string; }
  "/app/mapas/[id]/desafiar": { "id": string; }
  "/app/mapas/novo": {}
  "/app/mapas/prontos": {}
  "/app/notificacoes": {}
  "/app/onboarding": {}
  "/app/planos": {}
  "/app/planos/sucesso": {}
  "/app/progresso": {}
  "/app/revisar": {}
  "/app/revisar/sessao": {}
  "/auth/callback": {}
  "/cadastro": {}
  "/cobertura/[[...rest]]": { "rest"?: string[]; }
  "/conta/[[...rest]]": { "rest"?: string[]; }
  "/dev/emails": {}
  "/editorial/[[...rest]]": { "rest"?: string[]; }
  "/entrar": {}
  "/hoje/[[...rest]]": { "rest"?: string[]; }
  "/i/[code]": { "code": string; }
  "/loja/[[...rest]]": { "rest"?: string[]; }
  "/lp": {}
  "/m/[token]": { "token": string; }
  "/m/revisar/[[...rest]]": { "rest"?: string[]; }
  "/mapas/[[...rest]]": { "rest"?: string[]; }
  "/offline.html": {}
  "/planos/[[...rest]]": { "rest"?: string[]; }
  "/precos": {}
  "/privacidade": {}
  "/progresso/[[...rest]]": { "rest"?: string[]; }
  "/recuperar-senha": {}
  "/redefinir-senha": {}
  "/regulamento-indicacao": {}
  "/revisar/[[...rest]]": { "rest"?: string[]; }
  "/termos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/app": never
  "/app/conta": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
