// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/cadastro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/cadastro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/entrar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrar">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/entrar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/recuperar-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar-senha">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/recuperar-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/redefinir-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redefinir-senha">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/redefinir-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/lp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lp">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/lp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/precos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/precos">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/precos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/i/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/i/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/i/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/m/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/m/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidade">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/regulamento-indicacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/regulamento-indicacao">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/regulamento-indicacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/termos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/termos">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/termos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/admin/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/indicacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/indicacoes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/indicacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/lista-de-espera/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/lista-de-espera">> = Specific
  const handler = {} as typeof import("../../src/app/admin/lista-de-espera/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/mapas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/mapas">> = Specific
  const handler = {} as typeof import("../../src/app/admin/mapas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/suporte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suporte">> = Specific
  const handler = {} as typeof import("../../src/app/admin/suporte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/transacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transacoes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/transacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/admin/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/calendario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/calendario">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/calendario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/cobertura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/cobertura">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/cobertura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/conta/[secao]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/conta/[secao]">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/conta/[secao]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/conta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/conta">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/conta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/hoje/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/hoje">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/hoje/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/indicar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/indicar">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/indicar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/loja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/loja">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/loja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/mapas/[id]/desafiar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/mapas/[id]/desafiar">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/mapas/[id]/desafiar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/mapas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/mapas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/mapas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/mapas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/mapas">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/mapas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/mapas/prontos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/mapas/prontos">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/mapas/prontos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/notificacoes">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/planos">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/planos/sucesso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/planos/sucesso">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/planos/sucesso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/progresso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/progresso">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/progresso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/revisar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/revisar">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/revisar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/revisar/sessao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/revisar/sessao">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/revisar/sessao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(editorial)/editorial/metricas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/editorial/metricas">> = Specific
  const handler = {} as typeof import("../../src/app/app/(editorial)/editorial/metricas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(editorial)/editorial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/editorial">> = Specific
  const handler = {} as typeof import("../../src/app/app/(editorial)/editorial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(fullscreen)/mapas/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/mapas/novo">> = Specific
  const handler = {} as typeof import("../../src/app/app/(fullscreen)/mapas/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(fullscreen)/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/app/(fullscreen)/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(mobile)/m/revisar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/m/revisar">> = Specific
  const handler = {} as typeof import("../../src/app/app/(mobile)/m/revisar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/emails">> = Specific
  const handler = {} as typeof import("../../src/app/dev/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline.html/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/offline.html">> = Specific
  const handler = {} as typeof import("../../src/app/offline.html/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/conta/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/conta">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/conta/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(editorial)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/(editorial)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/(mobile)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/(mobile)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
