'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { t } from './labels';
import { Alert, Button, Input, Tag } from '@remoa/ui';
import type { ExamPaperPublic, QuestionPublic } from '@remoa/contracts';
import { getExam, listExams, questionError } from './api';
import {useQuestionFeatureFlags} from './flags';
import {SessionHistoryScreen} from './session-history-screen';
import { actionLink, ConfigDialog, PageTitle, panel, QuestionMeta } from './shared';
export function ExamsScreen({sessionsEnabled=true}:{sessionsEnabled?:boolean}={}){
  const [exams,setExams]=useState<ExamPaperPublic[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [version,setVersion]=useState(0);
  useEffect(()=>{const abort=new AbortController();setLoading(true);setError(null);void listExams(abort.signal).then(setExams).catch(e=>{if(!abort.signal.aborted)setError(questionError(e));}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[version]);
  const visible=exams.filter(e=>`${e.name} ${e.institution} ${e.year} ${e.booklet}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  return <div className="mx-auto flex w-full max-w-[1280px] flex-col gap-6 py-2 md:px-6"><PageTitle title={t('questions.examsTitle')} description={t('questions.examsDescription')}>{sessionsEnabled?<Link className={actionLink} href="/app/simulados">{t('questions.sessions')}</Link>:null}</PageTitle><Input variant="search" label={t('questions.examsSearch')} placeholder={t('questions.examsSearch')} value={search} onChange={e=>setSearch(e.target.value)}/>{loading?<p role="status">{t('common.loading')}</p>:error?<Alert role="alert" tone="review" title={error}><Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>{t('common.retry')}</Button></Alert>:visible.length===0?<section className={`${panel} py-14 text-center`}><h2 className="font-display text-2xl font-bold">{t('questions.examsEmpty')}</h2><p className="mt-3 text-muted">{t('questions.examsEmptyHelp')}</p></section>:<section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map(e=><article key={e.id} className={panel}><Tag>{t('questions.source.official_exam')}</Tag><h2 className="mt-5 font-display text-2xl font-extrabold">{e.name}</h2><p className="mt-3 text-muted">{e.institution} · {e.year}</p><p className="mt-2 text-sm text-muted">{t('questions.booklet',{name:e.booklet})}</p><p className="mt-4">{t('questions.examCount',{n:e.questionCount})}</p><p className="my-3 text-sm text-muted">{e.durationSec?t('questions.examDuration',{n:Math.round(e.durationSec/60)}):t('questions.examNoDuration')}</p><Link className={actionLink} href={`/app/provas/${e.id}`}>{t('questions.openExam')}</Link></article>)}</section>}<Link className={actionLink} href="/app/banco-de-questoes">{t('questions.backBank')}</Link></div>;
}
export function ExamDetailScreen({examId,sessionsEnabled=true}:{examId:string;sessionsEnabled?:boolean}){
  const [exam,setExam]=useState<{paper:ExamPaperPublic;questions:QuestionPublic[]}|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [version,setVersion]=useState(0);const [config,setConfig]=useState(false);
  useEffect(()=>{const abort=new AbortController();setLoading(true);setError(null);void getExam(examId,abort.signal).then(setExam).catch(e=>{if(!abort.signal.aborted)setError(questionError(e));}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[examId,version]);
  if(loading)return <p role="status">{t('common.loading')}</p>;if(!exam)return <Alert role="alert" tone="review" title={error??t('questions.examDetailError')}><Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>{t('common.retry')}</Button></Alert>;
  return <div className="mx-auto flex w-full max-w-[1100px] flex-col gap-6 py-2 md:px-6"><PageTitle title={exam.paper.name} description={`${exam.paper.institution} · ${exam.paper.year} · ${t('questions.booklet',{name:exam.paper.booklet})}`}><Button disabled={!sessionsEnabled||exam.paper.questionCount===0||exam.paper.status!=='published'} onClick={()=>setConfig(true)}>{t('questions.startExam')}</Button></PageTitle><Alert title={t('questions.examOriginal')}><p>{t('questions.examCount',{n:exam.paper.questionCount})}</p><p>{exam.paper.durationSec?t('questions.examDuration',{n:Math.round(exam.paper.durationSec/60)}):t('questions.examNoDuration')}</p></Alert>{exam.questions.map(q=><article className={panel} key={q.id}><QuestionMeta question={q}/><h2 className="mt-4 whitespace-pre-wrap break-words font-display text-xl font-bold">{q.stem}</h2></article>)}<Link className={actionLink} href="/app/provas">{t('common.back')}</Link>{config?<ConfigDialog examId={examId} count={exam.paper.questionCount} timerSec={exam.paper.durationSec} open onOpenChange={setConfig}/>:null}</div>;
}
export function SessionsScreen(){const flags=useQuestionFeatureFlags();return <SessionHistoryScreen enabled={flags.sessions}/>;}
