'use client';
import {useEffect,useState} from 'react';
import {Alert,Button,Dialog,Textarea} from '@remoa/ui';
import type {QuestionPublic} from '@remoa/contracts';
import {t} from './labels';
import {emptyUserState,getUserState,questionError,saveUserState,type QuestionUserState} from './api';
export function PersonalDialog({ question, open, onOpenChange, onSaved }: { question: QuestionPublic; open: boolean; onOpenChange: (v: boolean) => void; onSaved?: (v: QuestionUserState) => void }) {
  const [values, setValues] = useState<QuestionUserState>(emptyUserState); const [loaded, setLoaded] = useState(false); const [retry, setRetry] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false);
  useEffect(() => { if (!open) return; let active = true; setLoading(true); setLoaded(false); setError(null); setSaved(false); void getUserState(question.id).then(v => { if (active) { setValues(v); setLoaded(true); } }).catch(e => { if (active) setError(questionError(e)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [open, question.id, retry]);
  const save = async () => { setBusy(true); setError(null); try { const result = await saveUserState(question.id, values); setValues(result); onSaved?.(result); setSaved(true); } catch(e) { setError(questionError(e)); } finally { setBusy(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange} title={t('questions.noteTitle')} closeLabel={t('common.close')}><div className="flex flex-col gap-5">{loading ? <p role="status">{t('common.loading')}</p> : loaded ? <><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={values.favorite} onChange={e => { setSaved(false); setValues({ ...values, favorite: e.target.checked }); }} />{t('questions.favorite')}</label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={values.doubtful} onChange={e => { setSaved(false); setValues({ ...values, doubtful: e.target.checked }); }} />{t('questions.markDoubt')}</label><Textarea label={t('questions.note')} placeholder={t('questions.notePlaceholder')} maxLength={10000} value={values.annotation} onChange={e => { setSaved(false); setValues({ ...values, annotation: e.target.value }); }} /><Button loading={busy} onClick={() => void save()}>{t('questions.saveNote')}</Button></> : <Button variant="secondary" onClick={()=>setRetry(n=>n+1)}>{t('common.retry')}</Button>}{error ? <Alert tone="review" role="alert" title={error} /> : null}{saved ? <p role="status" className="text-primary-deep">{t('questions.noteSaved')}</p> : null}</div></Dialog>;
}
