import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QuestionsHub } from './questions-hub';
import { SessionScreen } from './session-screen';
import { ConfigDialog } from './shared';
import type { QuestionPublic } from '@remoa/contracts';
const ID=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const q: QuestionPublic={id:ID(1),canonicalId:ID(1),version:1,type:'objective',stem:'Amostra sintética de interpretação',alternatives:[{key:'A',text:'Comparar parte e total'},{key:'B',text:'Descartar informações'}],origin:'official_exam',visibility:'public',availability:'active',difficulty:'medium',topicId:null,areaId:null,sourceId:null,sourceLabel:'Fonte sintética',reviewed:false,assets:[],boardId:null,cardIds:[],createdAt:new Date('2026-10-08T12:00:00.000Z')};
const reference={questionId:ID(1),version:1,correctKey:'A',explanation:'Explicação autorizada após a resposta',distractorNotes:null,annulled:false,reviewed:false,reviewerName:null,reviewerCrm:null,referenceDate:null,sourceUrl:null,obsolete:false};
const session=(mode='study',answered=false,status='active'): {id:string;mode:string;status:string;revision:number;startedAt:string;deadline:string|null;finishedAt:string|null;serverTime:string;items:{id:string;position:number;question:QuestionPublic;originalNumber:string;selectedKey:string|null;answered:boolean;doubtful:boolean;revision:number}[]}=>({id:ID(20),mode,status,revision:0,startedAt:'2026-10-08T12:00:00.000Z',deadline:null,finishedAt:status==='active'?null:'2026-10-08T13:00:00.000Z',serverTime:new Date().toISOString(),items:[{id:ID(21),position:0,question:q,originalNumber:'01',selectedKey:answered?'A':null,answered,doubtful:false,revision:answered?1:0}]});
const report={sessionId:ID(20),version:1,correct:1,incorrect:0,unanswered:0,annulled:0,denominator:1,score:1,items:[{itemId:ID(21),result:'correct',reference}]};
let institutions={items:[{name:'Instituição sintética',paperCount:1}],truncated:false};let areasList:{id:string;name:string}[]=[];let topicsList:{id:string;name:string}[]=[];let current=session();let list:unknown={items:[q],nextCursor:null,total:1};let failAnswer=false,failCreate=false;let failPersonal=false;let catalogueError:string|null=null;let answerAttempts:RequestInit[]=[];let createAttempts:RequestInit[]=[];let maps:{id:string;title:string}[]=[];let lastAiBody='';const calls:string[]=[];const push=vi.fn();
vi.mock('next/navigation',()=>({useRouter:()=>({push})}));
vi.mock('@/lib/api',()=>({api:vi.fn(async(path:string,init?:RequestInit)=>{
  calls.push(path);
  if(path==='/v1/question-institutions')return {ok:true,data:institutions};
  if(path.endsWith('/recalculation'))return {ok:true,data:{sessionId:ID(20),originalVersion:1,calculatedAt:new Date(),complete:false,aggregates:null,items:[{itemId:ID(21),originalQuestionId:q.id,originalQuestionVersion:1,comparedQuestionId:null,comparedQuestionVersion:null,outcome:'unavailable',reasonCode:'rights_unavailable',reference:null}]}};
  if(path==='/v1/question-sessions'&&init?.method==='POST'){createAttempts.push(init);if(failCreate){failCreate=false;throw new Error('retry');}return {ok:true,data:current};}
  if(path.startsWith('/v1/questions?'))return catalogueError?{ok:false,error:{code:catalogueError,message:'machine'}}:{ok:true,data:list};
  if(path==='/v1/boards')return {ok:true,data:maps};
  if(path==='/v1/challenge-ai/sessions'&&init?.method==='POST'){lastAiBody=String(init.body);return {ok:true,data:{id:ID(30)}};}
  if(path.startsWith('/v1/challenge-ai/taxonomy?kind=area'))return {ok:true,data:areasList};
  if(path.startsWith('/v1/challenge-ai/taxonomy?kind=topic'))return {ok:true,data:topicsList};
  if(path==='/v1/exams'||path==='/v1/question-sessions'||path.startsWith('/v1/challenge-ai/taxonomy'))return {ok:true,data:[]};
  if(path.endsWith('/answer')){answerAttempts.push(init!);if(failAnswer){failAnswer=false;throw new Error('lost acknowledgement');}const input=JSON.parse(String(init?.body));current={...current,items:[{...current.items[0]!,answered:true,selectedKey:input.selectedKey,revision:1}]};return {ok:true,data:{itemId:ID(21),selectedKey:input.selectedKey,revision:1,savedAt:new Date().toISOString()}};}
  if(path.endsWith('/reference'))return {ok:true,data:reference};
  if(path.endsWith('/finish')||path.endsWith('/report'))return {ok:true,data:report};
  if(path.endsWith('/user-state'))return failPersonal?{ok:false,error:{code:'internal',message:'failed'}}:{ok:true,data:{favorite:false,doubtful:true,annotation:''}};
  if(path===`/v1/question-sessions/${ID(20)}`)return {ok:true,data:current};
  return {ok:false,error:{code:'not_found',message:path}};
})}));
beforeEach(()=>{document.documentElement.dataset.motion='reduced';institutions={items:[{name:'Instituição sintética',paperCount:1}],truncated:false};areasList=[];topicsList=[];current=session();list={items:[q],nextCursor:null,total:1};calls.length=0;answerAttempts=[];createAttempts=[];maps=[];lastAiBody='';failAnswer=false;failCreate=false;failPersonal=false;catalogueError=null;push.mockClear();});afterEach(cleanup);
describe('F33 Questões',()=>{
  it('skip sends no answer while explicit do not know submits null and locks study',async()=>{current={...session(),items:[session().items[0]!,{...session().items[0]!,id:ID(22),position:1,question:{...q,id:ID(2),stem:'Outra amostra sintética'}}]};render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);fireEvent.click(screen.getByRole('button',{name:'Pular sem responder'}));await screen.findByText('Outra amostra sintética');expect(answerAttempts).toHaveLength(0);fireEvent.click(screen.getByRole('button',{name:'Questão anterior'}));await screen.findByText(q.stem);fireEvent.click(screen.getByRole('button',{name:'Não sei'}));await screen.findByText(reference.explanation);expect(JSON.parse(String(answerAttempts[0]?.body)).selectedKey).toBeNull();expect(screen.getByRole('button',{name:'Não sei'})).toBeDisabled();});
  it('simulation do not know remains editable and never reveals before finish',async()=>{current=session('simulation');render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);fireEvent.click(screen.getByRole('button',{name:'Não sei'}));await waitFor(()=>expect(answerAttempts).toHaveLength(1));expect(calls.some(path=>path.endsWith('/reference'))).toBe(false);fireEvent.click(screen.getByRole('radio',{name:/Comparar parte e total/}));fireEvent.click(screen.getByRole('button',{name:'Confirmar resposta'}));await waitFor(()=>expect(answerAttempts).toHaveLength(2));expect(JSON.parse(String(answerAttempts[1]?.body)).selectedKey).toBe('A');});
  it('incomplete optional comparison shows no replacement score and keeps original result',async()=>{current=session('simulation',true,'finished');render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText('1 de 1 questão correta');expect(calls.some(path=>path.endsWith('/recalculation'))).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Comparar com versões atuais'}));await screen.findByText('A comparação está incompleta. Não há uma nova nota para esta tentativa.');expect(screen.getByText('1 de 1 questão correta')).toBeInTheDocument();expect(screen.queryByText('0%')).toBeNull();await screen.findByText('A versão atual está indisponível por direitos de uso.');});
  it('institution options are independent from paper and allow searching beyond the capped list',async()=>{institutions.truncated=true;render(<QuestionsHub/>);await screen.findByText('Há mais instituições. Busque pelo nome para refinar as opções.');fireEvent.change(screen.getByLabelText('Instituição'),{target:{value:'sint'}});fireEvent.click(await screen.findByRole('option',{name:/Instituição sintética/}));await waitFor(()=>expect(calls.some(path=>path.includes('institution=Institui%C3%A7%C3%A3o+sint%C3%A9tica'))).toBe(true));fireEvent.change(screen.getByLabelText('Instituição'),{target:{value:'Outra instituição'}});await waitFor(()=>expect(calls.some(path=>path.includes('institution=Outra+institui%C3%A7%C3%A3o'))).toBe(true));expect(calls.some(path=>path.includes('examId=Outra'))).toBe(false);});
  it('suggests an area while typing and filters by the chosen id',async()=>{areasList=[{id:ID(7),name:'Clínica médica'}];render(<QuestionsHub/>);fireEvent.change(await screen.findByRole('combobox',{name:'Área'}),{target:{value:'clin'}});fireEvent.click(await screen.findByRole('option',{name:'Clínica médica'}));await waitFor(()=>expect(calls.some(path=>path.includes(`areaId=${ID(7)}`))).toBe(true));});
  it('catalogue rejects stray reference fields instead of leaking a key',async()=>{list={items:[{...q,correctKey:'SECRET_KEY'}],nextCursor:null,total:1};render(<QuestionsHub/>);await screen.findByRole('alert');expect(document.body.textContent).not.toContain('SECRET_KEY');expect(screen.queryByRole('article')).not.toBeInTheDocument();});
  it('filters private IA server-side and handles no results without production fixtures',async()=>{list={items:[],nextCursor:null,total:0};render(<QuestionsHub/>);await screen.findByText('A administração está trabalhando nisso');fireEvent.click(screen.getByRole('button',{name:'Minhas questões IA'}));await waitFor(()=>expect(calls.some(p=>p.includes('scope=mine')&&p.includes('origin=ai_generated'))).toBe(true));expect(screen.queryByText(q.stem)).not.toBeInTheDocument();});
  it('simulado never requests references before finishing',async()=>{current=session('simulation');render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);fireEvent.click(screen.getByRole('radio',{name:/Comparar parte e total/}));fireEvent.click(screen.getByRole('button',{name:'Confirmar resposta'}));await waitFor(()=>expect(answerAttempts).toHaveLength(1));expect(calls.some(p=>p.endsWith('/reference'))).toBe(false);expect(screen.queryByText(reference.explanation)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Concluir sessão'}));fireEvent.click(screen.getByRole('button',{name:'Concluir e ver resultado'}));await screen.findByText(reference.explanation);expect(screen.getByText('1 de 1 questão correta')).toBeInTheDocument();});
  it('study fetches reference only after server acknowledgement',async()=>{render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);expect(calls.some(p=>p.endsWith('/reference'))).toBe(false);fireEvent.click(screen.getByRole('radio',{name:/Comparar parte e total/}));fireEvent.click(screen.getByRole('button',{name:'Confirmar resposta'}));await screen.findByText(reference.explanation);expect(calls.filter(p=>p.endsWith('/reference'))).toHaveLength(1);});
  it('lost answer acknowledgement retries same mutation and revision',async()=>{failAnswer=true;render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);fireEvent.click(screen.getByRole('radio',{name:/Comparar parte e total/}));fireEvent.click(screen.getByRole('button',{name:'Confirmar resposta'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Confirmar resposta'}));await screen.findByText(reference.explanation);expect(answerAttempts).toHaveLength(2);expect(answerAttempts[1]!.body).toBe(answerAttempts[0]!.body);});
  it('reload resumes selected answer and gets allowed study feedback',async()=>{current=session('study',true);render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(reference.explanation);expect(screen.getByRole('radio',{name:/Comparar parte e total/})).toBeChecked();expect(screen.getByRole('button',{name:'Confirmar resposta'})).toBeDisabled();});
  it('persisted doubts update immediately and remain server-owned',async()=>{render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);fireEvent.click(screen.getByRole('button',{name:'Marcar dúvida'}));await screen.findByRole('button',{name:'Com dúvida',pressed:true});expect(calls).toContain(`/v1/questions/${ID(1)}/user-state`);});
  it('creation retries preserve Idempotency-Key until config changes',async()=>{failCreate=true;render(<ConfigDialog question={q} open onOpenChange={()=>undefined}/>);fireEvent.click(await screen.findByRole('button',{name:'Começar sessão'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Começar sessão'}));await waitFor(()=>expect(push).toHaveBeenCalled());expect(createAttempts).toHaveLength(2);expect(createAttempts[1]!.headers).toEqual(createAttempts[0]!.headers);});
  it('timer uses server deadline and clock offset, not a fresh local duration',async()=>{current={...session('simulation'),serverTime:new Date(Date.now()+3600000).toISOString(),deadline:new Date(Date.now()+3720000).toISOString()};render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);expect(await screen.findByLabelText('Tempo restante')).toHaveTextContent(/02:00|01:59/);});
  it('save and exit persists a selected response before navigating',async()=>{render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(q.stem);fireEvent.click(screen.getByRole('radio',{name:/Comparar parte e total/}));fireEvent.click(screen.getByRole('button',{name:'Salvar e sair'}));await waitFor(()=>expect(push).toHaveBeenCalledWith('/app/simulados'));expect(answerAttempts).toHaveLength(1);});
  it('failed personal-state read cannot overwrite notes with defaults',async()=>{failPersonal=true;render(<QuestionsHub/>);await screen.findByRole('article');fireEvent.click(screen.getByRole('button',{name:'Favoritos e anotações'}));await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Salvar marcações'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Tentar de novo'})).toBeInTheDocument();});
  it('quota error preserves access navigation and never injects sample rows',async()=>{catalogueError='quota_exceeded';render(<QuestionsHub/>);await screen.findByText('Seu limite foi atingido. As questões já salvas continuam disponíveis.');expect(screen.queryByRole('article')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Minhas questões IA'})).toBeInTheDocument();});
  it('after study correction the first answer is locked; retry creates a new session',async()=>{current=session('study',true);render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText(reference.explanation);expect(screen.getByRole('radio',{name:/Descartar informações/})).toBeDisabled();});
  it('expired session loads server result without answering again',async()=>{current=session('simulation',true,'expired');render(<SessionScreen sessionId={ID(20)}/>);await screen.findByText('1 de 1 questão correta');expect(calls.some(p=>p.endsWith('/reference'))).toBe(false);expect(screen.queryByRole('button',{name:'Confirmar resposta'})).not.toBeInTheDocument();});
});
it('maps the actual validation detail for insufficient selection to guidance',async()=>{const {questionError,QuestionsApiError}=await import('./api');expect(questionError(new QuestionsApiError('validation','insufficient_questions: available=3'))).toContain('quantidade');expect(questionError(new QuestionsApiError('validation','other_invalid_field'))).not.toBe(questionError(new QuestionsApiError('validation','insufficient_questions')));});
  it('sessions rollout off preserves catalogue while hiding creation and session requests',async()=>{render(<QuestionsHub sessionsEnabled={false}/>);await screen.findByText(q.stem);expect(screen.queryByRole('button',{name:'Criar treino'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Gerar com IA'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Resolver'})).toBeDisabled();expect(calls).not.toContain('/v1/question-sessions');});
  it('opens AI exam preferences from the bank and starts from the chosen map',async()=>{maps=[{id:ID(9),title:'Mapa de clínica'}];render(<QuestionsHub/>);fireEvent.click(await screen.findByRole('button',{name:'Gerar com IA'}));expect(await screen.findByRole('dialog',{name:/Gerar prova ou simulado com IA/})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Conteúdo'),{target:{value:'clín'}});fireEvent.click(await screen.findByRole('button',{name:'Mapa de clínica'}));fireEvent.click(screen.getByRole('button',{name:'Gerar e começar'}));await waitFor(()=>expect(push).toHaveBeenCalledWith(`/app/mapas/${ID(9)}/desafio-ia?session=${ID(30)}`));const body=JSON.parse(lastAiBody);expect(body).toMatchObject({boardId:ID(9),format:'generated',n:10,questionType:'mixed',grading:'end',timerSec:15*60,scope:{kind:'board'}});});
