'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { t } from './labels';
import { Alert, Button, Empty, FilterChip, Tag } from '@remoa/ui';
import type { QuestionListQuery, QuestionPublic, QuestionSessionSummaryPublic, ExamPaperPublic, BoardSummary } from '@remoa/contracts';
import { api } from '@/lib/api';
import { listExams, listQuestions, listQuestionInstitutions, listSessions, questionError, listQuestionTaxonomy } from './api';
import { actionLink, ConfigDialog, MapLink, PageTitle, panel, PersonalDialog, QuestionMeta, ReportDialog } from './shared';
import { QuestionFilterBar } from './questions-filters';
import { QuestionsSkeleton } from './questions-skeleton';
import { GenerateExamDialog } from './generate-exam-dialog';

type Tab = 'all' | 'catalog' | 'mine' | 'ai' | 'wrong' | 'favorite' | 'doubtful';
type Filters = Partial<QuestionListQuery>;
const tabKeys = { all: 'questions.all', catalog: 'questions.explore', mine: 'questions.mine', ai: 'questions.mineAi', wrong: 'questions.errors', favorite: 'questions.favorites', doubtful: 'questions.doubts' } as const;
const base = (tab: Tab): Filters => ({ scope: tab === 'catalog' ? 'catalog' : tab === 'mine' || tab === 'ai' ? 'mine' : 'all', ...(tab === 'ai' ? { origin: 'ai_generated' as const } : {}), ...(['wrong','favorite','doubtful'].includes(tab) ? { state: tab as 'wrong' | 'favorite' | 'doubtful' } : {}), limit: 25 });
export function QuestionsHub({ initialState,sessionsEnabled=true }: { initialState?: string;sessionsEnabled?:boolean } = {}) {
  const [tab, setTab] = useState<Tab>(initialState==='wrong'?'wrong':'all'); const [filters, setFilters] = useState<Filters>({});const[institution,setInstitution]=useState('');const[institutions,setInstitutions]=useState<Awaited<ReturnType<typeof listQuestionInstitutions>>>({items:[],truncated:false});const[institutionError,setInstitutionError]=useState(false);const[institutionReload,setInstitutionReload]=useState(0); const [search, setSearch] = useState(''); const [items, setItems] = useState<QuestionPublic[]>([]); const [total, setTotal] = useState(0); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState<string | null>(null);
  const [sessions, setSessions] = useState<QuestionSessionSummaryPublic[]>([]); const [recentError, setRecentError] = useState(false); const [exams, setExams] = useState<ExamPaperPublic[]>([]); const [areas, setAreas] = useState<{id:string;name:string}[]>([]); const [topics, setTopics] = useState<{id:string;name:string}[]>([]); const [boards, setBoards] = useState<BoardSummary[]>([]);
  const [config, setConfig] = useState<true | QuestionPublic | null>(null); const [generate, setGenerate] = useState(false); const [personal, setPersonal] = useState<QuestionPublic | null>(null); const [report, setReport] = useState<QuestionPublic | null>(null); const generation = useRef(0); const personalFocus=useRef<string|null>(null);
  useEffect(() => { const timer = setTimeout(() => setFilters(f => ({ ...f, search: search.trim() || undefined })), 300); return () => clearTimeout(timer); }, [search]);
  useEffect(()=>{const timer=setTimeout(()=>setFilters(old=>({...old,institution:institution.trim()||undefined})),300);return()=>clearTimeout(timer);},[institution]);
  useEffect(()=>{let active=true;void listQuestionInstitutions().then(result=>{if(active){setInstitutions(result);setInstitutionError(false);}}).catch(()=>{if(active)setInstitutionError(true);});return()=>{active=false;};},[institutionReload]);
  const load = useCallback(async () => { const seq = ++generation.current; setLoading(true); setError(null); setCursor(null); try { const data = await listQuestions({ ...base(tab), ...filters }); if (seq !== generation.current) return; setItems(data.items); setTotal(data.total); setCursor(data.nextCursor); } catch(e) { if (seq === generation.current) setError(questionError(e)); } finally { if (seq === generation.current) setLoading(false); } }, [tab, filters]);
  useEffect(() => { const guard = generation; void load(); return () => { guard.current++; }; }, [load]);
  useEffect(() => { let active = true; if(sessionsEnabled)void listSessions().then(v => { if (active) setSessions(v); }).catch(() => { if(active)setRecentError(true); }); void listExams().then(v => { if(active)setExams(v); }).catch(() => undefined);
    void listQuestionTaxonomy('area').then(v => { if(active)setAreas(v); }).catch(() => undefined);
    void listQuestionTaxonomy('topic').then(v => { if(active)setTopics(v); }).catch(() => undefined);
    void api<BoardSummary[]>('/v1/boards').then(v => { if(active&&v.ok)setBoards(v.data); }).catch(() => undefined); return () => { active=false; }; }, [sessionsEnabled]);
  const more = async () => { if(!cursor)return; const seq = generation.current; setLoadingMore(true); setError(null); try { const data=await listQuestions({...base(tab),...filters,cursor}); if(seq!==generation.current)return; setItems(old=>[...old,...data.items.filter(q=>!old.some(x=>x.id===q.id))]);setCursor(data.nextCursor);setTotal(data.total); } catch(e){if(seq===generation.current)setError(questionError(e));}finally{setLoadingMore(false);} };
  const filter = (key: keyof Filters, value: string) => setFilters(old => ({ ...old, [key]: value === 'all' || !value ? undefined : key === 'year' ? Number(value) : value }));
  const recent=sessions.find(s=>s.status==='active');
  useEffect(()=>{if(loading||personal||!personalFocus.current)return;const id=personalFocus.current;personalFocus.current=null;const target=document.querySelector<HTMLButtonElement>(`[data-question-personal="${id}"]`);if(target)target.focus();else document.querySelector<HTMLHeadingElement>('h1')?.focus();},[loading,personal,items]);
  return <div className="mx-auto flex w-full max-w-[1280px] flex-col gap-6 py-2 md:px-6"><PageTitle title={t('questions.title')} description={t('questions.subtitle')}>{sessionsEnabled?<><Button variant="secondary" onClick={()=>setGenerate(true)}>{t('questions.generateAi')}</Button><Button onClick={()=>setConfig(true)}>{t('questions.create')}</Button></>:null}</PageTitle>
    <nav aria-label={t('questions.nav')} className="flex flex-wrap items-center gap-2">{(Object.keys(tabKeys) as Tab[]).map(value=><FilterChip key={value} pressed={tab===value} onClick={()=>{setTab(value);setFilters({});setSearch('');setInstitution('');}}>{t(tabKeys[value])}</FilterChip>)}{sessionsEnabled?<Link className={actionLink} href="/app/simulados">{t('questions.sessions')}</Link>:null}</nav>
    {sessionsEnabled&&recent?<section className="flex flex-col gap-4 rounded-[30px] bg-panel-dark p-7 text-white md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-on-dark-muted">{t('questions.continueTitle')}</p><h2 className="mt-3 font-display text-[30px] font-extrabold">{t(recent.mode==='study'?'questions.sessionTitle':'questions.simulationTitle')}</h2><p className="mt-2 text-on-dark-muted">{t('questions.answered',{n:recent.answeredCount})}</p></div><Link className={actionLink} href={`/app/simulados/${recent.id}`}>{t('questions.continue')}</Link></section>:null}
    {sessionsEnabled&&recentError?<p className="text-sm text-muted">{t('questions.loadError')}</p>:null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_280px]"><section className="min-w-0"><QuestionFilterBar search={search} onSearch={setSearch} filters={filters} onFilter={filter} onClear={()=>{setFilters({});setSearch('');setInstitution('');}} tabAi={tab==='ai'} institution={institution} onInstitution={setInstitution} institutions={institutions} institutionError={institutionError} onInstitutionRetry={()=>setInstitutionReload(value=>value+1)} areas={areas} topics={topics} exams={exams} boards={boards} />
      {loading?<QuestionsSkeleton />:<>{!error?<p className="mb-4 text-sm text-muted">{total===1?t('questions.countOne'):t('questions.count',{n:total})}</p>:null}{items.length===0&&!error?<Empty title={t('questions.empty')} description={t('questions.emptyHelp')} />:null}<div className="flex flex-col gap-4">{items.map(q=><article key={q.id} aria-label={q.stem} className={panel}><QuestionMeta question={q}/><h2 className="mt-4 whitespace-pre-wrap break-words font-display text-xl font-bold leading-relaxed">{q.stem}</h2>{q.topicId&&topics.some(v=>v.id===q.topicId)?<p className="mt-2 text-sm text-primary-deep">{t('questions.topicName',{name:topics.find(v=>v.id===q.topicId)!.name})}</p>:null}{q.sourceLabel?<p className="mt-2 text-sm text-muted">{q.sourceLabel}</p>:null}<div className="mt-5 flex flex-wrap gap-2">{q.type==='discursive'?<MapLink question={q}/>:<Button disabled={!sessionsEnabled||q.availability!=='active'} onClick={()=>setConfig(q)}>{t('questions.resolve')}</Button>}<Button data-question-personal={q.id} variant="secondary" onClick={()=>setPersonal(q)}>{t('questions.preferences')}</Button><Button variant="quiet" onClick={()=>setReport(q)}>{t('questions.report')}</Button></div></article>)}</div>{cursor?<div className="mt-5"><Button variant="secondary" loading={loadingMore} onClick={()=>void more()}>{t('questions.more')}</Button></div>:null}</>}
      {error?<div className="mt-4"><Alert role="alert" tone="review" title={error}><Button variant="secondary" onClick={()=>void load()}>{t('common.retry')}</Button></Alert></div>:null}
    </section><aside className={`${panel} h-fit`}><Tag tone="review">{t('questions.mineAi')}</Tag><h2 className="mt-4 font-display text-2xl font-extrabold">{t('questions.provenance')}</h2><p className="mt-3 text-muted">{t('questions.privateInfo')}</p><p className="mt-4 text-sm text-muted">{t('questions.fsrsInfo')}</p><Link className={`${actionLink} mt-5`} href="/app/provas">{t('questions.viewProofs')}</Link></aside></div>
    {config?<ConfigDialog key={config===true?'filters':config.id} filters={{...base(tab),...filters}} question={config===true?undefined:config} open onOpenChange={v=>{if(!v)setConfig(null);}}/>:null}{generate?<GenerateExamDialog open onOpenChange={setGenerate} />:null}{personal?<PersonalDialog question={personal} open onOpenChange={v=>{if(!v){personalFocus.current=personal.id;setPersonal(null);void load();}}}/>:null}{report?<ReportDialog question={report} open onOpenChange={v=>{if(!v)setReport(null);}}/>:null}
  </div>;
}
