import {beforeEach,expect,it,vi} from 'vitest';
import {mockQuestionSessionsPage} from '@remoa/contracts/mocks';
vi.mock('@/lib/api',()=>({api:vi.fn()}));
import {api} from '@/lib/api';
import {listSessionHistory} from './session-history-api';
beforeEach(()=>vi.resetAllMocks());
it('validates exact metadata and retains authoritative expired status in an active-filter response',async()=>{const result={...mockQuestionSessionsPage,items:mockQuestionSessionsPage.items.map(item=>({...item,status:'expired',deadline:new Date('2020-01-01'),finishedAt:new Date()}))};vi.mocked(api).mockResolvedValue({ok:true,data:result});await expect(listSessionHistory({status:'active',mode:'simulation',cursor:'opaque cursor'})).resolves.toEqual(result);expect(vi.mocked(api).mock.calls[0]![0]).toBe('/v1/question-sessions/history?limit=20&cursor=opaque+cursor&status=active&mode=simulation');});
it('rejects additional score/items/answer material and invalid limit instead of manufacturing a list',async()=>{await expect(listSessionHistory({limit:21})).rejects.toThrow();expect(api).not.toHaveBeenCalled();vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionSessionsPage,score:.5}});await expect(listSessionHistory({})).rejects.toMatchObject({code:'invalid_response'});vi.mocked(api).mockResolvedValue({ok:true,data:{...mockQuestionSessionsPage,items:mockQuestionSessionsPage.items.map(item=>({...item,correctKey:'A'}))}});await expect(listSessionHistory({})).rejects.toMatchObject({code:'invalid_response'});});
it('preserves ownership/permission failure and abort rather than falling back to recent summaries',async()=>{const abort=new AbortController();vi.mocked(api).mockResolvedValue({ok:false,error:{code:'unauthorized',message:'session_expired'}});await expect(listSessionHistory({},abort.signal)).rejects.toMatchObject({code:'unauthorized'});expect(api).toHaveBeenCalledOnce();expect(api).toHaveBeenCalledWith('/v1/question-sessions/history?limit=20',{signal:abort.signal});});
