'use client';
import Link from 'next/link';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import type {QuestionSessionsPageQuery,QuestionSessionsPageResult} from '@remoa/contracts';
import {Alert,Button,Empty,Select,Tag} from '@remoa/ui';
import {t} from './labels';
import {questionError} from './api';
import {listSessionHistory} from './session-history-api';
import {actionLink,panel,PageTitle} from './shared';
import {GenerateExamDialog} from './generate-exam-dialog';
import {QuestionsSkeleton} from './questions-skeleton';
type Summary=QuestionSessionsPageResult['items'][number];
export function SessionHistoryScreen({enabled=true}:{enabled?:boolean}){
 const[status,setStatus]=useState('all');const[mode,setMode]=useState('all');const[items,setItems]=useState<Summary[]>([]);const[cursor,setCursor]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[more,setMore]=useState(false);const[error,setError]=useState<string|null>(null);const[retry,setRetry]=useState(0);const[generate,setGenerate]=useState(false);
 const generation=useRef(0),abortRef=useRef<AbortController|null>(null),busy=useRef(false),region=useRef<HTMLDivElement|null>(null),moreButton=useRef<HTMLButtonElement|null>(null),pendingFocus=useRef<string|null>(null);
 const query:Partial<QuestionSessionsPageQuery>={limit:20,...(status!=='all'?{status:status as QuestionSessionsPageQuery['status']}:{}),...(mode!=='all'?{mode:mode as QuestionSessionsPageQuery['mode']}:{})};const queryRef=useRef(query);queryRef.current=query;const signature=JSON.stringify({enabled,...query});
 useEffect(()=>{abortRef.current?.abort();const current=++generation.current;busy.current=false;pendingFocus.current=null;setItems([]);setCursor(null);setError(null);setMore(false);if(!enabled){setLoading(false);return;}
  const abort=new AbortController();abortRef.current=abort;busy.current=true;setLoading(true);void listSessionHistory(queryRef.current,abort.signal).then(value=>{if(current===generation.current&&!abort.signal.aborted){setItems(value.items);setCursor(value.nextCursor);}}).catch(reason=>{if(current===generation.current&&!abort.signal.aborted)setError(questionError(reason));}).finally(()=>{if(current===generation.current&&!abort.signal.aborted){busy.current=false;setLoading(false);}});
  return()=>{abortRef.current?.abort();generation.current=current+1;};
 },[signature,retry,enabled]);
 useLayoutEffect(()=>{const target=pendingFocus.current;if(!target||more)return;pendingFocus.current=null;if(document.activeElement!==document.body&&document.activeElement!==moreButton.current)return;if(target==='retry'){region.current?.querySelector<HTMLButtonElement>('[data-session-retry]')?.focus();return;}region.current?.querySelector<HTMLAnchorElement>(`[data-session-id="${target}"] a`)?.focus();},[items,more,error]);
 const loadMore=async()=>{if(!enabled||!cursor||busy.current)return;const current=generation.current,abort=new AbortController();abortRef.current=abort;busy.current=true;const keyboard=document.activeElement===moreButton.current||Boolean(document.activeElement?.matches('[data-session-retry]'));setMore(true);setError(null);
  try{const value=await listSessionHistory({...queryRef.current,cursor},abort.signal);if(current!==generation.current||abort.signal.aborted)return;if(keyboard)pendingFocus.current=value.items.find(item=>!items.some(existing=>existing.id===item.id))?.id??value.items[0]?.id??null;setItems(previous=>[...new Map([...previous,...value.items].map(item=>[item.id,item])).values()]);setCursor(value.nextCursor);}
  catch(reason){if(current===generation.current&&!abort.signal.aborted){if(keyboard)pendingFocus.current='retry';setError(questionError(reason));}}
  finally{if(current===generation.current&&!abort.signal.aborted){busy.current=false;setMore(false);}}
 };
 return <div ref={region} className="mx-auto flex w-full min-w-0 max-w-[1100px] flex-col gap-6 py-2 md:px-6"><PageTitle title={t('questions.sessions')} description={t('questions.continueSubtitle')}>{enabled?<><Button variant="secondary" onClick={()=>setGenerate(true)}>{t('questions.generateAi')}</Button><Link className={actionLink} href="/app/banco-de-questoes">{t('questions.create')}</Link></>:null}</PageTitle>{!enabled?<p>{t('questions.historyDisabled')}</p>:<><div className="grid min-w-0 gap-4 md:grid-cols-2"><Select label={t('questions.historyStatus')} value={status} onValueChange={setStatus} options={[{value:'all',label:t('questions.historyAllStatuses')},...(['active','finished','expired'] as const).map(value=>({value,label:t(`questions.${value}`)}))]}/><Select label={t('questions.historyMode')} value={mode} onValueChange={setMode} options={[{value:'all',label:t('questions.historyAllModes')},{value:'study',label:t('questions.study')},{value:'simulation',label:t('questions.simulation')}]}/></div><p className="text-sm text-muted">{t('questions.historyStateHelp')}</p>{loading?<QuestionsSkeleton cards={2} />:!items.length&&!error?<Empty title={t('questions.noSessions')} description={t('questions.sessionsEmptyHelp')} />:items.map(session=><article key={session.id} data-session-id={session.id} className={`${panel} flex min-w-0 flex-wrap items-center justify-between gap-4`}><div className="min-w-0"><Tag tone={session.status==='active'?'brand':'unknown'}>{t(`questions.${session.status}`)}</Tag><h2 className="mt-3 font-display text-xl font-bold">{t(session.mode==='study'?'questions.study':'questions.simulation')}</h2><p className="mt-2 text-sm text-muted">{t(session.answeredCount===1?'questions.answeredOne':'questions.answered',{n:session.answeredCount})} · {t('questions.examCount',{n:session.count})}</p><p className="mt-2 text-sm text-muted">{t('questions.historyStarted',{date:session.startedAt.toLocaleString('pt-BR')})}</p></div><Link className={actionLink} href={`/app/simulados/${session.id}`}>{t(session.status==='active'?'questions.continue':'questions.openResult')}</Link></article>)}{error?<Alert role="alert" tone="review" title={error}><Button data-session-retry="" variant="secondary" onClick={()=>{if(items.length&&cursor)void loadMore();else setRetry(value=>value+1);}}>{t('common.retry')}</Button></Alert>:null}{cursor?<Button ref={moreButton} variant="secondary" loading={more} disabled={loading} onClick={()=>void loadMore()}>{t('questions.historyMore')}</Button>:null}</>}{generate?<GenerateExamDialog open onOpenChange={setGenerate} />:null}</div>;
}
