'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { t } from './labels';
import { Alert, Button, Dialog, Tag } from '@remoa/ui';
import type { QuestionAnswerInput, QuestionReferenceAfterAnswer, QuestionSessionPublic, QuestionSessionReport } from '@remoa/contracts';
import { finishSession, getReference, getReport, getSession, questionError, saveAnswer, saveUserState } from './api';
import {SessionResult} from './session-result';
import { actionLink, MapLink, PageTitle, panel, PersonalDialog, QuestionMeta, ReportDialog } from './shared';

type PendingAnswer = { itemId: string; input: QuestionAnswerInput };
const clockText=(n:number)=>`${String(Math.floor(Math.max(0,n)/60)).padStart(2,'0')}:${String(Math.max(0,n)%60).padStart(2,'0')}`;
export function SessionScreen({ sessionId }: { sessionId: string }) {
  const [session,setSession]=useState<QuestionSessionPublic|null>(null); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [reference,setReference]=useState<QuestionReferenceAfterAnswer|null>(null); const [referenceError,setReferenceError]=useState(false); const [report,setReport]=useState<QuestionSessionReport|null>(null); const [eliminated,setEliminated]=useState<Set<string>>(new Set()); const [personalOpen,setPersonalOpen]=useState(false); const [reportOpen,setReportOpen]=useState(false); const [finishOpen,setFinishOpen]=useState(false); const [remaining,setRemaining]=useState<number|null>(null); const [saved,setSaved]=useState(false);
  const pending=useRef<PendingAnswer|null>(null); const finishKey=useRef(crypto.randomUUID()); const loadedAt=useRef(Date.now()); const serverOffset=useRef(0); const expireChecked=useRef(false); const qTitle=useRef<HTMLHeadingElement>(null); const loadSeq=useRef(0); const router=useRouter();
  const load=useCallback(async()=>{const seq=++loadSeq.current;setLoading(true);setError(null);setReport(null);try{const data=await getSession(sessionId);if(seq!==loadSeq.current)return;serverOffset.current=new Date(data.serverTime).getTime()-Date.now();setSession(data);const at=data.items.findIndex(i=>!i.answered);setIndex(at<0?0:at);if(data.status!=='active'){const result=await getReport(sessionId);if(seq===loadSeq.current)setReport(result);}}catch(e){if(seq===loadSeq.current)setError(questionError(e));}finally{if(seq===loadSeq.current)setLoading(false);}},[sessionId]);
  useEffect(()=>{const guard=loadSeq;void load();return()=>{guard.current++;};},[load]);
  const item=session?.items[index]; const sid=session?.id, smode=session?.mode, sstatus=session?.status, iid=item?.id, answered=item?.answered, revision=item?.revision;
  useEffect(()=>{setSelected(item?.selectedKey??null);setReference(null);setReferenceError(false);setEliminated(new Set());loadedAt.current=Date.now();},[item?.id,item?.selectedKey]);
  useEffect(()=>{if(!sid||!iid||smode!=='study'||!answered||sstatus!=='active')return;let active=true;void getReference(sid,iid).then(v=>{if(active)setReference(v);}).catch(()=>{if(active)setReferenceError(true);});return()=>{active=false;};},[sid,smode,sstatus,iid,answered,revision]);
  useEffect(()=>{if(!session?.deadline||session.status!=='active'){setRemaining(null);return;}const tick=()=>setRemaining(Math.max(0,Math.ceil((new Date(session.deadline!).getTime()-Date.now()-serverOffset.current)/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[session?.deadline,session?.status]);
  useEffect(()=>{if(remaining!==0||!session||session.status!=='active'||expireChecked.current)return;expireChecked.current=true;void getSession(session.id).then(async v=>{setSession(v);if(v.status!=='active')setReport(await getReport(v.id));else expireChecked.current=false;}).catch(e=>{setError(questionError(e));expireChecked.current=false;});},[remaining,session]);
  const submit=async(answer:QuestionAnswerInput['selectedKey']=selected as QuestionAnswerInput['selectedKey'])=>{if(!session||!item||busy)return false;const old=pending.current;if(!old||old.itemId!==item.id||old.input.selectedKey!==answer)pending.current={itemId:item.id,input:{selectedKey:answer,mutationId:crypto.randomUUID(),revision:item.revision,elapsedMs:Math.min(86400000,Date.now()-loadedAt.current)}};setBusy(true);setError(null);try{const ack=await saveAnswer(session.id,item.id,pending.current!.input);pending.current=null;setSelected(ack.selectedKey);setSession(oldSession=>oldSession?{...oldSession,items:oldSession.items.map(i=>i.id===ack.itemId?{...i,selectedKey:ack.selectedKey,answered:true,revision:ack.revision}:i)}:null);setSaved(true);return true;}catch(e){setError(questionError(e));return false;}finally{setBusy(false);}};
  const doubt=async()=>{if(!item||busy)return;setBusy(true);setError(null);try{const savedState=await saveUserState(item.question.id,{doubtful:!item.doubtful});setSession(old=>old?{...old,items:old.items.map(i=>i.question.id===item.question.id?{...i,doubtful:savedState.doubtful}:i)}:null);}catch(e){setError(questionError(e));}finally{setBusy(false);}};
  const finish=async()=>{if(!session||busy)return;setBusy(true);setError(null);try{const result=await finishSession(session.id,finishKey.current);setReport(result);setSession(old=>old?{...old,status:'finished'}:null);setFinishOpen(false);}catch(e){setError(questionError(e));}finally{setBusy(false);}};
  const exit=async()=>{if(busy)return;if(selected!==null&&selected!==item?.selectedKey){if(!await submit())return;}router.push('/app/simulados');};
  const jump=(n:number)=>{if(busy)return;setIndex(n);requestAnimationFrame(()=>qTitle.current?.focus());};
  if(loading)return <div className={panel} role="status">{t('common.loading')}</div>;
  if(!session)return <Alert role="alert" tone="review" title={error??t('questions.loadError')}><Button variant="secondary" onClick={()=>void load()}>{t('common.retry')}</Button></Alert>;
  if(report)return <SessionResult session={session} report={report}/>;
  if(session.status!=='active')return <Alert role="alert" tone="review" title={error??t('questions.resultError')}><Button variant="secondary" onClick={()=>void load()}>{t('common.retry')}</Button></Alert>;
  if(!item)return <Alert role="alert" tone="review" title={t('questions.empty')}><Link href="/app/banco-de-questoes" className={actionLink}>{t('questions.backBank')}</Link></Alert>;
  const canReveal=session.mode==='study'&&item.answered;const refsAllowed=session.status!=='active'||canReveal;
  return <div className="mx-auto flex w-full max-w-[1280px] flex-col gap-6 py-2 md:px-6"><PageTitle title={t(session.mode==='simulation'?'questions.simulationTitle':'questions.sessionTitle')} description={t('questions.position',{n:index+1,total:session.items.length})}><div className="flex flex-wrap items-center gap-3"><Tag>{remaining===null?t('questions.noDeadline'):<span aria-label={t('questions.timer')}>{clockText(remaining)}</span>}</Tag><Button variant="secondary" disabled={busy} onClick={()=>void exit()}>{t('questions.saveExit')}</Button></div></PageTitle>
    {error?<Alert role="alert" tone="review" title={error}><Button variant="secondary" disabled={busy} onClick={()=>void load()}>{t('questions.reload')}</Button></Alert>:null}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><section className={`${panel} min-w-0`}><div className="flex flex-wrap items-center justify-between gap-3"><QuestionMeta question={item.question}/><Button variant="quiet" aria-pressed={item.doubtful} disabled={busy} onClick={()=>void doubt()}>{t(item.doubtful?'questions.doubtMarked':'questions.markDoubt')}</Button></div><h2 ref={qTitle} tabIndex={-1} className="my-6 whitespace-pre-wrap break-words font-display text-[23px] font-bold leading-relaxed outline-none md:text-[26px]">{item.question.stem}</h2>
      {item.originalNumber?<p className="mb-4 text-sm text-muted">{t('questions.originalNumber',{n:item.originalNumber})}</p>:null}
      {item.question.assets.map(asset=><figure key={asset.id} className="my-4"><img src={asset.url} alt={asset.alt} className="h-auto max-w-full rounded-map border border-border"/><figcaption className="mt-1 text-xs text-muted">{asset.alt}</figcaption></figure>)}
      {item.question.type==='discursive'?<div className="flex flex-col gap-4"><p className="text-muted">{t('questions.discursiveInfo')}</p><MapLink question={item.question}/></div>:<fieldset className="min-w-0 flex flex-col gap-3"><legend className="sr-only">{t('questions.resolve')}</legend>{item.question.alternatives?.map(a=>{const correct=refsAllowed&&reference?.correctKey===a.key;return <div key={a.key} className={`flex items-center gap-2 rounded-field border p-3 ${correct?'border-steady bg-steady-bg':selected===a.key?'border-primary bg-primary-tint':'border-border bg-surface'}`}><label className={`flex min-w-0 min-h-11 flex-1 cursor-pointer items-center gap-3 ${eliminated.has(a.key)?'line-through opacity-50':''}`}><input type="radio" name={`answer-${item.id}`} value={a.key} checked={selected===a.key} disabled={busy||session.status!=='active'||(session.mode==='study'&&item.answered)} onChange={()=>{setSelected(a.key);setSaved(false);}}/><span className="rounded-[10px] bg-primary-tint px-3 py-2 font-bold text-primary-deep">{a.key}</span><span className="min-w-0 whitespace-pre-wrap break-words">{a.text}</span></label><button type="button" aria-label={t(eliminated.has(a.key)?'questions.restore':'questions.eliminate',{key:a.key})} aria-pressed={eliminated.has(a.key)} className="min-h-11 min-w-11 rounded-btn text-muted hover:bg-primary-tint focus-visible:outline-2 focus-visible:outline-primary" onClick={()=>setEliminated(old=>{const next=new Set(old);if(next.has(a.key))next.delete(a.key);else next.add(a.key);return next;})}>×</button></div>;})}</fieldset>}
      {reference&&refsAllowed?<section className="mt-6"><Alert tone={reference.annulled?'watch':item.selectedKey===reference.correctKey?'steady':'review'} title={t(reference.annulled?'questions.annulled':item.selectedKey===reference.correctKey?'questions.correct':'questions.incorrect')}><p>{t('questions.correctKey',{key:reference.correctKey??'—'})}</p><p className="whitespace-pre-wrap break-words">{reference.explanation??t('questions.noExplanation')}</p>{reference.distractorNotes?Object.entries(reference.distractorNotes).map(([key,note])=><p key={key}><b>{key}</b> {note}</p>):null}<p>{t(reference.reviewed?'questions.reviewed':'questions.unreviewed')}</p>{reference.obsolete?<p>{t('questions.obsolete')}</p>:null}{reference.sourceUrl?<a href={reference.sourceUrl} target="_blank" rel="noopener noreferrer">{t('questions.provenance')}</a>:null}</Alert><div className="mt-4"><MapLink question={item.question}/></div></section>:null}
      {referenceError&&canReveal?<Alert tone="review" title={t('questions.referenceError')}><Button variant="secondary" onClick={()=>void load()}>{t('common.retry')}</Button></Alert>:null}
      <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><Button variant="secondary" disabled={busy} onClick={()=>setPersonalOpen(true)}>{t('questions.preferences')}</Button>{item.question.type==='objective'?<Button loading={busy} loadingLabel={t('questions.saving')} disabled={selected===null||session.status!=='active'||(item.answered&&(session.mode==='study'||item.selectedKey===selected))} onClick={()=>void submit()}>{t('questions.confirm')}</Button>:null}</div>{saved?<p className="mt-3 text-sm text-primary-deep" role="status">{t('questions.saved')}</p>:null}<div className="mt-4 flex flex-wrap gap-3">{item.question.type==='objective'?<Button variant="secondary" disabled={busy||(item.answered&&(session.mode==='study'||(item.selectedKey===null&&selected===null)))} onClick={()=>void submit(null)}>{t('questions.doNotKnow')}</Button>:null}<Button variant="quiet" disabled={busy} onClick={()=>{if(index===session.items.length-1)setFinishOpen(true);else jump(index+1);}}>{t('questions.skipped')}</Button></div><div className="mt-6 flex justify-between gap-3"><Button variant="quiet" disabled={index===0||busy} onClick={()=>jump(index-1)}>{t('questions.previous')}</Button><Button variant="quiet" disabled={index===session.items.length-1||busy} onClick={()=>jump(index+1)}>{t('questions.next')}</Button></div></section>
      <aside className="flex flex-col gap-5"><section className={`${panel} min-w-0`}><h2 className="font-display text-xl font-bold">{t('questions.questionNavigator')}</h2><div className="my-4 grid grid-cols-5 gap-2">{session.items.map((i,n)=><button key={i.id} disabled={busy} aria-label={t('questions.questionNumber',{n:n+1})} aria-current={n===index?'step':undefined} className={`min-h-11 rounded-btn border text-sm font-bold focus-visible:outline-2 focus-visible:outline-primary ${n===index?'border-primary bg-primary text-white':i.answered?'border-border bg-primary-tint text-primary-deep':'border-border bg-surface'}`} onClick={()=>jump(n)}>{n+1}{i.doubtful?<span aria-hidden="true">?</span>:null}</button>)}</div><p className="mb-4 text-sm text-muted">{session.items.filter(i=>i.answered).length===1?t('questions.answeredOne'):t('questions.answered',{n:session.items.filter(i=>i.answered).length})}</p><Button variant="secondary" disabled={busy} onClick={()=>setFinishOpen(true)}>{t('questions.finish')}</Button></section><section className={`${panel} min-w-0`}><h2 className="font-display text-xl font-bold">{t('questions.provenance')}</h2>{item.question.sourceLabel?<p className="my-3 text-muted">{item.question.sourceLabel}</p>:null}<p className="my-3 text-sm text-muted">{t('questions.fsrsInfo')}</p><Button variant="quiet" onClick={()=>setReportOpen(true)}>{t('questions.report')}</Button></section></aside></div>
    <Dialog open={finishOpen} onOpenChange={setFinishOpen} title={t('questions.finishTitle')} description={t('questions.finishDescription')} closeLabel={t('common.close')}><Button loading={busy} onClick={()=>void finish()}>{t('questions.finishConfirm')}</Button></Dialog>{personalOpen?<PersonalDialog question={item.question} open onOpenChange={setPersonalOpen} onSaved={v=>setSession(old=>old?{...old,items:old.items.map(i=>i.question.id===item.question.id?{...i,doubtful:v.doubtful,question:{...i.question,userState:v}}:i)}:null)}/>:null}{reportOpen?<ReportDialog question={item.question} open onOpenChange={setReportOpen}/>:null}
  </div>;
}
