// F13 — Minha conta. Texto da tela "6. Minha conta" (docs/design/v2/source/Conta.dc.html).
// Reaproveitar, sem duplicar: common.save/cancel/close/retry, billing.plan.free/pro,
// billing.pricing.{monthly,annual,perMonth,perYear,annualHint}, billing.account.subscribe,
// billing.account.{grace,renewsAt,cancelsAt,usageLine,usageUnlimited}.
export const account = {
  title: 'Minha conta',
  loading: 'Carregando sua conta…',
  skeletonLabel: 'Carregando a seção',
  offline: 'Sem conexão. Reconecte para alterar sua conta.',
  retry: 'Tentar de novo',
  genericError: 'Não conseguimos concluir agora. Tente de novo.',
  dismissToast: 'Fechar aviso',
  liveRegionLabel: 'Avisos da conta',
  pages: {
    perfil: 'Remoa — Minha conta · Perfil',
    seguranca: 'Remoa — Minha conta · Segurança',
    plano: 'Remoa — Minha conta · Plano e uso',
    preferencias: 'Remoa — Minha conta · Preferências',
    dados: 'Remoa — Minha conta · Dados e privacidade',
  },
  hero: {
    label: 'Resumo do perfil',
    noName: 'Sem nome',
    plan: 'Plano {plan}',
    joined: 'Entrou em {month}',
    streak: '{n, plural, one {# dia seguido} other {# dias seguidos}}',
    avatarEdit: 'Alterar foto de perfil',
    completeness: 'Perfil {pct}% completo',
    completenessLabel: 'Completude do perfil: {pct}%',
    complete: 'Perfil completo',
    items: {
      photo: 'Foto',
      name: 'Nome',
      email: 'E-mail confirmado',
      goal: 'Objetivo de prova',
      reminder: 'Lembrete diário',
    },
    todo: {
      photo: 'Adicionar foto',
      name: 'Adicionar nome',
      email: 'Confirmar e-mail',
      goal: 'Definir objetivo',
      reminder: 'Ligar lembrete',
    },
  },
  nav: {
    label: 'Seções da conta',
    perfil: 'Perfil',
    seguranca: 'Segurança',
    plano: 'Plano e uso',
    preferencias: 'Preferências',
    dados: 'Dados e privacidade',
    signOut: 'Sair da conta',
    signedOut: 'Você saiu da conta.',
  },
  deletionBanner: {
    text: 'Sua conta será excluída em {date}. Até lá, você pode cancelar.',
    cancel: 'Cancelar exclusão',
    canceled: 'Exclusão cancelada. Sua conta continua ativa.',
  },
  profile: {
    personalTitle: 'Informações pessoais',
    personalBody: 'Como você aparece no Remoa e como falamos com você.',
    photo: 'Foto',
    photoHelp: 'JPG, PNG ou WebP. Você escolhe o recorte.',
    photoChange: 'Alterar',
    name: 'Nome',
    nameEdit: 'Editar',
    nameHelp: 'Entre 2 e 60 caracteres. É o nome que aparece no seu perfil.',
    nameSave: 'Salvar nome',
    nameInvalid: 'Use de 2 a 60 caracteres, só letras, espaço, hífen ou apóstrofo.',
    nameSaved: 'Nome atualizado.',
    email: 'E-mail',
    emailConfirmed: 'Confirmado',
    emailChange: 'Trocar',
    emailNew: 'Novo e-mail',
    emailHelp: 'Vamos enviar um link de confirmação para o novo endereço. Até você confirmar, continua valendo o e-mail atual.',
    emailSend: 'Enviar confirmação',
    emailInvalid: 'Digite um e-mail válido, diferente do atual.',
    emailSent: 'Enviamos um link de confirmação para {email}.',
    emailPending: 'Aguardando confirmação de {email}',
    emailResend: 'Reenviar',
    emailResent: 'Link reenviado para {email}.',
    emailResendWait: 'Você pode reenviar em {s} s.',
    emailCancel: 'Cancelar troca',
    emailCanceled: 'Troca de e-mail cancelada.',
    emailError: 'Não conseguimos trocar o e-mail. Confira o endereço e tente de novo.',
    emailBlockedByDeletion: 'Com a exclusão agendada, não dá para trocar o e-mail.',
    studyTitle: 'Seu estudo',
    studyBody: 'Usamos isso para sugerir mapas prontos e organizar a cobertura da matriz.',
    goal: 'Objetivo de prova',
    goalOptions: {
      enamed20271: 'Enamed 2027.1',
      enamed20272: 'Enamed 2027.2',
      unknown: 'Ainda não sei',
    },
    stage: 'Momento',
    stageLabel: 'Momento da graduação',
    stageOptions: {
      y34: '3º–4º ano',
      y56: '5º–6º ano',
      graduate: 'Formado(a)',
    },
    timezone: 'Fuso horário',
    timezoneValue: 'Brasília (GMT−3)',
    dayStartsAt: 'o dia de estudo vira às {hour}',
    studySaved: 'Salvo.',
  },
  photoDialog: {
    title: 'Foto de perfil',
    closeLabel: 'Fechar sem salvar',
    zoom: 'Zoom',
    zoomValue: '{n}%',
    drop: 'Arraste uma foto aqui',
    choose: 'Escolher foto',
    help: 'JPG, PNG ou WebP até 5 MB. Removemos os dados de localização da imagem.',
    initials: 'Ou use suas iniciais',
    colorLabel: 'Cor do avatar',
    colors: {
      brand: 'Roxo Remoa',
      deep: 'Roxo profundo',
      navy: 'Azul marinho',
      graphite: 'Grafite',
      violet: 'Violeta',
    },
    remove: 'Remover foto',
    cancel: 'Cancelar',
    save: 'Salvar foto',
    errorType: 'Esse arquivo não é uma imagem JPG, PNG ou WebP.',
    errorSize: 'A imagem passa de 5 MB. Escolha uma menor.',
    errorUpload: 'Não conseguimos enviar a foto. Tente de novo.',
    savedPhoto: 'Foto atualizada.',
    savedAvatar: 'Avatar atualizado.',
    removed: 'Foto removida.',
  },
  security: {
    passwordTitle: 'Senha',
    passwordChanged: 'Última alteração {when}',
    passwordChange: 'Alterar senha',
    passwordCancel: 'Cancelar',
    current: 'Senha atual',
    next: 'Nova senha',
    confirm: 'Confirmar nova senha',
    show: 'Mostrar ou ocultar a senha',
    meterLabel: 'Força da senha',
    strength: {
      empty: 'Digite uma senha',
      weak: 'Fraca',
      fair: 'Razoável',
      good: 'Boa',
      strong: 'Forte',
    },
    rules: {
      length: '8 ou mais caracteres',
      mix: 'Letras e números',
      long: '12 ou mais caracteres deixa a senha mais forte',
    },
    rulesLabel: 'Requisitos da senha',
    match: 'As senhas coincidem.',
    noMatch: 'As senhas ainda não coincidem.',
    save: 'Salvar nova senha',
    saveNote: 'Ao salvar, encerramos os outros dispositivos.',
    saved: 'Senha alterada. Encerramos os outros dispositivos.',
    wrongCurrent: 'A senha atual não confere.',
    rateLimited: 'Muitas tentativas. Tente de novo em {min, plural, one {# minuto} other {# minutos}}.',
    reauth: 'Por segurança, confirme sua identidade para continuar.',
    loginTitle: 'Como você entra',
    loginBody: 'Mantenha pelo menos um jeito de entrar ativo.',
    emailPassword: 'E-mail e senha',
    active: 'Ativo',
    google: 'Google',
    googleLetter: 'G',
    googleConnected: 'Conectado como {email}',
    googleOff: 'Não conectado',
    googleConnect: 'Conectar',
    googleDisconnect: 'Desconectar',
    googleConnectedOk: 'Google conectado.',
    googleDisconnectedOk: 'Google desconectado.',
    lastMethod: 'Não dá para desconectar o último jeito de entrar. Conecte outro antes ou defina uma senha.',
    devicesTitle: 'Dispositivos conectados',
    devicesBody: 'Encerre o que você não reconhece.',
    thisDevice: 'Este dispositivo',
    thisDeviceNow: 'Este dispositivo · agora',
    lastSeen: 'Visto {when}',
    deviceName: '{browser} no {os}',
    end: 'Encerrar',
    endLabel: 'Encerrar sessão em {name}',
    endOthers: 'Encerrar os outros',
    ended: 'Sessão encerrada em {name}.',
    endedOthers: 'Os outros dispositivos foram encerrados.',
    endAllFallback: 'Sair de todos os dispositivos',
    showText: 'Mostrar',
    hideText: 'Ocultar',
    rateLimitedGeneric: 'Muitas tentativas. Tente de novo mais tarde.',
    passwordError: 'Não conseguimos alterar a senha. Tente de novo.',
    devicesError: 'Não conseguimos carregar os dispositivos.',
    endError: 'Não conseguimos encerrar a sessão. Tente de novo.',
    googleError: 'Não conseguimos atualizar o Google. Tente de novo.',
    devicesLabel: 'Lista de dispositivos',
    justNow: 'agora',
    unknownDevice: 'Dispositivo desconhecido',
    ruleDone: 'cumprido',
    rulePending: 'pendente',
  },
  plan: {
    title: 'Seu plano',
    manage: 'Gerenciar assinatura',
    freeText: 'Tudo para começar: {boards} mapas, {cards} cards e {ai} correções por IA por dia.',
    proText: 'Mapas e cards ilimitados, correções por IA ilimitadas e {pdf} mapas gerados de PDF por mês. Renova em {date}.',
    pastDue: 'Não conseguimos cobrar a sua assinatura. Atualize o pagamento para não perder o acesso.',
    offerTitle: 'Pro',
    billingLabel: 'Período de cobrança',
    perks: {
      unlimited: 'Mapas e cards ilimitados',
      ai: 'Correções por IA ilimitadas',
      pdf: '{n} mapas gerados de PDF por mês',
      seeds: 'Mapas prontos revisados',
    },
    monthlyNote: 'Cobrado todo mês. Pix ou cartão.',
    annualNote: 'Equivale a {price} por mês.',
    subscribe: 'Assinar o Pro',
    reassure: 'Cancele em um clique. Seus mapas continuam seus.',
    checkoutError: 'Não conseguimos abrir o pagamento. Tente de novo.',
    usageTitle: 'Uso do plano',
    usageBody: 'Os limites renovam sozinhos. Nada é apagado quando você chega neles.',
    usage: {
      aiGrades: 'Correções por IA',
      aiGradesFree: 'Hoje · renova às 4h',
      aiGradesPro: 'Sem limite no uso diário',
      pdf: 'Mapas gerados de PDF',
      pdfSub: 'Neste mês · renova em {date}',
      boards: 'Mapas',
      cards: 'Cards',
      totalSub: 'Total na conta',
      value: '{used} de {limit}',
      unlimitedFem: 'Ilimitadas',
      unlimitedMasc: 'Ilimitados',
      meterLabel: '{label}: {used} de {limit}',
    },
    nearLimit: 'Perto do limite. O Pro remove esse teto.',
    atLimit: 'Você chegou ao limite. O Pro remove esse teto.',
    seePro: 'Ver o Pro',
    loadError: 'Não foi possível carregar o seu plano.',
  },
  prefs: {
    appearanceTitle: 'Aparência',
    appearanceBody: 'Ajustes que valem em todos os seus dispositivos.',
    theme: 'Tema',
    themeHelp: 'Claro, escuro ou o mesmo do seu sistema.',
    themeOptions: { light: 'Claro', dark: 'Escuro', system: 'Sistema' },
    reduceMotion: 'Reduzir movimento',
    reduceMotionHelp: 'Desliga animações e transições. Experimente: esta tela fica calma.',
    reduceMotionOn: 'Modo calmo ligado. Sem animações.',
    reduceMotionOff: 'Movimento normal.',
    routineTitle: 'Rotina de estudo',
    routineBody: 'Para o hábito caber na sua semana.',
    reminder: 'Lembrete diário por e-mail',
    reminderHelp: 'Um aviso com o que vence hoje, no horário que você escolher.',
    reminderHour: 'Horário do lembrete',
    reminderOn: 'Lembrete ligado para as {hour}.',
    reminderOff: 'Lembrete desligado.',
    reminderHourSaved: 'Horário do lembrete: {hour}.',
    newPerDay: 'Cards novos por dia',
    newPerDayFree: 'Free: até 10 por dia. No Pro, até 20.',
    newPerDayPro: 'De 5 a 20 por dia.',
    newPerDayDown: 'Diminuir cards novos por dia',
    newPerDayUp: 'Aumentar cards novos por dia',
    newPerDayValue: '{n}',
    newPerDayProNudge: 'Free permite até 10 por dia. O Pro vai a 20.',
    newPerDaySaved: 'Agora são {n} cards novos por dia.',
    emailsTitle: 'E-mails',
    emailsBody: 'Você escolhe o que quer receber.',
    emailReview: 'Lembretes de revisão vencida',
    emailReviewHelp: 'Um e-mail quando há conceitos para revisar e você não abriu o Remoa.',
    emailNews: 'Novidades do produto',
    emailNewsHelp: 'Lançamentos e mapas prontos novos.',
    saved: 'Preferência salva.',
    saveError: 'Não conseguimos salvar a preferência. Tente de novo.',
  },
  data: {
    exportTitle: 'Exportar seus dados',
    exportBody: 'Baixe seus mapas, cards, conexões e o histórico de tentativas em um arquivo JSON.',
    exportStart: 'Exportar meus dados',
    exportPreparing: 'Preparando seu arquivo…',
    exportPreparingBody: 'Pode continuar usando o Remoa. Avisamos quando estiver pronto.',
    exportReady: '{size} · pronto para baixar',
    exportDownload: 'Baixar',
    exportAgain: 'Gerar de novo',
    exportDownloaded: 'Download iniciado.',
    exportRateLimit: 'Você já pediu uma exportação na última hora. Tente de novo mais tarde.',
    exportError: 'Não conseguimos exportar agora. Tente de novo.',
    keepTitle: 'O que guardamos de você',
    keepBody: 'Poucos dados, com prazo.',
    keepAnswers: 'Respostas em texto',
    keepAnswersBody: 'Apagadas automaticamente depois de {days} dias.',
    keepAudio: 'Áudio da resposta por voz',
    keepAudioBody: 'Nunca é guardado. Só a transcrição, e só se você corrigir.',
    keepPhoto: 'Foto de perfil',
    keepPhotoBody: 'Sem dados de localização. Removida quando você troca a foto ou exclui a conta.',
    dangerTitle: 'Excluir conta',
    dangerBody: 'Apagamos mapas, cards e histórico depois de {days} dias. Nesse período você pode cancelar a exclusão. Depois, não há como recuperar.',
    dangerCta: 'Excluir conta',
    dialogTitle: 'Excluir sua conta?',
    dialogLine1: 'Seus mapas, cards, conexões e o histórico de revisão serão apagados em {days} dias.',
    dialogLine2: 'Até lá, você pode cancelar a exclusão pela própria conta.',
    dialogLine3: 'Se tiver assinatura, ela é cancelada agora e não há nova cobrança.',
    dialogConfirmLabel: 'Digite EXCLUIR para confirmar',
    dialogConfirmWord: 'EXCLUIR',
    dialogKeep: 'Manter minha conta',
    dialogConfirm: 'Excluir conta',
    dialogClose: 'Fechar',
    scheduled: 'Exclusão agendada para {date}.',
    deleteError: 'Não conseguimos agendar a exclusão. Tente de novo.',
    exportFile: 'Arquivo de dados pronto',
  },
  email: {
    unsubscribe: 'Não quer mais receber? Cancelar o lembrete: {url}',
    footer: 'Remoa · Você recebe este e-mail porque ligou o lembrete diário.',
    reminder: {
      subject: '{n, plural, one {# conceito vence hoje} other {# conceitos vencem hoje}}',
      preheader: 'Alguns minutos hoje mantêm o seu estudo em dia.',
      greeting: 'Oi, {name}.',
      body: '{n, plural, one {Hoje vence # conceito} other {Hoje vencem # conceitos}} na sua fila. Revisar agora leva poucos minutos.',
      cta: 'Revisar hoje',
    },
    passwordChanged: {
      subject: 'Sua senha do Remoa foi alterada',
      greeting: 'Oi, {name}.',
      body: 'A senha da sua conta foi alterada em {date}. Por segurança, encerramos a sessão nos outros dispositivos.',
      notYou: 'Não foi você? Redefina sua senha agora e responda este e-mail.',
      cta: 'Redefinir senha',
    },
  },
} as const;
