export const admin = {
  // FR-11: Papéis e navegação
  navigation: {
    admin: 'Admin',
    brand: 'Remoa',
    sealBadge: 'ADMIN',
    ariaLabel: 'Painel de administração',
    backToApp: 'Voltar ao app',
    signOut: 'Sair',
  },

  // Falha transitória (429/5xx/rede): error boundary do painel
  error: { title: 'Não foi possível carregar', body: 'Muitas consultas seguidas ou instabilidade momentânea. Tente de novo em instantes.', retry: 'Tentar de novo' },

  // FR-12: Casca
  shell: {
    sealLabel: 'Selado para administração',
    searchPlaceholder: 'Buscar usuários, mapas, transações…',
    adminInfo: 'Admin logado',
    currentTime: '{time}',
    openTickets: 'chamados abertos',
    openTicketsLabel: '{n} chamados abertos',
    adminName: 'Você',
  },

  // FR-13: Visão geral
  overview: {
    label: 'Visão geral',
    title: 'Dashboard administrativo',
    period: {
      label: 'Período',
      days7: '7 dias',
      days30: '30 dias',
      days90: '90 dias',
    },
    kpis: {
      totalAccounts: 'Total de contas',
      totalMaps: 'Total de mapas',
      proSubscribers: 'Assinantes Pro',
      revenue: 'Receita no período',
      qualifiedReferrals: 'Indicações qualificadas',
      openTickets: 'Chamados abertos',
      variation: '{change} vs. período anterior',
      staleBadge: '{n} sem resposta',
    },
    chart: {
      title: 'Crescimento no período',
      subtitle: 'Novos usuários e mapas por dia',
      newAccounts: 'Novas contas',
      newMaps: 'Novos mapas',
      xAxis: 'Dia',
      yAxis: 'Quantidade',
      aria: 'Gráfico de novas contas e novos mapas por dia',
      startLabel: 'há {n} dias',
      endLabel: 'hoje',
    },
    attention: {
      label: 'Precisa de atenção',
      referralsInReview: 'indicações em revisão por possível fraude',
      failedPayments: 'pagamentos falharam nas últimas 24 horas',
      unansweredTickets: 'chamados sem resposta há mais de 1 dia',
      pendingSeeds: 'mapas seed aguardando revisão médica',
      none: 'Tudo certo por aqui.',
    },
    tables: {
      latestPurchases: 'Últimas compras',
      latestUsers: 'Últimos usuários criados',
      latestMaps: 'Últimos mapas criados',
      viewAll: 'Ver todos',
      viewAllPurchases: 'Ver todas',
      columns: {
        user: 'Usuário',
        plan: 'Plano',
        item: 'Item',
        method: 'Método',
        amount: 'Valor',
        status: 'Status',
        date: 'Data',
        maps: 'Mapas',
        map: 'Mapa',
        origin: 'Origem',
        owner: 'Dono',
        cards: 'Cards',
      },
    },
    updated: 'Atualizado às {time}',
    items: { pro_monthly: 'Pro mensal', pro_annual: 'Pro anual', founder_lifetime: 'Fundador vitalício' },
    paymentStatus: { paid: 'Pago', pending: 'Pendente', failed: 'Falhou', refunded: 'Reembolsado' },
    plans: { free: 'Free', pro: 'Pro', founder: 'Fundador' },
    unknownUser: 'Conta excluída',
    loadError: 'Não foi possível carregar a visão geral.',
    export: {
      label: 'Exportar',
      tooltip: 'Gerar CSV dos agregados',
      done: 'Exportado com sucesso',
      title: 'Exportar visão geral',
      summary: 'Gera um CSV dos números do período. A exportação fica registrada na auditoria.',
      file: 'visao-geral-{period}d.csv',
    },
  },

  // F19 T8: shared by the Usuários, Mapas and Indicações lists
  lists: {
    all: 'Todos',
    results: '{n, plural, =0 {Nenhum resultado} one {# resultado} other {# resultados}}',
    exportCsv: 'Exportar CSV',
    exportReason: 'Exportar a lista',
    exportSummary: 'Gera um CSV com os filtros atuais. A exportação fica registrada na auditoria.',
    exportConfirm: 'Exportar',
    searchLabel: 'Buscar',
    pageSummary: 'Mostrando {from}–{to} de {total}',
    pageNav: 'Páginas',
    prev: 'Anterior',
    next: 'Próxima',
    empty: 'Nada encontrado com esses filtros.',
    loading: 'Carregando a lista…',
    loadError: 'Não foi possível carregar a lista.',
    retry: 'Tentar de novo',
    closeDrawer: 'Fechar detalhes',
    drawerRule: 'Toda ação pede um motivo e fica registrada na auditoria.',
    drawerLoadError: 'Não foi possível carregar os detalhes.',
    drawerNoActions: 'Sem ações disponíveis para este estado.',
    auditTrail: 'Registrado na auditoria',
    unknownPerson: 'Sem nome',
    yes: 'Sim',
    reasonCancel: 'Cancelar',
    reasonDone: 'Concluir',
    reasonTooShort: 'Escreva pelo menos 8 caracteres.',
    reasonError: 'Não foi possível concluir a ação. Tente de novo.',
    reasonReauth: 'Esta ação exige um login recente. Entre de novo e repita.',
    reasonNotFound: 'Este item não existe mais.',
    reasonConflict: 'A ação não se aplica ao estado atual (ele pode ter mudado). Atualize a lista.',
    reasonSeedNotReviewed: 'Falta a revisão médica registrada',
    receipt: 'Ação registrada na auditoria ({id})',
    loadReauth: 'Sua sessão de administração expirou. Entre de novo.',
  },

  // FR-14: Usuários
  users: {
    label: 'Usuários',
    title: 'Gerenciar usuários',
    subtitle: 'Gestão de contas, planos e acessos',
    search: {
      placeholder: 'Buscar por nome ou e-mail',
    },
    filters: {
      plan: 'Plano',
      status: 'Status',
      planFree: 'Free',
      planPro: 'Pro',
      planFounder: 'Founder',
      planProGrant: 'Pro por indicação',
      statusActive: 'Ativo',
      statusPending: 'Pendente',
      statusSuspended: 'Suspenso',
      statusDeleting: 'Excluindo',
    },
    summary: {
      totalAccounts: 'Contas',
      active: 'Ativas',
      pending: 'Pendentes',
      suspended: 'Suspensas',
    },
    table: {
      ariaLabel: 'Lista de usuários',
      columns: {
        user: 'Usuário',
        plan: 'Plano',
        maps: 'Mapas',
        cards: 'Cards',
        status: 'Status',
        origin: 'Origem',
        created: 'Criado',
        mapsCards: 'Mapas e cards',
      },
    },
    drawer: {
      label: 'Detalhes do usuário',
      id: 'ID',
      email: 'E-mail',
      name: 'Nome',
      plan: 'Plano',
      maps: 'Mapas',
      cards: 'Cards',
      origin: 'Origem do cadastro',
      createdAt: 'Criado em',
      lastSignIn: 'Último acesso',
      role: 'Papel',
      timeline: 'Linha do tempo',
      mapsCards: '{maps} mapas · {cards} cards',
      stepCreated: 'Conta criada',
      stepConfirmed: 'E-mail confirmado',
      stepGrant: 'Pro concedido até {date}',
      stepSuspended: 'Conta suspensa',
      stepDeletion: 'Exclusão agendada para {date}',
      suspendedReason: 'Motivo da suspensão',
    },
    plan: { free: 'Free', pro: 'Pro', founder: 'Founder', proGrant: 'Pro por indicação' },
    status: { active: 'Ativo', pending: 'Pendente', suspended: 'Suspenso', deleting: 'Excluindo' },
    origin: { direct: 'Direto', referral: 'Indicação' },
    role: { student: 'Usuário', reviewer: 'Revisor', admin: 'Admin' },
    mapsCount: '{maps, plural, =0 {0 mapas} one {# mapa} other {# mapas}} · {cards, plural, =0 {0 cards} one {# card} other {# cards}}',
    dialog: {
      grantProTitle: 'Conceder 1 mês de Pro',
      grantProSummary: 'A concessão começa agora e aparece para {name} como Pro por indicação.',
      passwordResetTitle: 'Enviar redefinição de senha',
      passwordResetSummary: 'Enviamos um link para {email}. A senha atual continua valendo até a troca.',
      suspendTitle: 'Suspender conta',
      suspendSummary: 'A pessoa deixa de acessar o Remoa. Os dados são mantidos.',
      reactivateTitle: 'Reativar conta',
      reactivateSummary: 'A pessoa volta a acessar o Remoa imediatamente.',
      deleteTitle: 'Excluir conta',
      deleteSummary: 'Agenda a exclusão em 7 dias, como no pedido do próprio usuário. Ação irreversível depois do prazo.',
      confirmGrant: 'Conceder',
      confirmReset: 'Enviar',
      confirmSuspend: 'Suspender',
      confirmReactivate: 'Reativar',
      confirmDelete: 'Agendar exclusão',
    },
    auditActions: {
      'user.grant_pro_month': 'Pro concedido',
      'user.password_reset': 'Redefinição de senha enviada',
      'user.suspend': 'Conta suspensa',
      'user.reactivate': 'Conta reativada',
      'user.schedule_deletion': 'Exclusão agendada',
    } as Record<string, string>,
    actions: {
      grantPro: 'Conceder 1 mês de Pro',
      sendPasswordReset: 'Enviar redefinição de senha',
      suspend: 'Suspender',
      reactivate: 'Reativar',
      scheduleDelete: 'Agendar exclusão',
    },
    messages: {
      grantProSuccess: 'Concedido 1 mês de Pro',
      sendPasswordResetSuccess: 'E-mail de redefinição enviado',
      suspendSuccess: 'Usuário suspenso',
      reactivateSuccess: 'Usuário reativado',
      deleteScheduledSuccess: 'Exclusão agendada para {date}',
    },
  },

  // FR-15: Mapas
  maps: {
    label: 'Mapas',
    title: 'Gerenciar mapas',
    subtitle: 'Todos os mapas da plataforma, privados e seeds',
    search: {
      placeholder: 'Buscar por título ou dono',
    },
    summary: { total: 'mapas', private: 'privados', seedDraft: 'seeds em rascunho', seedApproved: 'seeds aprovados' },
    filters: {
      origin: 'Origem',
      status: 'Status',
      originUser: 'Criado pelo usuário',
      originSeed: 'Seed',
      origin_manual: 'Em branco',
      origin_import: 'Importado',
      origin_seed_copy: 'Cópia de seed',
      origin_link_copy: 'Cópia de link',
      origin_seed: 'Seed',
      statusPublic: 'Público',
      statusPrivate: 'Privado',
      statusSeedDraft: 'Seed rascunho',
      statusSeedApproved: 'Seed aprovado',
      statusArchived: 'Arquivado',
    },
    table: {
      ariaLabel: 'Lista de mapas',
      columns: {
        map: 'Mapa',
        owner: 'Dono',
        cardsEdges: 'Cards e conexões',
        cards: 'Cards',
        edges: 'Conexões',
        status: 'Status',
        origin: 'Origem',
        created: 'Criado',
      },
    },
    drawer: {
      label: 'Detalhes do mapa',
      id: 'ID',
      title: 'Título',
      owner: 'Dono',
      cards: 'Cards',
      edges: 'Conexões',
      status: 'Status',
      origin: 'Origem',
      createdAt: 'Criado em',
      updatedAt: 'Atualizado em',
      timeline: 'Linha do tempo',
      cardsEdges: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
      noOwner: 'Sem dono',
    },
    status: { private: 'Privado', seed_draft: 'Seed rascunho', seed_approved: 'Seed aprovado', archived: 'Arquivado' },
    audit: {
      banner: 'Modo auditoria · somente leitura · este acesso foi registrado ({id})',
      close: 'Fechar mapa',
      canvasLabel: 'Mapa aberto em modo auditoria',
      empty: 'Este mapa ainda não tem cards.',
    },
    dialog: {
      openTitle: 'Abrir mapa do usuário',
      openSummary: 'O conteúdo é privado do aluno. O acesso é somente leitura e fica registrado com o seu motivo.',
      openConfirm: 'Abrir',
      archiveTitle: 'Arquivar mapa',
      archiveSummary: 'O mapa sai da lista do dono e pode ser restaurado por você.',
      archiveConfirm: 'Arquivar',
      approveTitle: 'Aprovar seed',
      approveSummary: 'A seed fica publicada para todos. Só aprove com a revisão médica registrada.',
      approveConfirm: 'Aprovar',
      unpublishTitle: 'Despublicar seed',
      unpublishSummary: 'A seed deixa de aparecer para os alunos e volta a rascunho.',
      unpublishConfirm: 'Despublicar',
    },
    auditActions: {
      'map.open_readonly': 'Mapa aberto (somente leitura)',
      'map.archive': 'Mapa arquivado',
      'seed.approve': 'Seed aprovada',
      'seed.unpublish': 'Seed despublicada',
    } as Record<string, string>,
    actions: {
      viewReadOnly: 'Abrir (somente leitura)',
      archive: 'Arquivar',
      approveSeed: 'Aprovar seed',
      unpublishSeed: 'Despublicar',
    },
    messages: {
      viewReadOnlySuccess: 'Abrindo em modo de auditoria…',
      archiveSuccess: 'Mapa arquivado',
      approveSeedSuccess: 'Seed aprovada',
      unpublishSeedSuccess: 'Seed despublicada',
      accessDenied: 'Acesso negado (motivo registrado)',
    },
  },

  // FR-16: Transações
  payments: {
    label: 'Transações',
    title: 'Gerenciar transações',
    subtitle: 'Compras e créditos, espelhados do Stripe',
    search: {
      label: 'Buscar transações',
      placeholder: 'Buscar por usuário ou ID da transação',
    },
    filters: {
      status: 'Status',
      method: 'Método',
      all: 'Todos',
      statusPaid: 'Pago',
      statusPending: 'Pendente',
      statusFailed: 'Falhou',
      statusRefunded: 'Reembolsado',
      methodPix: 'Pix',
      methodCard: 'Cartão',
      methodCredit: 'Crédito',
    },
    summary: {
      received: 'recebidos',
      paid: 'pagos',
      pending: 'pendentes',
      failed: 'falhas',
      refunded: 'reembolsos',
    },
    count: '{n} resultados',
    pagination: { summary: 'Mostrando {from}–{to} de {total}', nav: 'Paginação das transações', prev: 'Anterior', next: 'Próxima' },
    table: {
      ariaLabel: 'Lista de transações',
      columns: {
        user: 'Usuário',
        transaction: 'Transação',
        id: 'ID',
        item: 'Item',
        method: 'Método',
        coupon: 'Cupom',
        status: 'Status',
        amount: 'Valor',
        date: 'Data',
        when: 'Quando',
      },
      row: 'Abrir transação de {name}',
    },
    drawer: {
      label: 'Detalhes da transação',
      close: 'Fechar detalhes',
      id: 'ID',
      user: 'Usuário',
      item: 'Item',
      method: 'Método',
      coupon: 'Cupom',
      status: 'Status',
      amount: 'Valor',
      createdAt: 'Criado em',
      refundedAt: 'Reembolsado em',
      timeline: 'Linha do tempo',
      stripeIds: 'IDs do Stripe',
      customerId: 'ID do cliente',
      subscriptionId: 'ID da assinatura',
      paymentIntentId: 'ID do pagamento',
      invoiceId: 'ID da fatura',
      none: '—',
      rule: 'Toda ação pede um motivo e fica registrada na auditoria.',
      trail: 'Registrado na auditoria',
      loadError: 'Não foi possível abrir esta transação.',
      newTab: '(abre em nova aba)',
    },
    events: {
      checkout_created: 'Checkout iniciado',
      pix_generated: 'Pix gerado',
      card_authorized: 'Cartão autorizado',
      paid: 'Pagamento confirmado',
      plan_released: 'Plano liberado',
      failed: 'Pagamento falhou',
      refund_requested: 'Reembolso solicitado',
      refunded: 'Reembolsado',
      marked_paid: 'Marcado como pago',
    },
    actions: {
      resendReceipt: 'Reenviar recibo',
      markPaid: 'Marcar como pago',
      refund: 'Reembolsar',
      openInStripe: 'Abrir no Stripe',
    },
    dialogs: {
      resendReceipt: { title: 'Reenviar recibo', summary: 'O recibo desta transação é enviado de novo para o e-mail do usuário.' },
      refund: { title: 'Reembolsar transação', summary: 'Pede ao Stripe o reembolso total de {amount}. O status continua Pago até o Stripe confirmar.' },
      markPaid: { title: 'Marcar como pago', summary: 'Libera o plano sem esperar o Stripe. Só depois de conferir o pagamento.', checked: 'Conferi no Stripe' },
    },
    trail: {
      resendReceipt: 'Recibo reenviado',
      refund: 'Reembolso solicitado — o status muda quando o Stripe confirmar',
      markPaid: 'Marcado como pago',
    },
    messages: {
      resendReceiptSuccess: 'Recibo reenviado',
      markPaidSuccess: 'Marcado como pago',
      refundSuccess: 'Reembolso processado',
      refundError: 'Não foi possível processar o reembolso',
    },
    export: {
      label: 'Exportar CSV',
      title: 'Exportar transações',
      summary: 'Gera um CSV com os filtros atuais. A exportação fica registrada na auditoria.',
      done: 'Concluir',
      file: 'transacoes.csv',
    },
    states: { loadError: 'Não foi possível carregar as transações.' },
  },

  // FR-17: Indicações
  waitlist: {
    label: 'Lista de espera',
    subtitle: 'Pessoas que pediram acesso na página inicial. O e-mail é dado pessoal: o acesso a esta lista fica registrado na auditoria.',
    search: { placeholder: 'Buscar por e-mail' },
    summaryTotal: 'na lista',
    ariaLabel: 'Lista de espera',
    drawerLabel: 'Detalhes da inscrição',
    columns: { email: 'E-mail', segment: 'Momento', origin: 'Origem', date: 'Data' },
    store: { total: 'na lista da loja', buy: 'querem comprar', sell: 'querem vender', teacher: 'vendedores professores', student_resident: 'vendedores alunos ou residentes', physician: 'vendedores médicos', export: 'Exportar CSV da loja' },
    segment: { y3_4: '3º/4º ano', y5_6: '5º/6º ano', graduated: 'Recém-formado' },
    drawer: { email: 'E-mail', segment: 'Momento', origin: 'Origem', variant: 'Variante de preço', createdAt: 'Inscrito em', none: 'Não informado' },
  },
  referrals: {
    label: 'Indicações',
    title: 'Gerenciar indicações',
    subtitle: 'Programa "Indique e ganhe": quem indicou quem, sinais de fraude e meses concedidos',
    search: {
      placeholder: 'Buscar por indicador ou indicado',
    },
    filters: {
      status: 'Status',
      statusQualified: 'Qualificadas',
      statusInProgress: 'Em andamento',
      statusInReview: 'Em revisão',
      statusRejected: 'Rejeitadas',
      channel: 'Canal',
      status_invited: 'Convite enviado',
      status_signed_up: 'Cadastrou',
      status_qualified: 'Qualificada',
      status_in_review: 'Em revisão',
      status_rejected: 'Rejeitada',
      status_expired: 'Expirada',
      channel_link: 'Link',
      channel_email: 'E-mail',
    },
    summary: {
      qualified: 'Qualificadas',
      inProgress: 'Em andamento',
      inReview: 'Em revisão',
      rejected: 'Rejeitadas',
      monthsGranted: 'Meses concedidos',
    },
    table: {
      ariaLabel: 'Lista de indicações',
      columns: {
        referrer: 'Indicador',
        referred: 'Indicado',
        pair: 'Indicador → indicado',
        channel: 'Canal',
        signals: 'Sinais',
        fraudSignals: 'Sinais de fraude',
        status: 'Status',
        reward: 'Recompensa',
        date: 'Data',
      },
    },
    drawer: {
      label: 'Detalhes da indicação',
      referrer: 'Indicador',
      referred: 'Indicado',
      channel: 'Canal',
      fraudSignals: 'Sinais de fraude',
      status: 'Status',
      reward: 'Recompensa',
      createdAt: 'Criado em',
      qualifiedAt: 'Qualificado em',
      timeline: 'Linha do tempo',
      none: 'Nenhum sinal detectado',
      signedUpAt: 'Cadastro em',
      grants: 'Concessões',
      grantLine: '{name}: até {date}',
      grantRevoked: 'revogada',
      stepInvited: 'Convite criado',
      stepSignedUp: 'Indicado se cadastrou',
      stepQualified: 'Qualificada',
      rewardNone: '—',
    },
    reward: '{n, plural, one {# mês} other {# meses}}',
    rewardPair: '1 + 1 mês',
    signalsNone: 'Nenhum',
    signalsCount: '{n, plural, one {# sinal} other {# sinais}}',
    signal: {
      self_referral: 'Autoindicação',
      disposable_email: 'E-mail descartável',
      existing_account: 'Conta já existente',
      velocity_limit: 'Muitos convites em pouco tempo',
      fraud_signals: 'Sinais de fraude',
      manual: 'Marcada à mão',
    },
    dialog: {
      approveTitle: 'Aprovar indicação',
      approveSummary: 'Libera 1 mês de Pro para {from} e 1 mês para o indicado, ao mesmo tempo.',
      approveConfirm: 'Aprovar e conceder',
      rejectTitle: 'Rejeitar indicação',
      rejectSummary: 'Nenhum mês é concedido. O motivo fica registrado.',
      rejectConfirm: 'Rejeitar',
      revokeTitle: 'Revogar concessão',
      revokeSummary: 'Remove os dois meses de Pro concedidos por esta indicação.',
      revokeConfirm: 'Revogar',
    },
    auditActions: {
      'referral.approve': 'Indicação aprovada',
      'referral.reject': 'Indicação rejeitada',
      'referral.auto_reject': 'Indicação rejeitada automaticamente',
      'grant.revoke': 'Concessão revogada',
    } as Record<string, string>,
    actions: {
      approve: 'Aprovar e conceder',
      reject: 'Rejeitar',
      revoke: 'Revogar concessão',
    },
    messages: {
      approveSuccess: '2 meses concedidos aos dois',
      rejectSuccess: 'Indicação rejeitada',
      revokeSuccess: 'Concessão revogada',
    },
  },

  // FR-18: Suporte (caixa de entrada)
  support: {
    label: 'Suporte',
    title: 'Caixa de entrada',
    filters: {
      status: 'Status',
      statusAll: 'Todos',
      statusOpen: 'Aberto',
      statusInProgress: 'Em análise',
      statusAnswered: 'Respondido',
      statusResolved: 'Resolvido',
    },
    summary: {
      allTickets: 'Todos os chamados',
      openCount: '{count} aberto',
      openCountMany: '{count} abertos',
      openUnassigned: '{count} aberto · {unassigned} sem responsável',
      openUnassignedMany: '{count} abertos · {unassigned} sem responsável',
    },
    list: {
      ariaLabel: 'Lista de chamados de suporte',
      empty: 'Nenhum chamado nesse filtro.',
      loadError: 'Não foi possível carregar os chamados.',
      searchLabel: 'Buscar chamado',
      searchPlaceholder: 'Buscar por assunto ou usuário',
      filterLabel: 'Filtrar chamados',
      subject: 'Assunto',
      number: 'Número',
      user: 'Usuário',
      status: 'Status',
      date: 'Data',
    },
    detail: {
      header: {
        subject: 'Assunto',
        number: 'Número',
        user: 'Usuário',
        plan: 'Plano',
        status: 'Status',
        viewProfile: 'Ver perfil do usuário',
      },
      type: 'Tipo',
      types: {
        broken: 'Algo não funciona',
        billing: 'Cobrança e plano',
        medical: 'Conteúdo médico',
        suggestion: 'Sugestão',
        other: 'Outro',
      },
      technicalInfo: 'Informações técnicas enviadas pelo usuário',
      technicalSummary: 'Tela: {screen} · {browser} no {os} · app {version}',
      planLabel: 'Plano {plan}',
      assigned: 'Atribuído: {name}',
      noAssignee: '—',
      pick: 'Escolha um chamado para ver a conversa.',
      loadError: 'Não foi possível abrir o chamado.',
      team: 'Equipe Remoa',
      system: 'Sistema',
      attachment: 'Anexo enviado pelo usuário',
      unknownUser: 'Conta excluída',
      noTechnicalInfo: 'Sem informações técnicas',
      messages: 'Conversa',
      noMessages: 'Sem mensagens ainda',
      internalNoteLabel: 'Nota interna',
      internalNoteHint: 'Invisível para o usuário',
    },
    macros: {
      label: 'Respostas prontas',
      loading: 'Carregando respostas prontas…',
      error: 'Erro ao carregar respostas prontas',
      insert: 'Inserir',
      manage: 'Gerenciar',
    },
    actions: {
      assignToMe: 'Atribuir a mim',
      assignTo: 'Atribuir a {name}',
      markResolved: 'Marcar como resolvido',
      unassign: 'Desatribuir',
      sendReply: 'Enviar resposta',
      addInternalNote: 'Adicionar nota interna',
      sendNote: 'Salvar nota interna',
    },
    reply: {
      label: 'Resposta',
      placeholder: 'Escreva a resposta',
      sending: 'Enviando…',
      error: 'Não foi possível enviar a resposta',
      successTicket: 'Resposta enviada ao chamado',
      successNote: 'Nota interna adicionada',
    },
  },

  // FR-18: Macros/respostas prontas
  macros: {
    replyMoreInfo: 'Pedir mais detalhes',
    replyMoreInfoBody: 'Oi! Para investigar, pode me contar qual era a tela, o que você esperava e o que aconteceu? Se tiver uma captura de tela, ajuda bastante.',
    replyInvestigating: 'Estamos investigando',
    replyInvestigatingBody: 'Obrigado por avisar. Já estamos investigando e voltamos a falar assim que tivermos uma resposta.',
    replyResolved: 'Resolvido',
    replyResolvedBody: 'Corrigimos o problema. Pode tentar de novo? Se continuar, é só responder aqui.',
    list: {
      awaiting: 'Aguardando resposta sua',
      evaluated: 'Já foi avaliado',
      contact: 'Entraremos em contato em breve',
      thankyou: 'Obrigado por reportar',
    } as Record<string, string>,
    // These can be edited in the admin UI; defaults are shown
  },

  // FR-19: Auditoria
  audit: {
    label: 'Auditoria',
    title: 'Log de auditoria',
    subtitle: 'Registro imutável de ações de administradores, do sistema e do Stripe',
    search: {
      label: 'Buscar no log',
      placeholder: 'Buscar por ação, alvo ou motivo',
    },
    summary: { records: 'registros', admins: 'de admins', system: 'do sistema', denied: 'negados' },
    count: '{n} resultados',
    pagination: { summary: 'Mostrando {from}–{to} de {total}', nav: 'Paginação do log', prev: 'Anterior', next: 'Próxima' },
    filters: {
      actor: 'Quem',
      result: 'Resultado',
      period: 'Período',
      action: 'Ação',
      all: 'Todos',
      actorMe: 'Você (admin)',
      actorSystem: 'Sistema',
      actorStripe: 'Webhook Stripe',
      allActions: 'Todas as ações',
      resultSuccess: 'Sucesso',
      resultDenied: 'Negado',
      period1: 'Hoje',
      period7: '7 dias',
      period30: '30 dias',
    },
    who: { me: 'Você (admin)', system: 'Sistema', stripe: 'Webhook Stripe', user: 'Sem permissão (não admin)', unknown: 'Admin removido' },
    targets: { user: 'Usuário', board: 'Mapa', payment: 'Transação', referral: 'Indicação', grant: 'Concessão', ticket: 'Chamado', export: 'Exportação', route: 'Rota', blog_post: 'Post do blog', blog_category: 'Categoria do blog', sitemap: 'Sitemap' },
    denials: { not_admin: 'Sem papel de admin', reauth_required: 'Reautenticação necessária', missing_reason: 'Sem motivo informado', invalid_state: 'Estado inválido', error: 'Erro ao executar' },
    noReason: '—',
    origin: 'IP …{hash}',
    actions: {
      user: { grant_pro_month: 'Concedeu 1 mês de Pro', password_reset: 'Enviou redefinição de senha', suspend: 'Suspendeu conta', reactivate: 'Reativou conta', schedule_deletion: 'Agendou exclusão da conta', make_admin: 'Criou administrador' },
      map: { open_readonly: 'Abriu mapa de usuário (somente leitura)', archive: 'Arquivou mapa' },
      seed: { approve: 'Aprovou seed', unpublish: 'Despublicou seed' },
      payment: { refund: 'Reembolsou transação', mark_paid: 'Marcou transação como paga', resend_receipt: 'Reenviou recibo', webhook: 'Pagamento recebido do Stripe' },
      referral: { approve: 'Aprovou indicação', reject: 'Rejeitou indicação', auto_reject: 'Rejeitou indicação (antifraude)' },
      grant: { revoke: 'Revogou concessão' },
      ticket: { reply: 'Respondeu chamado', internal_note: 'Anotou no chamado', assign: 'Atribuiu chamado', resolve: 'Resolveu chamado' },
      export: { csv: 'Exportou CSV' },
      admin: { access: 'Tentou acessar o painel' },
      waitlist: { view: 'Consultou a lista de espera' },
      store_waitlist: { view: 'Consultou a lista de espera da loja' },
      blog: {
        create: 'Criou post do blog',
        update: 'Editou post do blog',
        duplicate: 'Duplicou post do blog',
        publish: 'Publicou post do blog',
        schedule: 'Agendou post do blog',
        unpublish: 'Despublicou post do blog',
        delete: 'Excluiu post do blog',
        restore_revision: 'Restaurou revisão do post',
        upload_image: 'Enviou imagem do blog',
        category_upsert: 'Salvou categoria do blog',
        preview_link: 'Gerou link de pré-visualização',
        auto_publish: 'Publicou post agendado',
      },
      sitemap: { regenerate: 'Atualizou o sitemap' },
    },
    table: {
      ariaLabel: 'Log de auditoria',
      columns: {
        when: 'Quando',
        who: 'Quem',
        action: 'Ação',
        target: 'Alvo',
        reason: 'Motivo',
        result: 'Resultado',
        ip: 'IP',
        origin: 'Origem',
      },
      row: 'Abrir registro {id}',
    },
    drawer: {
      label: 'Detalhes do registro',
      close: 'Fechar detalhes',
      timestamp: 'Data e hora',
      actor: 'Quem',
      action: 'Ação',
      target: 'Alvo',
      reason: 'Motivo',
      result: 'Resultado',
      denial: 'Motivo da negação',
      requestId: 'ID da requisição',
      ipHash: 'Hash do IP',
      userAgent: 'Agente do usuário',
      before: 'Antes',
      after: 'Depois',
      noChange: 'Sem alterações',
      none: '—',
    },
    export: {
      label: 'Exportar CSV',
      tooltip: 'Gerar CSV dos registros',
      title: 'Exportar log de auditoria',
      summary: 'Gera um CSV com os filtros atuais. A exportação também fica registrada.',
      done: 'Concluir',
      file: 'auditoria.csv',
    },
    states: { loadError: 'Não foi possível carregar o log.' },
  },

  // FR-20: Diálogo de motivo
  reason: {
    title: 'Confirmar ação',
    label: 'Motivo (obrigatório)',
    placeholder: 'Mínimo 8 caracteres',
    hint: 'Este motivo será registrado na auditoria',
    error: 'Motivo deve ter pelo menos 8 caracteres',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    confirming: 'Confirmando…',
    registered: 'Ação registrada na auditoria ({id})',
  },

  // FR-11: Autenticação
  auth: {
    recentAuth: 'Reautenticação necessária',
    recentAuthDesc: 'Esta ação exige uma autenticação recente. Faça login novamente.',
    reauth: 'Autenticar novamente',
    expiredTitle: 'Sua sessão de administrador expirou',
    expiredDesc: 'Por segurança, a sessão de administração dura 12 horas desde o último login. Entre de novo para continuar.',
    signInAgain: 'Entrar de novo',
    confirmTitle: 'Confirme sua senha para continuar',
    confirmDesc: 'A sessão de administração dura 12 horas desde o último login. Confirme sua senha e continue de onde parou.',
    password: 'Senha',
    confirm: 'Confirmar',
    wrongPassword: 'Senha incorreta. Tente de novo.',
    otherMethod: 'Entrei com Google ou link por e-mail',
  },

  // FR-21: Segurança
  security: {
    restrictedAccess: 'Acesso restrito',
    accessDenied: 'Você não tem permissão para esta ação.',
    loggedWarning: 'Esta ação foi registrada na auditoria.',
  },

  // FR-23: Estados
  states: {
    empty: 'Nenhum resultado',
    loading: 'Carregando…',
    error: 'Erro ao carregar dados',
    noPermission: 'Sem permissão',
    retryError: 'Tentar de novo',
  },

  // Erros
  errors: {
    unauthorized: 'Não autorizado',
    forbidden: 'Acesso negado',
    notFound: 'Não encontrado',
    serverError: 'Erro do servidor. Tente mais tarde.',
    networkError: 'Erro de conexão. Verifique sua internet.',
  },
} as const;
