// F25 Calendário (D-043..D-048). Textos dos componentes de `@remoa/ui/calendar`, agrupados na forma das props `text`.
// Meses e dias da semana vêm do Intl (pt-BR), não daqui.
export const calendar = {
  navLabel: 'Calendário',
  today: 'Hoje',
  prev: 'Anterior',
  next: 'Próximo',
  newEvent: 'Novo compromisso',
  howItWorks: 'Como o calendário funciona',
  labelsTitle: 'Etiquetas',
  newLabel: 'Nova etiqueta',
  agendaTitle: 'Próximos 30 dias',
  galleryTitle: 'Galeria de compromissos',
  views: { label: 'Visão do calendário', month: 'Mês', week: 'Semana', agenda: 'Agenda', gallery: 'Galeria' },
  month: {
    gridLabel: 'Calendário do mês',
    allDay: 'Dia inteiro',
    count: '{n, plural, =0 {nenhum compromisso} one {# compromisso} other {# compromissos}}',
    more: '+{n} mais',
  },
  week: { allDayRow: 'dia todo', allDay: 'Dia inteiro', nowLabel: 'Agora' },
  agenda: { label: 'Compromissos por dia', todayWord: 'Hoje', allDay: 'Dia inteiro', loadMore: 'Carregar mais' },
  gallery: { allDay: 'Dia inteiro' },
  relative: {
    today: 'Hoje',
    tomorrow: 'Amanhã',
    inDays: 'Em {n} dias',
    past: 'Passou',
    todayLower: 'hoje',
    tomorrowLower: 'amanhã',
    inDaysLower: 'em {n} dias',
    pastLower: 'passou',
  },
  mini: { label: 'Mini calendário', prev: 'Mês anterior', next: 'Próximo mês', hasEvents: 'com compromissos' },
  labels: {
    show: 'Mostrar {name}',
    colorPicker: 'Cor da etiqueta',
    colors: { azul: 'Azul', rosa: 'Rosa', verde: 'Verde', violeta: 'Violeta', turquesa: 'Turquesa', laranja: 'Laranja', ambar: 'Âmbar', cinza: 'Cinza' },
    defaults: { prova: 'Prova', trabalho: 'Trabalho', importante: 'Data importante', plantao: 'Plantão', pessoal: 'Pessoal' },
  },
  form: {
    titleNew: 'Novo compromisso',
    titleEdit: 'Editar compromisso',
    close: 'Fechar',
    title: 'Título',
    label: 'Etiqueta',
    date: 'Data',
    start: 'Início',
    end: 'Fim',
    allDay: 'Dia inteiro',
    location: 'Local',
    description: 'Descrição',
    cover: 'Imagem de capa',
    reminders: 'Avisos por e-mail e no sino',
    d1: '1 dia antes',
    d1Hint: 'Às 18:00 do dia anterior',
    d0: 'No dia',
    d0Hint: 'Às 07:00 do dia do compromisso',
    cancel: 'Cancelar',
    save: 'Salvar compromisso',
    saving: 'Salvando',
    errors: {
      title: 'Dê um título com pelo menos 2 caracteres.',
      titleMax: 'O título pode ter no máximo 120 caracteres.',
      date: 'Escolha a data.',
      end: 'O fim não pode ser antes do início.',
      location: 'O local pode ter no máximo 160 caracteres.',
      description: 'A descrição pode ter no máximo 2.000 caracteres.',
    },
    coverText: {
      title: 'Adicionar imagem de capa',
      description: 'PNG ou JPG, até 5 MB. Mostramos em 16:9.',
      button: 'Escolher imagem',
      replace: 'Trocar',
      remove: 'Remover imagem',
      preview: 'Prévia da capa em 16:9',
      errorType: 'Use uma imagem PNG ou JPG.',
      errorSize: 'A imagem passa de 5 MB. Escolha uma menor.',
    },
    saved: 'Compromisso salvo. Avisamos por e-mail 1 dia antes e no dia.',
  },
  details: {
    drawerTitle: 'Detalhes do compromisso',
    close: 'Fechar',
    allDay: 'Dia inteiro',
    remindersTitle: 'Avisos por e-mail e no sino',
    edit: 'Editar',
    duplicate: 'Duplicar',
    delete: 'Excluir',
    confirmTitle: 'Excluir este compromisso?',
    confirmBody: 'Os avisos agendados também serão cancelados.',
    confirmYes: 'Excluir',
    confirmNo: 'Manter',
    addToCalendar: 'Adicionar ao Google Agenda',
  },
  tour: {
    dialog: 'Como o calendário funciona',
    eyebrow: 'Calendário · Passo {step} de {total}',
    skip: 'Pular',
    back: 'Voltar',
    next: 'Próximo',
    create: 'Criar meu primeiro compromisso',
    done: 'Entendi',
    steps: {
      s1: { title: 'Seu calendário de estudo', body: 'Marque provas, trabalhos e datas importantes em um só lugar, no jeito do Google Agenda.' },
      s2: { title: 'Cada compromisso com os detalhes', body: 'Título, dia e hora, local, descrição e uma imagem de capa, para você bater o olho e lembrar.' },
      s3: { title: 'Etiquetas para organizar', body: 'Agrupe por Prova, Trabalho, Plantão ou crie as suas. Ligue e desligue cada grupo na lateral.' },
      s4: { title: 'Avisos por e-mail e no sino', body: 'Enviamos um aviso 1 dia antes e outro no dia. Tudo também aparece na central de notificações, no sino.' },
      s5: { title: 'Tudo aparece em Hoje', body: 'Os próximos compromissos e o que está chegando ficam na sua tela inicial, junto da revisão do dia.' },
    },
    demo: {
      coverChip: 'Imagem de capa',
      label: 'Prova',
      eventTitle: 'Prova de Clínica Médica',
      when: 'Amanhã · 08:00 – 10:00',
      place: 'Sala 204 · Bloco B',
      notes: 'Capítulos 1 a 6',
      l1: 'Prova',
      l2: 'Trabalho',
      l3: 'Data importante',
      l4: 'Plantão',
      r1: 'Prova de Clínica Médica',
      r2: 'Entrega de Epidemiologia',
      r3: 'Plantão no pronto-socorro',
      d1: '1 dia antes',
      d1At: 'às 18:00',
      d0: 'No dia',
      d0At: 'às 07:00',
      bell: 'e no sino',
      upcoming: 'Próximos compromissos',
      i1: { day: '9', mon: 'out', title: 'Prova de Clínica Médica', chip: 'Amanhã' },
      i2: { day: '12', mon: 'out', title: 'Entrega de Epidemiologia', chip: 'Em 3 dias' },
      i3: { day: '14', mon: 'out', title: 'Prazo da inscrição', chip: 'Em 5 dias' },
    },
  },
  upcoming: {
    title: 'Próximos compromissos',
    seeAll: 'Calendário',
    allDay: 'Dia inteiro',
    empty: 'Nada marcado ainda. Adicione suas provas e receba um aviso por e-mail 1 dia antes e no dia.',
    add: 'Adicionar compromisso',
  },
  banner: {
    ariaLabel: 'Compromisso chegando',
    cta: 'Ver no calendário',
    headline: '{when}: {title}',
    todayAt: 'Hoje às {time}',
    tomorrowAt: 'Amanhã às {time}',
    todayAllDay: 'Hoje, o dia todo',
    tomorrowAllDay: 'Amanhã, o dia todo',
  },
  page: {
    railDot: 'Há compromisso nas próximas 24 horas',
    reminderAt: '{date}, às {time}',
    reminderSkipped: '{date}, às {time} (horário já passou, não enviamos)',
    reminderSent: 'Enviado em {date}, às {time}',
    saved: 'Compromisso salvo.',
    deleted: 'Compromisso excluído.',
    duplicated: 'Compromisso duplicado para {date}.',
    pending: 'Salvando',
    offline: 'Sem conexão. Salvamos o compromisso quando você voltar.',
    loadError: 'Não foi possível carregar o calendário.',
    saveError: 'Não foi possível salvar. Seu compromisso não foi perdido.',
    actionError: 'Não foi possível concluir. Tente de novo.',
    coverError: 'Não foi possível enviar a imagem. Tente de novo.',
    retry: 'Tentar de novo',
    dismiss: 'Dispensar',
    icsError: 'Não foi possível baixar o arquivo do calendário.',
    editLabel: 'Editar etiqueta {name}',
  },
  labelDialog: {
    titleNew: 'Nova etiqueta',
    titleEdit: 'Editar etiqueta',
    name: 'Nome da etiqueta',
    save: 'Salvar etiqueta',
    cancel: 'Cancelar',
    delete: 'Excluir etiqueta',
    confirmTitle: 'Excluir esta etiqueta?',
    confirmBody: 'Os compromissos dela vão para "Pessoal".',
    confirmYes: 'Excluir',
    confirmNo: 'Manter',
    errorName: 'Dê um nome com 2 a 40 caracteres.',
    errorLimit: 'Você chegou ao limite de 20 etiquetas.',
    close: 'Fechar',
  },
  states: {
    emptyTitle: 'Seu calendário está vazio.',
    emptyBody: 'Comece pela próxima prova. Você recebe um aviso 1 dia antes e no dia.',
    emptyCta: 'Adicionar a primeira prova',
    loading: 'Carregando o calendário',
  },
} as const;
