/** F32 G25: opções e rótulos do desafio com IA no mapa. */
export const challengeAi = {
  open: 'Desafiar',
  modalTitle: 'Desafiar este mapa',
  scope: {
    card: 'Este card',
    module: 'Este módulo',
    board: 'O mapa inteiro',
  },
  format: {
    generated: 'A IA cria as perguntas',
    map: 'Perguntas do mapa, a IA corrige',
  },
  count: 'Quantidade',
  difficulty: {
    easy: 'Fácil',
    medium: 'Médio',
    hard: 'Difícil',
    mixed: 'Misto',
  },
  type: {
    discursive: 'Discursiva',
    objective: 'Objetiva (A a D)',
    mixed: 'Mista',
  },
  grading: {
    now: 'Corrigir na hora',
    end: 'Corrigir no final',
  },
  cost: 'Esta sessão usa {n} correções de IA',
  generatedLabel: 'Gerada por IA, no estilo ENAMED. Não é questão oficial.',
  confirmTopic: 'Confirmar tema',
  chooseTopic: 'Tema do ENAMED',
  topicNotInList: 'Escolha um tema da lista desta área.',
  topicSuggested: 'Tema sugerido: {name}',
  topicConfirmed: 'Tema confirmado: {name}',
  report: 'Reportar erro',
  disagree: 'Discordar',
  dontKnow: 'Não sei',
  bankTitle: 'Banco de questões',
  edit: 'Editar',
  saveEdit: 'Salvar pergunta',
  ungrounded: 'Esse número não está na pergunta original.',
  summaryButton: 'Resumo com IA',
  summarySize: {
    quick: 'Rápido',
    standard: 'Padrão',
    full: 'Completo',
  },
  summaryFocus: {
    overview: 'Visão geral',
    high_yield: 'O que costuma cair',
    exam_eve: 'Véspera de prova',
  },
  summaryDisclaimer: 'Gerado por IA a partir do seu mapa. Confira a fonte.',
  summaryStale: 'O mapa mudou desde este resumo. Gerar de novo',
  copy: 'Copiar',
  print: 'Imprimir',
  verdict: {
    correct: 'Correta',
    partial: 'Parcial',
    incorrect: 'Incorreta',
    pending: 'Pendente de correção',
  },
  aiCanErr: 'A IA pode errar. Confira a fonte no card.',
  headline: {
    correct: 'Acertou!',
    partial: 'Quase lá',
    incorrect: 'Não foi dessa vez',
  },
  next: 'Próxima pergunta',
  finish: 'Finalizar desafio',
  finishing: 'Calculando o resultado…',
  timer: {
    question: 'Nesta pergunta',
    total: 'No desafio',
  },
  duration: {
    sec: '{s} s',
    min: '{m} min {s} s',
    none: '—',
  },
  result: {
    title: 'Resultado do desafio',
    good: 'Mandou bem! Continue revisando para manter.',
    low: 'Abaixo de 70%: vale estudar os pontos que faltaram.',
    ring: '{percent}% de aproveitamento',
    of: 'de aproveitamento',
    correct: 'Acertos',
    partial: 'Parciais',
    incorrect: 'Erros',
    pending: 'Pendentes',
    totalTime: 'Tempo total',
    avgTime: 'Tempo médio por pergunta',
    perQuestion: 'Pergunta por pergunta',
    question: 'Pergunta {n}',
    adviceTitle: 'O que estudar agora',
    adviceAi: 'Sugestão gerada por IA a partir dos seus erros. Confira no card.',
    adviceCards: 'Cards deste mapa para revisar',
    adviceMaps: 'Mapas que podem ajudar',
    readyMap: 'Mapa pronto',
    backToMap: 'Voltar ao mapa',
  },
  done: 'Você respondeu todas as perguntas desta sessão.',
  score: '{correct} corretas · {partial} parciais · {incorrect} incorretas · {pending} pendentes',
  preset: {
    practice: 'Treino',
    mock: 'Simulado',
  },
} as const;
