/** F32 G25: opções e rótulos do desafio com IA no mapa. */
export const challengeAi = {
  open: 'Desafiar',
  modalTitle: 'Desafiar este mapa',
  scope: {
    card: 'Este card',
    module: 'Este módulo',
    branch: 'Este ramo',
    board: 'O mapa inteiro',
  },
  format: {
    generated: 'A IA cria as perguntas',
    map: 'Perguntas do mapa, a IA corrige',
  },
  count: 'Quantidade',
  difficulty: {
    easy: 'Fácil',
    medium: 'Médio',
    hard: 'Difícil',
    mixed: 'Misto',
  },
  type: {
    discursive: 'Discursiva',
    objective: 'Objetiva (A a D)',
    mixed: 'Mista',
  },
  grading: {
    now: 'Corrigir na hora',
    end: 'Corrigir no final',
  },
  cost: 'Esta sessão usa {n} correções de IA',
  generatedLabel: 'Gerada por IA, no estilo ENAMED. Não é questão oficial.',
  confirmTopic: 'Confirmar tema',
  chooseTopic: 'Tema do ENAMED',
  topicNotInList: 'Escolha um tema da lista desta área.',
  topicSuggested: 'Tema sugerido: {name}',
  topicConfirmed: 'Tema confirmado: {name}',
  report: 'Reportar erro',
  reportSent: 'Recebido. Um revisor vai analisar esta pergunta.',
  shortfall: 'Entregamos {got} de {asked} perguntas. As outras não ficaram fiéis ao mapa.',
  shortfallQuota: 'Entregamos {got} de {asked} perguntas. A cota de geração acabou.',
  shortfallError: 'Entregamos {got} de {asked} perguntas. A geração parou no meio.',
  disagree: 'Discordar',
  dontKnow: 'Não sei',
  bankTitle: 'Banco de questões',
  search: 'Buscar no enunciado',
  origin: 'Origem',
  source: {
    ai: 'IA',
    map: 'Mapa de origem',
    student: 'Minha',
  },
  filterArea: 'Área',
  filterDomain: 'Domínio',
  filterTopic: 'Tema',
  stats: '{correct} acertos · {incorrect} erros',
  edit: 'Editar',
  saveEdit: 'Salvar pergunta',
  ungrounded: 'Esse número não está na pergunta original.',
  rubric: {
    title: 'Rubrica automática',
    hint: 'A correção por IA usa estes pontos. Eles valem para o texto atual do card.',
    essential: 'Pontos essenciais',
    variants: 'Variações aceitas',
    critical: 'Erros críticos',
    lineHint: 'Um ponto por linha.',
    save: 'Salvar rubrica',
    saved: 'Rubrica salva.',
    approved: 'Rubrica aprovada. Ela não muda por aqui.',
    empty: 'Escreva ao menos um ponto essencial.',
    numbers: 'Esse número não está no card.',
    error: 'Não foi possível salvar a rubrica.',
    statusAuto: 'Automática',
    statusEdited: 'Editada por você',
  },
  summaryButton: 'Resumo com IA',
  summarySize: {
    quick: 'Rápido',
    standard: 'Padrão',
    full: 'Completo',
  },
  summaryFocus: {
    overview: 'Visão geral',
    high_yield: 'O que costuma cair',
    exam_eve: 'Véspera de prova',
  },
  summaryDisclaimer: 'Gerado por IA a partir do seu mapa. Confira a fonte.',
  summaryStale: 'O mapa mudou desde este resumo. Gerar de novo',
  copy: 'Copiar',
  print: 'Imprimir',
  verdict: {
    correct: 'Correta',
    partial: 'Parcial',
    incorrect: 'Incorreta',
    pending: 'Pendente de correção',
  },
  aiCanErr: 'A IA pode errar. Confira a fonte no card.',
  headline: {
    correct: 'Acertou!',
    partial: 'Quase lá',
    incorrect: 'Não foi dessa vez',
  },
  next: 'Próxima pergunta',
  finish: 'Finalizar desafio',
  finishing: 'Calculando o resultado…',
  timer: {
    question: 'Nesta pergunta',
    total: 'No desafio',
    off: 'Sem cronômetro',
    m5: '5 min',
    m10: '10 min',
    m20: '20 min',
    m30: '30 min',
    remaining: 'Tempo restante',
    up: 'O tempo deste desafio acabou.',
  },
  duration: {
    sec: '{s} s',
    min: '{m} min {s} s',
    none: '—',
  },
  result: {
    title: 'Resultado do desafio',
    good: 'Mandou bem! Continue revisando para manter.',
    low: 'Abaixo de 70%: vale estudar os pontos que faltaram.',
    ring: '{percent}% de aproveitamento',
    of: 'de aproveitamento',
    correct: 'Acertos',
    partial: 'Parciais',
    incorrect: 'Erros',
    pending: 'Pendentes',
    totalTime: 'Tempo total',
    avgTime: 'Tempo médio por pergunta',
    perQuestion: 'Pergunta por pergunta',
    groups: 'Por módulo e por tema',
    groupModule: 'Módulo',
    groupTopic: 'Tema do ENAMED',
    groupLine: '{label}: {correct} acertos, {partial} parciais, {incorrect} erros',
    retryMissed: 'Refazer só os que errei',
    retryError: 'Não foi possível refazer agora.',
    addToReview: 'Adicionar à revisão',
    addedToReview: '{n, plural, =0 {Esses cards já estavam na revisão.} one {1 card entrou na revisão de hoje.} other {# cards entraram na revisão de hoje.}}',
    reviewError: 'Não foi possível adicionar à revisão.',
    question: 'Pergunta {n}',
    adviceTitle: 'O que estudar agora',
    adviceAi: 'Sugestão gerada por IA a partir dos seus erros. Confira no card.',
    adviceCards: 'Cards deste mapa para revisar',
    adviceMaps: 'Mapas que podem ajudar',
    readyMap: 'Mapa pronto',
    backToMap: 'Voltar ao mapa',
  },
  done: 'Você respondeu todas as perguntas desta sessão.',
  score: '{correct} corretas · {partial} parciais · {incorrect} incorretas · {pending} pendentes',
  preset: {
    quick: 'Revisão rápida',
    practice: 'Treino',
    mock: 'Simulado',
  },
} as const;
