/** G14 C1 (D-603–D-609): opções do desafio, mínimo de cards, autoavaliação Acertei/Errei, tour do desafio e paleta global. */
export const challengeSetup = {
  minCards: {
    tooltip: 'Para desafiar um mapa ele precisa de pelo menos {min} cards (sem contar Conteúdo). Faltam {n}.',
    tooltipOne: 'Para desafiar um mapa ele precisa de pelo menos {min} cards (sem contar Conteúdo). Falta 1.',
    title: 'Ainda faltam cards para o desafio',
    body: 'Um mapa precisa de pelo menos {min} cards (Pergunta e Resposta, fluxograma, imagem ou caso) para ser desafiado. Faltam {n}.',
  },
  dialog: {
    title: 'Desafiar este mapa',
    description: 'Escolha como responder e em que ordem os cards aparecem.',
    format: 'Formato',
    self: { title: 'Eu respondo', description: 'Sem IA: você escreve, revela a resposta do card e marca se acertou ou errou.' },
    ai: { title: 'IA responde', description: 'A IA corrige a sua resposta com base no card e no mapa e sugere a nota.' },
    soon: 'Em breve',
    order: 'Como será a ordem de avaliação?',
    random: { title: 'Aleatório', description: 'Os cards vêm embaralhados.' },
    flow: { title: 'Seguindo o fluxo das setas', description: 'Começa pelos cards de origem e segue as conexões.' },
    start: 'Começar desafio',
    cancel: 'Cancelar',
  },
  answer: {
    voice: 'Voz',
    voiceSoonNote: 'Responder por voz chega em breve. Por enquanto, escreva a resposta.',
    revealHint: 'Escreva o que lembrar (opcional) e revele a resposta do card.',
    markLabel: 'Você acertou?',
    correct: 'Acertei',
    wrong: 'Errei',
    gradeHint: '{interval} · tecla {key}',
    shortcutsSelf: 'Atalhos: espaço revela · 1 errei · 2 acertei · Esc pula',
    shortcutsDaily: 'Atalhos: espaço revela · 1 a 4 notas · Esc pula',
    minCardsError: 'Este mapa ainda não tem cards suficientes para o desafio.',
  },
  tour: {
    title: 'Como funciona o desafio',
    stepOf: 'Passo {n} de {total}',
    steps: {
      format: { title: 'Escolha o formato', body: 'Em “Desafiar este mapa” você escolhe como responder e a ordem dos cards: aleatória ou seguindo as setas.' },
      answer: { title: 'Responda um card', body: 'O card fica em destaque no mapa. Escreva o que lembrar, sem olhar.' },
      reveal: { title: 'Revele e marque', body: 'Revele a resposta do card e diga com honestidade: acertei ou errei.' },
      glow: { title: 'Veja o mapa acender', body: 'Cada resposta atualiza a lembrança estimada: o mapa mostra o que está firme e o que pede revisão.' },
    },
    next: 'Próximo',
    back: 'Voltar',
    done: 'Entendi',
    replay: 'Como funciona o desafio',
    demo: { card: 'Sepse', answer: 'Disfunção orgânica…', correct: 'Acertei', wrong: 'Errei', self: 'Eu respondo', ai: 'IA responde' },
  },
  palette: {
    open: 'Buscar ou comandar',
    groups: { account: 'Conta' },
    progress: { label: 'Desempenho', hint: 'Seu progresso' },
    account: { label: 'Minha conta', hint: 'Perfil e plano' },
    tour: { label: 'Como funciona o desafio', hint: 'Rever o tutorial' },
  },
} as const;
