import { offline } from './offline';
import { nav } from './nav';
import { plan } from './plan';
import { support } from './support';
import { challengeSetup } from './challenge-setup';
import { challengeAi } from './challenge-ai';
import { mapState, challengeMode, editor, quiz, boundary } from './landing-shared';
import { calendarCore } from './calendar';
import { notifications } from './notifications';
import { referralShell, storeShell, adminShell, legalShell } from './shell';

export const ptBRCore = {
  referral: referralShell,
  store: storeShell,
  admin: adminShell,
  legal: legalShell,
  offline,
  nav,
  plan,
  support,
  challengeSetup,
  challengeAi,
  calendar: calendarCore,
  notifications,
  common: {
    appName: 'Remoa',
    appDescription: 'Mapa de estudo com revisão espaçada para medicina',
    loading: 'Carregando…',
    save: 'Salvar',
    cancel: 'Cancelar',
    close: 'Fechar',
    back: 'Voltar',
    retry: 'Tentar de novo',
    comingSoon: 'Em breve',
    notifications: 'Notificações',
  },
  vocab: {
    board: 'mapa',
    boards: 'mapas',
    card: 'card',
    cards: 'cards',
    edge: 'conexão',
    edges: 'conexões',
    reviewToday: 'Revisar hoje',
    challengeBoard: 'Desafiar este mapa',
    retrievability: 'Lembrança estimada',
  },
  revisar: {
    hoje: 'Revisar hoje',
  },
  review: {
    eyebrow: 'Revisar hoje',
    heroEyebrow: 'Fila do dia',
    heroTitle: '{n, plural, one {# conceito na fila} other {# conceitos na fila}}',
    estimate: 'Cerca de {min} min em {boards, plural, one {# mapa} other {# mapas}}. Dê uma nota ao fim de cada conceito.',
    share: '{board}: {n} de {total} na fila',
    headlineNone: 'Nada vence hoje',
    headlineOne: '1 conceito vence hoje',
    headlineMany: '{due} conceitos vencem hoje',
    headlineIn: '{head}, {n} em {board}',
    due: 'Vencem hoje',
    new: 'Novos',
    weak: 'Para acompanhar',
    start: 'Começar revisão',
    groupsLabel: 'Fila por mapa',
    unknownBoard: 'Mapa sem nome',
    savedOffline: 'Esta é a última fila salva neste aparelho. A correção por IA volta quando a rede voltar.',
    empty: { title: 'Nada para revisar hoje', body: 'Volte amanhã ou adicione conceitos a um mapa.', cta: 'Ir para Meus mapas' },
    badge: '{n, plural, one {# card na fila de hoje} other {# cards na fila de hoje}}',
  },
  mapState,
  grade: {
    again: 'Não lembrei',
    hard: 'Difícil',
    good: 'Bom',
    easy: 'Fácil',
  },
  challengeMode,
  rail: {
    home: 'Hoje',
    maps: 'Mapas',
    review: 'Revisar',
    enamed: 'Enamed',
    store: 'Loja',
    account: 'Minha conta',
  },
  library: {
    title: 'Meus mapas',
    summary: '{n, plural, one {# mapa} other {# mapas}} · {cards, plural, one {# card} other {# cards}} · {due, plural, =0 {sem vencimentos} one {# vence} other {# vencem}} hoje',
    searchPlaceholder: 'Buscar mapa',
    viewGrid: 'Ver em grade',
    viewList: 'Ver em lista',
    filterArea: 'Filtrar por área',
    newMapButton: 'Novo mapa',
    noMaps: 'Nenhum mapa encontrado',
    noMapsDesc: 'Tente outro nome ou outra área, ou comece um mapa novo.',
    cardMeta: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    eyebrow: 'Biblioteca',
    all: 'Todos',
    columns: { map: 'Mapa', area: 'Área', states: 'Estados', cards: 'Cards', today: 'Hoje', saved: 'Salvo' },
    saved: 'Salvo {time}',
    ago: {
      now: 'agora',
      minutes: 'há {n} min',
      hours: 'há {n} h',
      yesterday: 'ontem',
      days: 'há {n} dias',
      weeks: 'há {n, plural, one {# semana} other {# semanas}}',
    },
    dueToday: '{n, plural, =0 {Em dia} one {# vence hoje} other {# vencem hoje}}',
    stateLabel: 'Estados',
  },
  pages: {
    home: 'Remoa — Hoje',
    coverage: 'Remoa — Cobertura Enamed',
    pricing: 'Remoa — Planos',
    account: 'Remoa — Minha conta',
    library: 'Remoa — Meus mapas',
    progress: 'Remoa — Progresso',
    editorial: 'Remoa — Revisão editorial',
    newMap: 'Remoa — Novo mapa',
    editorTitle: 'Remoa — Editor do mapa {mapa}',
    challengeTitle: 'Remoa — Desafio dentro do mapa',
    logoLink: 'Remoa, ir para Hoje',
    navLabel: 'Principal',
  },
  shell: {
    nav: {
      label: 'Navegação principal',
      boards: 'Meus mapas',
      review: 'Revisar hoje',
      coverage: 'Cobertura Enamed',
      store: 'Loja de boards',
      account: 'Conta',
      progress: 'Progresso',
    },
    sidebar: {
      library: 'Biblioteca pessoal',
      dueToday: '{n, plural, one {# conceito vence hoje} other {# conceitos vencem hoje}}',
      dueTop: '{n} em {mapa}',
      dueNone: 'Nada vence hoje.',
      start: 'Começar',
      account: 'Minha conta',
      plan: 'Plano Free',
    },
    mobileMenu: {
      open: 'Abrir menu',
      title: 'Menu',
      description: 'Navegue pelo Remoa',
      account: 'Conta',
    },
    header: {
      breadcrumbRoot: 'Meus mapas',
      breadcrumbLabel: 'Você está em',
      savedAgo: 'Salvo há {tempo}',
      savedNow: 'Salvo agora',
      import: 'Importar',
      importTitle: 'Importar material',
      importBody: 'Crie um mapa a partir de um PDF ou de um arquivo do Anki.',
      themeLight: 'Tema claro',
      themeDark: 'Tema escuro',
      themeToggle: 'Alternar tema',
      openMenu: 'Abrir menu',
    },
  },
  auth: {
    signIn: {
      title: 'Entrar',
      subtitle: 'Continue de onde parou.',
      submit: 'Entrar',
      noAccount: 'Ainda não tem conta?',
      toSignUp: 'Criar conta',
    },
    signUp: {
      title: 'Criar conta',
      subtitle: 'Sua conta começa com {days} dias de Pro grátis. Sem cartão.',
      submit: 'Criar conta',
      hasAccount: 'Já tem conta?',
      toSignIn: 'Entrar',
    },
    email: 'E-mail',
    emailPlaceholder: 'voce@exemplo.com',
    password: 'Senha',
    // G08: login/cadastro v2
    brand: {
      tagline: 'Seu mapa de estudo, revisado no tempo certo.',
      sub: 'Cards conectados, revisão espaçada e desafios feitos do seu próprio mapa.',
    },
    showChars: 'Mostrar caracteres',
    emailInvalid: 'Informe um e-mail válido, como voce@exemplo.com.',
    passwordRequired: 'Informe sua senha.',
    passwordWeak: 'Use 8 ou mais caracteres, com letras e números.',
    forgot: {
      link: 'Esqueci minha senha',
      title: 'Recuperar senha',
      subtitle: 'Informe o e-mail da conta e enviaremos um link para criar uma nova senha.',
      submit: 'Enviar link',
      sentTitle: 'Verifique seu e-mail',
      sentBody: 'Se houver uma conta com este e-mail, enviamos um link para redefinir a senha. Ele vale por pouco tempo.',
      back: 'Voltar para entrar',
    },
    reset: {
      title: 'Nova senha',
      subtitle: 'Escolha uma senha nova para a sua conta.',
      submit: 'Salvar nova senha',
      invalidLink: 'Este link expirou ou já foi usado. Peça um novo.',
      newLink: 'Pedir novo link',
      saved: 'Senha atualizada.',
    },
    generalError: {
      unauthorized: 'E-mail ou senha incorretos.',
      conflict: 'Já existe uma conta com este e-mail. Tente entrar.',
    },
    steps: {
      label: 'Etapas do cadastro',
      done: 'concluído',
      account: 'Conta',
      about: 'Sobre você',
      confirm: 'Confirmação',
      next: 'Continuar',
      back: 'Voltar',
    },
    about: {
      title: 'Sobre você',
      subtitle: 'Nome e telefone são obrigatórios. O resto é opcional e você completa depois no perfil.',
      name: 'Como podemos te chamar?',
      nameInvalid: 'Use de 2 a 60 caracteres, só letras, espaço, hífen ou apóstrofo.',
      nameRequired: 'Informe o seu nome.',
    },
    review: {
      title: 'Confirme e crie sua conta',
      subtitle: 'Confira os dados antes de criar.',
      emailRow: 'E-mail',
      nameRow: 'Nome',
      sexRow: 'Sexo',
      phoneRow: 'Telefone',
      addressRow: 'Endereço',
      empty: 'Não informado',
      consent: 'Concordo com os {terms} e a {privacy}, e com o tratamento dos meus dados conforme a LGPD.',
      consentTerms: 'Termos de uso',
      consentPrivacy: 'Política de Privacidade',
      consentRequired: 'Para criar a conta, marque que você concorda com os termos e a política de privacidade.',
    },
    magicLink: 'Enviar link mágico',
    google: 'Entrar com Google',
    signOut: 'Sair',
    or: 'ou',
    confirm: {
      title: 'Confirme seu e-mail',
      body: 'Enviamos um link de confirmação para {email}. Abra-o para continuar; depois você escolhe como quer estudar.',
      bodyNoEmail: 'Informe o e-mail do cadastro e enviaremos um novo link de confirmação.',
      failedTitle: 'Não foi possível confirmar',
      failedBody: 'O link expirou, já foi usado ou foi aberto em outro navegador. Se você já confirmou, é só entrar; senão, peça um novo link.',
      resend: 'Reenviar e-mail',
      resent: 'Enviamos um novo link. Pode levar alguns minutos; olhe também o spam.',
      hint: 'O link vale por pouco tempo. Use o mais recente.',
      toSignIn: 'Ir para entrar',
    },
    linkSent: {
      title: 'Confira seu e-mail',
      body: 'Enviamos um link de acesso para {email}. Ele vale por poucos minutos.',
    },
  },
  errors: {
    unauthorized: 'Você precisa entrar para continuar.',
    forbidden: 'Você não tem acesso a isto.',
    not_found: 'Não encontramos o que você procura.',
    validation: 'Confira os campos e tente de novo.',
    quota_exceeded: 'Você chegou ao limite do seu plano.',
    rate_limited: 'Muitas tentativas. Espere um pouco e tente de novo.',
    conflict: 'Isto mudou em outro lugar. Atualize e tente de novo.',
    ai_unavailable: 'A IA está indisponível agora. Tente em instantes.',
    internal: 'Algo deu errado do nosso lado. Tente de novo.',
  },
  boundary,
  empty: {
    boards: {
      title: 'Seu primeiro mapa',
      body: 'Importe seu material, comece com um mapa pronto ou crie um em branco.',
      importPdf: 'Importar PDF',
      importAnki: 'Importar do Anki',
      template: 'Começar com um mapa pronto',
    },
    review: {
      title: 'Revisar hoje',
      body: 'Sua fila de revisão aparece aqui.',
    },
    coverage: {
      title: 'Cobertura Enamed',
      body: 'Ligue um mapa a um item da matriz do Enamed e veja aqui quanto do tema você já cobriu.',
    },
    store: {
      title: 'Loja',
      body: 'Em breve.',
    },
    account: {
      title: 'Conta',
      body: 'Seus dados e preferências ficam aqui.',
    },
    mobileReview: {
      title: 'Revisar hoje',
      body: 'Um desafio por vez, direto no celular.',
    },
    editorial: {
      title: 'Revisão editorial',
      body: 'Conteúdo aguardando revisão aparece aqui.',
    },
  },
  editor,
  palette: {
    placeholder: 'Buscar comando',
    notFound: 'Nada encontrado para essa busca.',
    closeLabel: 'Fechar busca',
    keyboardHint: '⌘K',
    // T5 (editor v2)
    esc: 'esc',
    groups: { create: 'Criar', map: 'Mapa', layers: 'Camadas', cards: 'Cards', goTo: 'Ir para' },
    newConcept: { label: 'Nova Pergunta e Resposta', hint: 'Frente e verso, entra no desafio' },
    newNote: { label: 'Novo Conteúdo', hint: 'Só informativo, fora do desafio' },
    newFlow: { label: 'Novo fluxograma de conduta', hint: 'Passos ordenados' },
    newImage: { label: 'Novo card de imagem', hint: 'Com máscaras de oclusão' },
    newCase: { label: 'Novo caso clínico', hint: 'Etapas do caso' },
    link: { label: 'Ligar dois cards', hint: 'Ferramenta de conexão' },
    organize: { label: 'Organizar o mapa', hint: 'Layout automático' },
    challenge: { label: 'Desafiar este mapa', hint: 'Começa pelos vencidos' },
    structure: { label: 'Mostrar estrutura', hint: 'Conexões' },
    recall: { label: 'Mostrar lembrança estimada', hint: 'Cores do FSRS' },
    coverage: { label: 'Mostrar cobertura da matriz', hint: 'Enamed' },
    card: 'Ir para o card',
    home: { label: 'Hoje', hint: 'Início' },
    maps: { label: 'Meus mapas', hint: 'Biblioteca' },
    newMap: { label: 'Novo mapa', hint: 'PDF, Anki ou mapa pronto' },
    review: { label: 'Revisar hoje', hint: 'Fila do dia' },
  },
  quiz,
  billing: {
    plan: { free: 'Free', pro: 'Pro', founder: 'Founder' },
    paywall: {
      title: 'Você chegou ao limite do Free',
      ai_quota: 'Você usou as {n} correções por IA de hoje. No Pro, são {pro} por dia.',
      boards: 'Você chegou ao limite de {n} mapas do Free. No Pro, os mapas são ilimitados.',
      cards: 'Você chegou ao limite de {n} cards do Free. No Pro, os cards são ilimitados.',
      pdf: 'Mapas gerados de PDF não vêm no Free. No Pro, são {n} por mês; no Founder, sem limite.',
      anki: '{n, plural, one {Você já usou a importação do Anki do Free} other {Você já usou as # importações do Anki do Free}}. No Pro, as importações são ilimitadas.',
      cta: 'Assinar o Pro',
      dismiss: 'Continuar no Free',
    },
    pricing: {
      title: 'Planos',
      subtitle: 'Comece no Free. Assine o Pro quando o seu estudo pedir mais espaço.',
      tableLabel: 'Comparação entre Free e Pro',
      feature: 'Recurso',
      price: 'Preço',
      boards: 'Mapas',
      cards: 'Cards',
      ai_grades: 'Correções por IA por dia',
      ai_generations: 'Geração de mapa por PDF por mês',
      anki: 'Import do Anki (cards)',
      newCards: 'Novos cards por dia',
      unlimited: 'Ilimitados',
      freePrice: 'R$ 0',
      periodLabel: 'Período de cobrança',
      monthly: 'Mensal',
      annual: 'Anual',
      perMonth: '{price}/mês',
      perYear: '{price}/ano',
      annualHint: 'Equivale a {price} por mês',
      methodLabel: 'Forma de pagamento',
      pix: 'Pix',
      card: 'Cartão',
      founder: 'Tenho o preço de fundador',
      cta: 'Assinar o Pro',
      ctaBusy: 'Abrindo o pagamento',
      alreadyPro: 'Você já está no Pro.',
      manage: 'Ver minha conta',
      error: 'Não conseguimos abrir o pagamento. Tente de novo.',
    },
    account: {
      title: 'Minha conta',
      planLabel: 'Plano',
      status: {
        active: 'Ativo',
        trialing: 'Em teste',
        past_due: 'Pagamento pendente',
        canceled: 'Cancelado',
        incomplete: 'Incompleto',
      },
      renewsAt: 'Próxima cobrança em {date}',
      cancelsAt: 'O Pro fica ativo até {date} e não renova sozinho.',
      grace: 'Não conseguimos cobrar a sua assinatura. O Pro continua ativo até {date}; atualize o pagamento para não perder o acesso.',
      usageTitle: 'Uso do plano',
      usageLine: '{used} de {limit}',
      usageUnlimited: '{used} (sem limite)',
      usageNotIncluded: 'Não incluso',
      daily: 'hoje',
      monthly: 'neste mês',
      total: 'no total',
      manage: 'Gerenciar pagamento',
      cancel: 'Cancelar assinatura',
      subscribe: 'Assinar o Pro',
      portalError: 'Não conseguimos abrir o portal de pagamento. Tente de novo.',
      loadError: 'Não foi possível carregar o seu plano.',
      checkoutOk: 'Assinatura ativada. Bem-vindo ao Pro.',
      portalOk: 'Pagamento atualizado.',
      dataTitle: 'Seus dados',
      dataBody: 'Você pode baixar tudo o que é seu ou excluir a conta.',
      export: 'Exportar meus dados',
      exportOk: 'Exportação baixada.',
      exportError: 'Não conseguimos exportar agora. Tente de novo.',
      delete: 'Excluir conta',
      deleteTitle: 'Excluir a conta?',
      deleteBody: 'Sua conta fica desativada agora e os dados são apagados de vez depois de 7 dias. Exporte antes se quiser guardar uma cópia.',
      deleteConfirm: 'Excluir minha conta',
      deleteCancel: 'Manter a conta',
      deleteError: 'Não conseguimos excluir a conta. Tente de novo.',
    },
  },
} as const;

