import { account } from './account';
import { offline } from './offline';
import { nav } from './nav';
import { plan } from './plan';
import { plans } from './plans';
import { reviewHub } from './review';
import { support } from './support';
import { f17 } from './f17';
import { onboarding, cardStudy } from './onboarding';
import { personal } from './personal';
import { challengeSetup } from './challenge-setup';
import { mapState, challengeMode, challenge, editor, canvas, quiz, boundary } from './landing-shared';
import { mapMobile } from './map-mobile';
import { calendar } from './calendar';
import { notifications } from './notifications';
import { referralShell, storeShell, adminShell, legalShell } from './shell';

export const ptBRCore = {
  referral: referralShell,
  store: storeShell,
  admin: adminShell,
  legal: legalShell,
  account,
  offline,
  nav,
  plan,
  plans,
  support,
  onboarding,
  cardStudy,
  personal,
  challengeSetup,
  mapMobile,
  calendar,
  notifications,
  // F17 — Importador Anki v2 (T1)
  ...f17,
  common: {
    appName: 'Remoa',
    appDescription: 'Mapa de estudo com revisão espaçada para medicina',
    loading: 'Carregando…',
    save: 'Salvar',
    cancel: 'Cancelar',
    close: 'Fechar',
    back: 'Voltar',
    retry: 'Tentar de novo',
    comingSoon: 'Em breve',
    notifications: 'Notificações',
  },
  vocab: {
    board: 'mapa',
    boards: 'mapas',
    card: 'card',
    cards: 'cards',
    edge: 'conexão',
    edges: 'conexões',
    reviewToday: 'Revisar hoje',
    challengeBoard: 'Desafiar este mapa',
    retrievability: 'Lembrança estimada',
  },
  revisar: {
    hoje: 'Revisar hoje',
  },
  review: {
    eyebrow: 'Revisar hoje',
    heroEyebrow: 'Fila do dia',
    heroTitle: '{n, plural, one {# conceito na fila} other {# conceitos na fila}}',
    estimate: 'Cerca de {min} min em {boards, plural, one {# mapa} other {# mapas}}. Dê uma nota ao fim de cada conceito.',
    share: '{board}: {n} de {total} na fila',
    headlineNone: 'Nada vence hoje',
    headlineOne: '1 conceito vence hoje',
    headlineMany: '{due} conceitos vencem hoje',
    headlineIn: '{head}, {n} em {board}',
    due: 'Vencem hoje',
    new: 'Novos',
    weak: 'Para acompanhar',
    start: 'Começar revisão',
    groupsLabel: 'Fila por mapa',
    unknownBoard: 'Mapa sem nome',
    savedOffline: 'Esta é a última fila salva neste aparelho. A correção por IA volta quando a rede voltar.',
    empty: { title: 'Nada para revisar hoje', body: 'Volte amanhã ou adicione conceitos a um mapa.', cta: 'Ir para Meus mapas' },
    badge: '{n, plural, one {# card na fila de hoje} other {# cards na fila de hoje}}',
    hub: reviewHub,
  },
  mapState,
  grade: {
    again: 'Não lembrei',
    hard: 'Difícil',
    good: 'Bom',
    easy: 'Fácil',
  },
  challengeMode,
  challenge,
  rail: {
    home: 'Hoje',
    maps: 'Mapas',
    review: 'Revisar',
    enamed: 'Enamed',
    store: 'Loja',
    account: 'Minha conta',
  },
  home: {
    greeting: 'Boa {periodo}. {n, plural, =0 {Nenhum conceito espera} one {# conceito espera} other {# conceitos esperam}} por você.',
    reviewSection: 'Revisão de hoje',
    reviewSummary: '{boards, plural, one {# mapa} other {# mapas}}, {n, plural, one {# conceito} other {# conceitos}} para fixar hoje.',
    queueStart: 'A fila começa por {card}, que vence hoje com lembrança estimada de {pct}%.',
    startReview: 'Começar revisão',
    reviewOnlyBoard: 'Só {board}',
    reviewOpenLabel: 'Abrir o mapa {mapa}',
    continueFrom: 'Continue de onde parou',
    seeAll: 'Ver todos os mapas',
    coverage: 'Cobertura da matriz do Enamed',
    coverageHint: 'Conteúdo mapeado, não peso de prova',
    weekTitle: 'Sua semana',
    weekStreak: '{n, plural, =0 {0 dias seguidos} one {# dia seguido} other {# dias seguidos}}',
    weekDays: { seg: 'Seg', ter: 'Ter', qua: 'Qua', qui: 'Qui', sex: 'Sex', sab: 'Sáb', dom: 'Dom' },
    done: 'Feitos',
    planned: 'Previstos',
    reviewedToday: '{n} de {total} revisados hoje',
    reviewedTitle: '{n} de {total}',
    reviewedCaption: 'revisados hoje',
    nextReviewsTitle: 'Próximas revisões',
    nextReviews: { today: 'Hoje', tomorrow: 'Amanhã', saturday: 'Sábado', sunday: 'Domingo' },
    startSomething: 'Comece algo novo',
    generatePdf: 'Gerar mapa de um PDF',
    generatePdfDesc: 'Rascunho por IA para revisar',
    importAnki: 'Importar do Anki',
    importAnkiDesc: 'Seu .apkg vira mapa',
    seedMap: 'Mapa pronto',
    seedMapDesc: 'Revisado por médico, com fonte',
    salutation: { morning: 'Bom dia', afternoon: 'Boa tarde', evening: 'Boa noite' },
    greetingDue: '{saudacao}. {n, plural, one {# conceito espera} other {# conceitos esperam}} por você.',
    greetingNone: '{saudacao}. Nada vence hoje.',
    greetingNoMaps: '{saudacao}. Seu primeiro mapa começa aqui.',
    reviewEmptyTitle: 'Nada para revisar hoje.',
    reviewEmptyBody: 'Quando um conceito vencer, ele entra aqui. Que tal abrir um mapa e conectar mais um card?',
    noMapsTitle: 'Crie o seu primeiro mapa.',
    noMapsBody: 'Cada card do mapa entra na revisão espaçada e a cobertura da matriz aparece aqui.',
    openMaps: 'Abrir meus mapas',
    coverageEmpty: 'Ligue um mapa a um item da matriz ao criar para ver a cobertura aqui.',
    weekBarLabel: '{dia}: {done} feitos, {planned} previstos',
    loadError: 'Não foi possível carregar o resumo de hoje.',
    slider: {
      title: 'Continue de onde parou',
      viewAll: 'Ver todos',
      prevArrow: 'Mapas anteriores',
      nextArrow: 'Próximos mapas',
      counter: '{from}–{to} de {total}',
      a11y: {
        containerMessage: 'Carrossel de mapas. Use as setas para navegar.',
        slideLabelMessage: '{{index}} de {{slidesLength}}',
      },
      newCard: {
        aria: 'Criar um novo mapa',
        title: 'Novo mapa',
        text: 'Comece do zero, de um PDF ou do seu Anki.',
        freeRemaining: 'Você ainda pode criar {n, plural, one {# mapa} other {# mapas}} no plano Free.',
      },
      lockedCard: {
        title: 'Limite do plano Free',
        text: 'O Free permite até {max} mapas. Faça upgrade para criar o próximo.',
        aria: 'Criar novo mapa (bloqueado no plano Free)',
      },
    },
  },
  library: {
    title: 'Meus mapas',
    summary: '{n, plural, one {# mapa} other {# mapas}} · {cards, plural, one {# card} other {# cards}} · {due, plural, =0 {sem vencimentos} one {# vence} other {# vencem}} hoje',
    searchPlaceholder: 'Buscar mapa',
    viewGrid: 'Ver em grade',
    viewList: 'Ver em lista',
    filterArea: 'Filtrar por área',
    newMapButton: 'Novo mapa',
    noMaps: 'Nenhum mapa encontrado',
    noMapsDesc: 'Tente outro nome ou outra área, ou comece um mapa novo.',
    cardMeta: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    eyebrow: 'Biblioteca',
    all: 'Todos',
    columns: { map: 'Mapa', area: 'Área', states: 'Estados', cards: 'Cards', today: 'Hoje', saved: 'Salvo' },
    saved: 'Salvo {time}',
    ago: {
      now: 'agora',
      minutes: 'há {n} min',
      hours: 'há {n} h',
      yesterday: 'ontem',
      days: 'há {n} dias',
      weeks: 'há {n, plural, one {# semana} other {# semanas}}',
    },
    dueToday: '{n, plural, =0 {Em dia} one {# vence hoje} other {# vencem hoje}}',
    stateLabel: 'Estados',
  },
  import: {
    heading: {
      sending: { title: 'Lendo o seu baralho', desc: 'Enviamos o arquivo e conferimos o que tem dentro.' },
      preview: { title: 'Confira o que vira o quê', desc: 'Veja como os baralhos e os campos do Anki viram mapa e cards. Você pode ajustar antes de importar.' },
      importing: { title: 'Importando o seu baralho', desc: 'Pode deixar esta tela aberta. Os cards aparecem no mapa quando terminar.' },
      done: { title: 'Baralho importado', desc: 'Veja o que entrou no mapa.' },
      error: { title: 'Não deu para importar', desc: 'Alguns cards podem ter sido criados. Importar o arquivo de novo não duplica o que já entrou.' },
    },
    subdecksNote: 'Os sub-baralhos viram colunas do mapa e a “Fonte” de cada card.',
    uploading: 'Enviando o arquivo… {pct}%',
    uploadingLabel: 'Progresso do envio',
    inspecting: 'Lendo o baralho…',
    errors: { upload: 'Não conseguimos enviar o arquivo. Confira a conexão e tente de novo.', failed: 'A importação falhou. Tente de novo.' },
    counts: { decks: '{n, plural, one {# baralho} other {# baralhos}}', cards: '{n, plural, one {# card do Anki} other {# cards do Anki}}', media: '{n, plural, one {# mídia} other {# mídias}}' },
    countsLabel: 'Resumo do arquivo',
    serverCounts: 'O número final conta notas e pode ser menor: duplicatas e notas vazias são ignoradas.',
    cap: 'Este arquivo tem {n} cards e o seu plano importa até {max} por vez. No plano gratuito, uma importação acima do limite é recusada. Assine o Pro para importar arquivos maiores.',
    capTitle: 'Acima do limite do plano',
    decks: { title: 'Baralhos', root: 'vira coluna do mapa', sub: 'vira coluna e “Fonte” do card', check: 'Importar o baralho {name}' },
    rules: 'Cada nota vira um card. Lacunas (cloze) viram conceitos com [...]. Oclusão de imagem vira card de imagem com máscaras. Todos os baralhos entram no mesmo mapa; se já existir um mapa com esse nome, você escolhe entre importar nele (duplicatas são ignoradas) ou criar outro.',
    noteTypes: { title: 'Tipos de nota', count: '{n, plural, one {# nota} other {# notas}}' },
    kind: { basic: 'Básico', cloze: 'Lacunas (cloze)', image_occlusion: 'Oclusão de imagem', other: 'Outro' },
    field: { cardType: 'Vira card do tipo', title: 'Título', front: 'Frente', back: 'Verso', deriveTitle: 'Derivar da frente', none: 'Nenhum' },
    cardType: { concept: 'Conceito', image: 'Imagem' },
    sample: { title: 'Amostra de {name}', colTitle: 'Título', colFront: 'Frente', colBack: 'Verso', empty: '—' },
    confirm: 'Importar {n, plural, one {# card} other {# cards}}',
    noDeck: 'Escolha ao menos um baralho.',
    back: 'Escolher outro arquivo',
    progress: 'Progresso da importação',
    progressText: '{processed} de {total} cards',
    report: {
      title: 'Relatório da importação',
      imported: 'Cards importados',
      skippedDuplicate: 'Ignorados por duplicata',
      skippedEmpty: 'Ignorados por estarem vazios',
      missingMedia: 'Cards com mídia faltando',
      duration: 'Tempo',
      seconds: '{s} s',
      open: 'Abrir o mapa',
      openN: 'Abrir o mapa {n}',
    },
  },
  newMap: {
    step: { one: 'Início', two: 'Detalhes', three: 'Material' },
    step1Title: 'Como você quer começar?',
    step1Desc: 'Você muda de ideia quando quiser. O mapa é seu e continua editável.',
    path: {
      pdf: 'Do meu PDF',
      pdfDesc: 'Resumo, apostila ou capítulo. A IA monta um rascunho do mapa para você revisar.',
      pdfTag: 'Rascunho por IA',
      anki: 'Do meu Anki',
      ankiDesc: 'Importe o arquivo .apkg: os cards viram conceitos e a oclusão de imagem vem junto.',
      ankiTag: 'Importação',
      seed: 'De um mapa pronto',
      seedDesc: 'Mapas revisados por médico, com fonte, versão e marco temporal da edição.',
      seedTag: 'Revisado',
      blank: 'Em branco',
      blankDesc: 'Comece do zero e monte do seu jeito, card por card.',
      blankTag: 'Livre',
    },
    step2Title: 'Sobre o que é este mapa?',
    step2Desc: 'A área e o item da matriz do Enamed organizam a cobertura e sugerem o nome.',
    areaLabel: 'Grande área',
    itemLabel: 'Item da matriz',
    nameLabel: 'Nome do mapa',
    step3Title: {
      pdf: 'Envie o seu material',
      anki: 'Envie o seu arquivo',
      seed: 'Escolha o mapa pronto',
      blank: 'Tudo pronto para criar',
    },
    step3Desc: {
      pdf: 'Aceitamos PDF de resumos e capítulos. O resultado é um rascunho que você revisa antes de estudar.',
      anki: 'Seus cards viram conceitos; a repetição espaçada começa do zero.',
      seed: 'Cada mapa vem com fontes, rubricas aprovadas e a edição do Enamed em que foi revisado.',
      blank: 'Confira os dados. Você poderá mudar tudo depois no editor.',
    },
    dropTitle: { pdf: 'Arraste seu PDF aqui', anki: 'Arraste seu arquivo .apkg aqui' },
    dropDesc: { pdf: 'ou escolha um arquivo do computador', anki: 'ou escolha o arquivo exportado do Anki' },
    cta: { pdf: 'Gerar rascunho do mapa', anki: 'Importar para o mapa', seed: 'Adicionar ao meu mapa', blank: 'Criar mapa' },
    generating: '{stage}… {n}%',
    generatingLabel: 'Progresso da geração do mapa',
    pdfUnreadable: 'Não foi possível ler este PDF. Envie um arquivo com texto selecionável.',
    aiNotConfigured: 'A geração de mapas por IA não está disponível neste ambiente. Crie o mapa em branco ou tente mais tarde.',
    pdfTooLarge: 'O PDF passa de 10 MB. Envie um arquivo menor ou divida o material.',
    pdfInvalid: 'Este arquivo não é um PDF. Escolha um arquivo .pdf.',
    generateTimeout: 'A geração passou de 10 minutos e foi interrompida. A cota foi devolvida.',
    stage: { ocr: 'Lendo o PDF', extract: 'Extraindo conceitos', layout: 'Organizando o mapa' },
    previewLabel: 'Prévia do seu mapa',
    limits: { notIncluded: 'não incluso', unlimited: 'sem limite', perMonth: '{n} por mês' },
    info: {
      howLabel: 'Como funciona',
      getsLabel: 'Você recebe',
      limitLabel: 'Limites',
      pdf: {
        title: 'Do PDF ao rascunho',
        lead: 'A IA lê o seu material e propõe um mapa. Você revisa antes de estudar.',
        s1: 'Você envia um resumo, apostila ou capítulo em PDF.',
        s2: 'A IA extrai conceitos, fluxogramas de conduta e as conexões entre eles.',
        s3: 'Tudo chega marcado como “rascunho não revisado”, para você conferir.',
        gets: 'Um mapa editável, com rubricas de correção sugeridas. Cada card leva a marca de rascunho até a sua revisão.',
        limit: 'Mapas gerados de PDF: {free} no Free, {pro} no Pro.',
        status: 'Em breve: a geração por IA ainda não está ativa.',
      },
      anki: {
        title: 'Do Anki para o mapa',
        lead: 'Importe o arquivo .apkg e seus cards viram um mapa que você liga e edita.',
        s1: 'No Anki, exporte o baralho como .apkg com “Support older Anki versions” marcado.',
        s2: 'Cada nota vira um card. O cloze mantém as lacunas; a oclusão de imagem vira card de imagem com máscaras.',
        s3: 'Você dá nome ao mapa, confere o resumo e importa. Os baralhos viram colunas.',
        gets: 'Um mapa só, com os baralhos como colunas e as imagens. O agendamento do Anki não é trazido: a repetição espaçada começa do zero.',
        limit: 'Free: {freeImports, plural, one {# importação} other {# importações}} de até {free} cards. Pro: {pro}. As tags do Anki não entram.',
        status: 'Disponível agora.',
      },
      seed: {
        title: 'Mapas prontos e revisados',
        lead: 'Mapas montados e revisados por médico, com fonte e marco temporal.',
        s1: 'Cada card traz a fonte, a edição e o nome e CRM de quem revisou.',
        s2: 'Você escolhe um mapa e o adiciona à sua biblioteca.',
        s3: 'Depois, liga o que já sabe e estuda com a revisão espaçada.',
        gets: 'Conteúdo aprovado por médico revisor. Nada gerado por IA é publicado sem essa revisão.',
        limit: 'Os limites serão definidos junto com a primeira edição.',
        status: 'A lista mostra a edição já publicada pela revisão editorial.',
      },
      blank: {
        title: 'Comece do zero',
        lead: 'Um mapa vazio e você no comando, card por card.',
        s1: 'Dê um nome ao mapa e escolha o item da matriz do Enamed.',
        s2: 'Adicione o primeiro card e escreva o que você já sabe.',
        s3: 'Ligue os cards com rótulos como “causa”, “leva a” e “trata com”.',
        gets: 'Um card central, pronto para você ligar ao resto do que sabe. Nada é gerado por IA.',
        limit: 'Free: {boards} mapas e {cards} cards. Pro: sem limite.',
        status: 'Disponível agora.',
      },
    },
    stepsLabel: 'Passos',
    stepDone: 'concluído',
    areaSoon: 'Em breve',
    noItems: 'Nenhum item da matriz disponível para esta área.',
    seedSoon: 'Os mapas prontos aparecem aqui quando a revisão editorial publicar a primeira edição.',
    replaceFile: 'Trocar',
    fileMeta: '{mb} MB',
    opts: {
      pdf: { flows: 'Gerar fluxogramas de conduta quando houver algoritmo no texto', rubrics: 'Gerar rubricas de correção para cada card' },
      anki: { tags: 'Transformar tags do Anki em seções do mapa', images: 'Trazer imagens e máscaras de oclusão' },
    },
    previewSub: {
      pdf: 'Rascunho por IA a partir do seu PDF',
      anki: 'Importado do seu arquivo do Anki',
      seed: 'Mapa pronto, revisado por médico',
      blank: 'Mapa em branco',
    },
    sat: {
      concept: 'Conceito',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso clínico',
      ankiCard: 'Card do Anki',
      definition: 'Definição',
      conduct: 'Conduta',
      criteria: 'Critérios',
      case1: 'Caso 1',
      figure: 'Figura',
      treatment: 'Tratamento',
      occlusion: 'Oclusão',
      diagnosis: 'Diagnóstico',
      exams: 'Exames',
    },
    closeLabel: 'Cancelar e voltar',
    filePickerLabel: 'Escolher arquivo',
    seedsLabel: 'Mapas prontos',
    backButton: 'Voltar',
    continueButton: 'Continuar',
  },
  pages: {
    home: 'Remoa — Hoje',
    coverage: 'Remoa — Cobertura Enamed',
    pricing: 'Remoa — Planos',
    account: 'Remoa — Minha conta',
    library: 'Remoa — Meus mapas',
    progress: 'Remoa — Progresso',
    editorial: 'Remoa — Revisão editorial',
    newMap: 'Remoa — Novo mapa',
    editorTitle: 'Remoa — Editor do mapa {mapa}',
    challengeTitle: 'Remoa — Desafio dentro do mapa',
    logoLink: 'Remoa, ir para Hoje',
    navLabel: 'Principal',
  },
  progress: {
    title: 'Progresso',
    retention7: 'Retenção em 7 dias',
    retention30: 'Retenção em 30 dias',
    streak: 'Dias seguidos',
    none: 'Sem tentativas neste período',
    chart: 'Revisões por dia',
    dayCount: '{date}: {n} revisões',
    weak: 'Cards fracos',
    weakHint: 'Lembrança estimada abaixo de 70%',
    weakEmpty: 'Nenhum card com lembrança abaixo de 70%.',
    accuracyEmpty: 'Sem tentativas neste período.',
    review: 'Revisar',
    accuracy: 'Acurácia',
    topic: 'Tópico da matriz',
    area: 'Clínica Médica',
    export: 'Exportar histórico',
    loadError: 'Não foi possível carregar o progresso.',
  },
  editorial: {
    title: 'Revisão editorial',
    empty: 'Nenhum card na fila.',
    queueWaiting: '{shown} de {total} na fila',
    forbidden: 'Esta área é só para revisores.',
    approve: 'Aprovar',
    request: 'Pedir ajuste',
    reject: 'Rejeitar',
    note: 'Nota',
    metrics: 'Concordância do corretor',
    metricsCounts: '{overridden} notas alteradas em {submitted} correções',
    metricsError: 'Não foi possível carregar a concordância.',
    seeds: 'Mapas prontos',
    copy: 'Adicionar aos meus mapas',
    publish: 'Publicar versão',
    publishBlocked: 'Ainda há cards em rascunho. Aprove a fila antes de publicar.',
    changelog: 'O que mudou nesta edição',
    temporalMark: 'Marco temporal',
    publishMark: 'Informe o marco temporal da edição.',
    editOnComputer: 'Editar no computador',
    filterAll: 'Todos',
    filterDraft: 'Rascunho',
    filterAi: 'Sinal da IA',
    filterDisagree: 'Discordância',
    filterMap: 'Mapa',
    source: 'Fonte: {fonte}',
    studentAnswer: 'Resposta do aluno',
    noAnswer: 'Sem texto de resposta.',
    verdict: 'Veredito',
    noVerdict: 'Sem veredito.',
    critical: 'Erro crítico',
    verdictName: { correct: 'Correto', partial: 'Parcial', incorrect: 'Incorreto' },
    rubricCorrect: 'Rubrica estava certa',
    rubricAdjust: 'Ajustar rubrica',
    point: 'Ponto {n} da rubrica',
    crm: 'CRM',
    crmSave: 'Salvar CRM',
    crmSaved: 'CRM salvo. As próximas aprovações levam esse registro.',
    ownCard: 'Outro revisor precisa aprovar este card. Você criou o mapa.',
    before: 'Versão anterior',
    diffOut: 'Saiu: {text}',
    diffIn: 'Entrou: {text}',
    diffSame: 'A rubrica está igual à versão anterior.',
    crmPlaceholder: '123456-SP',
    onlyReviewer: 'Só o revisor médico assina.',
    crmRequired: 'Informe seu CRM para assinar decisões.',
    crmRequiredLink: 'Informar CRM',
    crmFormat: 'Formato do CRM: número e UF, como 123456-SP.',
    stateChanged: 'Este item já foi decidido ou mudou. A fila foi atualizada.',
    publishPending: 'Ainda há {n, plural, one {# card} other {# cards}} em rascunho. Aprove a fila antes de publicar.',
    provenance: 'Revisado por {name}, CRM {crm}, em {date}',
  },
  shell: {
    nav: {
      label: 'Navegação principal',
      boards: 'Meus mapas',
      review: 'Revisar hoje',
      coverage: 'Cobertura Enamed',
      store: 'Loja de boards',
      account: 'Conta',
      progress: 'Progresso',
    },
    sidebar: {
      library: 'Biblioteca pessoal',
      dueToday: '{n, plural, one {# conceito vence hoje} other {# conceitos vencem hoje}}',
      dueTop: '{n} em {mapa}',
      dueNone: 'Nada vence hoje.',
      start: 'Começar',
      account: 'Minha conta',
      plan: 'Plano Free',
    },
    mobileMenu: {
      open: 'Abrir menu',
      title: 'Menu',
      description: 'Navegue pelo Remoa',
      account: 'Conta',
    },
    header: {
      breadcrumbRoot: 'Meus mapas',
      breadcrumbLabel: 'Você está em',
      savedAgo: 'Salvo há {tempo}',
      savedNow: 'Salvo agora',
      import: 'Importar',
      importTitle: 'Importar material',
      importBody: 'A importação de PDF e de decks do Anki chega em breve.',
      themeLight: 'Tema claro',
      themeDark: 'Tema escuro',
      themeToggle: 'Alternar tema',
      openMenu: 'Abrir menu',
    },
  },
  devEmails: {
    title: 'Prévia de e-mails',
    templates: 'Modelos',
    width: 'Largura da prévia',
    desktop: '600 px',
    mobile: '360 px',
    view: 'Formato',
    html: 'HTML',
    text: 'Texto simples',
    subject: 'Assunto',
    preheader: 'Pré-cabeçalho',
    class: 'Classe',
    size: 'Tamanho',
    frame: 'Prévia do e-mail',
    loading: 'Carregando...',
    error: 'Não foi possível carregar a prévia. A API está no ar?',
    kb: '{kb} KB',
    classes: { transactional: 'Transacional', reminder: 'Lembrete', list: 'Lista' },
  },
  auth: {
    signIn: {
      title: 'Entrar',
      subtitle: 'Continue de onde parou.',
      submit: 'Entrar',
      noAccount: 'Ainda não tem conta?',
      toSignUp: 'Criar conta',
    },
    signUp: {
      title: 'Criar conta',
      subtitle: 'Seu mapa de estudo começa aqui.',
      submit: 'Criar conta',
      hasAccount: 'Já tem conta?',
      toSignIn: 'Entrar',
    },
    email: 'E-mail',
    emailPlaceholder: 'voce@exemplo.com',
    password: 'Senha',
    // G08: login/cadastro v2
    brand: {
      tagline: 'Seu mapa de estudo, revisado no tempo certo.',
      sub: 'Cards conectados, revisão espaçada e desafios feitos do seu próprio mapa.',
    },
    showChars: 'Mostrar caracteres',
    emailInvalid: 'Informe um e-mail válido, como voce@exemplo.com.',
    passwordRequired: 'Informe sua senha.',
    passwordWeak: 'Use 8 ou mais caracteres, com letras e números.',
    forgot: {
      link: 'Esqueci minha senha',
      title: 'Recuperar senha',
      subtitle: 'Informe o e-mail da conta e enviaremos um link para criar uma nova senha.',
      submit: 'Enviar link',
      sentTitle: 'Verifique seu e-mail',
      sentBody: 'Se houver uma conta com este e-mail, enviamos um link para redefinir a senha. Ele vale por pouco tempo.',
      back: 'Voltar para entrar',
    },
    reset: {
      title: 'Nova senha',
      subtitle: 'Escolha uma senha nova para a sua conta.',
      submit: 'Salvar nova senha',
      invalidLink: 'Este link expirou ou já foi usado. Peça um novo.',
      newLink: 'Pedir novo link',
      saved: 'Senha atualizada.',
    },
    generalError: {
      unauthorized: 'E-mail ou senha incorretos.',
      conflict: 'Já existe uma conta com este e-mail. Tente entrar.',
    },
    steps: {
      label: 'Etapas do cadastro',
      done: 'concluído',
      account: 'Conta',
      about: 'Sobre você',
      confirm: 'Confirmação',
      next: 'Continuar',
      back: 'Voltar',
    },
    about: {
      title: 'Sobre você',
      subtitle: 'Nome e telefone são obrigatórios. O resto é opcional e você completa depois no perfil.',
      name: 'Como podemos te chamar?',
      nameInvalid: 'Use de 2 a 60 caracteres, só letras, espaço, hífen ou apóstrofo.',
      nameRequired: 'Informe o seu nome.',
    },
    review: {
      title: 'Confirme e crie sua conta',
      subtitle: 'Confira os dados antes de criar.',
      emailRow: 'E-mail',
      nameRow: 'Nome',
      sexRow: 'Sexo',
      phoneRow: 'Telefone',
      addressRow: 'Endereço',
      empty: 'Não informado',
      consent: 'Concordo com os {terms} e a {privacy}, e com o tratamento dos meus dados conforme a LGPD.',
      consentTerms: 'Termos de uso',
      consentPrivacy: 'Política de Privacidade',
      consentRequired: 'Para criar a conta, marque que você concorda com os termos e a política de privacidade.',
    },
    magicLink: 'Enviar link mágico',
    google: 'Entrar com Google',
    signOut: 'Sair',
    or: 'ou',
    confirm: {
      title: 'Confirme seu e-mail',
      body: 'Enviamos um link de confirmação para {email}. Abra-o para continuar; depois você escolhe como quer estudar.',
      bodyNoEmail: 'Informe o e-mail do cadastro e enviaremos um novo link de confirmação.',
      failedTitle: 'Não foi possível confirmar',
      failedBody: 'O link expirou, já foi usado ou foi aberto em outro navegador. Se você já confirmou, é só entrar; senão, peça um novo link.',
      resend: 'Reenviar e-mail',
      resent: 'Enviamos um novo link. Pode levar alguns minutos; olhe também o spam.',
      hint: 'O link vale por pouco tempo. Use o mais recente.',
      toSignIn: 'Ir para entrar',
    },
    linkSent: {
      title: 'Confira seu e-mail',
      body: 'Enviamos um link de acesso para {email}. Ele vale por poucos minutos.',
    },
  },
  errors: {
    unauthorized: 'Você precisa entrar para continuar.',
    forbidden: 'Você não tem acesso a isto.',
    not_found: 'Não encontramos o que você procura.',
    validation: 'Confira os campos e tente de novo.',
    quota_exceeded: 'Você chegou ao limite do seu plano.',
    rate_limited: 'Muitas tentativas. Espere um pouco e tente de novo.',
    conflict: 'Isto mudou em outro lugar. Atualize e tente de novo.',
    ai_unavailable: 'A IA está indisponível agora. Tente em instantes.',
    internal: 'Algo deu errado do nosso lado. Tente de novo.',
  },
  boundary,
  empty: {
    boards: {
      title: 'Seu primeiro mapa',
      body: 'Importe seu material, comece com um mapa pronto ou crie um em branco.',
      importPdf: 'Importar PDF',
      importAnki: 'Importar do Anki',
      template: 'Começar com um mapa pronto',
    },
    review: {
      title: 'Revisar hoje',
      body: 'Sua fila de revisão aparece aqui.',
    },
    coverage: {
      title: 'Cobertura Enamed',
      body: 'Ligue um mapa a um item da matriz do Enamed e veja aqui quanto do tema você já cobriu.',
    },
    store: {
      title: 'Loja',
      body: 'Em breve.',
    },
    account: {
      title: 'Conta',
      body: 'Seus dados e preferências ficam aqui.',
    },
    mobileReview: {
      title: 'Revisar hoje',
      body: 'Um desafio por vez, direto no celular.',
    },
    editorial: {
      title: 'Revisão editorial',
      body: 'Conteúdo aguardando revisão aparece aqui.',
    },
  },
  boards: {
    title: 'Meus mapas',
    new: 'Novo mapa',
    create: 'Criar mapa',
    titleLabel: 'Nome do mapa',
    titlePlaceholder: 'Ex.: Sepse',
    counts: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    stateBarLabel: '{review} para revisitar, {watch} a acompanhar, {steady} mais estáveis, {unknown} sem revisões',
    menu: 'Mais ações de {title}',
    today: {
      label: 'Hoje',
      due: '{n, plural, one {# conceito vence} other {# conceitos vencem}} hoje · {m} em {title}',
      none: 'Nada vence hoje. Que tal criar um mapa?',
      start: 'Começar',
    },
    soon: { title: 'Em breve', body: 'A importação chega nas próximas versões. Por enquanto, crie um mapa e adicione seus cards.' },
    open: 'Abrir {title}',
    rename: 'Renomear',
    renameTitle: 'Renomear mapa',
    duplicate: 'Duplicar',
    duplicateTitle: '{title} (cópia)',
    duplicated: 'Mapa duplicado',
    archive: 'Arquivar',
    archiveTitle: 'Arquivar “{title}”?',
    archiveBody: 'O mapa sai de Meus mapas. Cards e revisões continuam guardados.',
    archived: 'Mapa arquivado',
    unarchive: 'Desarquivar',
    unarchived: 'Mapa desarquivado',
    archivedBadge: 'Arquivado',
    delete: 'Excluir',
    deleteTitle: 'Excluir “{title}” para sempre?',
    deleteBody: 'Isso apaga o mapa, todos os cards e o histórico de revisão dele. Não dá para desfazer.',
    deleteConfirmLabel: 'Para confirmar, digite o nome do mapa',
    deleted: 'Mapa excluído',
    statusLabel: 'Mostrar mapas',
    statusActive: 'Ativos',
    statusArchived: 'Arquivados',
    statusAll: 'Todos',
    emptyArchived: 'Nenhum mapa arquivado',
    undo: 'Desfazer',
    sidebarLabel: 'Seus mapas',
    area: {
      CM: 'Clínica Médica',
      CIR: 'Cirurgia',
      GO: 'Ginecologia e Obstetrícia',
      PED: 'Pediatria',
      MP: 'Medicina Preventiva e Saúde Coletiva',
    },
  },
  coverage: {
    areaFilter: 'Grande área',
    summaryLabel: 'Resumo da cobertura',
    catalog: 'Cobertura do catálogo',
    catalogHint: 'Média sobre todos os itens da área; item sem mapa conta 0%',
    reviewToday: 'Revisar hoje',
    reviewTodayHint: '{n, plural, =0 {nenhum card vence} one {# card vence} other {# cards vencem}}',
    maps: 'Mapas',
    tableLabel: 'Cobertura por tópico',
    topic: 'Tópico',
    mapCount: 'Mapas',
    coverage: 'Cobertura',
    recall: 'Lembrança estimada',
    noRecall: '—',
    footer: 'Cobertura mede quanto do tópico você mapeou, não quanto você lembra. Lembrança estimada vem das suas revisões. Os tópicos são uma organização do Remoa, não uma lista oficial do INEP, e não indicam peso de prova.',
    loadError: 'Não foi possível carregar a cobertura.',
    explain: 'Cobertura é quantos cards você tem num tema dividido pela meta do tema. Temas sem mapa são lacunas: comece por eles.',
    gapsTitle: 'Lacunas',
    gapsCount: '{gaps} de {total} temas sem mapa',
    gapsNone: 'Todos os temas desta área já têm mapa. Veja abaixo onde falta aprofundar.',
    gapsListLabel: 'Temas sem mapa em {group}',
    gapsNoGroup: 'Outros temas',
    target: 'meta: {n, plural, one {# card} other {# cards}}',
    createMap: 'Criar mapa para este tema',
    createMapFor: 'Criar mapa para {topic}',
    linkExisting: 'Ligar um mapa que já tenho',
    linkExistingFor: 'Ligar um mapa que já tenho a {topic}',
    linkTitle: 'Ligar um mapa a {topic}',
    linkBody: 'Escolha um dos seus mapas ainda sem tema.',
    linkNone: 'Você não tem mapas sem tema. Crie um mapa para este tema.',
    linkPick: 'Ligar {map}',
    linkCards: '{n, plural, one {# card} other {# cards}}',
    linkDone: '{map} ligado a {topic}.',
    linkError: 'Não foi possível ligar o mapa. Tente de novo.',
    inProgressTitle: 'Em andamento',
    inProgressHint: 'Do tema menos coberto para o mais coberto.',
    openMap: 'Abrir mapa',
    openMapFor: 'Abrir mapa de {topic}',
    openMapMore: '+{n}',
    actions: 'Ações',
    loading: 'Carregando a cobertura',
    emptyIntro1: 'Você ainda não ligou nenhum mapa a um tema do Enamed.',
    emptyIntro2: 'Comece por um destes temas ou abra seus mapas e ligue um deles a um tema.',
    emptySuggestionsLabel: 'Temas para começar',
    myMaps: 'Meus mapas',
    heroLabel: 'Cobertura geral da área',
    heroRing: '{pct}% da matriz coberta',
    heroSub: '{covered} cobertos · {partial} em andamento · {gaps} sem mapa',
    stateGap: 'Sem mapa',
    statePartial: 'Em andamento',
    stateCovered: 'Coberto',
    nextTitle: 'Comece por aqui',
    nextHint: 'Os temas sem mapa com a maior meta de cards.',
    filterLabel: 'Filtrar por estado',
    filterAll: 'Todos',
    searchLabel: 'Buscar tema',
    searchPlaceholder: 'Buscar tema',
    groupsTitle: 'Temas por grupo',
    groupsHint: 'Do tema menos coberto ao mais coberto em cada grupo.',
    groupSummary: '{n, plural, one {# tema} other {# temas}} · {pct}% coberto',
    groupBar: 'Cobertura de {group}',
    topicBar: 'Cobertura de {topic}',
    recallInline: 'lembrança {pct}%',
    noResults: 'Nenhum tema encontrado com esse filtro.',
    clearFilters: 'Limpar filtros',
    noAreaItems: 'Esta área ainda não tem temas na matriz do Remoa.',
    groupsCount: '{n, plural, =0 {nenhum tema} one {# tema} other {# temas}} na lista',
  },
  editor,
  inspector: {
    essentialLabel: 'Essencial',
    reviewerLabel: 'Revisor',
    temporalLabel: 'Marco temporal',
    sourceLabel: 'Fonte',
    statusLabel: 'Status',
    status: { draft: 'Rascunho', approved: 'Aprovada' },
    aiDraft: 'Gerado por IA, não revisado',
    reviewerInfo: '{revisor} · CRM {crm}',
    reviewerSourceNote: 'Corrigido contra a rubrica do card, revisada por {revisor} · CRM {crm}. Fonte: {fonte}.',
    coverage: 'Cobertura de {pct, plural, one {# por cento} other {# por cento}}',
    version: 'Versão',
    reviewThis: 'Revisar este card',
    noRubricWarning: 'Este card ainda não tem rubrica. A correção por texto só funciona contra uma rubrica aprovada; sem ela, o desafio usa autoavaliação.',
    noHistory: 'Nenhuma tentativa ainda. O histórico aparece depois da primeira revisão.',
    // T5 (editor v2)
    tabs: { content: 'Conteúdo', rubric: 'Rubrica', origin: 'Origem', history: 'Histórico' },
    nextToday: 'próxima revisão: hoje',
    nextOn: 'próxima revisão: {data}',
    connections: 'Conexões · {n}',
    noConnections: 'Nenhuma conexão ainda.',
    unlabelled: 'sem rótulo',
    outgoing: 'Sai para',
    incoming: 'Chega de',
    optionalLabel: 'Opcional',
    rubricApproved: 'v{v} · usada na correção por IA',
    rubricDraft: 'v{v} · aguardando revisão editorial',
    editorialLabel: 'Revisão editorial',
    noSource: 'Você ainda não adicionou fonte',
    noMark: 'Sem marco (card privado)',
    changelog: 'O que mudou na edição {mark}',
    noEditorial: 'Sem revisão editorial',
    reviewerPending: 'Aprovado; nome e CRM do revisor indisponíveis',
    reviewerNamed: 'Revisado por {revisor}',
    noSummary: 'Sem resumo ainda.',
  },
  canvas,
  palette: {
    placeholder: 'Buscar comando',
    notFound: 'Nada encontrado para essa busca.',
    closeLabel: 'Fechar busca',
    keyboardHint: '⌘K',
    // T5 (editor v2)
    esc: 'esc',
    groups: { create: 'Criar', map: 'Mapa', layers: 'Camadas', cards: 'Cards', goTo: 'Ir para' },
    newConcept: { label: 'Nova Pergunta e Resposta', hint: 'Frente e verso, entra no desafio' },
    newNote: { label: 'Novo Conteúdo', hint: 'Só informativo, fora do desafio' },
    newFlow: { label: 'Novo fluxograma de conduta', hint: 'Passos ordenados' },
    newImage: { label: 'Novo card de imagem', hint: 'Com máscaras de oclusão' },
    newCase: { label: 'Novo caso clínico', hint: 'Etapas do caso' },
    link: { label: 'Ligar dois cards', hint: 'Ferramenta de conexão' },
    organize: { label: 'Organizar o mapa', hint: 'Layout automático' },
    challenge: { label: 'Desafiar este mapa', hint: 'Começa pelos vencidos' },
    structure: { label: 'Mostrar estrutura', hint: 'Conexões' },
    recall: { label: 'Mostrar lembrança estimada', hint: 'Cores do FSRS' },
    coverage: { label: 'Mostrar cobertura da matriz', hint: 'Enamed' },
    card: 'Ir para o card',
    home: { label: 'Hoje', hint: 'Início' },
    maps: { label: 'Meus mapas', hint: 'Biblioteca' },
    newMap: { label: 'Novo mapa', hint: 'PDF, Anki ou mapa pronto' },
    review: { label: 'Revisar hoje', hint: 'Fila do dia' },
  },
  quiz,
  map: {
    canvasLabel: 'Mapa {title}',
    hint: 'Clique em um conceito para abrir. Arraste para reorganizar o mapa.',
    listEmpty: 'Nenhum card com esse filtro.',
    stats: '{cards, plural, =0 {0 conceitos} one {# conceito} other {# conceitos}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    titleLabel: 'Nome do mapa',
    titleEdit: 'Renomear mapa',
    eyebrow: 'Seu mapa de {area}',
    attribution: 'React Flow',
    legend: 'Legenda dos estados',
    toolbar: {
      label: 'Ferramentas do mapa',
      concept: 'Card',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso',
      add: 'Adicionar {type}',
      organize: 'Organizar',
      heat: 'Lembrança estimada',
      mode: 'Modo do mapa',
      explore: 'Explorar',
      challenge: 'Desafio',
      move: 'Mover',
      connect: 'Conexão',
      addCard: 'Card',
    },
    cardType: {
      concept: 'Conceito',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso',
    },
    newCardTitle: {
      concept: 'Novo conceito',
      flow: 'Novo fluxograma',
      image: 'Nova imagem',
      case: 'Novo caso',
      note: 'Novo conteúdo',
    },
    card: {
      open: 'Abrir',
      openLabel: 'Abrir {title}',
      menu: 'Mais ações de {title}',
      delete: 'Excluir',
      drag: 'Arrastar {title}',
      label: '{type}: {title}',
    },
    edge: {
      labelPlaceholder: 'Rótulo da conexão',
      labelInput: 'Rótulo da conexão',
      editLabel: 'Editar rótulo: {label}',
      addLabel: 'Adicionar rótulo',
      noLabel: 'Sem rótulo não vira pergunta',
      empty: '+ rótulo',
    },
    zoom: {
      in: 'Aproximar',
      out: 'Afastar',
      fit: 'Ajustar à tela',
      minimap: 'Mini-mapa',
      controls: 'Controles de zoom',
      percent: '{n}%',
    },
    save: {
      saving: 'Salvando…',
      offline: 'Sem conexão, salvando depois',
      error: 'Não conseguimos salvar suas mudanças.',
    },
    delete: {
      title: 'Excluir os cards selecionados?',
      body: 'As conexões desses cards também saem. Você pode desfazer com Ctrl+Z.',
      confirm: 'Excluir',
    },
    limit: 'Este mapa chegou ao limite de {max} cards.',
    ago: {
      minutes: '{n} min',
      hours: '{n} h',
    },
    a11y: {
      node: 'Enter ou espaço seleciona o card. Delete exclui; Esc cancela.',
      nodeKeyboard: 'Enter ou espaço seleciona o card. Use as setas para mover; Delete exclui; Esc cancela.',
      moved: 'Card movido. Nova posição: x {x}, y {y}',
      edge: 'Enter ou espaço seleciona a conexão. Delete exclui; Esc cancela.',
      handle: 'Porta de conexão',
    },
    inspector: {
      label: 'Detalhes do card',
      empty: 'Selecione um card no mapa',
      shortcuts: 'Atalhos',
      addCard: 'Adicionar card',
      challenge: 'Desafiar',
      yourCard: 'Card do seu mapa',
      type: 'Tipo',
      summary: 'Resumo',
      noSummary: 'Sem resumo ainda.',
      nextReview: 'Próxima revisão: {data}',
      noReview: 'Ainda sem revisões',
      provenance: 'Origem e edição',
      source: 'Fonte',
      temporalMark: 'Marco temporal',
      reviewer: 'Revisor',
      none: '—',
      reviewThis: 'Revisar este conceito',
      viewSource: 'Ver fonte e versão',
      status: {
        draft: 'Rascunho',
        approved: 'Aprovado',
      },
    },
  },
  cards: {
    edit: 'Editar card',
    editorLabel: 'Editar {title}',
    loading: 'Carregando card…',
    loadError: 'Não conseguimos abrir este card.',
    saving: 'Salvando…',
    saved: 'Card salvo',
    shortcuts: 'Enter salva (Ctrl+Enter nos textos longos). Esc cancela.',
    fields: {
      title: 'Título',
      front: 'Pergunta ou dica (opcional)',
      // G06: Conteúdo (note)
      text: 'Texto',
      noteHint: 'Conteúdo é só informativo: não tem resposta, não entra no desafio nem na revisão.',
      back: 'Resposta',
      backHint: 'Aceita **negrito**, *itálico*, listas com - e [links](https://…).',
      preview: 'Prévia da resposta',
      source: 'Fonte (texto ou URL)',
      sourcePlaceholder: 'Ex.: Diretriz Surviving Sepsis 2021',
    },
    flow: {
      count: '{n, plural, one {# passo} other {# passos}}',
      stepsLabel: 'Passos',
      step: 'Passo {n}',
      note: 'Observação do passo {n} (opcional)',
      image: 'Imagem do passo {n} (opcional)',
      addImage: 'Adicionar imagem ao passo {n}',
      removeImage: 'Remover imagem do passo {n}',
      add: 'Adicionar passo',
      remove: 'Remover passo {n}',
      drag: 'Reordenar passo {n}',
      min: 'Um fluxograma tem pelo menos 2 passos.',
      max: 'Um fluxograma tem no máximo 12 passos.',
      dnd: {
        instructions: 'Para reordenar, pressione espaço ou Enter, use as setas e pressione espaço ou Enter de novo. Esc cancela.',
        start: 'Passo {n} pego.',
        over: 'Passo {n} sobre a posição {to}.',
        end: 'Passo {n} solto na posição {to}.',
        cancel: 'Reordenação cancelada.',
      },
    },
    case: {
      stagesLabel: 'Etapas do caso',
      stage: {
        presentation: 'Apresentação',
        workup: 'Exames',
        diagnosis: 'Diagnóstico',
        management: 'Conduta',
      },
      // G06: o que é cada etapa e o que muda ao preenchê-la (tooltip no nó, no painel e no editor)
      hint: {
        presentation: 'Apresentação: quem é o paciente e por que procurou atendimento (queixa, história, exame físico). Preenchida, abre o caso: no desafio, é o contexto mostrado antes das perguntas.',
        workup: 'Exames: o que pedir e o que veio (laboratório, imagem, escores). Preenchida, o desafio mostra as etapas anteriores e pergunta os exames.',
        diagnosis: 'Diagnóstico: a hipótese principal e o que a sustenta. Preenchida, o desafio mostra as etapas anteriores e pergunta o diagnóstico.',
        management: 'Conduta: o que fazer agora (tratamento, dose, destino). Preenchida, o desafio mostra as etapas anteriores e pergunta a conduta.',
      },
      hintLabel: 'O que é {stage}?',
      empty: 'Etapa vazia: fica fora do desafio.',
      image: 'Imagem da etapa {stage} (opcional)',
      addImage: 'Adicionar imagem à etapa {stage}',
      removeImage: 'Remover imagem da etapa {stage}',
    },
    image: {
      alt: 'Imagem do card {title}',
      pick: 'Escolher imagem',
      dropHint: 'Arraste, cole ou escolha uma imagem JPG, PNG ou WebP de até 100 MB.',
      replace: 'Trocar imagem',
      openMasks: 'Abrir editor de máscaras',
      license: 'Licença da imagem',
      licenses: {
        own: 'Própria',
        cc_by: 'Creative Commons (CC BY)',
        servier: 'Servier Medical Art',
        openstax: 'OpenStax',
      },
      attribution: 'Autoria / atribuição',
      uploading: 'Enviando imagem… {pct}%',
      uploadProgress: 'Progresso do envio',
      failed: 'O envio da imagem falhou.',
      tooBig: 'A imagem passa de 100 MB. Reduza e tente de novo.',
      badType: 'Formato não aceito. Use JPG, PNG ou WebP.',
      noLicense: 'Licença não escolhida: informe a autoria da imagem para essa licença.',
      masksOne: '1 máscara',
      masks: '{n} máscaras',
    },
    frontImage: {
      label: 'Imagem da pergunta (opcional)',
      hint: 'Aparece na frente do card e no desafio.',
      alt: 'Imagem da pergunta de {title}',
      remove: 'Remover imagem',
    },
    backImage: {
      label: 'Imagem da resposta (opcional)',
      hint: 'Aparece no verso do card, depois de "Ver resposta".',
      alt: 'Imagem da resposta de {title}',
      remove: 'Remover imagem da resposta',
    },
    shape: {
      label: 'Formato no mapa',
      rect: 'Retângulo',
      pill: 'Pílula',
      circle: 'Círculo',
      diamond: 'Losango',
      hexagon: 'Hexágono',
      imageHint: 'No mapa, a imagem da pergunta só aparece no formato Retângulo.',
      saving: 'Salvando formato…',
      saved: 'Formato salvo.',
      error: 'Não deu para salvar o formato. Voltamos ao anterior.',
    },
    mask: {
      editorTitle: 'Máscaras de {title}',
      editorDescription: 'Cubra as regiões que você quer ser cobrado. As máscaras ficam por cima da imagem, nunca gravadas nela.',
      tools: 'Ferramenta',
      tool: {
        select: 'Selecionar',
        rect: 'Retângulo',
        polygon: 'Polígono',
      },
      surface: 'Área de desenho das máscaras',
      item: 'Máscara: {label}',
      defaultLabel: 'Região {n}',
      label: 'Rótulo da máscara',
      delete: 'Excluir máscara',
      add: 'Adicionar máscara',
      count: '{n} de {max} máscaras',
      limit: 'Limite de {max} máscaras por imagem.',
      polygonHint: 'Clique para marcar os pontos. Feche clicando no primeiro ponto, com duplo clique ou Enter.',
      rectHint: 'Arraste sobre a imagem para cobrir uma região.',
      selectHint: 'Clique numa máscara para mover; arraste os pontos para redimensionar. Setas movem, Delete exclui.',
      noImage: 'Envie a imagem antes de desenhar máscaras.',
    },
    rubric: {
      title: 'Rubrica',
      essential: 'Essencial',
      source: 'Fonte: {source}',
      generate: 'Gerar rubrica',
    },
    errors: {
      title: 'Dê um título ao card.',
      stepText: 'Preencha o texto de todos os passos.',
      steps: 'Um fluxograma tem de 2 a 12 passos.',
      caseMin: 'Preencha pelo menos uma etapa do caso.',
      image: 'Envie uma imagem antes de salvar.',
      maskLabel: 'Toda máscara precisa de um rótulo.',
      tooLong: 'Algum campo passou do tamanho máximo.',
      notSynced: 'O card ainda não chegou ao servidor. Confira a conexão e tente de novo.',
      offline: 'Sem conexão. Tente de novo quando voltar.',
    },
  },
  billing: {
    plan: { free: 'Free', pro: 'Pro', founder: 'Founder' },
    paywall: {
      title: 'Você chegou ao limite do Free',
      ai_quota: 'Você usou as {n} correções por IA de hoje. No Pro, são {pro} por dia.',
      boards: 'Você chegou ao limite de {n} mapas do Free. No Pro, os mapas são ilimitados.',
      cards: 'Você chegou ao limite de {n} cards do Free. No Pro, os cards são ilimitados.',
      pdf: 'Mapas gerados de PDF não vêm no Free. No Pro, são {n} por mês; no Founder, sem limite.',
      anki: '{n, plural, one {Você já usou a importação do Anki do Free} other {Você já usou as # importações do Anki do Free}}. No Pro, as importações são ilimitadas.',
      cta: 'Assinar o Pro',
      dismiss: 'Continuar no Free',
    },
    pricing: {
      title: 'Planos',
      subtitle: 'Comece no Free. Assine o Pro quando o seu estudo pedir mais espaço.',
      tableLabel: 'Comparação entre Free e Pro',
      feature: 'Recurso',
      price: 'Preço',
      boards: 'Mapas',
      cards: 'Cards',
      ai_grades: 'Correções por IA por dia',
      ai_generations: 'Geração de mapa por PDF por mês',
      anki: 'Import do Anki (cards)',
      newCards: 'Novos cards por dia',
      unlimited: 'Ilimitados',
      freePrice: 'R$ 0',
      periodLabel: 'Período de cobrança',
      monthly: 'Mensal',
      annual: 'Anual',
      perMonth: '{price}/mês',
      perYear: '{price}/ano',
      annualHint: 'Equivale a {price} por mês',
      methodLabel: 'Forma de pagamento',
      pix: 'Pix',
      card: 'Cartão',
      founder: 'Tenho o preço de fundador',
      cta: 'Assinar o Pro',
      ctaBusy: 'Abrindo o pagamento',
      alreadyPro: 'Você já está no Pro.',
      manage: 'Ver minha conta',
      error: 'Não conseguimos abrir o pagamento. Tente de novo.',
    },
    account: {
      title: 'Minha conta',
      planLabel: 'Plano',
      status: {
        active: 'Ativo',
        trialing: 'Em teste',
        past_due: 'Pagamento pendente',
        canceled: 'Cancelado',
        incomplete: 'Incompleto',
      },
      renewsAt: 'Próxima cobrança em {date}',
      cancelsAt: 'O Pro fica ativo até {date} e não renova sozinho.',
      grace: 'Não conseguimos cobrar a sua assinatura. O Pro continua ativo até {date}; atualize o pagamento para não perder o acesso.',
      usageTitle: 'Uso do plano',
      usageLine: '{used} de {limit}',
      usageUnlimited: '{used} (sem limite)',
      usageNotIncluded: 'Não incluso',
      daily: 'hoje',
      monthly: 'neste mês',
      total: 'no total',
      manage: 'Gerenciar pagamento',
      cancel: 'Cancelar assinatura',
      subscribe: 'Assinar o Pro',
      portalError: 'Não conseguimos abrir o portal de pagamento. Tente de novo.',
      loadError: 'Não foi possível carregar o seu plano.',
      checkoutOk: 'Assinatura ativada. Bem-vindo ao Pro.',
      portalOk: 'Pagamento atualizado.',
      dataTitle: 'Seus dados',
      dataBody: 'Você pode baixar tudo o que é seu ou excluir a conta.',
      export: 'Exportar meus dados',
      exportOk: 'Exportação baixada.',
      exportError: 'Não conseguimos exportar agora. Tente de novo.',
      delete: 'Excluir conta',
      deleteTitle: 'Excluir a conta?',
      deleteBody: 'Sua conta fica desativada agora e os dados são apagados de vez depois de 7 dias. Exporte antes se quiser guardar uma cópia.',
      deleteConfirm: 'Excluir minha conta',
      deleteCancel: 'Manter a conta',
      deleteError: 'Não conseguimos excluir a conta. Tente de novo.',
    },
  },
} as const;

