// Namespaces used by the landing client bundle; split out of pt-BR.ts so `@remoa/strings/landing` ships only these (P-174).
export const mapState = {
  review: 'Revisitar',
  watch: 'Acompanhar',
  steady: 'Mais estável',
  unknown: 'Sem revisões',
} as const;

export const challengeMode = {
  hidden_card: 'Card oculto',
  edge: 'Conexão',
  next_step: 'Próximo passo',
  occlusion: 'Imagem',
  case: 'Caso',
} as const;

export const challenge = {
  progress: '{n} de {total}',
  progressLabel: 'Progresso da sessão',
  loading: 'Montando sua sessão…',
  loadError: 'Não conseguimos montar a sessão.',
  backToReview: 'Voltar para Revisar hoje',
  empty: { title: 'Nada para revisar agora', body: 'Volte mais tarde ou adicione conceitos ao mapa.' },
  stagesLabel: 'Etapas até aqui',
  edgeAsk: 'O que liga {from} a {to}?',
  imageAlt: 'Imagem com regiões cobertas',
  answerMode: 'Como responder',
  write: 'Escrever',
  options: 'Opções',
  optionsLabel: 'Alternativas',
  textLabel: 'Sua resposta',
  submitText: 'Corrigir resposta',
  grading: 'corrigindo…',
  submitOption: 'Confirmar alternativa',
  reveal: 'Revelar resposta',
  skip: 'Pular',
  skipLimit: 'Este item já foi pulado duas vezes. Responda para seguir.',
  skipError: 'Não conseguimos pular agora. Tente de novo.',
  noRubricBody: 'Este conceito ainda não tem rubrica aprovada. Revele a resposta e diga como foi.',
  ownRubric: 'Rubrica sua',
  answerError: 'Não conseguimos registrar a resposta. Tente de novo.',
  canonical: 'Resposta',
  yourAnswer: 'Sua resposta',
  gradeLocked: 'Nota travada em “Não lembrei”: a resposta tem um erro crítico (dose, droga ou conduta). Reveja a resposta acima.',
  fallbackNoRubric: 'Sem rubrica aprovada para corrigir: avalie você mesmo.',
  fallbackGraderError: 'A correção automática falhou. Compare com a resposta e avalie você mesmo.',
  fallbackQuota: 'Suas correções por IA de hoje acabaram. Compare com a resposta e avalie você mesmo.',
  quotaCta: 'Ver planos',
  rateError: 'Não conseguimos salvar a nota. Tente de novo.',
  disputed: 'Obrigado. Vamos revisar esta correção.',
  disputeError: 'Não conseguimos enviar. Tente de novo.',
  intervalDays: { zero: 'hoje', one: '1 dia', many: '{n} dias' },
  shortcuts: 'Atalhos: 1 a 4 notas · Enter corrige ou revela · Esc pula',
  verdict: {
    title: { correct: 'Acertou', partial: 'Quase lá', incorrect: 'Não foi dessa vez' },
    matched: 'Acertou',
    missing: 'Faltou',
  },
  summary: {
    title: 'Sessão concluída',
    correct: 'Acertos',
    wrong: 'Erros',
    duration: 'Tempo',
    minutes: '{n} min',
    toReview: 'Cards que pedem revisão',
    toReviewNone: 'Nenhum card pede revisão agora.',
    openBoard: 'Abrir no mapa',
    untitled: 'Card sem título',
    nextDue: 'Próximo vencimento',
    nextNone: 'Sem vencimentos agendados',
    more: 'Mais 5',
  },
} as const;

export const editor = {
  headerTitle: '{area} · {title}',
  savedLabel: 'Salvo há {time}',
  savedNow: 'Salvo agora',
  layers: 'Camadas',
  explore: 'Explorar',
  challenge: 'Desafio',
  commandPalette: 'Buscar ou comandar',
  progress: '{n} de {total}',
  addCardConcept: 'Adicionar Pergunta e Resposta',
  addCardNote: 'Adicionar Conteúdo',
  addCardFlow: 'Adicionar fluxograma',
  addCardImage: 'Adicionar imagem',
  addCardCase: 'Adicionar caso clínico',
  // G06
  resetSize: 'Restaurar tamanho padrão',
  searchLabel: 'Buscar card, comando ou mapa',
  closeAlert: 'Fechar aviso',
  closePanelLabel: 'Fechar painel do card',
  recordVoiceLabel: 'Gravar resposta por voz',
  panelLabel: 'Painel do mapa',
  backToLibrary: 'Voltar para Meus mapas',
  sections: 'Seções do card',
  // T5 (editor v2)
  saving: 'Salvando…',
  suggestLink: 'Ligar a {item}',
  linkError: 'Não foi possível ligar o mapa ao item.',
  coversHeader: 'cobre {pct}% de {item}',
  cardMenu: 'Mais ações de {title}',
  // G02
  moreActions: 'Mais ações do mapa',
} as const;

export const canvas = {
  layers: { structure: 'Estrutura', retrievability: 'Lembrança estimada', coverage: 'Cobertura' },
  layersLabel: 'Estados dos cards',
  legend: 'Legenda dos estados',
  legendLabel: 'Legenda dos estados',
  zoom: {
    in: 'Aumentar zoom',
    out: 'Diminuir zoom',
    fit: 'Ajustar à tela',
    percent: '{n}%',
    controls: 'Controles de zoom',
  },
  toolbar: {
    label: 'Ferramentas do mapa',
    concept: 'Card',
    flow: 'Fluxograma',
    image: 'Imagem',
    case: 'Caso',
    move: 'Mover o mapa',
    connect: 'Ligar dois cards',
    organize: 'Organizar o mapa',
    heat: 'Lembrança estimada',
    explore: 'Explorar',
    challenge: 'Desafio',
    select: 'Selecionar',
    hint: {
      select: 'Selecionar: clique num card para ver e editar; arraste para mover.',
      move: 'Mover o mapa: arraste o fundo para navegar sem mexer nos cards.',
      concept: 'Adicionar Pergunta e Resposta: cria um card para revisar com pergunta e resposta.',
      note: 'Adicionar Conteúdo: cria um card de anotação livre.',
      flow: 'Adicionar fluxograma: cria um card com passos ligados em sequência.',
      image: 'Adicionar imagem: cria um card com figura para oclusão.',
      case: 'Adicionar caso clínico: cria um card com as etapas de um caso.',
      connect: 'Ligar dois cards: arraste de um card para outro e dê um rótulo à conexão.',
      organize: 'Organizar o mapa: arruma os cards automaticamente.',
    },
  },
  // T5 (editor v2)
  fitShort: 'Ajustar',
  layerSwitch: { structure: 'Estrutura', recall: 'Lembrança', coverage: 'Cobertura' },
  nodeType: { concept: 'Pergunta e Resposta', flow: 'Fluxograma', image: 'Imagem', case: 'Caso clínico', note: 'Conteúdo' },
  selectCard: 'Selecionar {title}',
  footer: {
    recall: '{state} · {pct}%',
    due: '{text} · vence hoje',
    none: 'Sem revisões ainda',
    edges: '{n, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    coverage: 'Entra em {item}',
    noItem: 'Fora da matriz do Enamed',
  },
  edgeDialog: 'Rótulo da conexão',
  edgeDialogBody: 'Sem rótulo, a conexão não vira pergunta no desafio.',
  // G02
  flip: 'Ver resposta',
  unflip: 'Ver pergunta',
  backLoading: 'Carregando resposta…',
  backEmpty: 'Sem resposta ainda.',
  connectFrom: 'Agora clique no card de destino.',
  connectStart: 'Clique no card de origem.',
  // G06
  stepImageAlt: 'Imagem do passo {n} de {title}',
  stageImageAlt: 'Imagem da etapa {stage} de {title}',
  backImageAlt: 'Imagem da resposta de {title}',
} as const;

export const quiz = {
  exit: 'Sair do desafio',
  challengeBoard: 'Desafiar {n, plural, one {o # que vence} other {os # que vencem}} hoje',
  transcription: 'Só a transcrição fica salva. O áudio é descartado.',
  dispute: 'Discordo da correção',
  hiddenTitle: 'Conceito oculto',
  hiddenStep: 'Passo oculto: responda no painel',
  hiddenEdge: 'Qual conexão?',
  hiddenEdgeLabel: 'Rótulo da conexão oculto: responda no painel',
  ratingLabel: 'Como foi lembrar?',
  ratingLabelSuggested: 'Como foi lembrar? Sugestão: {grade}',
  verdictLabel: { correct: 'Correto', partial: 'Parcial', incorrect: 'Incorreto' },
  subject: { step: 'Passo', stage: 'Etapa', region: 'Região', card: 'Card' },
  chipState: '{subject} em {state}',
  summaryPanel: 'Resumo da sessão',
  speak: 'Falar',
  voiceRecord: 'Falar a resposta',
  // G06 (D-203): Web Speech transcription removed from the UI until F09
  voiceSoon: 'Em breve',
  voiceSoonNote: 'Responder falando ainda não está disponível. Por enquanto, escreva a resposta.',
} as const;

export const boundary = {
  title: 'Algo deu errado',
  body: 'Tivemos um problema ao abrir esta tela.',
  retry: 'Tentar de novo',
  home: 'Ir para Meus mapas',
  ref: 'Código do erro: {id}',
} as const;
