// G24 (pacote G21): copy das seções IA, ENAMED e Calendário. A lista de temas não é a fonte dos slides:
// o slider só mostra mapas publicados; o texto de cada tema casa pelo título.
export const landingExtras = {
  ia: {
    eyebrow: 'IA que estuda com você',
    title: 'Do PDF ao desafio, a IA trabalha com o seu mapa.',
    lead: 'Ela cria cards, perguntas e resumos a partir do que você estuda, corrige com justiça e sempre mostra a fonte.',
    leadPartial: 'Ela cria cards a partir do que você estuda e corrige com justiça, sempre mostrando a fonte.',
    leadSafe: 'A prévia mostra o caminho. O que já está no ar aparece nos cartões; o restante diz Em breve.',
    playerLabel: 'Animação em quatro passos: a IA cria cards a partir de um PDF, cria perguntas do mapa, corrige uma resposta escrita com suas palavras e gera um resumo do mapa.',
    preview: 'Prévia',
    windowTitle: 'Remoa · Sepse e choque séptico',
    soon: 'Em breve',
    pro: 'Disponível no Pro',
    proCta: 'PDF disponível no Pro',
    warning: 'A IA pode errar. Por isso cada card mostra a origem e você sempre confere a fonte. Não envie dados de pacientes.',
    steps: [
      { title: 'Envie o PDF', text: 'A IA lê o texto e cria os cards, cada um com a página de origem.' },
      { title: 'A IA cria perguntas', text: 'Discursivas ou de A a D, no estilo ENAMED, salvas por assunto.' },
      { title: 'Você responde, a IA corrige', text: 'O que vale é o sentido e estar certo, não o texto igual. A nota é da IA.' },
      { title: 'Resumo do mapa', text: 'Um resumo para estudar, e cada ponto aponta para o card.' },
    ],
    legends: [
      'Envie o PDF e a IA cria os cards, com a página de origem.',
      'A IA cria perguntas do seu mapa e guarda por assunto.',
      'Você responde com suas palavras. A IA corrige o sentido.',
      'Um resumo do mapa, com a origem de cada ponto.',
    ],
    cards: {
      pdf: {
        title: 'PDF vira cards',
        body: 'Envie o PDF da aula. A IA cria os cards e anota a página de origem de cada um. Você revisa antes de estudar.',
        soonBody: 'Enviar um PDF para virar cards ainda não está no ar.',
      },
      gerar: {
        title: 'A IA cria as perguntas',
        body: 'Perguntas abertas ou de A a D, no estilo ENAMED, feitas a partir do seu mapa e guardadas por assunto.',
        soonBody: 'A criação de perguntas pela IA ainda não está no ar.',
      },
      corrigir: {
        title: 'Correção que entende você',
        body: 'Escreva com suas palavras. A IA confere se o sentido está certo. A nota é dela, e ela pode errar.',
        soonBody: 'A correção por IA ainda não está no ar.',
      },
      resumo: {
        title: 'Resumo do mapa',
        body: 'Um resumo para estudar, com a origem de cada ponto. Se o mapa mudar, ele avisa que ficou desatualizado.',
        soonBody: 'O resumo do mapa ainda não está no ar.',
      },
    },
    play: {
      pdf: 'PDF',
      file: 'aula-sepse.pdf',
      reading: 'Lendo o PDF…',
      created: '12 cards criados',
      cards: [
        { title: 'Definição de sepse', source: 'Fonte: página 3', text: 'Disfunção orgânica causada por resposta desregulada à infecção.' },
        { title: 'Triagem', source: 'Fonte: página 5', text: 'Ferramentas de triagem e o papel do qSOFA.' },
        { title: 'Primeira hora', source: 'Fonte: página 8', text: 'Sequência de condutas nas primeiras horas.' },
      ],
      chips: ['10 perguntas', 'Nível médio', 'Objetiva A a D', 'Estilo ENAMED'],
      question: 'Adulto com foco urinário provável e disfunção orgânica, com diagnóstico de sepse. Qual é a conduta quanto ao antimicrobiano?',
      options: [
        { letter: 'A', text: 'Aguardar o resultado das culturas' },
        { letter: 'B', text: 'Iniciar imediatamente, idealmente em até 1 hora' },
        { letter: 'C', text: 'Iniciar após 6 horas de observação' },
        { letter: 'D', text: 'Iniciar só se houver choque' },
      ],
      saved: 'Salva no banco:',
      tags: ['Clínica Médica', 'Sepse', 'Gerada por IA'],
      gradeQ: 'O que diferencia choque séptico de sepse?',
      answer: 'Hipotensão que persiste mesmo depois de repor volume e lactato alto.',
      grade: 'Corrigir',
      verdict: 'Parcial',
      verdictNote: 'Mesmo sentido, faltou um ponto',
      hit: 'Acertou:',
      hitText: 'hipotensão que persiste apesar do volume.',
      miss: 'Faltou:',
      missText: 'a necessidade de vasopressor.',
      summaryTitle: 'Resumo: Sepse e choque séptico',
      generated: 'Gerado por IA',
      points: [
        { text: 'Sepse é a disfunção de órgãos causada por uma resposta desregulada à infecção.', mark: 'c1' },
        { text: 'Triagem: use NEWS, MEWS ou SIRS; o qSOFA sozinho não basta.', mark: 'c3' },
        { text: 'Primeira hora: antimicrobiano imediato, cristaloide e vasopressor se persistir.', mark: 'c4' },
        { text: 'Pegadinha: esperar a cultura para dar o antibiótico.', mark: 'c9' },
      ],
      copy: 'Copiar',
      print: 'Imprimir',
      cite: 'Cada ponto cita o card de origem.',
    },
  },
  enamed: {
    badge: 'NO AR',
    title: 'Mapas prontos do ENAMED, com fonte citada em cada card.',
    lead: 'Dez trilhas com perguntas, sequência de estudo, imagens e macetes. Abra, estude e edite a sua cópia.',
    cta: 'Ver os mapas prontos',
    eyebrow: 'Os 10 temas que mais caem',
    heading: 'Cada tema é uma trilha, do básico à decisão.',
    support: 'Base, diagnóstico, conduta, tratamento, casos clínicos e pegadinhas, na ordem em que o estudo rende.',
    prev: 'Tema anterior',
    next: 'Próximo tema',
    region: 'Os 10 temas que mais caem no ENAMED',
    carousel: 'carrossel',
    slide: 'slide',
    counter: 'Temas {n} de {total}',
    slideLabel: '{n} de {total}',
    empty: 'Os mapas prontos aparecem aqui quando a revisão editorial publicar a primeira edição.',
    tags: ['Perguntas', 'Fluxogramas', 'Casos clínicos', 'Macetes'],
    note: 'Temas mais cobrados segundo análises de cursinhos. O ENAMED é do Inep, e a lista pode mudar a cada edição. Conteúdo educacional: não substitui diretriz clínica.',
    areas: {
      CM: 'Clínica Médica',
      CIR: 'Cirurgia',
      GO: 'Ginecologia e Obstetrícia',
      PED: 'Pediatria',
      MP: 'Medicina Preventiva e Saúde Coletiva',
      OUTRO: 'Outro assunto',
    },
    themes: [
      { title: 'Sepse e choque séptico', blurb: 'Critérios qSOFA e SOFA, ressuscitação volêmica precoce e antibioticoterapia empírica.' },
      { title: 'SUS e políticas de saúde', blurb: 'Princípios, leis orgânicas (8.080/90 e 8.142/90) e rede de atenção.' },
      { title: 'Síndrome coronariana aguda', blurb: 'Diagnóstico e conduta no IAM com e sem supradesnivelamento do segmento ST.' },
      { title: 'Diabetes mellitus tipo 2', blurb: 'Critérios diagnósticos (HbA1c e glicemia de jejum), metas terapêuticas e drogas associadas.' },
      { title: 'Insuficiência cardíaca', blurb: 'Manejo clínico, critérios de Framingham modificados e escalonamento de drogas.' },
      { title: 'APS e medicina de família', blurb: 'Atributos essenciais e derivados da APS, prevenção e vínculo.' },
      { title: 'Asma e DPOC', blurb: 'Classificação de gravidade e tratamento das exacerbações agudas no pronto-socorro.' },
      { title: 'Vacinação e puericultura na infância', blurb: 'Calendário vacinal do PNI, puericultura e infecções respiratórias pediátricas.' },
      { title: 'Hipotireoidismo e hipertireoidismo', blurb: 'Leitura do eixo laboratorial (TSH e T4 livre) e condutas iniciais.' },
      { title: 'Ética médica e declaração de óbito', blurb: 'Preenchimento correto de atestados de óbito e resoluções do CFM.' },
    ],
  },
  calendar: {
    eyebrow: 'Calendário',
    title: 'Suas provas e prazos, junto do estudo.',
    lead: 'Anote provas, trabalhos, plantões e datas importantes. O Remoa avisa 1 dia antes e no dia, e mostra o que vem aí em Hoje.',
    playerLabel: 'Animação em três passos: criar uma prova no calendário, ativar os avisos de 1 dia antes e no dia, e ver os próximos compromissos em Hoje e no e-mail.',
    preview: 'Prévia',
    windowTitle: 'Remoa · Calendário',
    month: 'Outubro',
    views: 'Mês · Semana · Agenda · Galeria',
    weekdays: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    today: '7',
    chips: { exam: 'Prova', work: 'Trabalho', deadline: 'Prazo' },
    field: 'Prova de Clínica Médica',
    save: 'Salvar',
    when: 'Amanhã, 08:00 · Sala 204',
    notify: 'Avisar',
    dayBefore: '1 dia antes',
    sameDay: 'No dia',
    tomorrow: 'Amanhã',
    noticeTitle: 'Prova de Clínica Médica, 08:00',
    noticeWhere: 'Sala 204 · Bloco B',
    email: 'E-mail',
    emailTitle: 'Amanhã você tem 3 compromissos',
    rows: [
      { time: '08:00', title: 'Prova de Clínica Médica', kind: 'Prova' },
      { time: '14:00', title: 'Grupo de estudo', kind: 'Pessoal' },
      { time: '19:00', title: 'Plantão no pronto-socorro', kind: 'Plantão' },
    ],
    upcoming: 'Próximos compromissos',
    upcomingRows: [
      { day: '08', month: 'out', title: 'Prova de Clínica Médica' },
      { day: '10', month: 'out', title: 'Entrega do trabalho' },
      { day: '12', month: 'out', title: 'Prazo da inscrição' },
    ],
    legends: [
      'Crie o compromisso e escolha o tipo: prova, trabalho, prazo.',
      'Ative os avisos: 1 dia antes e no dia.',
      'Veja o que vem aí em Hoje e no e-mail.',
    ],
    steps: [
      { title: 'Anote o que importa', text: 'Provas, trabalhos, prazos, plantões e datas importantes, com horário, local e imagem.' },
      { title: 'Receba o aviso no dia certo', text: 'Notificação no Remoa e e-mail, 1 dia antes e no dia.' },
      { title: 'Veja tudo em Hoje', text: 'Os próximos compromissos aparecem em Hoje, e o e-mail lista o que vem amanhã.' },
    ],
    kindsTitle: 'Cinco tipos de compromisso',
    kinds: ['Prova', 'Trabalho', 'Data importante', 'Plantão', 'Pessoal'],
    kindsNote: 'Veja em mês, semana, agenda ou galeria, e anexe uma imagem ao compromisso.',
  },
} as const;
