// F23/F26 — Central de notificações (sino, popover, página, preferências). Textos de Main.dc.html e Notificacoes.dc.html.
export const notifications = {
  bell: {
    none: 'Notificações',
    unread: '{n, plural, one {Notificações, # não lida} other {Notificações, # não lidas}}',
  },
  popover: {
    label: 'Central de notificações',
    title: 'Notificações',
    markAll: 'Marcar tudo como lido',
    settings: 'Preferências de notificação',
    tabsLabel: 'Filtrar',
    tabAll: 'Todas',
    tabUnread: 'Não lidas',
    seeAll: 'Ver todas as notificações',
    empty: 'Nenhuma notificação por aqui.',
    allRead: 'Tudo lido. Bom trabalho.',
    loading: 'Carregando notificações…',
    error: 'Não foi possível carregar as notificações.',
    retry: 'Tentar de novo',
  },
  group: {
    today: 'Hoje',
    yesterday: 'Ontem',
    week: 'Esta semana',
    before: 'Antes',
  },
  type: {
    calendarD1: { title: 'Amanhã: {title}' },
    calendarD0: { title: 'Hoje: {title}' },
    calendarDigestD1: { title: '{count} compromissos amanhã', body: 'Abra o calendário para ver os horários.' },
    calendarDigestD0: { title: '{count} compromissos hoje', body: 'Abra o calendário para ver os horários.' },
    calendarAllDay: 'Dia inteiro',
    calendarBody: '{time} · {location}',
    reviewTitle: '{cards, plural, one {# card espera} other {# cards esperam}} por você hoje',
    reviewBody: 'Uma revisão rápida fixa o que vence.',
    mapTitle: 'Seu mapa {title} está pronto',
    mapBody: '{cards, plural, one {# card.} other {# cards.}} Revise antes de estudar.',
    referrerTitle: 'Um amigo entrou pelo seu convite',
    refereeTitle: 'Você ganhou Pro pelo convite',
    referralBody: 'O mês de Pro já está na sua conta.',
    supportTitle: 'Resposta no chamado #{n}',
    supportBody: 'A equipe respondeu. Abra para ler.',
    purchaseTitle: 'Pagamento confirmado',
    purchaseBody: '{plan}. O comprovante foi enviado por e-mail.',
    waitlistTitle: 'Você está na lista da Loja de mapas',
    waitlistBody: 'Avisamos por e-mail quando ela abrir.',
    trialD3Title: 'Seu teste do Pro termina em 3 dias',
    trialD0Title: 'Seu teste do Pro termina hoje',
    trialBody: 'Depois, sua conta volta para o Grátis sem perder nada. Assine para seguir sem limites.',
  },
  when: {
    now: 'agora',
    minutes: 'há {n} min',
    hours: 'há {n} h',
    yesterday: 'ontem',
    date: '{date}',
  },
  live: 'Nova notificação: {title}',
  item: {
    markRead: 'Marcar como lida',
    open: 'Abrir',
    remove: 'Remover notificação',
    meta: '{when} · {category}',
  },
  category: {
    all: 'Todas',
    calendar: 'Calendário',
    review: 'Revisão',
    maps: 'Mapas',
    referrals: 'Indicações',
    support: 'Suporte',
    account: 'Conta e cobrança',
    store: 'Loja',
  },
  page: {
    eyebrow: 'Central',
    title: 'Notificações',
    markAll: 'Marcar tudo como lido',
    listLabel: 'Suas notificações',
    categoryLabel: 'Categoria',
    onlyUnread: 'Só não lidas',
    noneUnread: 'Tudo lido nesta categoria.',
    none: 'Nada por aqui ainda.',
    more: 'Ver mais',
    loadError: 'Não foi possível carregar as notificações.',
    retry: 'Tentar de novo',
    loading: 'Carregando notificações…',
    removed: 'Notificação removida.',
  },
  prefs: {
    title: 'Como avisar você',
    intro: 'Escolha onde cada tipo de aviso aparece.',
    type: 'Tipo de aviso',
    app: 'App',
    email: 'E-mail',
    notApplicable: 'Não se aplica',
    locked: 'Sempre enviado',
    lockedHint: 'Sempre enviamos',
    cellApp: '{title} no app',
    cellEmail: '{title} por e-mail',
    pauseTitle: 'Pausar e-mails de lembrete',
    pauseText: 'Calendário, revisão e “volte quando sumir”. E-mails de conta continuam.',
    timeTitle: 'Horário do lembrete de revisão',
    timeGroup: 'Horário',
    timeNote: 'Horário de Brasília (GMT−3). Só enviamos se houver cards para revisar.',
    saved: 'Preferência salva.',
    saveError: 'Não foi possível salvar. Tente de novo.',
    loadError: 'Não foi possível carregar as preferências.',
    accountLink: 'Ajustar avisos e e-mails',
    footnote: 'Todo e-mail de lembrete tem um link para parar de receber aquele tipo de aviso.',
    row: {
      calendarD1: { title: 'Compromissos: 1 dia antes', text: 'Às 18:00 do dia anterior' },
      calendarD0: { title: 'Compromissos: no dia', text: 'Às 07:00 do dia' },
      review: { title: 'Lembrete de revisão', text: 'Quando houver cards para revisar' },
      mapReady: { title: 'Mapa pronto', text: 'Quando um mapa gerado terminar' },
      inactivity: { title: 'Volte quando sumir', text: 'Depois de mais de 10 dias sem entrar' },
      referral: { title: 'Indicações', text: 'Quando um amigo libera Pro' },
      support: { title: 'Suporte', text: 'Respostas aos seus chamados' },
      account: { title: 'Conta e cobrança', text: 'Cadastro, compras e senha' },
      store: { title: 'Loja de mapas', text: 'Lista de espera e abertura' },
    },
  },
} as const;
