/** F12 FR-4 onboarding (4 passos, pulável) + FR-9 checklist de ativação; F03 FR-9 suspender/retomar/reiniciar card. */
export const onboarding = {
  title: 'Remoa — Boas-vindas',
  stepsLabel: 'Passos do onboarding',
  stepDone: 'concluído',
  step: { userType: 'Perfil', institution: 'Instituição', segment: 'Momento', goal: 'Objetivo', area: 'Área', start: 'Começar' },
  userType: { title: 'Conte quem você é', desc: 'Falta completar o seu cadastro: nome, telefone e quem você é.' },
  segment: { title: 'Em que momento você está?', desc: 'Usamos isso para sugerir mapas prontos. Você muda quando quiser no perfil.' },
  goal: { title: 'Quais são os seus objetivos?', desc: 'Escolha até 5: uma prova específica ou só manter o estudo em dia.' },
  area: { title: 'Qual grande área primeiro?', desc: 'O Remoa começa por Clínica Médica. As outras áreas estão a caminho.' },
  goalCount: '{n} de {max} escolhidos',
  start: { title: 'Como você quer começar?', desc: 'Você sai daqui direto para o seu primeiro mapa.' },
  goalGroups: { enamed: 'Enamed', residencia: 'Residência', outros: 'Outros' },
  institution: {
    label: 'Instituição de ensino',
    desc: 'Usamos isso para te conhecer melhor. Você pode pular e informar depois no perfil.',
    title: 'Onde você estuda (ou estudou)?',
    titleOther: 'Qual instituição de ensino?',
    placeholder: 'Busque pelo nome, sigla ou cidade',
    empty: 'Nenhuma instituição encontrada',
    custom: 'Usar “{texto}”',
    clear: 'Limpar instituição',
    more: 'Mostrando as primeiras {n}. Refine a busca para ver as outras.',
  },
  back: 'Voltar',
  next: 'Continuar',
  skipStep: 'Pular este passo',
  skipAll: 'Pular por enquanto',
  finish: 'Ir para o primeiro mapa',
  saveError: 'Não conseguimos salvar agora. Tente de novo.',
  checklist: {
    title: 'Comece por aqui',
    progress: '{done} de {total} concluídos',
    cards: 'Criar {n} cards',
    edges: 'Ligar {n} conexões',
    sessions: 'Fazer 1 sessão',
    install: 'Instalar no celular',
    count: '{current} de {target}',
    done: 'Feito',
    installHint: 'Abra o menu do navegador e escolha Instalar ou Adicionar à tela inicial.',
  },
} as const;

export const cardStudy = {
  title: 'Estudo deste card',
  suspend: 'Suspender',
  unsuspend: 'Retomar',
  reset: 'Reiniciar progresso',
  suspendedNote: 'Suspenso: fora do Revisar hoje e dos desafios. O progresso foi mantido.',
  suspended: 'Suspenso',
  resetTitle: 'Reiniciar o progresso deste card?',
  resetBody: 'A lembrança estimada volta ao zero. Seu histórico de respostas é mantido.',
  resetConfirm: 'Reiniciar',
  resetCancel: 'Cancelar',
  resetClose: 'Fechar sem reiniciar',
  sealNote: 'Editar o conteúdo de um card aprovado remove o selo de revisão editorial.',
  error: 'Não conseguimos salvar agora. Tente de novo.',
} as const;
