/** F12 FR-4 onboarding (4 passos, pulável) + FR-9 checklist de ativação; F03 FR-9 suspender/retomar/reiniciar card. */
export const onboarding = {
  title: 'Remoa — Boas-vindas',
  stepsLabel: 'Passos do onboarding',
  stepDone: 'concluído',
  step: { segment: 'Momento', goal: 'Objetivo', area: 'Área', start: 'Começar' },
  segment: { title: 'Em que momento você está?', desc: 'Usamos isso para sugerir mapas prontos. Você muda quando quiser no perfil.' },
  goal: { title: 'Qual é o seu objetivo?', desc: 'Pode ser uma prova específica ou só manter o estudo em dia.' },
  area: { title: 'Qual grande área primeiro?', desc: 'O Remoa começa por Clínica Médica. Outras áreas chegam depois.' },
  start: { title: 'Como você quer começar?', desc: 'Você sai daqui direto para o seu primeiro mapa.' },
  goalGroups: { enamed: 'Enamed', residencia: 'Residência', outros: 'Outros' },
  back: 'Voltar',
  next: 'Continuar',
  skipStep: 'Pular este passo',
  skipAll: 'Pular por enquanto',
  finish: 'Ir para o primeiro mapa',
  saveError: 'Não conseguimos salvar agora. Tente de novo.',
  checklist: {
    title: 'Comece por aqui',
    progress: '{done} de {total} concluídos',
    cards: 'Criar {n} cards',
    edges: 'Ligar {n} conexões',
    sessions: 'Fazer 1 sessão',
    install: 'Instalar no celular',
    count: '{current} de {target}',
    done: 'Feito',
    installHint: 'Abra o menu do navegador e escolha Instalar ou Adicionar à tela inicial.',
  },
} as const;

export const cardStudy = {
  title: 'Estudo deste card',
  suspend: 'Suspender',
  unsuspend: 'Retomar',
  reset: 'Reiniciar progresso',
  suspendedNote: 'Suspenso: fora do Revisar hoje e dos desafios. O progresso foi mantido.',
  suspended: 'Suspenso',
  resetTitle: 'Reiniciar o progresso deste card?',
  resetBody: 'A lembrança estimada volta ao zero. Seu histórico de respostas é mantido.',
  resetConfirm: 'Reiniciar',
  resetCancel: 'Cancelar',
  resetClose: 'Fechar sem reiniciar',
  sealNote: 'Editar o conteúdo de um card aprovado remove o selo de revisão editorial.',
  error: 'Não conseguimos salvar agora. Tente de novo.',
} as const;
