/** G14 S1 (D-594–D-599): dados pessoais do cadastro e do perfil (tipo de usuário, sexo, telefone, endereço). PII: nunca em log/evento. */
export const personal = {
  userType: {
    label: 'Você é',
    aluno: 'Aluno',
    professor: 'Professor',
    medico_formado: 'Médico formado',
    required: 'Escolha uma opção para continuar.',
  },
  sex: {
    label: 'Sexo (opcional)',
    feminino: 'Feminino',
    masculino: 'Masculino',
    nao_binario: 'Não binário',
    outro: 'Outro',
    prefiro_nao_dizer: 'Prefiro não dizer',
  },
  phone: { label: 'Telefone (opcional)', placeholder: '(11) 91234-5678', invalid: 'Informe um telefone com DDD, como (11) 91234-5678.' },
  address: {
    title: 'Endereço (opcional)',
    cep: 'CEP',
    cepPlaceholder: '01310-100',
    searching: 'Buscando o CEP…',
    notFound: 'CEP não encontrado',
    offline: 'Não deu para buscar o CEP agora. Preencha o endereço à mão.',
    found: 'Endereço preenchido. Confira e complete o número.',
    street: 'Logradouro',
    number: 'Número',
    numberHelp: 'Use S/N se não houver número.',
    complement: 'Complemento (opcional)',
    district: 'Bairro',
    city: 'Cidade',
    uf: 'UF',
    ufPlaceholder: 'Selecione o estado',
    ufNames: {
      AC: 'Acre',
      AL: 'Alagoas',
      AP: 'Amapá',
      AM: 'Amazonas',
      BA: 'Bahia',
      CE: 'Ceará',
      DF: 'Distrito Federal',
      ES: 'Espírito Santo',
      GO: 'Goiás',
      MA: 'Maranhão',
      MT: 'Mato Grosso',
      MS: 'Mato Grosso do Sul',
      MG: 'Minas Gerais',
      PA: 'Pará',
      PB: 'Paraíba',
      PR: 'Paraná',
      PE: 'Pernambuco',
      PI: 'Piauí',
      RJ: 'Rio de Janeiro',
      RN: 'Rio Grande do Norte',
      RS: 'Rio Grande do Sul',
      RO: 'Rondônia',
      RR: 'Roraima',
      SC: 'Santa Catarina',
      SP: 'São Paulo',
      SE: 'Sergipe',
      TO: 'Tocantins',
    },
    incomplete: 'Preencha CEP, logradouro, número, bairro, cidade e UF, ou deixe o endereço em branco.',
    clear: 'Limpar endereço',
  },
  saved: 'Dados salvos.',
  edit: 'Editar',
  notGiven: 'Não informado',
  title: 'Dados pessoais',
  body: 'Só você vê estes dados. Eles não aparecem em compartilhamentos nem em indicações.',
  goalsHelp: 'Escolha até {max}. O primeiro que você marcar é o principal.',
  goalsMax: 'Você já escolheu {max} objetivos. Desmarque um para trocar.',
  goalsLabel: 'Objetivos de prova',
} as const;
