// F15 — Planos e checkout. Texto da tela "7. Planos" (docs/design/v2/source/Planos.dc.html).
// Nenhum preço literal: valores, datas e percentuais entram por placeholder ({price}, {value}, {pct}, {date}).
// Reaproveitar, sem duplicar: common.retry/close, billing.plan.free/pro, billing.pricing.{monthly,annual,perMonth,perYear,
// annualHint,pix,card,cta,alreadyPro}, billing.account.{renewsAt,status.*,grace}.
export const plans = {
  pages: {
    index: 'Remoa — Planos',
    success: 'Remoa — Pro ativado',
    canceled: 'Remoa — Pagamento cancelado',
  },
  header: {
    eyebrow: 'Planos',
    free: { title: 'Seu estudo pede mais espaço?', subtitle: 'Comece no Free. Assine o Pro quando precisar de mais mapas, cards e correções.' },
    pro: { title: 'Você está no Pro.', subtitle: 'Veja o que está liberado e gerencie a sua assinatura.' },
    founder: { title: 'Você é Founder.', subtitle: 'Acesso vitalício, IA ilimitada e as novidades primeiro.' },
  },
  // Founder (compra única, vitalícia). Oferta para quem está no Free.
  founderOffer: {
    title: 'Founder',
    price: 'Pagamento único',
    description: 'Tudo do Pro, IA sem limite e as novidades antes de todo mundo. Acesso vitalício.',
    benefits: ['Tudo do Pro', 'Correções por IA ilimitadas', 'Mapas de PDF ilimitados', 'Novidades primeiro'],
    choose: 'Quero ser Founder',
    back: 'Prefiro o Pro',
  },
  period: {
    label: 'Período de cobrança',
    monthly: 'Mensal',
    annual: 'Anual',
    discount: '-{pct}%',
    discountLabel: 'Desconto de {pct}% no anual',
  },
  limitNotice: {
    boards: 'Você usou {used} de {limit} mapas. O Pro libera o resto.',
    cards: 'Você usou {used} de {limit} cards. O Pro tira o teto.',
    seeSummary: 'Ver o resumo',
  },
  matrix: {
    title: 'O que muda do Free para o Pro',
    caption: 'Comparação entre Free e Pro',
    feature: 'Recurso',
    freePrice: 'R$ 0',
    currentPlan: 'Seu plano atual',
    recommended: 'Recomendado',
    // Ilimitado concorda com o gênero da linha.
    unlimited: { boards: 'Ilimitados', cards: 'Ilimitados', aiGrades: 'Ilimitadas' },
    rows: {
      boards: { label: 'Mapas', sub: 'total na conta' },
      cards: { label: 'Cards', sub: 'total na conta' },
      aiGrades: { label: 'Correções por IA', sub: 'por dia' },
      pdfMaps: { label: 'Mapas gerados de PDF', sub: 'por mês' },
      ankiImport: { label: 'Importação do Anki', sub: 'cards por arquivo' },
      newCards: { label: 'Novos cards por dia', sub: 'na fila de revisão' },
    },
    usage: {
      total: 'Você usa {used} de {limit}',
      today: 'Hoje: {used} de {limit}',
      month: 'Neste mês: {used} de {limit}',
      proBoards: '{used, plural, one {Você tem # mapa} other {Você tem # mapas}}',
      proCards: '{used, plural, one {Você tem # card} other {Você tem # cards}}',
      proNoDailyLimit: 'Sem limite diário',
      level: 'Uso: {pct}% do limite',
    },
  },
  summary: {
    title: 'Resumo do pedido',
    planName: 'Pro',
    founderPlanName: 'Founder',
    founderPer: 'pagamento único',
    founderNote: 'Acesso vitalício, sem renovação. Pix ou cartão.',
    founderLine: 'Founder, acesso vitalício',
    founderSubscribe: 'Comprar o Founder',
    billingNote: {
      monthly: 'Cobrado todo mês.',
      annual: 'Cobrado uma vez por ano. Equivale a {price} por mês.',
    },
    saving: 'Economize {value} por ano',
    method: {
      label: 'Forma de pagamento',
      pix: { label: 'Pix', desc: 'Pague pelo app do seu banco, com QR code ou copia e cola.' },
      card: { label: 'Cartão', desc: 'Crédito, com cobrança automática a cada período.' },
      // D-101: Pix é pagamento único do período e não renova sozinho.
      pixNote: 'No Pix, você paga um período e renova quando quiser. Ele não renova sozinho.',
    },
    founder: {
      open: 'Tenho um código de fundador',
      label: 'Código de fundador',
      placeholder: 'Digite o código',
      apply: 'Aplicar',
      applying: 'Verificando o código',
      error: 'Código não reconhecido. Confira e tente de novo.',
      applied: 'Preço de fundador aplicado',
      remove: 'Remover',
      removeLabel: 'Remover o código de fundador',
      badge: 'Fundador',
    },
    totals: {
      list: 'Pro {period}',
      founder: 'Preço de fundador',
      today: 'Total hoje',
      period: { monthly: 'mensal', annual: 'anual' },
      perMonth: '{price}/mês',
      perYear: '{price}/ano',
      unitMonth: '/mês',
      unitYear: '/ano',
      listSr: 'Preço de tabela',
    },
    nextCharge: 'Próxima cobrança em {date}.',
    subscribe: 'Assinar o Pro',
    secure: 'Pagamento seguro pelo Stripe. Cancele em um clique. Seus mapas continuam seus.',
  },
  redirecting: {
    title: 'Abrindo o pagamento seguro',
    body: 'Você conclui com {method} no Stripe e volta para cá em seguida.',
    method: { pix: 'Pix', card: 'cartão' },
  },
  success: {
    founder: {
      title: 'Você agora é Founder.',
      subtitle: 'Seu acesso vitalício está ativo. Tudo isto já está liberado.',
      benefits: {
        pro: 'Tudo do Pro, para sempre',
        aiGrades: 'Correções por IA ilimitadas',
        pdfMaps: 'Mapas gerados de PDF ilimitados',
        early: 'As novidades primeiro',
      },
    },
    title: 'Você agora é Pro.',
    subtitle: 'Seu plano foi atualizado. Tudo isto já está liberado.',
    benefits: {
      unlimited: 'Mapas e cards ilimitados',
      aiGrades: 'Correções por IA sem limite diário',
      pdfMaps: '{n} mapas gerados de PDF por mês',
      anki: 'Importação de até {n} cards do Anki',
    },
    goToday: 'Ir para Hoje',
    createMap: 'Criar um mapa',
    seePlans: 'Ver meus planos',
    verifying: 'Confirmando o seu pagamento',
    verifyError: 'Não conseguimos confirmar o pagamento agora. Se algo foi cobrado, o Pro é liberado assim que o Stripe avisar.',
  },
  pixPending: {
    title: 'Estamos aguardando a confirmação do Pix',
    body: 'Assim que o banco confirmar, o Pro é liberado aqui. Pode fechar esta página: a liberação não depende dela.',
    checking: 'Verificando a cada poucos segundos',
    timeout: 'A confirmação está demorando mais que o normal. Seu Pro será liberado assim que o Pix for confirmado.',
    seePlans: 'Voltar aos planos',
  },
  canceled: {
    message: 'Pagamento cancelado. Nada foi cobrado.',
    retry: 'Escolher de novo',
  },
  subscriber: {
    title: 'Sua assinatura',
    plan: 'Pro',
    founderPlan: 'Founder',
    founderStatus: 'Vitalício',
    founderText: 'Acesso vitalício, sem renovação. Obrigado por apoiar o Remoa.',
    status: { active: 'Ativa', pastDue: 'Pagamento pendente', canceling: 'Termina em {date}' },
    perYear: '{price} por ano',
    perMonth: '{price} por mês',
    billing: 'Cobrança',
    billingValue: { monthly: 'Mensal', annual: 'Anual', lifetime: 'Pagamento único' },
    amount: 'Valor',
    renewal: 'Renova em',
    endsAt: 'Termina em {date}',
    upsell: {
      title: 'No anual você economiza',
      body: '{annual} por ano, em vez de {monthlyYear}. São {value} a menos.',
      cta: 'Mudar para o anual',
    },
    manage: 'Gerenciar assinatura',
    reactivate: 'Reativar',
    secure: 'Pagamento seguro pelo Stripe. Cancele em um clique.',
    statusLabel: 'Situação',
    switched: 'Pronto: você está no plano anual.',
    actionError: 'Não conseguimos concluir agora. Tente de novo.',
    methodValue: { card: 'Cartão', pix: 'Pix' },
    pastDue: 'Pagamento em atraso. Seu Pro continua até {date}; atualize a forma de pagamento.',
    pixRenew: 'Seu período no Pix termina em {date}. Pague de novo para continuar no Pro.',
  },
  faq: {
    title: 'Perguntas frequentes',
    // q1..q4 as an object: the typed t() paths don't index arrays.
    items: {
      q1: { q: 'Posso cancelar quando quiser?', a: 'Sim, em um clique, na sua conta. Seus mapas continuam seus.' },
      q2: {
        q: 'O que acontece com meus mapas se eu voltar ao Free?',
        a: 'Nada é apagado nem escondido. Você só não cria mapas ou cards novos acima do limite do Free.',
      },
      q3: {
        q: 'Como eu pago?',
        a: 'Com Pix ou cartão, no pagamento seguro do Stripe. Você escolhe aqui e conclui na página de pagamento. No cartão, a cobrança se repete a cada período. O Pix é um pagamento único do período: ele não renova sozinho, e você paga de novo quando quiser continuar.',
      },
      q4: {
        q: 'Como funciona o preço de fundador?',
        a: 'É para quem entrou no beta. Com o código, o Pro sai por um preço menor.',
      },
    },
  },
  states: {
    loadingLabel: 'Carregando os planos',
    pageError: 'Não foi possível carregar os planos agora.',
    loadError: 'Não foi possível carregar o seu uso. Os planos continuam aqui, sem os seus números.',
    checkoutError: 'Não conseguimos abrir o pagamento. Nada foi cobrado.',
    retry: 'Tentar de novo',
    offline: 'Sem conexão. Reconecte para assinar.',
    dismissToast: 'Fechar aviso',
    liveRegionLabel: 'Avisos dos planos',
  },
} as const;
