export const ptBR = {
  common: {
    appName: 'Remoa',
    loading: 'Carregando…',
    save: 'Salvar',
    cancel: 'Cancelar',
    close: 'Fechar',
    back: 'Voltar',
    retry: 'Tentar de novo',
    comingSoon: 'Em breve',
    notifications: 'Notificações',
  },
  vocab: {
    board: 'mapa',
    boards: 'mapas',
    card: 'card',
    cards: 'cards',
    edge: 'conexão',
    edges: 'conexões',
    reviewToday: 'Revisar hoje',
    challengeBoard: 'Desafiar este mapa',
    retrievability: 'Lembrança estimada',
  },
  revisar: {
    hoje: 'Revisar hoje',
  },
  mapState: {
    review: 'Revisitar',
    watch: 'Acompanhar',
    steady: 'Mais estável',
    unknown: 'Sem revisões',
  },
  grade: {
    again: 'Não lembrei',
    hard: 'Difícil',
    good: 'Bom',
    easy: 'Fácil',
  },
  challengeMode: {
    hidden_card: 'Card oculto',
    edge: 'Conexão',
    next_step: 'Próximo passo',
    occlusion: 'Imagem',
    case: 'Caso',
  },
  shell: {
    nav: {
      label: 'Navegação principal',
      boards: 'Meus mapas',
      review: 'Revisar hoje',
      coverage: 'Cobertura Enamed',
      store: 'Loja',
      account: 'Conta',
    },
    bottomNav: {
      label: 'Navegação inferior',
      boards: 'Mapas',
      review: 'Revisar',
      coverage: 'Cobertura',
      account: 'Conta',
    },
    header: {
      breadcrumbRoot: 'Meus mapas',
      breadcrumbLabel: 'Você está em',
      savedAgo: 'Salvo há {tempo}',
      savedNow: 'Salvo agora',
      import: 'Importar',
      themeLight: 'Tema claro',
      themeDark: 'Tema escuro',
      themeToggle: 'Alternar tema',
      openMenu: 'Abrir menu',
    },
  },
  auth: {
    signIn: {
      title: 'Entrar',
      subtitle: 'Continue de onde parou.',
      submit: 'Entrar',
      noAccount: 'Ainda não tem conta?',
      toSignUp: 'Criar conta',
    },
    signUp: {
      title: 'Criar conta',
      subtitle: 'Seu mapa de estudo começa aqui.',
      submit: 'Criar conta',
      hasAccount: 'Já tem conta?',
      toSignIn: 'Entrar',
    },
    email: 'E-mail',
    emailPlaceholder: 'voce@exemplo.com',
    password: 'Senha',
    magicLink: 'Enviar link mágico',
    google: 'Entrar com Google',
    signOut: 'Sair',
    or: 'ou',
    linkSent: {
      title: 'Confira seu e-mail',
      body: 'Enviamos um link de acesso para {email}. Ele vale por poucos minutos.',
    },
  },
  errors: {
    unauthorized: 'Você precisa entrar para continuar.',
    forbidden: 'Você não tem acesso a isto.',
    not_found: 'Não encontramos o que você procura.',
    validation: 'Confira os campos e tente de novo.',
    quota_exceeded: 'Você chegou ao limite do seu plano.',
    rate_limited: 'Muitas tentativas. Espere um pouco e tente de novo.',
    conflict: 'Isto mudou em outro lugar. Atualize e tente de novo.',
    ai_unavailable: 'A IA está indisponível agora. Tente em instantes.',
    internal: 'Algo deu errado do nosso lado. Tente de novo.',
  },
  boundary: {
    title: 'Algo deu errado',
    body: 'Tivemos um problema ao abrir esta tela.',
    retry: 'Tentar de novo',
    home: 'Ir para Meus mapas',
    ref: 'Código do erro: {id}',
  },
  empty: {
    boards: {
      title: 'Você ainda não tem mapas',
      body: 'Importe seu material ou comece com um mapa pronto.',
      import: 'Importar',
      template: 'Começar com um mapa pronto',
    },
    review: {
      title: 'Revisar hoje',
      body: 'Sua fila de revisão aparece aqui.',
    },
    coverage: {
      title: 'Cobertura Enamed',
      body: 'Veja quais temas da prova você já cobriu.',
    },
    store: {
      title: 'Loja',
      body: 'Em breve.',
    },
    account: {
      title: 'Conta',
      body: 'Seus dados e preferências ficam aqui.',
    },
    mobileReview: {
      title: 'Revisar hoje',
      body: 'Um desafio por vez, direto no celular.',
    },
    editorial: {
      title: 'Revisão editorial',
      body: 'Conteúdo aguardando revisão aparece aqui.',
    },
  },
  landing: {
    tagline: 'O que você aprende, fica.',
    subtitle: 'Monte seu mapa de estudo, revise na hora certa e teste o que realmente lembra.',
    cta: 'Começar agora',
    signIn: 'Entrar',
  },
} as const;

export type Dict = typeof ptBR;
