import { account } from './account';

export const ptBR = {
  account,
  common: {
    appName: 'Remoa',
    loading: 'Carregando…',
    save: 'Salvar',
    cancel: 'Cancelar',
    close: 'Fechar',
    back: 'Voltar',
    retry: 'Tentar de novo',
    comingSoon: 'Em breve',
    notifications: 'Notificações',
  },
  vocab: {
    board: 'mapa',
    boards: 'mapas',
    card: 'card',
    cards: 'cards',
    edge: 'conexão',
    edges: 'conexões',
    reviewToday: 'Revisar hoje',
    challengeBoard: 'Desafiar este mapa',
    retrievability: 'Lembrança estimada',
  },
  revisar: {
    hoje: 'Revisar hoje',
  },
  review: {
    headlineNone: 'Nada vence hoje',
    headlineOne: '1 conceito vence hoje',
    headlineMany: '{due} conceitos vencem hoje',
    headlineIn: '{head}, {n} em {board}',
    due: 'Vencem hoje',
    new: 'Novos',
    weak: 'Para acompanhar',
    start: 'Começar revisão',
    groupsLabel: 'Fila por mapa',
    unknownBoard: 'Mapa sem nome',
    empty: { title: 'Nada para revisar hoje', body: 'Volte amanhã ou adicione conceitos a um mapa.', cta: 'Ir para Meus mapas' },
    badge: '{n, plural, one {# vence hoje} other {# vencem hoje}}',
  },
  mapState: {
    review: 'Revisitar',
    watch: 'Acompanhar',
    steady: 'Mais estável',
    unknown: 'Sem revisões',
  },
  grade: {
    again: 'Não lembrei',
    hard: 'Difícil',
    good: 'Bom',
    easy: 'Fácil',
  },
  challengeMode: {
    hidden_card: 'Card oculto',
    edge: 'Conexão',
    next_step: 'Próximo passo',
    occlusion: 'Imagem',
    case: 'Caso',
  },
  challenge: {
    progress: '{n} de {total}',
    progressLabel: 'Progresso da sessão',
    loading: 'Montando sua sessão…',
    loadError: 'Não conseguimos montar a sessão.',
    backToReview: 'Voltar para Revisar hoje',
    empty: { title: 'Nada para revisar agora', body: 'Volte mais tarde ou adicione conceitos ao mapa.' },
    stagesLabel: 'Etapas até aqui',
    edgeAsk: 'O que liga {from} a {to}?',
    imageAlt: 'Imagem com regiões cobertas',
    answerMode: 'Como responder',
    write: 'Escrever',
    options: 'Opções',
    optionsLabel: 'Alternativas',
    textLabel: 'Sua resposta',
    submitText: 'Corrigir resposta',
    grading: 'corrigindo…',
    submitOption: 'Confirmar alternativa',
    reveal: 'Revelar resposta',
    skip: 'Pular',
    skipLimit: 'Este item já foi pulado duas vezes. Responda para seguir.',
    skipError: 'Não conseguimos pular agora. Tente de novo.',
    noRubricBody: 'Este conceito ainda não tem rubrica aprovada. Revele a resposta e diga como foi.',
    ownRubric: 'Rubrica sua',
    answerError: 'Não conseguimos registrar a resposta. Tente de novo.',
    canonical: 'Resposta',
    yourAnswer: 'Sua resposta',
    gradeLocked: 'Nota travada em “Não lembrei”: a resposta tem um erro crítico (dose, droga ou conduta). Reveja a resposta acima.',
    fallbackNoRubric: 'Sem rubrica aprovada para corrigir: avalie você mesmo.',
    fallbackGraderError: 'A correção automática falhou. Compare com a resposta e avalie você mesmo.',
    fallbackQuota: 'Suas correções por IA de hoje acabaram. Compare com a resposta e avalie você mesmo.',
    quotaCta: 'Ver planos',
    rateError: 'Não conseguimos salvar a nota. Tente de novo.',
    disputed: 'Obrigado. Vamos revisar esta correção.',
    disputeError: 'Não conseguimos enviar. Tente de novo.',
    intervalDays: { zero: 'hoje', one: '1 dia', many: '{n} dias' },
    shortcuts: 'Atalhos: 1 a 4 notas · Enter corrige ou revela · Esc pula',
    verdict: {
      title: { correct: 'Acertou', partial: 'Quase lá', incorrect: 'Não foi dessa vez' },
      matched: 'Acertou',
      missing: 'Faltou',
    },
    summary: {
      title: 'Sessão concluída',
      correct: 'Acertos',
      wrong: 'Erros',
      duration: 'Tempo',
      minutes: '{n} min',
      toReview: 'Cards que pedem revisão',
      toReviewNone: 'Nenhum card pede revisão agora.',
      openBoard: 'Abrir no mapa',
      untitled: 'Card sem título',
      nextDue: 'Próximo vencimento',
      nextNone: 'Sem vencimentos agendados',
      more: 'Mais 5',
    },
  },
  rail: {
    home: 'Hoje',
    maps: 'Mapas',
    review: 'Revisar',
    enamed: 'Enamed',
    store: 'Loja',
    account: 'Minha conta',
  },
  home: {
    greeting: 'Boa {periodo}. {n, plural, =0 {Nenhum conceito espera} one {# conceito espera} other {# conceitos esperam}} por você.',
    reviewSection: 'Revisão de hoje',
    reviewSummary: '{boards, plural, one {# mapa} other {# mapas}}, {n, plural, one {# conceito} other {# conceitos}} para fixar hoje.',
    queueStart: 'A fila começa por {card}, que vence hoje com lembrança estimada de {pct}%.',
    startReview: 'Começar revisão',
    reviewOnlyBoard: 'Só {board}',
    reviewOpenLabel: 'Abrir o mapa {mapa}',
    continueFrom: 'Continue de onde parou',
    seeAll: 'Ver todos os mapas',
    coverage: 'Cobertura da matriz do Enamed',
    coverageHint: 'Conteúdo mapeado, não peso de prova',
    weekTitle: 'Sua semana',
    weekStreak: '{n, plural, =0 {0 dias seguidos} one {# dia seguido} other {# dias seguidos}}',
    weekDays: { seg: 'Seg', ter: 'Ter', qua: 'Qua', qui: 'Qui', sex: 'Sex', sab: 'Sáb', dom: 'Dom' },
    done: 'Feitos',
    planned: 'Previstos',
    reviewedToday: '{n} de {total} revisados hoje',
    reviewedTitle: '{n} de {total}',
    reviewedCaption: 'revisados hoje',
    nextReviewsTitle: 'Próximas revisões',
    nextReviews: { today: 'Hoje', tomorrow: 'Amanhã', saturday: 'Sábado', sunday: 'Domingo' },
    startSomething: 'Comece algo novo',
    generatePdf: 'Gerar mapa de um PDF',
    generatePdfDesc: 'Rascunho por IA para revisar',
    importAnki: 'Importar do Anki',
    importAnkiDesc: 'Seu .apkg vira mapa',
    seedMap: 'Mapa pronto',
    seedMapDesc: 'Revisado por médico, com fonte',
    salutation: { morning: 'Bom dia', afternoon: 'Boa tarde', evening: 'Boa noite' },
    greetingDue: '{saudacao}. {n, plural, one {# conceito espera} other {# conceitos esperam}} por você.',
    greetingNone: '{saudacao}. Nada vence hoje.',
    greetingNoMaps: '{saudacao}. Seu primeiro mapa começa aqui.',
    reviewEmptyTitle: 'Nada para revisar hoje.',
    reviewEmptyBody: 'Quando um conceito vencer, ele entra aqui. Que tal abrir um mapa e conectar mais um card?',
    noMapsTitle: 'Crie o seu primeiro mapa.',
    noMapsBody: 'Cada card do mapa entra na revisão espaçada e a cobertura da matriz aparece aqui.',
    openMaps: 'Abrir meus mapas',
    coverageEmpty: 'Ligue um mapa a um item da matriz ao criar para ver a cobertura aqui.',
    weekBarLabel: '{dia}: {done} feitos, {planned} previstos',
    loadError: 'Não foi possível carregar o resumo de hoje.',
  },
  library: {
    title: 'Meus mapas',
    summary: '{n, plural, one {# mapa} other {# mapas}} · {cards, plural, one {# card} other {# cards}} · {due, plural, =0 {sem vencimentos} one {# vence} other {# vencem}} hoje',
    searchPlaceholder: 'Buscar mapa',
    viewGrid: 'Ver em grade',
    viewList: 'Ver em lista',
    filterArea: 'Filtrar por área',
    newMapButton: 'Novo mapa',
    noMaps: 'Nenhum mapa encontrado',
    noMapsDesc: 'Tente outro nome ou outra área, ou comece um mapa novo.',
    cardMeta: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    eyebrow: 'Biblioteca',
    all: 'Todos',
    columns: { map: 'Mapa', area: 'Área', states: 'Estados', cards: 'Cards', today: 'Hoje', saved: 'Salvo' },
    saved: 'Salvo {time}',
    ago: {
      now: 'agora',
      minutes: 'há {n} min',
      hours: 'há {n} h',
      yesterday: 'ontem',
      days: 'há {n} dias',
      weeks: 'há {n, plural, one {# semana} other {# semanas}}',
    },
    dueToday: '{n, plural, =0 {Em dia} one {# vence hoje} other {# vencem hoje}}',
    stateLabel: 'Estados',
  },
  newMap: {
    step: { one: 'Início', two: 'Detalhes', three: 'Material' },
    step1Title: 'Como você quer começar?',
    step1Desc: 'Você muda de ideia quando quiser. O mapa é seu e continua editável.',
    path: {
      pdf: 'Do meu PDF',
      pdfDesc: 'Resumo, apostila ou capítulo. A IA monta um rascunho do mapa para você revisar.',
      pdfTag: 'Rascunho por IA',
      anki: 'Do meu Anki',
      ankiDesc: 'Importe o arquivo .apkg: os cards viram conceitos e a oclusão de imagem vem junto.',
      ankiTag: 'Importação',
      seed: 'De um mapa pronto',
      seedDesc: 'Mapas revisados por médico, com fonte, versão e marco temporal da edição.',
      seedTag: 'Revisado',
      blank: 'Em branco',
      blankDesc: 'Comece do zero e monte do seu jeito, card por card.',
      blankTag: 'Livre',
    },
    step2Title: 'Sobre o que é este mapa?',
    step2Desc: 'A área e o item da matriz do Enamed organizam a cobertura e sugerem o nome.',
    areaLabel: 'Grande área',
    itemLabel: 'Item da matriz',
    nameLabel: 'Nome do mapa',
    step3Title: {
      pdf: 'Envie o seu material',
      anki: 'Envie o seu arquivo',
      seed: 'Escolha o mapa pronto',
      blank: 'Tudo pronto para criar',
    },
    step3Desc: {
      pdf: 'Aceitamos PDF de resumos e capítulos. O resultado é um rascunho que você revisa antes de estudar.',
      anki: 'Seus cards viram conceitos; a repetição espaçada começa do zero.',
      seed: 'Cada mapa vem com fontes, rubricas aprovadas e a edição do Enamed em que foi revisado.',
      blank: 'Confira os dados. Você poderá mudar tudo depois no editor.',
    },
    dropTitle: { pdf: 'Arraste seu PDF aqui', anki: 'Arraste seu arquivo .apkg aqui' },
    dropDesc: { pdf: 'ou escolha um arquivo do computador', anki: 'ou escolha o arquivo exportado do Anki' },
    cta: { pdf: 'Gerar rascunho do mapa', anki: 'Importar para o mapa', seed: 'Adicionar ao meu mapa', blank: 'Criar mapa' },
    previewLabel: 'Prévia do seu mapa',
    previewNote: {
      pdf: 'O que a IA gerar nasce como rascunho, com a marca "não revisado", até você conferir.',
      anki: 'Seus cards ficam privados. A oclusão de imagem vira máscara vetorial editável.',
      seed: 'Conteúdo revisado por médico, com nome, CRM, fonte e marco temporal em cada card.',
      blank: 'Um card central, pronto para você ligar ao resto do que sabe.',
    },
    stepsLabel: 'Passos',
    stepDone: 'concluído',
    areaSoon: 'Em breve',
    noItems: 'Nenhum item da matriz disponível para esta área.',
    seedSoon: 'Os mapas prontos aparecem aqui quando a revisão editorial publicar a primeira edição.',
    replaceFile: 'Trocar',
    fileMeta: '{mb} MB',
    opts: {
      pdf: { flows: 'Gerar fluxogramas de conduta quando houver algoritmo no texto', rubrics: 'Gerar rubricas de correção para cada card' },
      anki: { tags: 'Transformar tags do Anki em seções do mapa', images: 'Trazer imagens e máscaras de oclusão' },
    },
    previewSub: {
      pdf: 'Rascunho por IA a partir do seu PDF',
      anki: 'Importado do seu arquivo do Anki',
      seed: 'Mapa pronto, revisado por médico',
      blank: 'Mapa em branco',
    },
    sat: {
      concept: 'Conceito',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso clínico',
      ankiCard: 'Card do Anki',
      definition: 'Definição',
      conduct: 'Conduta',
      criteria: 'Critérios',
      case1: 'Caso 1',
      figure: 'Figura',
      treatment: 'Tratamento',
      occlusion: 'Oclusão',
      diagnosis: 'Diagnóstico',
      exams: 'Exames',
    },
    closeLabel: 'Cancelar e voltar',
    filePickerLabel: 'Escolher arquivo',
    seedsLabel: 'Mapas prontos',
    backButton: 'Voltar',
    continueButton: 'Continuar',
  },
  pages: {
    home: 'Remoa — Hoje',
    coverage: 'Remoa — Cobertura Enamed',
    pricing: 'Remoa — Planos',
    account: 'Remoa — Minha conta',
    library: 'Remoa — Meus mapas',
    newMap: 'Remoa — Novo mapa',
    editorTitle: 'Remoa — Editor do mapa {mapa}',
    challengeTitle: 'Remoa — Desafio dentro do mapa',
    logoLink: 'Remoa, ir para Hoje',
    navLabel: 'Principal',
  },
  shell: {
    nav: {
      label: 'Navegação principal',
      boards: 'Meus mapas',
      review: 'Revisar hoje',
      coverage: 'Cobertura Enamed',
      store: 'Loja de boards',
      account: 'Conta',
    },
    sidebar: {
      library: 'Biblioteca pessoal',
      dueToday: '{n, plural, one {# conceito vence hoje} other {# conceitos vencem hoje}}',
      dueTop: '{n} em {mapa}',
      dueNone: 'Nada vence hoje.',
      start: 'Começar',
      account: 'Minha conta',
      plan: 'Plano Free',
    },
    bottomNav: {
      label: 'Navegação inferior',
      boards: 'Mapas',
      review: 'Revisar',
      coverage: 'Cobertura',
      account: 'Conta',
    },
    header: {
      breadcrumbRoot: 'Meus mapas',
      breadcrumbLabel: 'Você está em',
      savedAgo: 'Salvo há {tempo}',
      savedNow: 'Salvo agora',
      import: 'Importar',
      importTitle: 'Importar material',
      importBody: 'A importação de PDF e de decks do Anki chega em breve.',
      themeLight: 'Tema claro',
      themeDark: 'Tema escuro',
      themeToggle: 'Alternar tema',
      openMenu: 'Abrir menu',
    },
  },
  auth: {
    signIn: {
      title: 'Entrar',
      subtitle: 'Continue de onde parou.',
      submit: 'Entrar',
      noAccount: 'Ainda não tem conta?',
      toSignUp: 'Criar conta',
    },
    signUp: {
      title: 'Criar conta',
      subtitle: 'Seu mapa de estudo começa aqui.',
      submit: 'Criar conta',
      hasAccount: 'Já tem conta?',
      toSignIn: 'Entrar',
    },
    email: 'E-mail',
    emailPlaceholder: 'voce@exemplo.com',
    password: 'Senha',
    magicLink: 'Enviar link mágico',
    google: 'Entrar com Google',
    signOut: 'Sair',
    or: 'ou',
    linkSent: {
      title: 'Confira seu e-mail',
      body: 'Enviamos um link de acesso para {email}. Ele vale por poucos minutos.',
    },
  },
  errors: {
    unauthorized: 'Você precisa entrar para continuar.',
    forbidden: 'Você não tem acesso a isto.',
    not_found: 'Não encontramos o que você procura.',
    validation: 'Confira os campos e tente de novo.',
    quota_exceeded: 'Você chegou ao limite do seu plano.',
    rate_limited: 'Muitas tentativas. Espere um pouco e tente de novo.',
    conflict: 'Isto mudou em outro lugar. Atualize e tente de novo.',
    ai_unavailable: 'A IA está indisponível agora. Tente em instantes.',
    internal: 'Algo deu errado do nosso lado. Tente de novo.',
  },
  boundary: {
    title: 'Algo deu errado',
    body: 'Tivemos um problema ao abrir esta tela.',
    retry: 'Tentar de novo',
    home: 'Ir para Meus mapas',
    ref: 'Código do erro: {id}',
  },
  empty: {
    boards: {
      title: 'Seu primeiro mapa',
      body: 'Importe seu material, comece com um mapa pronto ou crie um em branco.',
      importPdf: 'Importar PDF',
      importAnki: 'Importar do Anki',
      template: 'Começar com um mapa pronto',
    },
    review: {
      title: 'Revisar hoje',
      body: 'Sua fila de revisão aparece aqui.',
    },
    coverage: {
      title: 'Cobertura Enamed',
      body: 'Ligue um mapa a um item da matriz do Enamed e veja aqui quanto do tema você já cobriu.',
    },
    store: {
      title: 'Loja',
      body: 'Em breve.',
    },
    account: {
      title: 'Conta',
      body: 'Seus dados e preferências ficam aqui.',
    },
    mobileReview: {
      title: 'Revisar hoje',
      body: 'Um desafio por vez, direto no celular.',
    },
    editorial: {
      title: 'Revisão editorial',
      body: 'Conteúdo aguardando revisão aparece aqui.',
    },
  },
  boards: {
    title: 'Meus mapas',
    new: 'Novo mapa',
    create: 'Criar mapa',
    titleLabel: 'Nome do mapa',
    titlePlaceholder: 'Ex.: Sepse',
    counts: '{cards, plural, =0 {0 cards} one {# card} other {# cards}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    stateBarLabel: '{review} para revisitar, {watch} a acompanhar, {steady} mais estáveis, {unknown} sem revisões',
    menu: 'Mais ações de {title}',
    today: {
      label: 'Hoje',
      due: '{n, plural, one {# conceito vence} other {# conceitos vencem}} hoje · {m} em {title}',
      none: 'Nada vence hoje. Que tal criar um mapa?',
      start: 'Começar',
    },
    soon: { title: 'Em breve', body: 'A importação chega nas próximas versões. Por enquanto, crie um mapa e adicione seus cards.' },
    open: 'Abrir {title}',
    rename: 'Renomear',
    renameTitle: 'Renomear mapa',
    duplicate: 'Duplicar',
    duplicateTitle: '{title} (cópia)',
    duplicated: 'Mapa duplicado',
    archive: 'Arquivar',
    archiveTitle: 'Arquivar “{title}”?',
    archiveBody: 'O mapa sai de Meus mapas. Cards e revisões continuam guardados.',
    archived: 'Mapa arquivado',
    undo: 'Desfazer',
    sidebarLabel: 'Seus mapas',
    area: {
      CM: 'Clínica Médica',
      Cirurgia: 'Cirurgia',
      GO: 'Ginecologia e Obstetrícia',
      Pediatria: 'Pediatria',
      MP: 'Medicina Preventiva',
    },
  },
  coverage: {
    areaFilter: 'Grande área',
    summaryLabel: 'Resumo da cobertura',
    catalog: 'Cobertura do catálogo',
    catalogHint: 'Média sobre todos os itens da área; item sem mapa conta 0%',
    reviewToday: 'Revisar hoje',
    reviewTodayHint: '{n, plural, =0 {nenhum card vence} one {# card vence} other {# cards vencem}}',
    maps: 'Mapas',
    tableLabel: 'Cobertura por tópico',
    topic: 'Tópico',
    mapCount: 'Mapas',
    coverage: 'Cobertura',
    recall: 'Lembrança estimada',
    noRecall: '—',
    footer: 'Cobertura mede quanto do tópico você mapeou, não quanto você lembra. Lembrança estimada vem das suas revisões. Os tópicos são uma organização do Remoa, não uma lista oficial do INEP, e não indicam peso de prova.',
    loadError: 'Não foi possível carregar a cobertura.',
  },
  editor: {
    headerTitle: '{area} · {title}',
    savedLabel: 'Salvo há {time}',
    savedNow: 'Salvo agora',
    layers: 'Camadas',
    explore: 'Explorar',
    challenge: 'Desafio',
    commandPalette: 'Buscar ou comandar',
    progress: '{n} de {total}',
    addCardConcept: 'Adicionar card de conceito',
    addCardFlow: 'Adicionar fluxograma',
    addCardImage: 'Adicionar imagem',
    addCardCase: 'Adicionar caso clínico',
    searchLabel: 'Buscar card, comando ou mapa',
    closeAlert: 'Fechar aviso',
    closePanelLabel: 'Fechar painel do card',
    recordVoiceLabel: 'Gravar resposta por voz',
    panelLabel: 'Painel do mapa',
    backToLibrary: 'Voltar para Meus mapas',
    sections: 'Seções do card',
    // T5 (editor v2)
    saving: 'Salvando…',
    suggestLink: 'Ligar a {item}',
    linkError: 'Não foi possível ligar o mapa ao item.',
    coversHeader: 'cobre {pct}% de {item}',
    cardMenu: 'Mais ações de {title}',
    // G02
    moreActions: 'Mais ações do mapa',
  },
  inspector: {
    essentialLabel: 'Essencial',
    reviewerLabel: 'Revisor',
    temporalLabel: 'Marco temporal',
    sourceLabel: 'Fonte',
    statusLabel: 'Status',
    status: { draft: 'Rascunho', approved: 'Aprovada' },
    reviewerInfo: '{revisor} · CRM {crm}',
    reviewerSourceNote: 'Corrigido contra a rubrica do card, revisada por {revisor} · CRM {crm}. Fonte: {fonte}.',
    coverage: 'Cobertura de {pct, plural, one {# por cento} other {# por cento}}',
    version: 'Versão',
    reviewThis: 'Revisar este card',
    noRubricWarning: 'Este card ainda não tem rubrica. A correção por texto só funciona contra uma rubrica aprovada; sem ela, o desafio usa autoavaliação.',
    noHistory: 'Nenhuma tentativa ainda. O histórico aparece depois da primeira revisão.',
    // T5 (editor v2)
    tabs: { content: 'Conteúdo', rubric: 'Rubrica', origin: 'Origem', history: 'Histórico' },
    nextToday: 'próxima revisão: hoje',
    nextOn: 'próxima revisão: {data}',
    connections: 'Conexões · {n}',
    noConnections: 'Nenhuma conexão ainda.',
    unlabelled: 'sem rótulo',
    outgoing: 'Sai para',
    incoming: 'Chega de',
    optionalLabel: 'Opcional',
    rubricApproved: 'v{v} · usada na correção por IA',
    rubricDraft: 'v{v} · aguardando revisão editorial',
    editorialLabel: 'Revisão editorial',
    noSource: 'Você ainda não adicionou fonte',
    noMark: 'Sem marco (card privado)',
    noEditorial: 'Sem revisão editorial',
    reviewerPending: 'Aprovado; nome e CRM do revisor indisponíveis',
    noSummary: 'Sem resumo ainda.',
  },
  canvas: {
    layers: { structure: 'Estrutura', retrievability: 'Lembrança estimada', coverage: 'Cobertura' },
    layersLabel: 'Estados dos cards',
    legend: 'Legenda dos estados',
    legendLabel: 'Legenda dos estados',
    zoom: {
      in: 'Aumentar zoom',
      out: 'Diminuir zoom',
      fit: 'Ajustar à tela',
      percent: '{n}%',
      controls: 'Controles de zoom',
    },
    toolbar: {
      label: 'Ferramentas do mapa',
      concept: 'Card',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso',
      move: 'Mover o mapa',
      connect: 'Ligar dois cards',
      organize: 'Organizar o mapa',
      heat: 'Lembrança estimada',
      explore: 'Explorar',
      challenge: 'Desafio',
      select: 'Selecionar',
    },
    // T5 (editor v2)
    fitShort: 'Ajustar',
    layerSwitch: { structure: 'Estrutura', recall: 'Lembrança', coverage: 'Cobertura' },
    nodeType: { concept: 'Conceito', flow: 'Fluxograma', image: 'Imagem', case: 'Caso clínico' },
    selectCard: 'Selecionar {title}',
    footer: {
      recall: '{state} · {pct}%',
      due: '{text} · vence hoje',
      none: 'Sem revisões ainda',
      edges: '{n, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
      coverage: 'Entra em {item}',
      noItem: 'Fora da matriz do Enamed',
    },
    edgeDialog: 'Rótulo da conexão',
    edgeDialogBody: 'Sem rótulo, a conexão não vira pergunta no desafio.',
    // G02
    flip: 'Ver resposta',
    unflip: 'Ver pergunta',
    backLoading: 'Carregando resposta…',
    backEmpty: 'Sem resposta ainda.',
    connectFrom: 'Agora clique no card de destino.',
    connectStart: 'Clique no card de origem.',
  },
  palette: {
    placeholder: 'Buscar comando',
    notFound: 'Nada encontrado para essa busca.',
    closeLabel: 'Fechar busca',
    keyboardHint: '⌘K',
    // T5 (editor v2)
    esc: 'esc',
    groups: { create: 'Criar', map: 'Mapa', layers: 'Camadas', cards: 'Cards', goTo: 'Ir para' },
    newConcept: { label: 'Novo card de conceito', hint: 'Adiciona ao mapa' },
    newFlow: { label: 'Novo fluxograma de conduta', hint: 'Passos ordenados' },
    newImage: { label: 'Novo card de imagem', hint: 'Com máscaras de oclusão' },
    newCase: { label: 'Novo caso clínico', hint: 'Etapas do caso' },
    link: { label: 'Ligar dois cards', hint: 'Ferramenta de conexão' },
    organize: { label: 'Organizar o mapa', hint: 'Layout automático' },
    challenge: { label: 'Desafiar este mapa', hint: 'Começa pelos vencidos' },
    structure: { label: 'Mostrar estrutura', hint: 'Conexões' },
    recall: { label: 'Mostrar lembrança estimada', hint: 'Cores do FSRS' },
    coverage: { label: 'Mostrar cobertura da matriz', hint: 'Enamed' },
    card: 'Ir para o card',
    home: { label: 'Hoje', hint: 'Início' },
    maps: { label: 'Meus mapas', hint: 'Biblioteca' },
    newMap: { label: 'Novo mapa', hint: 'PDF, Anki ou mapa pronto' },
    review: { label: 'Revisar hoje', hint: 'Fila do dia' },
  },
  quiz: {
    exit: 'Sair do desafio',
    challengeBoard: 'Desafiar {n, plural, one {o # que vence} other {os # que vencem}} hoje',
    transcription: 'Só a transcrição fica salva. O áudio é descartado.',
    dispute: 'Discordo da correção',
    hiddenTitle: 'Conceito oculto',
    hiddenStep: 'Passo oculto: responda no painel',
    hiddenEdge: 'Qual conexão?',
    hiddenEdgeLabel: 'Rótulo da conexão oculto: responda no painel',
    ratingLabel: 'Como foi lembrar?',
    ratingLabelSuggested: 'Como foi lembrar? Sugestão: {grade}',
    verdictLabel: { correct: 'Correto', partial: 'Parcial', incorrect: 'Incorreto' },
    subject: { step: 'Passo', stage: 'Etapa', region: 'Região', card: 'Card' },
    chipState: '{subject} em {state}',
    summaryPanel: 'Resumo da sessão',
    speak: 'Falar',
    voiceRecord: 'Falar a resposta',
    voiceStop: 'Parar de ouvir',
    voiceNote: 'O navegador transcreve a sua fala. O Remoa não grava nem guarda áudio.',
    voiceListening: 'Ouvindo…',
    voiceUnavailable: 'Este navegador não transcreve voz. Responda escrevendo.',
    voiceSwitch: 'Escrever a resposta',
    voiceError: 'Não consegui ouvir. Tente de novo ou escreva a resposta.',
  },
  map: {
    canvasLabel: 'Mapa {title}',
    hint: 'Clique em um conceito para abrir. Arraste para reorganizar o mapa.',
    stats: '{cards, plural, =0 {0 conceitos} one {# conceito} other {# conceitos}} · {edges, plural, =0 {0 conexões} one {# conexão} other {# conexões}}',
    titleLabel: 'Nome do mapa',
    titleEdit: 'Renomear mapa',
    eyebrow: 'Seu mapa de {area}',
    attribution: 'React Flow',
    legend: 'Legenda dos estados',
    toolbar: {
      label: 'Ferramentas do mapa',
      concept: 'Card',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso',
      add: 'Adicionar {type}',
      organize: 'Organizar',
      heat: 'Lembrança estimada',
      mode: 'Modo do mapa',
      explore: 'Explorar',
      challenge: 'Desafio',
      move: 'Mover',
      connect: 'Conexão',
      addCard: 'Card',
    },
    cardType: {
      concept: 'Conceito',
      flow: 'Fluxograma',
      image: 'Imagem',
      case: 'Caso',
    },
    newCardTitle: {
      concept: 'Novo conceito',
      flow: 'Novo fluxograma',
      image: 'Nova imagem',
      case: 'Novo caso',
    },
    card: {
      open: 'Abrir',
      openLabel: 'Abrir {title}',
      menu: 'Mais ações de {title}',
      delete: 'Excluir',
      drag: 'Arrastar {title}',
      label: '{type}: {title}',
    },
    edge: {
      labelPlaceholder: 'Rótulo da conexão',
      labelInput: 'Rótulo da conexão',
      editLabel: 'Editar rótulo: {label}',
      addLabel: 'Adicionar rótulo',
      noLabel: 'Sem rótulo não vira pergunta',
      empty: '+ rótulo',
    },
    zoom: {
      in: 'Aproximar',
      out: 'Afastar',
      fit: 'Ajustar à tela',
      minimap: 'Mini-mapa',
      controls: 'Controles de zoom',
      percent: '{n}%',
    },
    save: {
      saving: 'Salvando…',
      offline: 'Sem conexão, salvando depois',
      error: 'Não conseguimos salvar suas mudanças.',
    },
    delete: {
      title: 'Excluir os cards selecionados?',
      body: 'As conexões desses cards também saem. Você pode desfazer com Ctrl+Z.',
      confirm: 'Excluir',
    },
    limit: 'Este mapa chegou ao limite de {max} cards.',
    ago: {
      minutes: '{n} min',
      hours: '{n} h',
    },
    a11y: {
      node: 'Enter ou espaço seleciona o card. Delete exclui; Esc cancela.',
      nodeKeyboard: 'Enter ou espaço seleciona o card. Use as setas para mover; Delete exclui; Esc cancela.',
      moved: 'Card movido. Nova posição: x {x}, y {y}',
      edge: 'Enter ou espaço seleciona a conexão. Delete exclui; Esc cancela.',
      handle: 'Porta de conexão',
    },
    inspector: {
      label: 'Detalhes do card',
      empty: 'Selecione um card no mapa',
      shortcuts: 'Atalhos',
      addCard: 'Adicionar card',
      challenge: 'Desafiar',
      yourCard: 'Card do seu mapa',
      type: 'Tipo',
      summary: 'Resumo',
      noSummary: 'Sem resumo ainda.',
      nextReview: 'Próxima revisão: {data}',
      noReview: 'Ainda sem revisões',
      provenance: 'Origem e edição',
      source: 'Fonte',
      temporalMark: 'Marco temporal',
      reviewer: 'Revisor',
      none: '—',
      reviewThis: 'Revisar este conceito',
      viewSource: 'Ver fonte e versão',
      status: {
        draft: 'Rascunho',
        approved: 'Aprovado',
      },
    },
  },
  cards: {
    edit: 'Editar card',
    editorLabel: 'Editar {title}',
    loading: 'Carregando card…',
    loadError: 'Não conseguimos abrir este card.',
    saving: 'Salvando…',
    saved: 'Card salvo',
    shortcuts: 'Enter salva (Ctrl+Enter nos textos longos). Esc cancela.',
    fields: {
      title: 'Título',
      front: 'Pergunta ou dica (opcional)',
      back: 'Resposta',
      backHint: 'Aceita **negrito**, *itálico*, listas com - e [links](https://…).',
      preview: 'Prévia da resposta',
      source: 'Fonte (texto ou URL)',
      sourcePlaceholder: 'Ex.: Diretriz Surviving Sepsis 2021',
    },
    flow: {
      count: '{n, plural, one {# passo} other {# passos}}',
      stepsLabel: 'Passos',
      step: 'Passo {n}',
      note: 'Observação do passo {n} (opcional)',
      add: 'Adicionar passo',
      remove: 'Remover passo {n}',
      drag: 'Reordenar passo {n}',
      min: 'Um fluxograma tem pelo menos 2 passos.',
      max: 'Um fluxograma tem no máximo 12 passos.',
      dnd: {
        instructions: 'Para reordenar, pressione espaço ou Enter, use as setas e pressione espaço ou Enter de novo. Esc cancela.',
        start: 'Passo {n} pego.',
        over: 'Passo {n} sobre a posição {to}.',
        end: 'Passo {n} solto na posição {to}.',
        cancel: 'Reordenação cancelada.',
      },
    },
    case: {
      stagesLabel: 'Etapas do caso',
      stage: {
        presentation: 'Apresentação',
        workup: 'Exames',
        diagnosis: 'Diagnóstico',
        management: 'Conduta',
      },
    },
    image: {
      alt: 'Imagem do card {title}',
      pick: 'Escolher imagem',
      dropHint: 'Arraste, cole ou escolha uma imagem JPG, PNG ou WebP de até 10 MB.',
      replace: 'Trocar imagem',
      openMasks: 'Abrir editor de máscaras',
      license: 'Licença da imagem',
      licenses: {
        own: 'Própria',
        cc_by: 'Creative Commons (CC BY)',
        servier: 'Servier Medical Art',
        openstax: 'OpenStax',
      },
      attribution: 'Autoria / atribuição',
      uploading: 'Enviando imagem… {pct}%',
      uploadProgress: 'Progresso do envio',
      failed: 'O envio da imagem falhou.',
      tooBig: 'A imagem passa de 10 MB. Reduza e tente de novo.',
      badType: 'Formato não aceito. Use JPG, PNG ou WebP.',
      noLicense: 'Licença não escolhida: informe a autoria da imagem para essa licença.',
      masksOne: '1 máscara',
      masks: '{n} máscaras',
    },
    frontImage: {
      label: 'Imagem da pergunta (opcional)',
      hint: 'Aparece na frente do card e no desafio.',
      alt: 'Imagem da pergunta de {title}',
      remove: 'Remover imagem',
    },
    shape: {
      label: 'Formato no mapa',
      rect: 'Retângulo',
      pill: 'Pílula',
      circle: 'Círculo',
      diamond: 'Losango',
      hexagon: 'Hexágono',
      imageHint: 'No mapa, a imagem da pergunta só aparece no formato Retângulo.',
    },
    mask: {
      editorTitle: 'Máscaras de {title}',
      editorDescription: 'Cubra as regiões que você quer ser cobrado. As máscaras ficam por cima da imagem, nunca gravadas nela.',
      tools: 'Ferramenta',
      tool: {
        select: 'Selecionar',
        rect: 'Retângulo',
        polygon: 'Polígono',
      },
      surface: 'Área de desenho das máscaras',
      item: 'Máscara: {label}',
      defaultLabel: 'Região {n}',
      label: 'Rótulo da máscara',
      delete: 'Excluir máscara',
      add: 'Adicionar máscara',
      count: '{n} de {max} máscaras',
      limit: 'Limite de {max} máscaras por imagem.',
      polygonHint: 'Clique para marcar os pontos. Feche clicando no primeiro ponto, com duplo clique ou Enter.',
      rectHint: 'Arraste sobre a imagem para cobrir uma região.',
      selectHint: 'Clique numa máscara para mover; arraste os pontos para redimensionar. Setas movem, Delete exclui.',
      noImage: 'Envie a imagem antes de desenhar máscaras.',
    },
    rubric: {
      title: 'Rubrica',
      essential: 'Essencial',
      source: 'Fonte: {source}',
      generate: 'Gerar rubrica',
    },
    errors: {
      title: 'Dê um título ao card.',
      stepText: 'Preencha o texto de todos os passos.',
      steps: 'Um fluxograma tem de 2 a 12 passos.',
      caseMin: 'Preencha pelo menos uma etapa do caso.',
      image: 'Envie uma imagem antes de salvar.',
      maskLabel: 'Toda máscara precisa de um rótulo.',
      tooLong: 'Algum campo passou do tamanho máximo.',
      notSynced: 'O card ainda não chegou ao servidor. Confira a conexão e tente de novo.',
      offline: 'Sem conexão. Tente de novo quando voltar.',
    },
  },
  billing: {
    plan: { free: 'Free', pro: 'Pro' },
    paywall: {
      title: 'Você chegou ao limite do Free',
      ai_quota: 'Você usou as {n} correções por IA de hoje. No Pro, elas são ilimitadas.',
      boards: 'Você chegou ao limite de {n} mapas do Free. No Pro, os mapas são ilimitados.',
      cards: 'Você chegou ao limite de {n} cards do Free. No Pro, os cards são ilimitados.',
      pdf: 'A geração de mapa por PDF do Free já foi usada. No Pro, são {n} por mês.',
      cta: 'Assinar o Pro',
      dismiss: 'Continuar no Free',
    },
    pricing: {
      title: 'Planos',
      subtitle: 'Comece no Free. Assine o Pro quando o seu estudo pedir mais espaço.',
      tableLabel: 'Comparação entre Free e Pro',
      feature: 'Recurso',
      price: 'Preço',
      boards: 'Mapas',
      cards: 'Cards',
      ai_grades: 'Correções por IA por dia',
      ai_generations: 'Geração de mapa por PDF por mês',
      anki: 'Import do Anki (cards)',
      newCards: 'Novos cards por dia',
      unlimited: 'Ilimitados',
      freePrice: 'R$ 0',
      periodLabel: 'Período de cobrança',
      monthly: 'Mensal',
      annual: 'Anual',
      perMonth: '{price}/mês',
      perYear: '{price}/ano',
      annualHint: 'Equivale a {price} por mês',
      methodLabel: 'Forma de pagamento',
      pix: 'Pix',
      card: 'Cartão',
      founder: 'Tenho o preço de fundador',
      cta: 'Assinar o Pro',
      ctaBusy: 'Abrindo o pagamento',
      alreadyPro: 'Você já está no Pro.',
      manage: 'Ver minha conta',
      error: 'Não conseguimos abrir o pagamento. Tente de novo.',
    },
    account: {
      title: 'Minha conta',
      planLabel: 'Plano',
      status: {
        active: 'Ativo',
        trialing: 'Em teste',
        past_due: 'Pagamento pendente',
        canceled: 'Cancelado',
        incomplete: 'Incompleto',
      },
      renewsAt: 'Próxima cobrança em {date}',
      cancelsAt: 'O Pro fica ativo até {date} e não renova sozinho.',
      grace: 'Não conseguimos cobrar a sua assinatura. O Pro continua ativo até {date}; atualize o pagamento para não perder o acesso.',
      usageTitle: 'Uso do plano',
      usageLine: '{used} de {limit}',
      usageUnlimited: '{used} (sem limite)',
      daily: 'hoje',
      monthly: 'neste mês',
      total: 'no total',
      manage: 'Gerenciar pagamento',
      cancel: 'Cancelar assinatura',
      subscribe: 'Assinar o Pro',
      portalError: 'Não conseguimos abrir o portal de pagamento. Tente de novo.',
      loadError: 'Não foi possível carregar o seu plano.',
      checkoutOk: 'Assinatura ativada. Bem-vindo ao Pro.',
      portalOk: 'Pagamento atualizado.',
      dataTitle: 'Seus dados',
      dataBody: 'Você pode baixar tudo o que é seu ou excluir a conta.',
      export: 'Exportar meus dados',
      exportOk: 'Exportação baixada.',
      exportError: 'Não conseguimos exportar agora. Tente de novo.',
      delete: 'Excluir conta',
      deleteTitle: 'Excluir a conta?',
      deleteBody: 'Sua conta fica desativada agora e os dados são apagados de vez depois de 7 dias. Exporte antes se quiser guardar uma cópia.',
      deleteConfirm: 'Excluir minha conta',
      deleteCancel: 'Manter a conta',
      deleteError: 'Não conseguimos excluir a conta. Tente de novo.',
    },
  },
  landing: {
    tagline: 'O que você aprende, fica.',
    subtitle: 'Monte seu mapa de estudo, revise na hora certa e teste o que realmente lembra.',
    cta: 'Começar agora',
    signIn: 'Entrar',
  },
} as const;

export type Dict = typeof ptBR;
