// G15 / F21 Revisar (T7): texto do mock Revisar.dc.html. Datas e dias da semana vêm de Intl (pt-BR), números por variável.
export const reviewHub = {
  pageTitle: 'Remoa — Revisar',
  greet: { morning: 'Bom dia', afternoon: 'Boa tarde', night: 'Boa noite' },
  title: {
    pending: '{greet}. {n, plural, one {# card espera} other {# cards esperam}} por você.',
    done: '{greet}. Tudo em dia.',
    empty: '{greet}. Vamos começar?',
  },
  panel: {
    ringLabel: '{done} de {total} revisados hoje',
    inQueue: 'na fila de hoje',
    upToDate: 'Em dia',
    noCards: 'Sem cards',
    doneToday: '{n, plural, one {# já revisado hoje} other {# já revisados hoje}}',
    heroPending: '{n, plural, one {# card para fixar hoje.} other {# cards para fixar hoje.}}',
    heroDone: 'Nada mais para revisar hoje.',
    heroEmpty: 'Você ainda não tem cards para revisar.',
    textStartsBy: 'A fila começa por {board}, o mapa com mais cards vencidos.',
    textOnlyNew: 'Hoje a fila é só de cards novos.',
    textDone: 'Amanhã você tem cerca de {n} cards. Quer adiantar alguns?',
    textEmpty: 'Crie um mapa e a fila nasce sozinha, na hora certa de cada card.',
    composition: '{due} vencidos, {new} novos e {weak} em atenção na fila',
    chipsLabel: 'O que entra na fila',
    due: 'Vencidos',
    dueSub: 'Passaram do ponto',
    new: 'Novos',
    newSub: 'Até {n} por dia',
    newSubNone: 'Sem limite por dia',
    weak: 'Em atenção',
    weakSub: 'Ainda lembra, mas por pouco',
    time: '{n, plural, one {Cerca de # minuto} other {Cerca de # minutos}}',
    limitNone: 'Sem limite de cards novos por dia no seu plano.',
    limitFree: 'Até {n} cards novos por dia no Free.',
    limitPro: 'Até {n} cards novos por dia no Pro.',
    maps: 'Mapas na sessão',
    start: 'Começar revisão · {n}',
    ahead: 'Adiantar revisões',
    noteStart: 'Você escolhe quanto tempo ficar. Pode parar quando quiser.',
    noteAhead: 'Adiantar não muda a data das próximas revisões dos outros cards.',
    startError: 'Não conseguimos montar a sessão.',
    startEmpty: 'Nenhum card para esta seleção agora.',
  },
  noData: {
    title: 'Seus gráficos aparecem depois da primeira revisão.',
    body: 'Crie um mapa, adicione alguns cards e volte aqui. A fila, a retenção e a previsão se montam sozinhas.',
    cta: 'Criar meu primeiro mapa',
  },
  table: 'Ver como tabela',
  error: { title: 'Não conseguimos carregar o Revisar', retry: 'Tentar de novo' },
  saved: { title: '{n, plural, one {# card na última fila salva} other {# cards na última fila salva}}' },
  kpi: {
    streak: 'Sequência',
    streakUnit: 'dias',
    streakSub: 'Seu recorde é de {n} dias',
    weekLabel: '{n} de 7 dias da semana com revisão',
    weekDays: { d0: 'S', d1: 'T', d2: 'Q', d3: 'Q', d4: 'S', d5: 'S', d6: 'D' },
    weekDaysFull: { d0: 'segunda', d1: 'terça', d2: 'quarta', d3: 'quinta', d4: 'sexta', d5: 'sábado', d6: 'domingo' },
    retention: 'Retenção (30 dias)',
    retentionDelta: '{delta} pontos desde o mês passado · meta 90%',
    retentionNoDelta: 'Meta 90%',
    retentionLabel: '{n}% de retenção, meta 90%',
    reviews: 'Revisados (7 dias)',
    reviewsUnit: 'cards',
    reviewsSub: 'Média de {n} por dia',
    firm: 'Cards firmes',
    firmSub: '{n} de {total} cards lembrados com folga',
    firmLabel: '{n}% dos cards firmes',
  },
  forecast: {
    title: 'Próximos 14 dias',
    peak: 'Pico em {day}, com {n} cards.',
    today: 'Hoje',
    planned: 'Previsto',
    todayLower: 'hoje',
    summary: 'Revisões previstas para os próximos 14 dias. {peak}',
    value: '{n, plural, one {# card} other {# cards}}',
    empty: 'Nenhuma revisão prevista.',
    head: { day: 'Dia', count: 'Cards' },
  },
  states: {
    title: 'Estado dos cards',
    sub: 'Lembrança estimada de cada card hoje',
    due: 'Vencidos',
    watch: 'Em atenção',
    steady: 'Firmes',
    new: 'Novos',
    total: 'cards no total',
    summary: 'Estado dos cards: {due} vencidos, {watch} em atenção, {steady} firmes e {new} novos.',
    head: { state: 'Estado', count: 'Cards' },
  },
  retention: {
    title: 'Retenção ao longo do tempo',
    avg: 'Média de {n}% no período · meta 90%',
    noAvg: 'Sem revisões no período · meta 90%',
    range: 'Período',
    r7: '7 dias',
    r30: '30 dias',
    r90: '90 dias',
    from: { r7: 'há 7 dias', r30: 'há 30 dias', r90: 'há 90 dias' },
    today: 'hoje',
    summary: 'Retenção nos últimos {range}. {avg}',
    empty: 'Sem revisões neste período.',
    head: { date: 'Data', value: 'Retenção' },
    target: 'meta',
  },
  activity: {
    title: 'Atividade',
    sub: 'Últimas 15 semanas',
    summary: 'Calendário de atividade das últimas 15 semanas: {n} cards revisados.',
    idle: 'Passe o mouse sobre um dia para ver os detalhes.',
    less: 'menos',
    more: 'mais',
    cell: '{n, plural, =0 {Nenhuma revisão} one {# card revisado} other {# cards revisados}} em {date}',
    head: { day: 'Dia', activity: 'Atividade' },
  },
  focus: {
    title: 'Onde focar',
    sub: 'Acerto por grande área, da mais fraca para a mais forte',
    weakest: 'mais fraca',
    meta: '{cards} cards · {due} vencem hoje',
    noCards: 'Sem cards ainda',
    review: 'Revisar',
    reviewArea: 'Revisar só {area}',
    createMap: 'Criar mapa',
  },
  hard: {
    title: 'Cards mais difíceis',
    sub: 'Os que você mais errou. Vale reescrever.',
    recall: 'lembra',
    meta: '{map} · {lapses, plural, one {errou # vez} other {errou # vezes}}',
    rewrite: 'Reescrever {title}',
    empty: 'Nenhum card difícil por enquanto.',
  },
  perMap: {
    title: 'Por mapa',
    map: 'Mapa',
    states: 'Estado dos cards',
    due: 'Vencem hoje',
    retention: 'Retenção',
    meta: '{area} · {cards} cards',
    dueNow: '{n, plural, =0 {Em dia} one {1 vence hoje} other {# vencem hoje}}',
    review: 'Revisar este mapa',
    reviewMap: 'Revisar o mapa {title}',
    barLabel: '{review} para revisitar, {watch} a acompanhar, {steady} mais estáveis, {unknown} sem revisões',
    noRetention: '—',
  },
} as const;
