// F20 Loja de mapas, Fase A ("Em breve"). Sem datas e sem percentual fixo (D-035, D-036): o percentual chega por variável.
export const store = {
  title: 'Loja de mapas',
  pageTitle: 'Remoa — Loja de mapas (em breve)',
  soonSeal: 'EM BREVE',
  soonTag: 'Breve',
  notice: 'A Loja de mapas ainda não está disponível. Esta página mostra o que vem por aí.',
  homeCard: 'Loja de mapas · Em breve',
  homeCardDesc: 'Mapas feitos por quem já passou por isso',
  hero: {
    eyebrow: 'Loja de mapas',
    titleStart: 'Mapas completos, feitos por quem',
    titleEmph: 'já passou por isso.',
    lead: 'Professores, residentes e médicos vão poder publicar mapas de estudo para você comprar, e ganhar a cada venda.',
    join: 'Entrar na lista de espera',
    sell: 'Quero vender',
  },
  status: {
    title: 'Em que pé estamos',
    items: {
      waitlist: { title: 'Lista de espera', desc: 'Você se cadastra e recebe um aviso quando a loja abrir.', chip: 'Agora' },
      sellers: { title: 'Vendedores publicam', desc: 'Um primeiro grupo de professores, residentes e médicos publica os primeiros mapas.', chip: 'Em seguida' },
      open: { title: 'Loja aberta', desc: 'Qualquer aluno compra. Mais vendedores entram aos poucos.', chip: 'Sem data ainda' },
    },
  },
  how: {
    eyebrow: 'Como vai funcionar',
    title: 'Para quem compra e para quem vende.',
    tabsLabel: 'Para quem',
    buy: 'Quero comprar',
    sell: 'Quero vender',
    buySteps: {
      s1: { title: 'Encontre um mapa', desc: 'Filtre por área, veja uma prévia gratuita, as avaliações e quem fez.' },
      s2: { title: 'Compre uma vez', desc: 'Pague por Pix ou cartão. O mapa vai para a sua biblioteca na hora.' },
      s3: { title: 'Estude do seu jeito', desc: 'O mapa vira seu: edite, revise com o agendador e faça os desafios.' },
    },
    sellSteps: {
      s1: { title: 'Publique seu mapa', desc: 'Monte seus cards e conexões. Antes de ir ao ar, a equipe revisa a qualidade.' },
      s2: { title: 'Defina o preço', desc: 'Você escolhe quanto cobrar e pode atualizar o mapa com o tempo.' },
      s3: { title: 'Receba a cada venda', desc: 'A divisão é automática: sua parte vai direto para a sua conta.' },
    },
  },
  who: {
    eyebrow: 'Quem pode vender',
    title: 'Quem sabe, ensina. E ganha por isso.',
    teacher: { title: 'Professores', desc: 'Transforme sua aula em um mapa que o aluno estuda no próprio ritmo e que sua experiência continue rendendo.', badge: 'Selo Professor' },
    student: { title: 'Alunos e residentes', desc: 'Quem acabou de passar pela prova sabe o que realmente caiu. Venda o mapa que você mesmo montou.', badge: 'Selo Aluno ou Residente' },
    doctor: { title: 'Médicos formados', desc: 'Compartilhe a prática do consultório e da residência. Conferimos o seu CRM, manualmente, e damos o selo de verificado.', badge: 'Selo Médico verificado' },
  },
  split: {
    unavailable: 'O simulador não está disponível agora. Recarregue a página para tentar de novo.',
    eyebrow: 'Divisão de cada venda',
    title: 'Uma parte para você, outra para a plataforma.',
    example: 'Exemplo ilustrativo',
    price: 'Preço do mapa',
    buyer: 'Comprador',
    payment: 'Pagamento',
    you: 'Você',
    brand: 'remoa',
    seller: 'vendedor',
    platform: 'plataforma',
    sellerLegend: 'Vendedor {pct}%',
    platformLegend: 'Plataforma {pct}%',
    note: 'Valores de exemplo. O percentual final, as taxas do meio de pagamento e as regras de repasse serão divulgados antes da abertura da loja.',
  },
  preview: {
    eyebrow: 'Prévia',
    title: 'Assim a loja vai parecer.',
    banner: 'Exemplos ilustrativos. Nada aqui está à venda.',
    filtersLabel: 'Filtros (indisponíveis)',
    filters: { all: 'Todas as áreas', cm: 'Clínica Médica', cir: 'Cirurgia', ped: 'Pediatria', go: 'Ginecologia e Obstetrícia', mp: 'Medicina Preventiva' },
    example: 'Exemplo',
    priceHidden: 'Preço disponível na abertura',
    priceMask: 'R$ 00,00',
    notify: 'Avise-me quando abrir',
    verified: 'Médico verificado',
    verifiedF: 'Médica verificada',
    teacher: 'Professor',
    teacherF: 'Professora',
    resident: 'Residente',
    student: 'Aluno',
    meta: '{area} · {cards} cards · {edges} conexões',
    rating: 'Nota {rating}, {count} avaliações',
    listings: {
      l1: { title: 'Cardiologia para a prova de residência', author: 'Dr. Rafael M.', area: 'Clínica Médica', cards: '86', edges: '104', rating: '4,9', count: '212' },
      l2: { title: 'Pediatria: do recém-nascido ao adolescente', author: 'Profa. Helena S.', area: 'Pediatria', cards: '64', edges: '71', rating: '4,8', count: '138' },
      l3: { title: 'Cirurgia geral em fluxogramas', author: 'Camila T.', area: 'Cirurgia', cards: '52', edges: '60', rating: '4,7', count: '96' },
      l4: { title: 'Ginecologia e Obstetrícia: pré-natal ao parto', author: 'Dra. Marina L.', area: 'Ginecologia e Obstetrícia', cards: '78', edges: '90', rating: '4,9', count: '174' },
      l5: { title: 'Infectologia: antibióticos sem decorar', author: 'Prof. André C.', area: 'Clínica Médica', cards: '58', edges: '66', rating: '4,8', count: '121' },
      l6: { title: 'Preventiva e saúde coletiva em 40 cards', author: 'Lucas P.', area: 'Medicina Preventiva', cards: '40', edges: '43', rating: '4,6', count: '58' },
    },
  },
  waitlist: {
    eyebrow: 'Lista de espera',
    title: 'Seja avisado quando a loja abrir.',
    lead: 'Quem entra na lista é avisado primeiro. Se quiser vender, conte quem você é e damos prioridade a vendedores no início.',
    email: 'E-mail',
    interestLabel: 'O que você quer fazer?',
    interestGroup: 'Interesse',
    buy: 'Quero comprar mapas',
    sell: 'Quero vender os meus',
    roleLabel: 'Você é',
    roleGroup: 'Quem você é',
    roles: { teacher: 'Professor', student_resident: 'Aluno ou residente', physician: 'Médico formado' },
    roleHint: 'Médicos recebem o selo de verificado depois que conferimos o CRM.',
    submit: 'Entrar na lista de espera',
    submitting: 'Enviando...',
    consent: 'Usamos o e-mail só para avisar sobre a loja. Você pode sair da lista a qualquer momento em Minha conta.',
    errEmail: 'Digite um e-mail válido.',
    errInterest: 'Escolha se quer comprar, vender ou os dois.',
    errRole: 'Conte se você é professor, aluno ou residente, ou médico formado.',
    errSave: 'Não foi possível salvar agora. Tente de novo em instantes.',
    errClosed: 'A lista de espera não está aberta agora.',
    errRate: 'Muitas tentativas. Aguarde um pouco e tente de novo.',
    doneTitle: 'Você está na lista.',
    doneBuy: 'Avisamos por e-mail quando a loja abrir.',
    doneSell: 'Avisamos por e-mail quando a loja abrir e, como você quer vender, entramos em contato antes sobre os primeiros vendedores.',
    edit: 'Alterar minhas respostas',
    loading: 'Carregando suas respostas...',
    errLoad: 'Não foi possível carregar a lista de espera agora.',
    retry: 'Tentar de novo',
  },
  meanwhile: {
    eyebrow: 'Enquanto isso',
    title: 'Comece pelos mapas da equipe.',
    lead: 'Já existem mapas prontos, revisados, para você estudar hoje. E dá para criar o seu a partir de PDF, do Anki ou do zero.',
    cta: 'Ver meus mapas e os prontos',
    faq: {
      q1: { q: 'Quando a loja abre?', a: 'Ainda não temos data. Quem está na lista de espera é avisado por e-mail antes de todo mundo.' },
      q2: { q: 'Quanto eu ganho vendendo?', a: 'Você define o preço e fica com a maior parte de cada venda. O percentual exato e as regras de repasse serão divulgados antes da abertura.' },
      q3: { q: 'Posso vender um mapa feito com material de terceiros?', a: 'Só é possível vender conteúdo autoral ou com licença para isso. Mapas denunciados são revisados e podem ser retirados.' },
      q4: { q: 'O que acontece com um mapa que eu comprar?', a: 'Ele entra na sua biblioteca e você estuda, edita e revisa como em qualquer mapa. Não é possível revendê-lo.' },
    },
  },
  account: {
    title: 'Lista de espera da loja',
    body: 'Você está na lista para ser avisado quando a Loja de mapas abrir. Usamos o e-mail só para isso.',
    leave: 'Sair da lista',
    left: 'Você saiu da lista de espera da loja.',
    error: 'Não foi possível sair da lista agora. Tente de novo.',
  },
} as const;
