import { test, type Page } from '@playwright/test';
import { createSepseBoard, signUpAndLogin } from '../visual/fixture';
const OUT = '/Users/fernandoviviurka/Desktop/Projetos/remoa/docs/design/v2/screens/app';
test.use({ colorScheme: 'light', viewport: { width: 390, height: 844 }, deviceScaleFactor: 3 });
test('capture', async ({ page, request }) => {
  test.setTimeout(180_000);
  const { headers } = await signUpAndLogin(page, request);
  const board = await createSepseBoard(request, headers);
  await page.goto(`/app/mapas/${board}`);
  await page.locator('.react-flow__node').first().waitFor();
  const shot = async (n: string) => { await page.waitForTimeout(900); await page.screenshot({ path: `${OUT}/mapa-mobile-${n}.png` }); };
  await shot('mapa');
  await page.getByRole('button', { name: 'Afastar' }).click(); await page.getByRole('button', { name: 'Afastar' }).click();
  await shot('visao');
  await page.getByRole('button', { name: 'Aproximar' }).click(); await page.getByRole('button', { name: 'Aproximar' }).click();
  await page.waitForTimeout(600);
  await page.getByRole('button', { name: 'Criar card' }).click(); await shot('criar');
  await page.keyboard.press('Escape'); await page.waitForTimeout(700);
  await page.locator('.react-flow__node').first().locator('button').first().click(); await shot('card');
  await page.getByRole('button', { name: 'Fechar' }).click();
  await page.getByRole('button', { name: 'Abrir o menu do mapa' }).click(); await page.waitForTimeout(800); await shot('menu');
  await page.getByRole('button', { name: /Cards em lista/ }).click(); await shot('lista');
  await page.getByRole('button', { name: 'Voltar ao mapa' }).click();
  await page.getByRole('button', { name: 'Criar card' }).click(); await page.getByRole('button', { name: /^Conceito/ }).click(); await shot('editar');
});
